### ISSUE TITLE
Scraper settings isn't saved

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#1004]
**Describe the bug**
Language settings for The TVDB and all settings under the 'TV Scraper'-tab isn't saved.

**To Reproduce**
1. Go to Settings-Scraper.
2. Change language for The TVDB.
3. Save settings.
4. Tool tip(?) says settings are saved but settings is back to what it was before and nothing changes when scraping either. Same thing with any setting under Scraper-TV Scraper.

**Expected behavior**
That settings are saved.

**MediaElch Version:**
 - [X] 2.6.7-dev (nightly)
 - [ ] 2.6.6 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**
Maybe irrelevant with the new scraper thingy you are working on so if that's the case just delete this.

**Comment by psonnosp** [comment]
I guessed HKEY_CURRENT_USER\Software\kvibes\MediaElch\Scrapers\TheTvDb\Language were the place where this was saved, at least it changes the setting in the program visually, but it doesn't change the behavior cause it still scrapes in English.
And yes the language I'm trying to scrape exist for the show in question.

**Comment by bugwelle** [comment]
Hi,

sorry for the late answer. I'm currently having exams at my university so my time is limited. I've rewritten a lot of scraper settings in the upcoming TV scraper rewrite (see https://github.com/Komet/MediaElch/pull/972 ).

This issue should be fixed by that as well. :)

**Comment by lynxstrike** [comment]
@bugwelle 

Sorry for the duplicate bug report... Most be it's sunday morning :D 
Thanks!

**Comment by bugwelle** [comment]
#972 is finally merged and has a rewritten TV scraper (and settings). Please note that a new nightly is not available, yet. But the next one will fix this issue. :-)

**Comment by lynxstrike** [comment]
Thank you for all your hard work.  :)
