### ISSUE TITLE
Local Title vs. Original Title

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#1006]
**Is your feature request related to a problem? Please describe.**
Local Title vs. Original Title

I regularly export my database to HTML.
I use this export in a .html table that has a search facility.
This Search Feature has the option to Search for a specific field.
And there is my problem.
Many records are missing the Original Title because MediaElch started not to store the Original Title when the title is the same as the Local Title.

**Describe the solution you'd like**
So I ask:
1 Can I change this behavior using the **advancedsettings.xml** file?
2 Would it be possible for this behavior to be a user option via the **MediaElch.ini** file?
3 Would it be possible to reverse this behavior?

I am not sure why this modification was implemented.
I don't know if there is an advantage. I don't know why this is better.
But, without a doubt, it was not useful for me.

**Comment by bugwelle** [comment]
Related PR: https://github.com/Komet/MediaElch/pull/812

Hi,

thank you for opening this feature request. My proposal: Make it a GUI option in Settings -> Movies (next to "Use plot when outline is not available"). 😃

**Comment by bugwelle** [comment]
Will be added by  #1007

**Comment by bugwelle** [comment]
The next nightly will have an option "Don't store the original title if it is the same as the normal title" which is enabled by default. :-)

**Comment by ticao2** [comment]
Great. 💯   
A curiosity of mine. Is there a way for me to see which **API Requests** are sent to **TMDb**?  
I enabled **Debug** in the **advancedsettings.xml** file but there I **see only the basic URL**.  
I do not see the Request that is sent.  
If you want I can open another issue for this topic.

**Comment by bugwelle** [comment]
@ticao2 No, at the moment that is not possible. I can make that a part of #972 if you'd like. :-)

**Comment by ticao2** [comment]
I have no idea how much work it takes. Would be great. If possible... :-)

**Comment by bugwelle** [comment]
@ticao2 With  #1015 we will have a central network manager. Then it should be rather easy to enable URL logging. :-)
