### ISSUE TITLE
TV Show Scrapper Does Not Retain Language Change

### ISSUE THREAD

**Issue by lynxstrike** [Komet/MediaElch#1023]
**Describe the bug**
TV Show Scrapper Does Not Retain Language Change after pressing "Save Settings" 
(Scrapper section, The TV DB option) (Does not accept other option but "english")
**To Reproduce**
1. Go to 'Scrapper section'
2. Click on 'The TV DB option'
3. Scroll down to 'any language but english'
4. Press "Save Settings"
5. Open Settings windows and go to "Scrapper section" and "english" language will be selected again. 

**Expected behavior**
Retain change in language.

**Screenshots**

**MediaElch Version:**
 - [ ] MediaElch_win_2.6.7-dev_2020-09-27_13-05_git-master-3bca3cb (nightly)
 - [ ] 2.6.6 stable

**Operating System:**
 - [ ] Windows 10 Pro x64
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**

**Comment by bugwelle** [comment]
Duplicate of #1004

Will be fixed by #972 (huge scraper rewrite). :-)
