### ISSUE TITLE
Clear Filter/Search

### ISSUE THREAD

**Issue by ksipple** [Komet/MediaElch#1025]
Please add an X at the end of the filter field to clear the current filter with one click

**Comment by bugwelle** [comment]
Good point. We have such functionality for certain fields already. But would be great to also clear the filters.

Because of the filters I have to build the clear functionality myself. But should possible. 👍

**Comment by bugwelle** [comment]
There should already be an X but it isn't visible (at least on macOS). Somehow the Icon isn't displayed...

I've already implemented the "Also clear filters" functionality. Just the Icon is still missing...

**Comment by bugwelle** [comment]
Will be fixed by #1026 when I make the icon visible again.

**Comment by bugwelle** [comment]
<img width="212" alt="Screen Shot 2020-10-05 at 22 44 18" src="https://user-images.githubusercontent.com/1667306/95130131-66eb1480-075c-11eb-8a49-4311ecbda8e0.png">

Will be fixed with the next Nightly. :)
