### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by grewterd** [Komet/MediaElch#1030]
After updating my Nvidia drivers, MediaElch will not function, it immediately goes into a not responding state and never comes out of it. I have downloaded 2.6.6, unzipped into a new folder and still have the same issue. Please help.

**Comment by bugwelle** [comment]
Hi,

what system are you using, i.e. Windows 10 (and which specific version of it)? What driver version are you using? :)

**Comment by faugusztin** [comment]
@grewterd by any chance you had moved MediaElch to secondary (non-main) monitor ? I found out some apps (MediaElch, Ryzen Master) goes into not responding state when you move said application to second monitor, close the app and try to open it again. 

Solved the freeze for myself by deleting/renaming keys MainWindowPosition and MainWindowSize in the Computer\HKEY_CURRENT_USER\SOFTWARE\kvibes\MediaElch registry key.

**Comment by ticao2** [comment]
Or maybe, just for testing, if you are on Windows, install a portable version.

**Comment by bugwelle** [comment]
MediaElch now has Qt6 support which should be used for Windows 10 and later. You can download a version of MediaElch for Windows 10 or later on https://mediaelch.github.io/mediaelch-doc/download/windows.html

It fixes _many_ graphics related issues. I personally have no issues on a workstation with an Nvidia graphics card.

If the issue persists, feel free to reply and I will re-open it.

Regards,
Andre
