### ISSUE TITLE
[macOS Big Sur] MediaElch hangup during start: Qt issue

### ISSUE THREAD

**Issue by TheTalll** [Komet/MediaElch#1035]
As mentioned in subject:

trying to start MediaElch under macOS 11.0 Big Sur (Beta 10) results in a hangup. No window is opened and you only able to kill the application.

Also tried nightly build but same effect with the nightly build.

**Comment by bugwelle** [comment]
Hi,

thanks for opening this issue. At the moment I don't have any possibility to test macOS Big Sur. :-/

But I found quite a few Qt issues for macOS Big Sur, e.g. https://bugreports.qt.io/browse/QTBUG-85546
Seems that they don't yet fully support Big Sur.
Qt is our user-interface framework, i.e. it is responsible for displaying graphics.

What I can do at the moment is to add a note to the documentation that Big Sur is not supported.

Sorry for the inconvenience.


Regards,
Andre

**Comment by endanger** [comment]
same problem here

**Comment by masi0** [comment]
pity... mediaelch is the best tool for Mac..

**Comment by bugwelle** [comment]
Hi everyone,

I can finally install Big Surr and will check this issue. :)

**Comment by bugwelle** [comment]
<img width="780" alt="Screen Shot 2020-11-15 at 14 51 27" src="https://user-images.githubusercontent.com/1667306/99186659-1c44bb00-2752-11eb-8a27-a12904dcc064.png">


:)

Also some bad news: I won't be able to test old macOS versions anymore. My old MacBook Pro from 2010 just blew up (battery...).

**Comment by bugwelle** [comment]
I can confirm this issue. Re-compiling MediaElch helps. I'll see if I can update our TravisCI nightly-build to BigSur.

**Comment by bugwelle** [comment]
Our build-pipeline does not support macOS Big Sur, yet. But I've updated to macOS 10.15.7 for now: https://github.com/Komet/MediaElch/commit/1e790a2960781520c092fe6cdab876cd864ed95b

I'll build MediaElch for BigSur on my MacBook and will publish a Nightly in this thread.

**Comment by masi0** [comment]
Thanks. Any estimations when Big Sur will be supported at least as a Nightly?

**Comment by bugwelle** [comment]
Can't give any. This depends on TravisCI (which builds our Nightlies). I'm currently updating my system and will publish a `.dmg` in this thread.

In the meantime I've added a warning to the Download page: https://mediaelch.github.io/mediaelch-doc/download.html

See also: https://docs.travis-ci.com/user/reference/osx/

**Comment by masi0** [comment]
anyway, thanks a lot for your efforts :)

**Comment by marcuszani** [comment]
error in console:
MediaElch 2020-11-16 17:44:43.384 WARN  : Populating font family aliases took 1957 ms. Replace uses of missing font family ".SF NS Text" with one that exists to avoid this cost.

**Comment by bugwelle** [comment]
Finally got my Mac set up with Big Sur. Build & Package Script:

```sh
# Build
cd MediaElch
export SCRIPT_DIR="$(pwd)/travis-ci"
export PATH="$HOME/Qt/5.15.1/clang_64/bin/:$PATH"
git submodule update --init
svn checkout https://github.com/MediaArea/MediaInfoLib/trunk/Source/MediaInfoDLL
svn checkout https://github.com/MediaArea/ZenLib/trunk/Source/ZenLib
mkdir build && cd build
qmake CONFIG+=release CONFIG+=sdk_no_version_check ..
make -j$(sysctl -n hw.logicalcpu)

# Package
cd ..
export CXX=clang++
export CC=clang
export MEDIAINFO_VERSION=20.09
export TARGET_OS="macOS"
export OS_NAME="$(uname -s)"
export FILE_TYPE="dmg"
export GIT_BRANCH=master
export GIT_DATE=$(git --git-dir=".git" show --no-patch --pretty="%ci")
export RELEASE_DATE=$(date -ujf "%Y-%m-%d %H:%M:%S %z" "${GIT_DATE}" "+%Y-%m-%dT%H:%M:%S%z")
export ME_VERSION=$(sed -ne 's/.*AppVersionFullStr[^"]*"\(.*\)";.*/\1/p' Version.h)
export GIT_HASH=$(git --git-dir=".git" show --no-patch --pretty="%h")
export DATE_HASH=$(date -u +"%Y-%m-%d_%H-%M")
export DATE_DESC=$(date -u +"%Y-%m-%d %H:%M")
export VERSION_NAME="${ME_VERSION}_${DATE_HASH}_git-${GIT_BRANCH}-${GIT_HASH}"
export RELEASE_DATE=$(date -ujf "%Y-%m-%d %H:%M:%S %z" "${GIT_DATE}" "+%Y-%m-%dT%H:%M:%S%z")

wget --output-document MediaInfo_DLL.tar.bz2 https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/MediaInfo_DLL_${MEDIAINFO_VERSION}_Mac_i386+x86_64.tar.bz2
tar -xvjf MediaInfo_DLL.tar.bz2
mv MediaInfoLib/libmediainfo.0.dylib ./
rm -rf MediaInfoLib
rm MediaInfo_DLL.tar.bz2

cd build
git clone https://github.com/andreyvit/create-dmg.git
wget --output-document ffmpeg.7z https://evermeet.cx/ffmpeg/ffmpeg-4.3.1.7z
7za e ffmpeg.7z
cp ffmpeg MediaElch.app/Contents/MacOS/
cp ../libmediainfo.0.dylib MediaElch.app/Contents/MacOS/
macdeployqt MediaElch.app -qmldir=../src/ui -verbose=2
create-dmg/create-dmg \
		--volname "MediaElch" \
		--volicon "../MediaElch.icns" \
		--background "${SCRIPT_DIR}/macOS/backgroundImage.tiff" \
		--window-pos 200 120 \
		--window-size 550 400 \
		--icon-size 100 \
		--icon MediaElch.app 150 190 \
		--hide-extension MediaElch.app \
		--app-drop-link 400 190 \
		MediaElch_macOS_${VERSION_NAME}.dmg \
		MediaElch.app
```

DMG:
https://bintray.com/bugwelle/MediaElch/MediaElch-macOS/2.6.7-dev_macOS_Big_Sur/view/files#files/

<img width="1792" alt="Screen Shot 2020-11-17 at 11 09 15" src="https://user-images.githubusercontent.com/1667306/99376569-64d0b580-28c5-11eb-9a9b-dc50268a0f79.png">

**Comment by masi0** [comment]
Thanks! Works great!

**Comment by internetR** [comment]
Thanks its working again !!!!

**Comment by bugwelle** [comment]
Thank you all for confirming this! 😄

**Comment by bugwelle** [comment]
I've added a link to my beta `.dmg` file for now: https://mediaelch.github.io/mediaelch-doc/download.html

**Comment by Mobius60** [comment]
Thanks for the update for mac. Just one small thing;  the total number of movies listed doesn't reflect the actual number in my library.
It's a little short.  If I add a new movie, it increases the total, but it's till wrong.  I've tried deleting the .plist and rescanning, but nothing seems to help. Not a big deal, but is there any way to correct this?

**Comment by bugwelle** [comment]
Strange behaviour. Out of curiosity: How many movies do you have and how many are said to be there? :)

**Comment by Mobius60** [comment]
I have 1808 and MediaElch shows a total of 1801.  I've exported the list to a spreadsheet and it shows the proper total.

**Comment by bugwelle** [comment]
Thanks. Could you open another issue for it? How did you export it? It may be that MediaElch does not load certain directories. :)

**Comment by bugwelle** [comment]
New nightly is available at:

https://github.com/Komet/MediaElch/releases/tag/v2.7.0-beta.1
