### ISSUE TITLE
MediaElch shows white screen after first install

### ISSUE THREAD

**Issue by broszies** [Komet/MediaElch#1036]
**Describe the bug**
Wether starting MediaElch by Shortcut or by directly opening the exe, the app screen stays white. One context menue can be opened, but neither option picked does anything.

**To Reproduce**
1. Download MediaElch_2.6.6_win.zip from GitHub
2. Unzipp
3. Moved "MediaElch Folder to c\ProgramFiles
4. Created Shortcut from Exe on Desktop
5. Doubleclicked Shortcut OR Doubleclicked Exe in C:\ProgramFiles\MediaElch

**Expected behavior**
Expected the program to show with menues and buttons. Instead, Program window opens but stays white

**Screenshots**

**MediaElch Version:**
 - [X] 2.6.6 stable

**Operating System:**
 - [X] Windows 10
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**

**Comment by ticao2** [comment]
Very strange.
After all, this stable version has been available since 2020-04-18.
I am not a programmer but I have used MediaElch for many years.
Can you check some zip file size data?
Version 2.6.6 "Ferenginar"
MediaElch_2.6.6_win.zip - size 52,123 KB
in Properties
Size		50,9 MB (53.373.565 bytes)
Disk Size	50,9 MB (53.379.072 bytes)

**Comment by bugwelle** [comment]
> Moved "MediaElch Folder to c\ProgramFiles

That be be the issue. But I'm not really sure as I don't use Windows but I don't know if simply moving MediaElch to that system folder works. It may be that certain libraries refuse to load.

I'll have to check this myself on a Windows machine. What version of Windows 10 do you use? :-)

**Comment by broszies** [comment]
Hi,
file sizes all match. Using Windows 10 Pro 64bit, Build 18362.1139 T-420 Lenovo.

Fun Fact:
I downloaded the same file (or at least I clicked on the same link :)) with my work laptop (T-480), unzipped the files MOVED THEM TO A DIFFERENT FOLDER, and it worked like a charm.
So, no idea, but no harm done for now.
Regards

**Comment by broszies** [comment]
Update: New download, new attempt, same behaviour. The error persists.

**Comment by bugwelle** [comment]
Thanks! May be old settings or that MediaElch doesn't work with Admin rights. Honestly, I'm not sure. I don't have a Windows system to test on, at the moment.

**Comment by bugwelle** [comment]
Hi,

in the latest nightlies we switched to a more recent version of Qt (our GUI framework).
Could you test one of the latest Nightlies? I've tested them on Windows 10 and they work well. :)
