### ISSUE TITLE
What is MediaElch's intent on monetizing? => Always free

### ISSUE THREAD

**Issue by aTosser** [Komet/MediaElch#1048]
I was a user of TMM and with their recent decision to monetize the software, I began searching for alternatives. Before investing time and code contributions, I am curios what the monetization model for this project will be.

**Comment by Komet** [comment]
MediaElch is a spare time project started by myself and currently the main development is done by @bugwelle (thanks again!) and community members. Although we accept donations, you can always support MediaElch by testing, submitting code contributions and helping new users. MediaElch will stay free to use and won't be monetized.

**Comment by bugwelle** [comment]
I can just emphasise what @Komet has said!  
I've taken over MediaElch's development for the last >2 years and will keep doing so (even though I've got less and less time at the moment). I also do not plan to monetize anything like TMM does (also no paid addons or similar)! 😃 

Code contributions are always welcome. You can ping me anytime if you have questions. I could also give examples for smaller changes that would be appreciated if you want to dig into MediaElch's code. :)

I've tried to document MediaElch's development here: https://github.com/Komet/MediaElch/tree/master/docs/contributing
It gives a good overview about the development process.

See also: https://github.com/mediaelch

Also thanks for this question!

**Comment by mhendu** [comment]
I've had both TMM and MediaElch for a while but after upgrading TMM it wiped out my database with the new paid limit of 50 titles. Very disconcerting so I'm switching fully to MediaElch.

How do I donate money by the way? I know some Python and VBScript but not much of a coder so my coding contributions would, I think, not be helpful.

**Comment by bugwelle** [comment]
Python knowledge is very welcome :-)

I've worked on a python script which creates a fake library a while ago but haven't updated in quite a while. I've just made it public and you can find it at: https://github.com/bugwelle/mediaelch-test-library-generator

My goal is to generate a fake library with > 1000 titles which I can use to test MediaElch. It should be possible to:
 - use different folder structures
 - use different folder/file names (spaces, special characters,...)
 - have movies in multiple languages
 - movie collections
 - TV shows
 - ...

It would be awesome if my scripts could be improved. :-)
That script may be moved to github.com/mediaelch in the future.

**Comment by fabricionaweb** [comment]
Have you already think about enable the GitHub sponsor feature? I'd like to contribute

**Comment by bugwelle** [comment]
I have added this question to our FAQ, see https://mediaelch.github.io/mediaelch-doc/faq.html#what-is-mediaelch-s-intent-on-monetizing

I'll close this issue but a reference to it is kept in the FAQ :)
