### ISSUE TITLE
TMDb changes

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#1049]
Not a feature request
TMDb changes
I think it would be interesting for you to hear about this conversation here:
https://www.themoviedb.org/talk/5fae6bd5c613ce003d21bd61
I have no idea if it can affect MediaElch.

**Comment by bugwelle** [comment]
As always: Thanks for letting me know!

We don't assume an order for JSON properties so MediaElch is on the safe side here. We also use `character` instead of `character_name` so we're good as well. :)


Thanks and kind regards,

Andre
