### ISSUE TITLE
MediaElch doesn't show the right number of movies. 

### ISSUE THREAD

**Issue by Mobius60** [Komet/MediaElch#1053]
MediaElch loads all the movies in my directory, but displays the wrong number. I exported to 
a mac numbers spreadsheet, and it shows they are all there. All my movies are in individual folders under the same directory.

Thanks. Could you open another issue for it? How did you export it? It may be that MediaElch does not load certain directories. :)

_Originally posted by @bugwelle in https://github.com/Komet/MediaElch/issues/1035#issuecomment-729709439_

**Comment by bugwelle** [comment]
Hi,

one question: Do you store your movies in one directory or a directory for each movie? :)

**Comment by Mobius60** [comment]
They're stored in individual directories.  I finally discovered why the total number of movies didn't match.
I had some movies that had a directory with all the mediaelch files, but no video file, so the total number
of movies naturally weren't the same.  I should have closed this thread earlier.

**Comment by bugwelle** [comment]
Thank you for your reply. I'm glad that it works :)
