### ISSUE TITLE
TMDB ID

### ISSUE THREAD

**Issue by mhendu** [Komet/MediaElch#1055]
In the UI, and possibly behind-the-scenes, MediaElch doesn't seem to give users the ability to select the ID from TMDB. There are certain movies that aren't on IMDB (for instance, https://www.themoviedb.org/movie/654086-in-the-mood-for-love) so for scraping purposes would be great to have a TMDB ID.

**Comment by ticao2** [comment]
If I'm not mistaken, this feature was added some 30 days ago.  
In the version I'm using, Windows **2.6.7 2020-10-24**,  
when I put a number in the search field, the possibility to search for **TMDb ID** appears.

**Comment by mhendu** [comment]
Great! I'm using version 2.6.6, which I think is the latest version on the website, so didn't realize these features had been added.

**Comment by ticao2** [comment]
@mhendu   
Sorry, but I did an Edit that you may not have seen.
It took me a long time and when I updated I saw your answer.

**Comment by bugwelle** [comment]
@mhendu I wanted to release a new MediaElch version in August but due to time issues I didn't get to make the big changes that I want in the next version. But as @ticao2 mentioned, the next version will resolve your issue. :-)

I've adapted the changelog a bit as well. :)
