### ISSUE TITLE
Doesn't open in Big Sur mac OS

### ISSUE THREAD

**Issue by clamel71** [Komet/MediaElch#1059]
**Describe the bug**

**To Reproduce**
4. See error / Crash

**Expected behavior**

**Screenshots**

**MediaElch Version:**
 - [ ] 2.6.7-dev (nightly)
 - [ ] 2.6.6 stable

**Operating System:**
 - [ ] Windows
 - [x] macOS
 - [ ] Linux (distribution: _._)

**Additional context**

**Comment by bugwelle** [comment]
Hi,

this is a known issue and a duplicate of https://github.com/Komet/MediaElch/issues/1035 :-)

I've provided a binary that works on macOS Big Sur on the Downloads page here:
https://mediaelch.github.io/mediaelch-doc/download.html (see the warning box)
