### ISSUE TITLE
Use Tags in Episodes

### ISSUE THREAD

**Issue by ThePapaw** [Komet/MediaElch#1061]
Would like to be able to TAGS to episodes

Thanks for considering

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bugwelle** [comment]
Are episode tags supported by Kodi? :-)
(`<tag>` is not listed in the Wiki: https://kodi.wiki/view/NFO_files/TV_shows#nfo_Tags_2 but that may be a mistake)

**Comment by ThePapaw** [comment]
I am not really sure, they are listed here though:

https://kodi.wiki/view/Smart_playlists/Rules_and_groupings#Episodes

**Comment by bugwelle** [comment]
Ok, just checked and episode tags are not picked up by the "TV shows -> Tags" page. Only those that are inside TV show's `NFO` files.

Nevertheless, I think this should be straightforward to implement. Movies and TV shows already have this, after all. :-)

**Comment by ThePapaw** [comment]
cool, the way the database sites are beginning to implement tags in episodes now, Kodi will probably follow.

**Comment by bugwelle** [comment]
Good to know! :-)

**Comment by bugwelle** [comment]
This will be implemented with #1070

Please note that there aren't any scrapers that support tags, yet. IMDb supports it but I haven't adapted the scraper, yet.
