### ISSUE TITLE
Ability to use TMDB as Series Scraper

### ISSUE THREAD

**Issue by ThePapaw** [Komet/MediaElch#1064]
If this feature is available, I can't find it. Need the option to choose TMDB as a TV Show scraper. All I can find that I can change is IMDB & TVDB.

Kodi defaults to TMDB as it's TV Show Scraper, I wish MediaElch would allow me to choose it to scrape shows/episodes instead of having to use only TVDB & IMDB.

I like the mix, just wish TMDB would be included. Thanks for considering.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by txtsd** [comment]
Already in the works #972

**Comment by ThePapaw** [comment]
Awesome, TY

**Comment by bugwelle** [comment]
#972 is merged. A new nightly is now yet available, though. But the next nightly will support TMDb as a show and episode scraper. :-)

**Comment by bugwelle** [comment]
macOS Beta is now available: https://github.com/Komet/MediaElch/releases/tag/v2.7.0-beta.1

Others will follow.
