### ISSUE TITLE
Universal Music Scraper : language choice does not work

### ISSUE THREAD

**Issue by webghost666** [Komet/MediaElch#1065]
**Scrapers that don't work:**
 - [ x ] The Audio DB

**Details which are wrong / not loaded:**
Regardless of the language chosen in the settings (Settings>Scraper>Universal Music Scraper), the artist's biography is always retrieved in English, even if it is available in another language.
So if I try to scrape, for example, the biography of Belgian band dEUS (available on TADB in English and French), I'm not able to get it in French even if I specifically choose this language in the settings.

**MediaElch Version:**
 - [ x ] 2.6.7-dev (nightly)
 - [ x ] 2.6.6 stable

**Operating System:**
 - [ x ] Windows 10

**Comment by bugwelle** [comment]
Thanks! I'll have a look at it. :-)

**Comment by bugwelle** [comment]
Seems that no language is used for MusicBrainz. And for the others: I'm not yet sure which provider uses which data.
I'll have to do a rewrite of certain parts. Will take some time.

**Comment by bugwelle** [comment]
The issue is that we no longer get a response from TheAudioDb so the biography is loaded from AllMusic which only supports English. This happens because part of the TheAudioDb-APi became paid. And we use exactly those API-endpoints that require a paid API-key.

Will see if we can use another API-endpoint.

**Comment by bugwelle** [comment]
Hi,

with #1154 we have added MusicBrainz as a biography source. Please change your settings to prefer MusicBrainz over TheAudioDb. :-)

MusicBrainz supports translated texts. It uses the text from Wikipedia.
