### ISSUE TITLE
Segfault while loading information

### ISSUE THREAD

**Issue by TimB87** [Komet/MediaElch#1073]
**Describe the bug**
I have had that since I use MediaElch (maybe the past 2 or 3 versions) and with some files, it randomly happens - it may work after restarting - but I have some that _always_ fail with a segfault.

**To Reproduce**
1. Go to Movies or TV series
2. Richt-click on a title, select "load information" 
3. Select the title matching your movie or series
4. seg fault after it starts fetching.
I hope this is the relevant output of gdb.

```
MediaElch 2020-12-07 18:44:18.451 DEBUG : Entered, searchStr= "Continuum"
MediaElch 2020-12-07 18:44:18.590 DEBUG : [Search Results] Count:  16
MediaElch 2020-12-07 18:44:18.590 DEBUG : [Search Results] Count:  16
MediaElch 2020-12-07 18:44:21.600 DEBUG : Entered, enabled= false
MediaElch 2020-12-07 18:44:21.600 DEBUG : [MainWindow] Search field: disabled
MediaElch 2020-12-07 18:44:21.600 DEBUG : Entered, message= "Lade..." id= 20062
MediaElch 2020-12-07 18:44:22.163 DEBUG : Entered, enabled= true
MediaElch 2020-12-07 18:44:22.165 DEBUG : Entered, enabled= false
MediaElch 2020-12-07 18:44:22.165 DEBUG : [FanartTv] Load movie data with image types: QUrl("https://webservice.fanart.tv/v3/movies/12914?api_key=842f7a5d1cc7396f142b8dd47c4ba42b")
[New Thread 0x7fffede36640 (LWP 11181)]
[New Thread 0x7fff6ffff640 (LWP 11182)]
MediaElch 2020-12-07 18:44:22.355 DEBUG : [NotificationBox] Hide Progress bar with id 20062
MediaElch 2020-12-07 18:44:22.355 DEBUG : Entered, id= 20062
MediaElch 2020-12-07 18:44:22.355 DEBUG : Entered, msg= "Lade Bilder..." id= 20062
MediaElch 2020-12-07 18:44:22.355 DEBUG : Entered, message= "Lade Bilder..." id= 20062
MediaElch 2020-12-07 18:44:22.357 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/exCFVhFQWnVbGPbr2JeTQwK7Mgw.jpg")
MediaElch 2020-12-07 18:44:22.357 DEBUG : [DownloadManager] Start next download
[New Thread 0x7fff6e72c640 (LWP 11186)]
MediaElch 2020-12-07 18:44:22.358 DEBUG : [DownloadManager] Enqueue download | QUrl("http://image.tmdb.org/t/p/original/jT7tdu9ksHkdS4R13ieXNs5efYW.jpg")
MediaElch 2020-12-07 18:44:22.358 DEBUG : [DownloadManager] Enqueue download | QUrl("https://assets.fanart.tv/fanart/movies/12914/hdmovielogo/stargate-continuum-5209f4e1a6922.png")
MediaElch 2020-12-07 18:44:22.358 DEBUG : [DownloadManager] Enqueue download | QUrl("https://assets.fanart.tv/fanart/movies/12914/hdmovieclearart/stargate-continuum-520d3e3b180f8.png")
MediaElch 2020-12-07 18:44:22.358 DEBUG : [DownloadManager] Enqueue download | QUrl("https://assets.fanart.tv/fanart/movies/12914/moviedisc/stargate-continuum-52664e819ae72.png")
MediaElch 2020-12-07 18:44:22.358 DEBUG : [DownloadManager] Enqueue download | QUrl("https://assets.fanart.tv/fanart/movies/12914/moviebanner/stargate-continuum-520bf8ae11239.jpg")
MediaElch 2020-12-07 18:44:22.358 DEBUG : [DownloadManager] Enqueue download | QUrl("https://assets.fanart.tv/fanart/movies/12914/moviethumb/stargate-continuum-520d41c19f56e.jpg")

Thread 1 "MediaElch" received signal SIGSEGV, Segmentation fault.
0x00007ffff794da45 in void QWidgetPrivate::update<QRect>(QRect) () from /usr/lib/libQt5Widgets.so.5
```
qt5 version is 5.15.2 and is compiled on this machine. I have no other faults with qt applications and this is reproducible on another machine I use. 

**Expected behavior**
It does not segfault while it fetches informations.

**MediaElch Version:**
 - [x] 2.7.0-dev
 - [x] 2.6.7-dev (nightly)
 - [x] 2.6.6 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: [CRUX](https://crux.nu))

**Comment by bugwelle** [comment]
Have you checked the latest master? Does it still happen there?

I always run MediaElch with Google's AddressSanitizer enabled. I thought I fixed this issue...

**Comment by TimB87** [comment]
This is with 2.6.7-dev, shall I still compile and try master?

**Comment by bugwelle** [comment]
v2.6.7-dev has been around since March. :)

Would be great if you could try the latest master. Thank you 😃

**Comment by TimB87** [comment]
Pardon me, I am trying 2.7.0-dev right now 😬 The bug report only stated 2.6.7 and I didn't double check 😪

**Comment by bugwelle** [comment]
Thanks! :-)

What scraper are you using and what movie do you scrape? I'll try this on a Linux machine in the next days.

**Comment by TimB87** [comment]
Hey! Sorry for the late answer.

It doesn't really make any difference which scraper I use (as far as I can tell at least) - but in the posted snipped I was using The Movie DB, and the movie is "Stargate: Continuum (2008)".
Thanks for looking into it 😀

**Comment by bugwelle** [comment]
hmm... Tested with:

 - macOS Debug mode, Qt 5.15.2 (+address sanitizer)
 - macOS Release mode, Qt 5.15.2
 - Linux Debug mode, Qt 5.12 (+address sanitizer)

Will test other setups as well. Seems to be a race condition... Oh man.

**Comment by TimB87** [comment]
Snap. I am afraid coding wise I might not be of any help here :| but if I can help debugging in any way please let me know!

**Comment by bugwelle** [comment]
Could you compile MediaElch in Debug mode and test it again? And if it fails could you paste the stacktrace (like the one you posted before?)? :smiley: 

I'm 95% sure it's a bug in our DownloadManager.

**Comment by TimB87** [comment]
This maybe a dumb question, currently I use qmake to build (as cmake fails to locate external quazip [as does qmake, but that i have solved with some seds and i haven't spend much time on the cmake approach yet]) - how do I build the debug version with qmake?

**Comment by bugwelle** [comment]
It should work with `qmake CONFIG+=debug` :-)

See https://doc.qt.io/qt-5/qmake-variable-reference.html#config

**Comment by TimB87** [comment]
I hope this is correct, steps taken:

1. `gdb MediaElch`
2. `set logging file elk.log`
3. `set logging on`
4. `run`
5. `steps in op`
6. `bt`
7. posting gdb.txt here 

[elk.log](https://github.com/Komet/MediaElch/files/5660112/elk.log)

**Comment by bugwelle** [comment]
Thank you for the `elk.log` file!

I see this line:

```
#2  0x00007fffefdcb8e4 in Kvantum::Style::advanceProgressbar() () from /usr/lib/qt5/plugins/styles/libkvantum.so
```

It didn't occur to me but we may have a race condition when we update the progress bar...
Signals and Concurrency is difficult...

OffTopic: Do you use this theme? https://github.com/tsujan/Kvantum/tree/master/Kvantum 😄 

-------------

> Another edit: sorry, I just realized there are more tickets opened for that issue 😪

I know. But I couldn't fix it, yet. 😭 
I'll leave this issue open. Thank you for testing MediaElch!

**Comment by TimB87** [comment]
yes, i use kvantum, i noticed it as well. I can try without kvantum in a bit and see if that makes any difference :-) but it'll have to wait for a bit

**Comment by bugwelle** [comment]
No you don't have to, other users have reported it with different systems. :-)
It's an issue with MediaElch.

**Comment by TimB87** [comment]
Ok, scrap the it has to wait part. I went with the quick and dirty method and removed kvantum completly for a second, scraping that movies information was now possible!

Maybe it's your refactored code for the new release, but it's also considerably fetching stuff faster.

**Comment by bugwelle** [comment]
I haven't touched the movie scrapers but I'm glad to hear that. 😄 
Ok, so it's the parallel updating of the progress bar that crashes the software on some systems...

You don't happen to have a quick start guide for CRUX with kvantum, do you? If I can't figure out what may be wrong then I have to reproduce it somehow. :)

**Comment by TimB87** [comment]
[a very old quickstart](https://crux.nu/Wiki/QuickInstallReference2-4) but not much has changed (well, UEFI is now a thing, if you don't virtualize). The handbook really isn't that long.
kvantum and mediaelch are in contrib repository, which needs to be enabled, I maintain both those ports. kvantum needs another repository enabled: [kde5 repository by T. Henschel](https://crux.nu/portdb/?a=repo&q=kde5)

If you don't feel hyped about configuring your own kernel, a quick and dirty solution is to take someone elses :D like arch or ubuntu. You could still do a `make localyesconfig` afterwards and then do some more changes without weeding through the wild.

After having the box setup it's condensed to:
1. enabling contrib and kde repos
2. `ports -u`
3. `prt-get depinst $someWMorDM kvantum mediaelch` (I use i3 on my desktop, sway on my notebook - both with kvantum and the error described here)
4. wait for some time, depending on your machine, as CRUX is a source based distro and you'll compile everything yourself (ccache and distcc are your friends)
5. done :) well, kvantum needs to be set up, but it's launching the gui and selecting a theme and that's pretty much about it already

CRUX 3.6 was just released some minutes ago, I was doing all that on 3.5. It should be the same, but it might make sense to utilize 3.5 if you want to test it yourself.
Feel free to shoot me more questions about it (freenode -> beerman)! For now, I'll have to run :-)

**Comment by bugwelle** [comment]
Hi,

I've opened a PR which may (or may not) fix this issue. Could you test it with kvantum? I haven't reproduced the bug, yet.

```sh
git clone https://github.com/bugwelle/MediaElch.git
git checkout downloadmanager # branch with fixes
mkdir build
cd build
qmake .. CONFIG+=release
make -j$(nproc)
```

See https://github.com/Komet/MediaElch/pull/1076

**Comment by bugwelle** [comment]
Ok, wait.. There's a new issue. I'll let you know when the PR is ready for testing.

**Comment by bugwelle** [comment]
Ok, ready to go :-)

**Comment by TimB87** [comment]
Hi!
Sorry, I haven't found the time yesterday. I tried it now between sessions and same error with the Series "Money Heist":
```
0x00007ffff794da45 in void QWidgetPrivate::update<QRect>(QRect) () from /usr/lib/libQt5Widgets.so.5
```
I tried a few times now and always hit it again.

**Comment by bugwelle** [comment]
Oh no... :/
Ok. Then I'll set up a VM.

**Comment by TimB87** [comment]
If you do it with CRUX, please take 3.5 for this test, I am in the process of updating my notebook but it'll take me some time, so I can't tell anything about that yet.
And if you run into questions, feel free to join #crux on freenode or hit me up directly. Thanks for digging into it!

**Comment by bugwelle** [comment]
Could you also try out this PR?
https://github.com/Komet/MediaElch/pull/1077

```sh
git checkout paralleldownloadmanager # branch with fixes
```

I checked my Kubuntu System with kvantum and MediaElch didn't crash with the current master... Will look into your distro. :)

**Comment by bugwelle** [comment]
Closing in favor of  #1060

I was able to reproduce the crash there.

**Comment by TimB87** [comment]
Hi! Sorry, I had troubles with some hardware failing on my Desktop where I tried it all, this sounds great! I will try out master in a bit, I just got it booted again

**Comment by bugwelle** [comment]
Master branch won't help you. :-)
If a branch works (and I haven't tested it)  then `paralleldownloadmanager` from #1077 but I don't think it will help.

**Comment by TimB87** [comment]
Indeed, it doesn't work :| Sorry I won't be of much coding help with that, if you need someone to test it though, feel free to tag me!

**Comment by bugwelle** [comment]
Hi,

I just wanted to inform you that I was able to reproduce this issue on Manjaro XFCE and that the bug will be fixed by #1078.
Turns out that this bug only happened with Kvantum installed which is why I wasn't able to reproduce this bug (I used Manjaro KDE for testing before...).

Regards,
Andre

**Comment by bugwelle** [comment]
@TimB87 Thanks. I'm 99% sure that #1078 will fix this issue once and for all. :smile:

**Comment by TimB87** [comment]
@bugwelle indeed it does seem to do that 🎊

**Comment by bugwelle** [comment]
Thank you so much for confirming it! :smile:
