### ISSUE TITLE
Renamer: Allow replacing spaces with other delimiters

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#1082]
**Is your feature request related to a problem? Please describe.**
Spaces in filenames are sometimes not wanted. It should be possible to replace them with other delimiters.

**Describe the solution you'd like**
I want to be able to replace spaces with `_`, `.` and other characters.

**Additional context**
Requested on the Kodi Forum. See https://forum.kodi.tv/showthread.php?tid=136333&pid=2995289#pid2995289

**Comment by norg** [comment]
I would also like this feature :) I migrated my DB from TMM to MediaElch now and quite happy. Currently I run a bash script to convert the spaces to underscore.

Can you give some hints for someone new to the project but willing to try to implement it?

**Comment by bugwelle** [comment]
Hi,

thank you very much for your interest in MediaElch. :-)

There are few files that are of interest. `RenamerDialog.cpp` (+`.h` and `.ui`) as well as `Renamer.cpp` and its variants (`MovieRenamer.cpp`, `ConcertRenamer.cpp` etc) in `src/renamer`).

You'd need to change the UI to add a way to configure space->char transformation as well as need to modify the appropriate classes (`MovieRenamer`, etc).

For building MediaElch, see https://mediaelch.github.io/mediaelch-doc/contributing/build/index.html

Regards,
Andre

**Comment by taniashafiei** [comment]
Hello, I also found this feature interesting and I implemented it in the PR #1827 :D .

**Comment by bugwelle** [comment]
Implemented by @taniashafiei 

The next snapshot version will contain this feature :)
