### ISSUE TITLE
Compiler error: ‘SplitBehaviorFlags’ in ‘class QString’ does not name a type

### ISSUE THREAD

**Issue by gieselbusch** [Komet/MediaElch#1099]
Hello,
I can't compile MediaElch from github (2.8.1-dev). Every time i get the following error while compiling main.cpp:

`In file included from ../src/globals/Helper.h:5,
                 from ../src/data/MediaInfoFile.cpp:3:
../src/globals/Globals.h:17:36: error: ‘SplitBehaviorFlags’ in ‘class QString’ does not name a type
 using ElchSplitBehavior = QString::SplitBehaviorFlags;
                                    ^~~~~~~~~~~~~~~~~~
`

My system is Debian Buster with Qt 5.11.3

Thank you!

**Comment by gieselbusch** [comment]
I'm relay not a developer. But from my point of view there a several errors in the code.
The first one causing the error above, I don't understand.
But I think I've found a second one: In QString, there is nothing named SplitBehaviorFlags.

**Comment by bugwelle** [comment]
Thanks! My bad, sorry. Will be fixed by #1100. :-)
