### ISSUE TITLE
GitHub: Unable to download due to low download speed (350bytes/second)

### ISSUE THREAD

**Issue by cairon-ha** [Komet/MediaElch#1101]
Hi there,

not a problem with Media Elch but: I am trying to download the current version since days an I have a 350 bytes (!) per second download speed.

Do you have a mirror for downloading?

Greets
Cairon

**Comment by bugwelle** [comment]
Hi, at the moment, no. I'll create a mirror on bintray.com. :-)

**Comment by bugwelle** [comment]
Mirror available at: https://bintray.com/bugwelle/MediaElch/MediaElch-Releases/v2.8.0#files

**Comment by bugwelle** [comment]
Documentation will be updated shortly.
