### ISSUE TITLE
2.8.0 AppImage produces linker errors

### ISSUE THREAD

**Issue by rmaeder** [Komet/MediaElch#1105]
**Describe the bug**
Trying to run the AppImage, I get
```
> ./MediaElch_linux_2.8.0_2020-12-13_git-d69831f1.AppImage 
/tmp/.mount_MediaEg1zSeH/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_MediaEg1zSeH/usr/bin/../lib/libpulse.so.0)
/tmp/.mount_MediaEg1zSeH/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_MediaEg1zSeH/usr/bin/../lib/libpulsecommon-13.99.so)
/tmp/.mount_MediaEg1zSeH/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_MediaEg1zSeH/usr/bin/../lib/libsystemd.so.0)
/tmp/.mount_MediaEg1zSeH/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_MediaEg1zSeH/usr/bin/../lib/libsndfile.so.1)
/tmp/.mount_MediaEg1zSeH/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_MediaEg1zSeH/usr/bin/../lib/libFLAC.so.8)
```

**To Reproduce**
run the AppImage in a shell.

**Expected behavior**
The app should launch

**MediaElch Version:**
 - [ ] 2.8.1-dev (nightly)
 - [X] 2.8.0 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [X] Linux (Debian: 10)

**Additional context**
The previous app image, MediaElch_2.6.6_win.AppImage, worked fine.

**Comment by bugwelle** [comment]
hmmm... I build the AppImage on KUbuntu 20.04. That may be the issue here.

I plan to release a new version tomorrow. I'll try to use Ubuntu 16.04 again.

**Comment by rmaeder** [comment]
I just tried it on my Ubuntu 20.04, and it works there.

**Comment by bugwelle** [comment]
The AppImage creators recommend to build on the oldest still supported distribution which is Ubuntu 16.04. :-/
We'll see tomorrow. :-)

If v2.6.6 worked then so should v2.8.2 if I build it on Ubuntu 16.04.

**Comment by bugwelle** [comment]
New AppImage is available. It was build on Ubuntu 16.04.

https://github.com/Komet/MediaElch/releases/tag/v2.8.2
https://bintray.com/bugwelle/MediaElch/MediaElch-Releases/v2.8.2#files

(bintray may need a few hours until the binaries appear)
