### ISSUE TITLE
[Scraper] TVDb - Language List

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#1119]
[Scraper] TVDb - Language List

I installed to test, in **Portable** mode, version **2.8.3 2020-12-20**
Today I noticed that in the TVDB Language List there is only one Portuguese.
And on the TVDB website there is a differentiation between pt-PT and pt-BR.
For example at Dr. House.
And from Dr. House I got the following list of languages:

` čeština dansk Deutsch ελληνική γλώσσα English suomi français עברית hrvatski jezik Magyar italiano 日本語 한국어 Nederlands Norsk bokmål język polski Português - Portugal русский язык slovenski jezik español svenska Türkçe 大陆简体 eesti العربية Português - Brasil 
`

I know that the TVDb will be by subscription from 2021 onwards.
But even so, it may be interesting to add.
In fact, when I made the Scraper I didn't even check if the data that came is from BR or PT.

**Comment by bugwelle** [comment]
Hi,

thanks. Just out of curiosity: Do you intend to subscribe to TheTvDb? :)

**Comment by bugwelle** [comment]
I just checked with their API v3: 

They list "pt" twice. "Portugal" and "Brazil". However, it seems we can't distinguish between them since their key is both "pt". :-/
Will have to check manually, though.

``` json
{
      "id": 214,
      "abbreviation": "pt",
      "name": "Português - Portugal",
      "englishName": "Portuguese - Portugal"
    },
    {
      "id": 26,
      "abbreviation": "pt",
      "name": "Português - Brasil",
      "englishName": "Portuguese - Brazil"
    },
```

See https://api.thetvdb.com/swagger and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

**Comment by ticao2** [comment]
> thanks. Just out of curiosity: Do you intend to subscribe to TheTvDb? :)

No, not even think. **:-)**
I already collaborate on TMDb with Films.
My Series collection is very small, but if I need to, I will go to TMDb.
And this question of 2 pt in fact being just one, already made me laugh.
It looks like marketing department solution.

**Comment by bugwelle** [comment]
Ah ok. In that case I will remove TheTvDb, see #1120  (unless there are users that _really_ want to use it).

I will close this issue. If we want to continue to support TheTvDb then I have to update to their API v4 (we use v3). That API may support more language variants. But v3 does not as far as I can see. :-/

**Comment by ticao2** [comment]
Just to make it a little worse.
In the TVDb, the translations for PT and BR are really different.
Just out of curiosity, I will compare what I did scraper and find out which pt I am actually receiving.
These people are very crazy.

**Comment by bugwelle** [comment]
Another point to drop support for their site ...

**Comment by ticao2** [comment]
House Season 8 is a good example. There are translations for **pt-PT** and **pt-BR**.
In pt-BR the episode titles are translated.
In pt-PT the episode titles **are not** translated.
I made the Scraper and the untranslated titles came.
And in the first episode, the overview has a small difference.
And came the overview in pt-PT.
Therefore, I believe they **only send pt-PT**.
Perhaps in API v4 will come pt-BR. But this problem is only for future users of TVDb. 
Maybe they'll complain to you.
It's not my case. **:-)**
