### ISSUE TITLE
Add WebM container and other codecs to the search function.

### ISSUE THREAD

**Issue by MatthewAllan93** [Komet/MediaElch#1122]
**Is your feature request related to a problem? Please describe.**

Yes it is, I have a couple of tv show episodes that use the WebM container.

**Describe the solution you'd like**

I would like the WebM container to be added to the TV Shows section of MediaElch. So that the episodes can be detected and information can be downloaded for them.

**Describe alternatives you've considered**

Another feature that I have considered that could be included in MediaElch is in the search function for the movies. I think more video codecs and audio codecs should be added.

**Additional context**

**Comment by bugwelle** [comment]
Hi,

good point. I can add `.webm` to the default file file filters. But you can already add it using an `advancedsettings.xml` file:

https://github.com/Komet/MediaElch/blob/d3b7ca579cd19a74a172e08b379a7a393f46001e/docs/advancedsettings.xml#L151-L157

https://mediaelch.github.io/mediaelch-doc/settings.html#advanced-settings
