### ISSUE TITLE
UI unusable on high-DPI laptop (Surface Book)

### ISSUE THREAD

**Issue by devhawk** [Komet/MediaElch#1134]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bugwelle** [comment]
Hi,

thank you for reporting this issue. Does MediaElch look the same as in  #429 ?

I'll close this issue as a duplicate of  #429. I don't have a Windows machine to test this on, though. And I couldn't find an easy fix for this, yet.
