### ISSUE TITLE
Rename feature request add <studio> in the rename

### ISSUE THREAD

**Issue by myxtrastufff** [Komet/MediaElch#1136]
**Describe the solution you'd like** I would like to use the "placeholder" of studio in renaming.
A clear and concise description of what you want to happen. Allow <studio> to be using in renaming

**Describe alternatives you've considered** editing the nfo file to rename movie folder or using a third party renaming solution

**Additional context**
example for Iron Man (2008)

currently yields 
<title> (< year >) (< studio >)  = Iron Man (2008) (studio)

would like 
<title>  (< year >) (< studio >)  = Iron Man (2008) (Paramount Pictures)

**Comment by bugwelle** [comment]
Hi,

I can do that. However, how should we handle multiple studios? Should they be concatenated by spaces, commas? 

Regards,
Andre

**Comment by myxtrastufff** [comment]
I'm not sure. Is there a way to do studo1 studio2 etc or is that not possible since the nfo file just lists the multiple studios on a new line? Up to you. I appreciate the change!

**Comment by myxtrastufff** [comment]
Would it be possible to delete the multiples from the GUI to use only one?

**Comment by ticao2** [comment]
And taking advantage of the theme, but for other reasons, 
would it be possible to delete all studios from all **.nfo** in my movie collection?
Any good ideas on how I can do this? **:-)**

**Comment by bugwelle** [comment]
> Would it be possible to delete the multiples from the GUI to use only one?

If go to a movie -> "Extended" tab, you can de-select studios that you do not want.

I will add `studio` as a replacement. If there is more than one studio, they will be concatenated and be separated by a comma.

**Comment by bugwelle** [comment]
> And taking advantage of the theme, but for other reasons,
would it be possible to delete all studios from all .nfo in my movie collection?
Any good ideas on how I can do this? :-)

Not possible with MediaElch. :-/
I also don't have any idea how to simply achieve that. :-/

**Comment by ticao2** [comment]
> Not possible with MediaElch. :-/

I already suspected that there is no such feature.
I'll see if it is possible using GrepWin.

As for the issue of a single studio, there is the feature of advancedsettings.xml
It is not ideal because the most important studio is not always the first on the list, but ...

`advancedsettings.xml



	<studios>
		<useFirstStudioOnly>false</useFirstStudioOnly>
		<map from="Studio 1" to="Studio 2" />
	</studios>`

**Comment by myxtrastufff** [comment]
bugwelle, thanks for the quick fix! I am new to MediaElch and I am liking the features!

**Comment by bugwelle** [comment]
> As for the issue of a single studio, there is the feature of advancedsettings.xml

Yes. :-/
Only the first one will be used in that case...


> bugwelle, thanks for the quick fix! I am new to MediaElch and I am liking the features!

You're welcome. :-)
I may release a new nightly this evening (timezone UTC+1 for Germany)

**Comment by myxtrastufff** [comment]
I just upgraded to ver 2.8.4.
In the movies directory I have a folder named Iron Man 2 with a dummy file named Iron Man 2.mp4 inside the folder.

\Movies\Iron Man 2
\Movies\Iron Man 2\Iron Man 2.mp4

I scrape it with tmdb everything comes back as expected.
I click on the save button and a .nfo file is written.
I click on rename and the actors directory stays in the base Iron Man 2 folder and new folder is created inside of the Iron man 2 folder called "Iron Man 2 (2010) (Marvel Studios,Paramount)" The rest of the files (mp4/jpg/png) are renamed and moved into the "Iron Man 2 (2010) (Marvel Studios,Paramount)" folder.

\Movies\Iron Man 2
\Movies\Iron Man 2\.actors
\Movies\Iron Man 2\Iron Man 2 (2010) (Marvel Studios,Paramount)\Iron Man 2 (2010).mp4
\Movies\Iron Man 2\Iron Man 2 (2010) (Marvel Studios,Paramount)\Iron Man 2 (2010).nfo
\Movies\Iron Man 2\Iron Man 2 (2010) (Marvel Studios,Paramount)\Iron Man 2 (2010)-poster.jpg (plus all the rest of the files)

Is this the expected behavior? 

My expected behavior is that the new folder "Iron Man 2 (2010) (Marvel Studios,Paramount)" is created in the root of movies directory (same directory as Iron Man 2 folder is in) and all files and actors directory are moved into "Iron Man 2 (2010) (Marvel Studios,Paramount)" 

\Movies\Iron Man 2 (2010) (Marvel Studios,Paramount)\.actors
\Movies\Iron Man 2 (2010) (Marvel Studios,Paramount)\Iron Man 2 (2010).mp4
\Movies\Iron Man 2 (2010) (Marvel Studios,Paramount)\Iron Man 2 (2010).nfo
\Movies\Iron Man 2 (2010) (Marvel Studios,Paramount)\Iron Man 2 (2010)-poster.jpg (plus all the rest of the files)

my settings

Rename files 
<title> (< year > ) . <extension>
<title> (< year > )  pt<partNo>.<extension>

rename directories
<title> (< year >) (< studio >)

**Comment by bugwelle** [comment]
> Is this the expected behavior?

No. And I tested it locally and could not reproduce it. :-/

Did you enable "separate folders" for your movie directory in MediaElch's settings? :)

**Comment by myxtrastufff** [comment]
If I understand your separate folders question. You are asking about Settings > Movies tab >  "Movie Set Artwork" option? That is set to Artwork next to movies. 

I believe that all my settings are default except the movies path and the setting to make "studio" part of the rename.

I deleted the registry key from windows and downloaded a fresh copy of mediaelch 2.8.4, I ran the installer/executable set my movies directory and did the same as above and scraped Iron Man 2. I got the same results as above with all default settings. Tried another movie and same result. where movies is renamed into a sub folder of original folder and actors folder stays in original folder.

Running mediaelch on Windows 10
Movies are on a share that is mapped to the Z drive in windows.
Windows 10 and share drive are on same local lan

**Comment by bugwelle** [comment]
> If I understand your separate folders question. You are asking about Settings > Movies tab > "Movie Set Artwork" option? That is set to Artwork next to movies.

No. I mean this: :-)

<img width="1003" alt="Screen Shot 2021-01-14 at 20 03 22" src="https://user-images.githubusercontent.com/1667306/104636400-9981a300-56a3-11eb-9493-6a80e01aab4b.png">

**Comment by myxtrastufff** [comment]
:) Thats was it!. Thank you!

I have one more question. If I already have a scrapped movie with .nfo and everything else. Is there a way to use MediaElch's renamer function to rename it without having to "save" the nfo file? Use the example above with Iron Man 2. Two months from now I decide my whole collection no longer needs the studio info in the folder name. When I try to change just the naming on previously scrapped movie I get a message Movie "Iron Man 2" has been edited but is not saved Finished. Is it possible to allow the rename to happen without having to click save? It's not a huge issue as I could always load up the library and click "save all" and I assume that would do it. This would be more of a convenience for me being lazy.. ;)

**Comment by bugwelle** [comment]
> I have one more question. [...]

Renaming should not mark the movie as unsaved. However, there is a bug where just clicking on the movie marks it as unsafed. :)
