### ISSUE TITLE
Movie/TV Show Year Autotag

### ISSUE THREAD

**Issue by GarfieldS** [Komet/MediaElch#1139]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to export my current list of scrapes with TV/Movie Year to make categorizing and filtering media by year very simple. 

**Describe alternatives you've considered**
I looked to see if there was an export feature that could export the info to an Excel compatible format but did not find any that would also allow me to choose attributes. Potentially other software could handle this but wanted to see if it was possible withing the program itself. There is a date for when first aired and that attribute is good enough because in Excel it would be easy to get the year.

**Additional context**
I create an online searchable TV/Movie Portal and would like to add this attribute as another way for users to find content. Eventually, I would love to allow searchers for 80's, 70's, 90's, etc.

**Comment by ticao2** [comment]
> I would like to export my current list of scrapes with TV/Movie Year  

I don't know if this will help you, but ...
I needed to export my movie collection to an HTML table and an Excel spreadsheet.
And I created 5 themes for exporting data.
The spreadsheet theme, in .csv, is attached here.
Just place the **T_csv10** folder inside the **export_themes** folder that is in the **MediaElch.exe** folder.
When you open your MediaElch, it will be one of the export options.

[T_csv10.zip](https://github.com/Komet/MediaElch/files/5752583/T_csv10.zip)
The text is in my language but if you think you can solve your problem I can put everything in English.

**Comment by GarfieldS** [comment]
> The spreadsheet theme, in .csv, is attached here.

Thank you very much. I will test

**Comment by GarfieldS** [comment]
I was unable to find an export_themes folder

**Comment by ticao2** [comment]
> 
> I was unable to find an export_themes folder

You can create the folder yourself, but I think the best solution, the safest, will be the following.
The **export_themes** folder is automatically created when you install any of the themes that come with MediaElch.
Then go to **Settings > Export**
You will see the list with **4 themes** that can be installed.
**DigitalRabbit - Datatables**, **Dummy Theme**, **Hidaya Theme** and **MediaElch**.
I suggest installing the **Dummy Theme**. It may be useful in the future.
Then click on its green button and it will be installed inside the **export_themes** folder that will be automatically created inside the MediaElch.exe folder.
I believe that it is now better to **close MediaElch**.
Copy the folder I sent into this newly created folder.
The folder name, **T_csv10**, cannot be changed.
Then open MediaElch and go to **Settings > Export** again.
If everything went well, you will see the **Dummy Theme** and my **T_csv10** theme added to the list of those already installed.

**Comment by GarfieldS** [comment]
I expected that would be the process and I did that before you even replied. 
I still do not see the export folder and I am using Window 10 and the latest version. 

I wonder if anyone else has a similar issue. I installed all the themes and now they say "Uninstall" in red. 
I check the folder for version 2.8.2 and don't see an export_themes folder

**Comment by GarfieldS** [comment]
I was able to do an export using the existing Export templates and I think this provides what I want at a minimum. 

I can convert the HTML to a format that can work with Excel. 

If I figure out how export works I'll use your template. 

Thank you for your assistance.

**Comment by ticao2** [comment]
My installation is in Portable mode.
Yours should be in normal mode.
So we need to find out where the Export_ Themes folder is created.
It can be in the folder of installed programs or maybe in 
a folder MediaElch that is probably in **User > YourName > APP Data> Roaming**.

I will reread the instructions.
I believe that there is indicated where the folder is.

**Comment by ticao2** [comment]
See here https://mediaelch.github.io/mediaelch-doc/export/create-theme.html

`

        Mac OS: /Users/username/Library/Application Support/kvibes/MediaElch/export_themes/dummy

        Linux: /home/username/.local/share/kvibes/MediaElch/export_themes/dummy

        Windows: C:\Users\username\AppData\Local\kvibes\MediaElch\export_themes\dummy

`

**Comment by GarfieldS** [comment]
Success!

Thank you. I was able to test the current exports and yours. 
I am inspired by this and may create my own template. 
Some templates work better than others. 

The Hidaya Template is impressive. 
https://github.com/stunkymonkey/hidaya

Thank you for pointing me to the guide as well I had forgotten where to find that as I investigate more of the features of MediaElch

**Comment by bugwelle** [comment]
FYI, #1147 will add a CSV export function for movies. Columns can be reordered, etc.
