### ISSUE TITLE
Renamer: Avoid path components with leading dots

### ISSUE THREAD

**Issue by acolomb** [Komet/MediaElch#1150]
I've encountered a movie (TMDb ID 9437) where the (localized German) title starts with an ellipsis (...). It's written as three simple dots, not using the single unicode character.  That movie was missing in the movies list after import, presumably because the leading dots were treated as a hidden directory or maybe MediaElch got confused about the baseFileName (nothing before first dot) and the extension?

I think such file / directory names should be avoided at all.  If a path component starts with one or more dots, they should be simply dropped during renaming.

**Describe alternatives you've considered**
One could use the sortTitle field to override the scraped title, but then batch renaming files becomes hard because ususally that field is empty.  I haven't found a way to conditionally use title instead of sortTitle when the latter is empty.

**Additional context**
Seeing that MediaElch starts sanitizing file names in the upcoming version, I think this feature will be a good fit to refine that functionality.

**Comment by bugwelle** [comment]
Thanks! The next MediaElch version already does some basic filename sanitizing, from the changelog:

> Renamer: Special characters that are not allowed in filenames are now replaced by a space.
Windows disallows the following characters in filenames: <, >, :, ", /, \, |, ?, *. MediaElch now does a bit of filename sanitization, even if not a lot.

Checking if the filename starts with a dot seems like a good idea! Thanks. :-)

**Comment by bugwelle** [comment]
Oh, seems we already did some filename sanitization. Still, this will be added. :-)

**Comment by acolomb** [comment]
Thanks for the quick fix, @bugwelle.  I skimmed over the code changes and it looks good from my side.  Tested with current master on the problematic file through manual rename and through a fresh import.  Both worked as expected.

Good work!

**Comment by bugwelle** [comment]
Thanks for confirming it! 😄
