### ISSUE TITLE
AdultDVDEmpire Scraper does not load actor thumbs (TEST also fail)

### ISSUE THREAD

**Issue by waywit** [Komet/MediaElch#1164]
**Scrapers that don't work:**

 - [X] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [X] TmdbConcert
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [X] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
The actor pictures are not loaded and stored to .actors folder. 
The scraper test also fail with the following error:

```
-------------------------------------------------------------------------------
AdultDvdEmpire scrapes correct movie details
  Movie has correct details
-------------------------------------------------------------------------------
../test/scrapers/testAdultDvdEmpire.cpp:22
...............................................................................

../test/scrapers/testAdultDvdEmpire.cpp:60: FAILED:
  CHECK( actorThumb == "https://imgs1cdn.adultempire.com/actors/652646h.jpg" )
with expansion:
  ""
  ==
  "https://imgs1cdn.adultempire.com/actors/652646h.jpg"

[ImdbMovieLoader] Loading movie poster detail view
```

**MediaElch Version:**
 - [ ] 2.8.3-dev (nightly)
 - [ ] 2.8.2 stable
 - [X] git master

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [X] Linux (distribution: ___)

**Additional context:**
2 other scraper test also fail:

```
../test/scrapers/imdbtv/testImdbTvShowSearch.cpp:32: FAILED:
  CHECK( scraperResults[0].title == "Scrubs - Die Anfänger" )
with expansion:
  "Scrubs: Die Anfänger"
  ==
  "Scrubs - Die Anfänger"
```

And also:
```
-------------------------------------------------------------------------------
../test/scrapers/tmdbconcert/testTmdbConcert.cpp:48
...............................................................................

../test/scrapers/tmdbconcert/testTmdbConcert.cpp:62: FAILED:
  CHECK( m.runtime() == 100min )
with expansion:
  223 m == 100 m
```

**Comment by bugwelle** [comment]
Oh, yes. I forgot about this. There were changes on their site. Thanks for the reminder. I'll look into it.
The "Scrubs" issue isn't an actual bug. The scraper only changed the German translation. I'll update our tests.
And for the concert: I'm a bit surprised about the change and will look into it.

Thanks!

**Comment by bugwelle** [comment]
hmm... Seems to be a server-side issue. They seem check for the user-agent in the network request. Compare:

Request with `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0` user-agent:

```html
								<a href="/652646/adriana-chechik-pornstars.html"
										style="display:inline-block;"
										Category="Item Page" Label="Performer"><div class="hover-popover-container"><u>Adriana Chechik</u><div class="hover-popover hover-popover-right"
														style=""><div class="hover-popover-detail" style="padding:0;"><img src="https://imgs1cdn.adultempire.com/actors/652646h.jpg"
																alt="Adriana Chechik Bodyshot" 
																title="Adriana Chechik" 
																class="img-responsive" /></div></div></div></a>, 
```

And with MediaElch's user agent:

```html
									<a href="/652646/adriana-chechik-pornstars.html"
										style="display:inline-block;"
										Category="Item Page" Label="Performer">
										
											Adriana Chechik
										
									</a>, 
```

Changing the user agent fixes this issue. A PR will follow soon.

**Comment by waywit** [comment]
Hi, thanks for fixing... I made some tests with the fixed code and found out, that the empty block also appears in "normal" ooperation... e.g. you can find it here: https://www.adultempire.com/1511672/briana-extreme-porn-movies.html

```
<a href="/467160/aiden-starr-pornstars.html"
	style="display:inline-block;"
	Category="Item Page" Label="Performer"><div class="hover-popover-container"><u>Aiden Starr</u><div class="hover-popover hover-popover-right"
					style=""><div class="hover-popover-detail" style="padding:0;"><img src="https://imgs1cdn.adultempire.com/actors/467160h.jpg"
							alt="Aiden Starr Bodyshot" 
							title="Aiden Starr" 
							class="img-responsive" /></div></div></div></a>, 
								
<a href="/37385/sascha-pornstars.html"
	style="display:inline-block;"
	Category="Item Page" Label="Performer">
	
		
			Sascha
		
	
</a>, 
								
<a href="/159473/ben-english-pornstars.html"
	style="display:inline-block;"
	Category="Item Page" Label="Performer"><div class="hover-popover-container"><u>Ben English</u><div class="hover-popover hover-popover-right"
					style=""><div class="hover-popover-detail" style="padding:0;"><img src="https://imgs1cdn.adultempire.com/actors/159473h.jpg"
							alt="Ben English Bodyshot" 
							title="Ben English" 
							class="img-responsive" /></div></div></div></a>, 
								
<a href="/310907/jerry-pornstars.html"
	style="display:inline-block;"
	Category="Item Page" Label="Performer">
	
		
			Jerry
		
	
</a>,
```

This leads to empty actors in "movie.nfo"...

```
    <actor>
        <name>Aiden Starr</name>
        <role></role>
        <order>4</order>
        <thumb>https://imgs1cdn.adultempire.com/actors/467160h.jpg</thumb>
    </actor>
    <actor>
        <name></name>
        <role></role>
        <order>5</order>
        <thumb></thumb>
    </actor>
    <actor>
        <name>Ben English</name>
        <role></role>
        <order>6</order>
        <thumb>https://imgs1cdn.adultempire.com/actors/159473h.jpg</thumb>
    </actor>
    <actor>
        <name></name>
        <role></role>
        <order>7</order>
        <thumb></thumb>
    </actor>
```
As I can see these actors do not have any picture llinked to the profile. I am not sure what can be done here, if this situation can be detected or if the scraper gives back an empty name it will not be added perhaps?

Just a short question... During my tests I mentioned in the UI that there are no "Extra Fanarts" shown inside the corrosponding Tab... but:
1. If you click on the Fanart on the general Information Tag all Extra Fanart gets loaded
2. The Extra Fanart is also stored in the movie.nfo

If you want, I can open an issue for this?

**Comment by bugwelle** [comment]
Hi,

thanks! I'll reopen this issue. I plan to rewrite our movie scrapers and with that empty actors should be removed as well.

**Comment by bugwelle** [comment]
Hi,

#1167 will fix the empty actor issue. My bad, sorry. I removed some code for debugging purposes and forgot to add it again.
Regarding the extra fanart: Yes, please open another issue. :-)

**Comment by waywit** [comment]
Hi, no problem... therefore I am doing some QA ;-)
