### ISSUE TITLE
Streamdetails do not display Audio Channels when Reload From File

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#1174]
latest 2.8.4 9/1/20 Windows version

Go to a Movie -> Stream Details -> Reload from File

No audio channel info is displayed

**Comment by bugwelle** [comment]
Duplicate of #1172

Will look into it at the end of this week :-)

Thanks for reporting!

**Comment by bugwelle** [comment]
Fixed by #1178
