### ISSUE TITLE
Questions / Issues for TV Shows in v2.8.4

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#1176]
**Is your feature request related to a problem? Please describe.**

**Doubts and Facts**
If you wish I can issue the item individually.

**Reminder:** I haven't used it in a long time. Since 2015.
So I don't remember if it was always like this.
So I'll just see.

**SERIES (TV Show) 2.8.4**

**1 Filter** = only works for Title, specifically Local Title.

**2 Make Scrapper** = In Movies I can do with the year in the title. In Series not.
Example: **Ad Astra (2019)** versus **Cosmos (2014)**

**3 TAGs** = is the keywords of TMDb, I presume.

**4 Advancedsettings** = Genres are not mapped. Certification is not mapped.

**5 Certification** = Does not display dropdown with those of the other Series.

**6 TV Tune** = What is it?

**7 Original Title** = is not in the UI.

**Comment by bugwelle** [comment]
Hi,

I'll try my best to answer your questions:

1. Yes. At the moment only the title is supported. Please let me know what other fields you would like. I wanted to refactor the filter because it has a few coding issues (like memory leaks, etc). That's why I don't want to spend too much time adding fields at the moment. :)
2. Could you elaborate what you mean? :)
3. Yes. TMDb for TV shows should use a show's keywords as tags. Needs documentation. :)
4. Ohhh...  genres should be mapped for TheTvDb at least. TMDb and TVmaze are missing, that is true. I'll look into it.
5. True. Would be a nice feature. Could you open a feature request for it? :)
6. See https://mediaelch.github.io/mediaelch-doc/tvshow/index.html#tv-tune :-)
7. AFAIK we don't support originaltitle for TV shows, yet, do we? 
   Please open a new feature request for it. :-)

**Comment by ticao2** [comment]
I will try to be concise. **:-)**

**1 Filter** = I divided my film library into 3 basic areas:
    Series = Big Bang, House ...
    Mini Series = Band of Brothers, Taken (2002) ...
    Doc Series Mini = Cosmos (1980), Cosmos (2014), Richard Feynman (1964) The Character of Physical Law ...
I use TAGs and/or Genres to make the distinction.
It would be interesting to be able to view the separate groups.
**2 Make Scrapper** = It's just my curiosity.
All titles in my movie and series folders are in the following format, for example:
**Title_pt-BR (YEAR) mkv @ 1080p 6.4G (Dual)**
When I make the Scraper in movies, just delete everything after (YEAR).
But the series scraper does not allow (YEAR) to remain.
Only after deleting the scraper is done.
**3 TAGs** = I just believe that TMDb's Keywords are the best and most perfect example of Chaos. **:-)**
**4 Advancedsettings** = Genres and Certification is not mapped. **:-)**
**5 Certification** = OK. I will open.
**6 TV Tune** = I had never heard of it.
**7 Original Title** = OK. I will open.

**Comment by bugwelle** [comment]
1. So filter by genre and tag if I understand you correctly? :)
2. Sorry, I don't get what you mean. :-/
  Do you want MediaElch to automatically strip the year from the search title?
  TMDb does not work if a year is provided in the search query. TheTvDb on the other hand works.
3. Oh... 😅 
4. Ok. What scraper do you use?
5. Thanks. :) 
  For reference: #1179 
6. Do you mean the term "TV Tune"? Maybe a help text would be useful. It's the soundtrack of a TV series.
7. Thanks again. :)
  For reference #1180

**Comment by ticao2** [comment]
1. Yes. TAGs and Genres. And Series only. Not from the episodes. I say this because TMDb intends to adopt TAGs also for episodes.
2. It is just my curiosity. I noticed that Series behaves differently from Movies. Nothing important. You don't need to change anything.
3. And TMDb intends to extend it to episodes.
4. I use TMDb. I used TvDB only for the tests I did.
6. I don't think it's necessary. I am an old man who turns 70 this year. Certainly all young people must know.

**Comment by bugwelle** [comment]
1. See #1186
2. hmm... I'll look into it after I've refactored the movie scrapers. :)
3. Good to know. I'll add support for it when they officially support it. :)
4. See #1185 ; is now fixed :)
5.
6. Oh awesome! Never thought that. :)

**Comment by bugwelle** [comment]
I think all points are answered or there are issues for it. I'll close this issue now. :)

**Comment by ticao2** [comment]
In changelog
https://mediaelch.github.io/mediaelch-doc/release-notes.html
I see
> Genre/Certification/Studio mappings for all TV show scrapers are now respected, now just for TheTvDb (#1176)

**now** or **not** for TheTvDb (#1176) ?

**Comment by bugwelle** [comment]
Typo! Thanks! :)

**Comment by bugwelle** [comment]
Fixed with https://github.com/Komet/MediaElch/commit/48bb9c675a724089673b0097487fde6a21881245

Thanks!
