### ISSUE TITLE
TV Show - Dropdown Certification

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#1179]
**Is your feature request related to a problem? Please describe.**

Series or TV Show - Dropdown Certification
In the Series UI, in the Certification item, the dropdown does not display the list of certifications for all BD Series.

**Comment by bugwelle** [comment]
Hi,

that combobox only contains certifications from a TV show's episodes at the moment.

Having a list of all certifications is possible but I'll have to see how to best gather them.

**Comment by ticao2** [comment]
It is not something important. Just to stay in the mind.
I don't know if I understood correctly.
TMDb only has Certification for the Series or TV Show.
Does not have certification for Episode.
Then I thought of a ComboBox that displays the Certifications of all Series or TV Shows.
As with Movies. We see from all the Movies on the BD.

And in addition I wondered if it would be possible to extend the ComboBox to **14 items**.
Many people usually store Certification from two countries.
I've seen some users here commenting on this.
So this cabalistic number of 14 items considers in my case:

> 6 BR Certifications: Livre, 10, 12, 14, 16 and 18.
> 6 PT Certifications: M/3, M/6, M/12, M/14, M/16 and M/18
> NR
> In blank

But none of this is important or urgent.
Only to be done if it is to relax and rest your head. **:-)**

**Comment by bugwelle** [comment]
Good idea 👍 

But I'm afraid that such a list would make our settings (again) more complicated.

My proposal: In the TV show widget make all certifications selectable of _all_ TV shows + of all episodes of the current TV show.

Would that work for you? I'm currently against another list of default certifications. :-)
