### ISSUE TITLE
TV Show - Original Title

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#1180]
**Is your feature request related to a problem? Please describe.**

Series or TV Show - Original Title
In the Series UI, it does not show the Original Title.
Only the Title or Local Title.

**Comment by bugwelle** [comment]
Steps to take:

- [ ] Add to TVShow class
- [ ] Add to TVShow UI
- [ ] Add to TVShow NFO reader/writer
- [ ] Add to TVShow CSV Exporter
- [ ] Add to TVShow HTML Exporter
- [ ] Find out which scrapers support original titles (help appreciated)

**Comment by bugwelle** [comment]
@ticao2 FYI, I plan to upload new nightlies to https://mediaelch-downloads.ameyering.de/ as bintray will shut down. The URL may still change, though.

**Comment by ticao2** [comment]
In TMDb the name of the field for the **Original Title** of a TV Show is **original_name**. **:-=**

**Comment by bugwelle** [comment]
That's what we're using :)

For TV shows and TMDb:

```
 m_show.setOriginalTitle(data["original_name"].toString());
```
