### ISSUE TITLE
[Fanart TV] Fresh installations have the first language selected instead of default "English"

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#1190]
I've installed MediaElch on a Windows computer for the first time and opened the image dialog for a TV show. I noticed that "Bulgarian" was selected even though it should be English (or German as its the system's language).

**Comment by ticao2** [comment]
It has been this behavior for so long that I even got used to it. **:-)**
But, yes, if it is possible for all language selection Dropdowns to respect and adopt the language of the OS, or advancedsettings, it would be very good.
When installing, 6 settings are required (4 for Movies and 2 for Series).
Of course, with those defined, all other resources must respect.
