### ISSUE TITLE
System's language not recognized on fresh installation

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#1191]
**Describe the bug**
Downloaded v2.8.4 for Windows. The system never ran MediaElch before. The system's language is German but MediaElch starts in English.

**Expected behavior**
MediaElch should start in German.

**MediaElch Version:**
 - [x] 2.8.5-dev (nightly)
 - [x] 2.8.4 stable

**Operating System:**
 - [x] Windows 10 Home
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Comment by ticao2** [comment]
My test when I install.

```
ITEM		2.8.4

Movies
TMDb Movies	English
TMDb Concerts	English
Universal Music	Chinese
Fanart.tv	Bulgarian

Series
TMDb TV		English
The TvDB	English


New Image
After setting the correct language in Settings.
Before and After restarting ME.

Movies
Poster Fanart.tv	Portuguese
Poster TMDb		English
Fanart Fanart.tv	Portuguese
Fanart TMDb		English

Series
Poster Fanart.tv	Portuguese
Poster TheTvDB		English
Fanart Fanart.tv	Portuguese
Fanart TheTvDB		English


Scraper Serie	All Unchecked
Scraper Episode	All Unchecked
```

**Comment by ticao2** [comment]
2.8.5 dev exactly the same as 2.8.4

**Comment by ticao2** [comment]
When I want a different poster than the one I have, I click on the poster and open the window.
Nothing happens when I change the language. They are always the same images.
Perhaps this problem is related.

**Comment by bugwelle** [comment]
I found the issue.

A fresh Windows 10 Education installtion for Germany has the following properties:

```
QLocale::system().uiLanguage() == ("de-DE", "en-US")
```

After reading https://doc.qt.io/qt-5/qtranslator.html#load-1 I would assume, that Qt looks at following files in the specified order:

1. `MediaElch_de_DE.qm`
1. `MediaElch_de.qm`
1. `MediaElch_en_US.qm`
1. `MediaElch_en.qm`
1. `MediaElch.qm`

For reference, this is from their documentation (2021-03-02):

<details>

<summary>click to expand</summary>

```
For example, an application running in the locale with the following ui languages - "es", "fr-CA", "de" might call load(QLocale(), "foo", ".", "/opt/foolib", ".qm"). load() would replace '-' (dash) with '_' (underscore) in the ui language and then try to open the first existing readable file from this list:

    /opt/foolib/foo.es.qm
    /opt/foolib/foo.es
    /opt/foolib/foo.fr_CA.qm
    /opt/foolib/foo.fr_CA
    /opt/foolib/foo.fr.qm
    /opt/foolib/foo.fr
    /opt/foolib/foo.de.qm
    /opt/foolib/foo.de
    /opt/foolib/foo.qm
    /opt/foolib/foo.
    /opt/foolib/foo
```

</details>

However, if I look at the documentation on Woboq: https://code.woboq.org/qt5/qtbase/src/corelib/kernel/qtranslator.cpp.html#746 we can see the Qt actually looks for:

1. `MediaElch_de_DE.qm`
1. `MediaElch_en_US.qm`
1. `MediaElch_de.qm`
1. `MediaElch_en.qm`
1. `MediaElch.qm`

`MediaElch_en_US.qm` exists but `MediaElch_de_DE.qm` does not.

If I delete the `en_US` version (that I use for plurals), everything is back to normal...

For reference, the code:

<details>

<summary>click to expand</summary>

```
For example, an application running in the \a locale with the following
\l{QLocale::uiLanguages()}{ui languages} - "es", "fr-CA", "de" might call
load(QLocale(), "foo", ".", "/opt/foolib", ".qm"). load() would
replace '-' (dash) with '_' (underscore) in the ui language and then try to
open the first existing readable file from this list:

\li \c /opt/foolib/foo.es.qm
\li \c /opt/foolib/foo.es
\li \c /opt/foolib/foo.fr_CA.qm
\li \c /opt/foolib/foo.fr_CA
\li \c /opt/foolib/foo.de.qm
\li \c /opt/foolib/foo.de
\li \c /opt/foolib/foo.fr.qm
\li \c /opt/foolib/foo.fr
\li \c /opt/foolib/foo.qm
\li \c /opt/foolib/foo.
\li \c /opt/foolib/foo
```

</details>

**Comment by bugwelle** [comment]
This was fixed in Qt6 (and Qt5.15 for commercial users), see 

- I reported it here: https://bugreports.qt.io/browse/QTBUG-91502
- Relevant change: https://codereview.qt-project.org/c/qt/qtbase/+/324710
- Code Commit: https://github.com/qt/qtbase/commit/e6e23d061cb8ac81007119603f8e7c64fc572e04
