### ISSUE TITLE
ME 2.8.4 for macOS has changed "Minimum OS Version" requirement to 10.14

### ISSUE THREAD

**Issue by workflowsguy** [Komet/MediaElch#1201]
**Describe the bug**
ME 2.8.4 requires a minimum OS version of 10.14.
Previous ME versions up to 2.8.2 had 10.6.8 as minimum OS version.
I hope this is just an oversight and not an actual change of requirements.

Also, I could not find any actual mention of minimum OS version for the various platforms on which ME runs

**To Reproduce**
n.a.

**Expected behavior**
ME 2.8.4. should still run on older versions of macOS. If the requirement for minimum OS version changes, this should be mentioned in the release notes and also cause ME's major version number to increase.

**Screenshots**
n.a.

**MediaElch Version:**
 - [x] 2.8.4 stable

**Operating System:**
 - [x] macOS

**Comment by bugwelle** [comment]
Hi,

what macOS version do you use? I can go back to 10.13 but older versions are not supported by our GUI framework Qt (see https://doc.qt.io/qt-5/supported-platforms.html ).

Please let me know. I plan to make a new release this weekend. 😄

**Comment by workflowsguy** [comment]
Hello @bugwelle,

> what macOS version do you use? I can go back to 10.13 but older versions are not supported by our GUI framework Qt (see https://doc.qt.io/qt-5/supported-platforms.html ).
> 

The Mac where ME is running is on macOS 10.13.6.

> Edit: // I don't mind setting an older version but then you may experience issues that I may not be able to fix.

If you introduce new features or update components that require a newer version of macOS, then that should be reflected in the minimum OS requirements setting and accepted by users. Setting this to an older version might just cause unneccessary support effort for you.

> 
> I'll also update our documentation.

That's great to hear!
Thanks!

**Comment by bugwelle** [comment]
> The Mac where ME is running is on macOS 10.13.6.

Thank you. I'll change it back to 10.13. That's also required by the user-interface framework Qt that we use. :-)

The documentation (download page) will point out what systems are supported (i.e. macOS >= 10.13, Windows >= 7, ...)

**Comment by bugwelle** [comment]
FIxed by https://github.com/Komet/MediaElch/commit/4f979f93156ec162ac192a62504dba9f3b87cc0e :-)
