### ISSUE TITLE
Save metadata to MP4 file

### ISSUE THREAD

**Issue by snakyjake1** [Komet/MediaElch#1211]
**Describe the solution you'd like**
Save metadata (TV show, Episode, Etc) to MP4 file.

**Describe alternatives you've considered**
DVDFab (Automatic)
VLC Media Information (Manual, no scrapper)

**Comment by bugwelle** [comment]
Hi there,

sorry, I forgot to answer.

This is currently out-of-scope, sorry. To put it simply: I don't have the time to work on this. :(
I know from other apps that working with MP4 files can be very frustrating. Too many fields, etc.

MusicBrainz offers a great tool for music, see https://mediaelch.github.io/mediaelch-doc/faq.html#what-alternatives-to-mediaelch-exist

However, if there is anyone who would like to open a pull request for this issue, I'll gladly merge it. :)
