### ISSUE TITLE
Find Bintray alternative

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#1213]
Bintray shuts down, see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

We need some alternative...

**Comment by bugwelle** [comment]
I will probably use my own server, see https://mediaelch-downloads.ameyering.de/

**Comment by bugwelle** [comment]
Updated https://mediaelch.github.io/mediaelch-doc/download.html

Let's see how that works out.

**Comment by ticao2** [comment]
On the page
https://mediaelch.github.io/mediaelch-doc/download.html
Link for Windows is on Linux and
Link for Linux is on Windows. **:-)**

**Comment by bugwelle** [comment]
Thanks. Is fixed now. :)
