### ISSUE TITLE
certifications  in advancedsettings.xml do not work in series

### ISSUE THREAD

**Issue by Megapit** [Komet/MediaElch#1224]
I use the certifications in the advacedsettings.
For films the mapping works fine for series not. 

For example i still get PG when i scape a episode. But i expect FSK-12. I need the correct mapping for parental control on my emby server. In german it only accepts german certifications.

I attached my xml. I'm using OSX 10.14

[advancedsettings.xml.zip](https://github.com/Komet/MediaElch/files/5973876/advancedsettings.xml.zip)

**Comment by ticao2** [comment]
Hi @Megapit   
The problem existed and in theory it was solved 30 days ago.
https://github.com/Komet/MediaElch/pull/1185
What version of MediaElch are you using?

**Comment by Megapit** [comment]
i use 2.8.6 Coridan
![Bildschirmfoto 2021-02-14 um 12 52 53](https://user-images.githubusercontent.com/50706199/107876029-b3d9b700-6ec3-11eb-99bc-b90431d16cd1.png)

**Comment by ticao2** [comment]
The correction was made on January 16.  
Coridien 2.8.6 I think it's from January 22nd.
So, he shouldn't have this problem.
I believe that only @bugwelle  can clarify.

**Comment by bugwelle** [comment]
Hi,

I just tested it with v2.8.6 and with your `advancedsettings.xml`. On my system, certifications for episodes and TV shows are replaced. For example "American Dad" has a certification of "FSK-16" after I scrape details.

How do you load the details? (i.e. select a single episode and scrape data, select multiple episodes, select TV shows, ...)

Also note that TMDb does not support certification for single episodes. :-)

You can also answer in German if you want (I'm German as well).


Regards,
Andre

**Comment by Megapit** [comment]
Hi Andre
Thanks for your help!
I try to use english, so other people have to chance to read this later.

On my Mac it does not work. I scrape "The Orville" with different scrapers and i don't get the FSK-12. I tryed single episode scaping and full season as well.

Maybe an Mac Problem? Ore some stange settings i made in the long history of MediaElch on this Mac?

I attached the Settingsfile as well. Maybe this brings light into the problem.

Thanks again. Peter

[com.kvibes.MediaElch.plist.zip](https://github.com/Komet/MediaElch/files/5977911/com.kvibes.MediaElch.plist.zip)

**Comment by bugwelle** [comment]
Hi,

nothing suspicious in your settings. Where have you placed your `advancedsettings.xml` file? :-)

See also : https://mediaelch.github.io/mediaelch-doc/settings.html#advanced-settings

**Comment by Megapit** [comment]
Hi

did the XML location changed in a new version? 
It worked in version ~1year ago.
I can check my path this evening. 
Next step for me is to make a new clean install with deleting all files.

**Comment by bugwelle** [comment]
> did the XML location changed in a new version?

It should not have changed. But just to remove one possible source of error. :-)

**Comment by Megapit** [comment]
Hi

I delete mediaelch and all files belonging to it (see: [https://mediaelch.github.io/mediaelch-doc/faq.html](url)) and after that everything works as expected. 
When I do an update i allways override the app with the new version in the OSX.dmg. This is my way since V2.0 of Mediaelch. Maybe somthing get wrong during update.

So for users finding the same problem: Make a Clean install and delete every file you can find in the locations shown in the link above.

**Comment by bugwelle** [comment]
Thank you for letting me know! Sadly, I do not know where we could have introduced this issue... :-/

**Comment by ticao2** [comment]
I remembered that 1 or 2 years ago there was a recommendation to Delete a file.  
I don't know when the initial installation was made by Megapit.  
https://mediaelch.github.io/mediaelch-doc/release-notes.html#ferenginar-2019-09-13

**Comment by Megapit** [comment]
hi

Initial installation was 2-3 years ago. I must be overread this tip to delete a file :(
Anyway: after clean new installation it works :) 👍
