### ISSUE TITLE
episodeguide url is for thetvdb when trying to use tmdb

### ISSUE THREAD

**Issue by ukoda** [Komet/MediaElch#1233]
Kodi v19 appears to want to use the tmdb scrapper but some TV series are not appearing.  Even after setting everything I can find to tmdb the generated tvshow.nfo references tvdb in key places and as the default.

**To Reproduce**
For TV series "World Witches Take Off! (2021)" at https://www.themoviedb.org/tv/106386?language=en-US.
1. Go to settings -> Scraper -> Custom TV Scraper and change every site possible to "TMDb TV".
2. In the main window click on "Shows".
3. Select "World Witches Take Off" in left column.
3. Click on "Scrape" button.  Check scraper shows as "TMDb TV".
4. Chose "Update TV Show and all Episodes"
5. Click on the single show found result.
6. After scraping is complete click on "Save button".

**Expected behavior**
A tvshow.nfo file to be created in the show's folder that references tmdb in the important areas.  However the default "uniqueid" is for tvdb and the "url" in the "episodeguide" points to api.thetvdb.com.

From the Kodi documentation it would appear to the likely reason Kodi is failing to scrape and not showing this show.

**MediaElch Version:**
 - [*] 2.8.6 stable

**Operating System:**
 - [*] Linux (Mint: 20.1)

**Additional context**
The generated file should be attached
[tvshow.nfo.zip](https://github.com/Komet/MediaElch/files/6035817/tvshow.nfo.zip)

**Comment by bugwelle** [comment]
Oh. That surprises me. Kodi shouldn't scrape more details. Only NFO meta data should be used.
Thanks you for reporting this issue!

**Comment by bugwelle** [comment]
If I use the NFO provided by you, the TV show appears in Kodi.

What I'll fix ASAP is that an empty TvDbId can appear: `<uniqueid type="tvdb" default="true">0</uniqueid>`

**Comment by bugwelle** [comment]
Ok, for TMDb, NFOs scraped with Kodi v19 look like this:

```xml
    <episodeguide>1434</episodeguide>
    <id>1434</id>
    <uniqueid type="imdb">tt0182576</uniqueid>
    <uniqueid type="tmdb" default="true">1434</uniqueid>
```

So it's rather easy to implement. Use the new format for v19 and TMDb. Use TvDb as fallback.

**Comment by bugwelle** [comment]
https://github.com/Komet/MediaElch/pull/1234 will fix this issue. MediaElch will then write the TMDb ID as the episodeguide URL per default.

And the new order for the default `uniqueid` is:

1. TMDB
2. TvDb
3. IMDb
4. TvMaze
