### ISSUE TITLE
Minor documentation error on download page

### ISSUE THREAD

**Issue by ukoda** [Komet/MediaElch#1235]
**Describe the bug**
You appear have the Windows and Linux links to the "Latest (unstable)" versions swapped in the table
![MediaElch_swapped](https://user-images.githubusercontent.com/13553631/109094986-c71c3a80-777f-11eb-8869-25467f59dd60.png)
 on the download page https://mediaelch.github.io/mediaelch-doc/download.html

**Comment by bugwelle** [comment]
Oh.. Thanks for reporting! Fixed. :)

https://mediaelch.github.io/mediaelch-doc/download.html
