### ISSUE TITLE
Duplicate entries for TV episodes

### ISSUE THREAD

**Issue by vegright** [Komet/MediaElch#1270]
Description:
Duplicate entries can happen if mistakes are made during normal operation.

To Reproduce:
1. Scrape show or don't scrape show
2. Do NOT scrape episodes
3. Rename episodes
4. Refresh
5. Duplicate entries for each episode renamed this way shows up in GUI

The mistake is the not scraping the episodes.  I'm a new user, so it happened to me, not knowing the consequences. 
Before:
E:\zzzTest\TV\Cells at Work! (2018)\Season 01\Cells at Work! - S01E01 - Pneumococcus.mkv
After:
E:\zzzTest\TV\Cells at Work! (2018)\Season 01\S01E01 - Cells at Work! - S01E01 - Pneumococcus.mkv

Even after scraping episodes (after mistake rename), and renaming, duplicates still show up.  But now the episode is named as follows but still treated as a duplicate even after refresh.
E:\zzzTest\TV\Cells at Work! (2018)\Season 01\S01E01-01 - Pneumococcus.mkv

Expected behavior:
Two issues here.  First one being that rename should not be allowed for un-scraped shows.  Second being that these episodes named this way should not be treated as duplicates. (my assumption is that they are being treated as multi-episode).

MediaElch Version:
2.8.6 stable
Windows

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this issue. I forgot about this issue, sorry.

This was fixed by https://github.com/Komet/MediaElch/pull/1302
