### ISSUE TITLE
TheTVDb does not scrape for high episode numbers

### ISSUE THREAD

**Issue by vegright** [Komet/MediaElch#1272]
TheTvDb

**Details which are wrong / not loaded:**
I assume the issue is that the scraper does not support 102+ episode numbers.  Though when I found the issue, it was for 142+, but after testing, found the start was at 102.

Testing with TMDb TV but only worked with a single episode selected, but not multiple selected episodes.

**MediaElch Version:**
2.8.6 stable

**Operating System:**
Windows

**Additional context:**

**Comment by bugwelle** [comment]
Hi,

indeed, for TheTvDb this is a known MediaElch issue that I didn't work on, yet.
For which  TV show does this happen? :)

Regards,
Andre

**Comment by vegright** [comment]
This happen for Doctor Who (2005) in Specials.  I switched MediaElch back to my test directories where I found that it stopped at 102+.  For some odd reason it scraped this time.  I did not update MediaElch version, still at 2.8.6.  So possibly something on TheTvDb side.

Thanks much for looking into it.

**Comment by vegright** [comment]
Ignore that.  I went back to my live library and it did not scrape.  I had the test library (through advancedsetting.xml) still set to TMDb TV.  So after scraping from TheTvDb for real this time and renaming it looks like this.  Sorry about that.  The other odd one I found is that S00E16 does not scrape either.  I have 217 TV shows that I scraped with with MediaElch and TheTvDb, and I have only run into issues with Doctor Who (2005).  I confirmed that the episodes exist (https://thetvdb.com/series/doctor-who-2005/seasons/official/0).

vegright@Veg:/mnt/e/zzzTest/Tv/Doctor Who (2005)/Season 00> ls -la
total 4790276
drwxrwxrwx 1 ericn users       512 Apr  7 17:30 .
drwxrwxrwx 1 ericn users       512 Apr  4 02:50 ..
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E100 - The Inforarium.mkv
-rwxrwxrwx 1 ericn users      2611 Apr  7 17:30 S00E100 - The Inforarium.nfo
-rwxrwxrwx 1 ericn users     84127 Apr  7 17:30 S00E100 - The Inforarium-thumb.jpg
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E101 - Farewell to Matt Smith.mkv
-rwxrwxrwx 1 ericn users      2516 Apr  7 17:30 S00E101 - Farewell to Matt Smith.nfo
-rwxrwxrwx 1 ericn users     61780 Apr  7 17:30 S00E101 - Farewell to Matt Smith-thumb.jpg
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E102 - .mkv
-rwxrwxrwx 1 ericn users      1410 Apr  7 17:30 S00E102 - .nfo
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E103 - .mkv
-rwxrwxrwx 1 ericn users      1410 Apr  7 17:30 S00E103 - .nfo
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E104 - .mkv
-rwxrwxrwx 1 ericn users      1410 Apr  7 17:30 S00E104 - .nfo
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E105 - .mkv
-rwxrwxrwx 1 ericn users      1410 Apr  7 17:30 S00E105 - .nfo
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E110 - .mkv
-rwxrwxrwx 1 ericn users      1410 Apr  7 17:30 S00E110 - .nfo
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E120 - .mkv
-rwxrwxrwx 1 ericn users      1410 Apr  7 17:30 S00E120 - .nfo
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E142 - .mkv
-rwxrwxrwx 1 ericn users      1410 Apr  7 17:30 S00E142 - .nfo
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E15 - Dreamland.mkv
-rwxrwxrwx 1 ericn users      2118 Apr  7 17:30 S00E15 - Dreamland.nfo
-rwxrwxrwx 1 ericn users     29702 Apr  7 17:30 S00E15 - Dreamland-thumb.jpg
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E16 - .mkv
-rwxrwxrwx 1 ericn users      1409 Apr  7 17:30 S00E16 - .nfo
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E17 - The End of Time (2).mkv
-rwxrwxrwx 1 ericn users      2927 Apr  7 17:30 S00E17 - The End of Time (2).nfo
-rwxrwxrwx 1 ericn users     34549 Apr  7 17:30 S00E17 - The End of Time (2)-thumb.jpg
-rwxrwxrwx 1 ericn users 377292338 Mar 21 17:04 S00E99 - Rain Gods.mkv
-rwxrwxrwx 1 ericn users      2107 Apr  7 17:30 S00E99 - Rain Gods.nfo
-rwxrwxrwx 1 ericn users    133331 Apr  7 17:30 S00E99 - Rain Gods-thumb.jpg

**Comment by vegright** [comment]
Got a new series called Black Clover.  Once it hit ep 101 (rather than 102 like Dr. Who), TheTVDB scrapper quit working.  Figured I would let you know.

**Comment by bugwelle** [comment]
Hi,

thanks for reporting. As the old TheTvDb API will shut down in October, I will have to switch to the new one. Hopefully, I can   fix this as well.

**Comment by bugwelle** [comment]
Due to the issue described in https://github.com/Komet/MediaElch/issues/1120 , support for TheTvDb has been completely removed. Therefore, this issue won't be worked on. Sorry about that.
