### ISSUE TITLE
Latest release MediaElch_win_2.8.8_2021-04-26_git-d209d8c6 has debug enabled

### ISSUE THREAD

**Issue by badkarmaboy** [Komet/MediaElch#1296]
Thank you for the latest release of MediaElch_win_2.8.8_2021-04-26_git-d209d8c6. 
Working good, but it looks like you forgot to disable debug before releasing.

Upon opening mediaelch.exe a DOSBOX opens additionally to the main programs window showing debug information.

Best regards!

![2021-04-26 20_10_39-MediaElch](https://user-images.githubusercontent.com/25039267/116130487-95661800-a6cb-11eb-99ad-5c04505067f3.png)

**Comment by bugwelle** [comment]
Aaahhhh. Why?

Thank you for reporting this. Debug mode isn't enabled (otherwise the logs in the terminal would look different).

I'll look into it tomorrow. :)

**Comment by bugwelle** [comment]
Maybe due to https://stackoverflow.com/questions/760323/why-does-my-qt-4-5-app-open-a-console-window-under-windows

**Comment by bugwelle** [comment]
I'm now testing a Windows build without `testlib`. Commit: 

https://github.com/Komet/MediaElch/commit/0820764c32e522d5ca61847890a83e4ca79b1366#diff-59ffab0292726a0fefda5c2f407f549af544c66c663ba994abb9c74c765233ed

**Comment by bugwelle** [comment]
The issue was indeed `testlib`. I will update the ZIP ASAP.

**Comment by bugwelle** [comment]
New version is now available. :-)

**Comment by badkarmaboy** [comment]
Thank you! I can confirm the dosbox is gone now.
