### ISSUE TITLE
build on launchpad ppa failed for bionic

### ISSUE THREAD

**Issue by mason-xx** [Komet/MediaElch#1300]
**Describe the bug**
the build on launchpad for bionic failed.

**MediaElch Version:**
 - [x] 2.8.8 stable

Sorry I'm not sure if this is the right platform to adress this. But the current build for bionic failed and I maintain an unraid docker for mediaelch, unfortunatly the base image I'm using is based on bionic. Can this be fixed?

Sorry again if this is not the right way to adress this but I'm by far no expert when it comes to these things... also thanks for all your work on this great tool :)

**Comment by bugwelle** [comment]
This is the right way to address it :)

It was not able to fix the build for bionic, yet. I'll have to look into it on the weekend again :)

**Comment by bugwelle** [comment]
Updated for Mediaelch-test repository: https://launchpad.net/~mediaelch/+archive/ubuntu/mediaelch-test/+packages

If the build succeeds, I know how to fix it and will do so for MediaElch-Stable ASAP. :-)

**Comment by bugwelle** [comment]
Worked. :tada:

I've just now pushed it to MediaElch-Stable as well. Bionic should be available in about 1-2 hours.

**Comment by mason-xx** [comment]
thanks a ton! :)

**Comment by bugwelle** [comment]
Latest version of MediaElch is now available for Bionic as well. :-)

**Comment by bugwelle** [comment]
Re-opening until v2.8.10 is published for Bionic.

**Comment by bugwelle** [comment]
Forgot about this issue. 2.8.12 is available for Bionic
