### ISSUE TITLE
Media status icons shows the wrong status

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#1304]
**Describe the bug**
The media status icons doesn't work for clearart and thumb

**To Reproduce**
1. Add clearart and thumb to a TV show
2. Save
3. Icons for the two are still red.

**Expected behavior**
That they turn green.

**Screenshots**

**MediaElch Version:**
 - [X] 2.8.9-dev (nightly)
 - [ ] 2.8.8 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**
Shouldn't the label Thumb be changed to Landscape?

**Comment by bugwelle** [comment]
Thank you very much for reporting this issue! Fixed by https://github.com/Komet/MediaElch/commit/12c77b56640ab26afc2253cbe3b900ab0ac7ccf2
