### ISSUE TITLE
Crashes when loading movies

### ISSUE THREAD

**Issue by MrBabafemi** [Komet/MediaElch#1318]
**Describe the bug**
when i try to refresh my movie folders it seems to scan for a minute or two and then crashes.

**To Reproduce**
1. Go to '...'    start mediaelch
2. Click on '....'  Click on movies
3. Scroll down to '....'   hit the refresh button
4. See error / Crash

**Expected behavior**
i expect it to scan and then show me all my movies in the folder and let me correctly tag the newest files added .

**Screenshots**
![Screenshot from 2021-05-06 13-34-36](https://user-images.githubusercontent.com/83782353/117346767-31cfad80-ae76-11eb-9cc4-96f23f90a0c7.png)
![Screenshot from 2021-05-06 13-35-25](https://user-images.githubusercontent.com/83782353/117346769-32684400-ae76-11eb-892d-5e4ea295e01a.png)
![Screenshot from 2021-05-06 13-39-21](https://user-images.githubusercontent.com/83782353/117346770-32684400-ae76-11eb-8b2a-e2c5ed8b9c17.png)
**MediaElch Version:**
 - [ ] 2.8.11-dev (nightly)
 - [ x] 2.8.10 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x ] Linux (distribution: _._) Ubuntu 20.04 LTS

**Additional context**
i have uninstalled at least 3x.  i had originally just tried to update without uninstalling the older version and when i first saw the issue i uninstalled both versions and then installed the fresh new version and still had the issue. i installed it via terminal copy and pasting the lines from your webpage. i have tried to use the appimage version.  that actually starts up with my movie folders loaded "properly" showing my files but then i hit refresh and it crashes again. sometimes it would load and only show maybe 20 or 33 movies and then i hit refresh and it crashes.  i was using 2.8.6 a few hours ago with no problems.  figured id update it today since i was home and then all this happened.

**Comment by MrBabafemi** [comment]
Yes I have 2 movie folders on 2 different drives. I separate my animated
movies/TV shows from the normal types.

**Comment by MrBabafemi** [comment]
I tried that.  I removed the main movie folder.
Then I removed the animated movie folders.
Then I even renamed the folder with all lowercase letters.
 Each time it still crashed.

**Comment by bugwelle** [comment]
OK, thanks for letting me know! :)

**Comment by bugwelle** [comment]
The issue is fixed. I'll release a new MediaElch version tomorrow. :)

**Comment by MrBabafemi** [comment]
Thank you very much.  It is working properly once again.

**Comment by bugwelle** [comment]
Thank you very much for confirming this! 🎉
