### ISSUE TITLE
Ignore articles when sorting doesn't work on shows

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#1333]
**Describe the bug**
The title pretty much sums it up.
The global setting 'Ignore article when sorting ("The")' has no effect on shows.
A show with a "The" in the beginning like for example The Blacklist is still presented as "Blacklist, The" with the setting in question checked.

**MediaElch Version:**
 - [X] 2.8.13-dev (nightly)
 - [ ] 2.8.12 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**
Don't know if this is new or go way back since I just now tried it for the first time.

**Comment by bugwelle** [comment]
hmmm... Thank you for reporting this. It should be possible, as we _should_ ignore articles.

_For reference_:

```
return (QString::localeAwareCompare(helper::appendArticle(a->title()), helper::appendArticle(b->title())) < 0);
```

**Comment by bugwelle** [comment]
What behavior do you expect? :-)

<img width="225" alt="Screen Shot 2021-05-16 at 19 53 09" src="https://user-images.githubusercontent.com/1667306/118407280-63b7ef80-b680-11eb-91d1-93413805751a.png">

(notice "Simpsons, The")

Could you please provide me the following information:

- Does the show have a "Sort Title" value?
- Do you have an advanced settings file?
- What "display value" do you expect?
- What ordering do you expect?

Regards,
Andre

**Comment by psonnosp** [comment]
They were all still sorted as with The in front but it looks like it just needed a refresh of the source for it to work because when i fired ME up now to check it's OK so seems I was just a bit impatient :wink:

**Comment by bugwelle** [comment]
Ah, yes. We don't refresh the model when the setting is changed... hmm.
