### ISSUE TITLE
Universal Music Scraper not parsing Born/Discography correctly

### ISSUE THREAD

**Issue by techie2000** [Komet/MediaElch#1336]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [ ] TmdbConcert
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster
 - [X] Universal Music Scraper

**Details which are wrong / not loaded:**

- Born
- Biography

**MediaElch Version:**
 - [ ] 2.8.13-dev (nightly)
 - [x] 2.8.12 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: Ubuntu 18.04.5 LTS)

**Additional context:**
Example Born pulled in : `<a href="/birthdate/1981-07-21">July 21, 1981</a> in <a href="/birthplace/london-england-mz0000001334">London, England</a>` for Paloma faith (MusicBrainz f23f6dd0-bfb0-43d5-bf06-eae4315db502)
Example Biography pulled in : 
```
Alex Kunnari (s. 1974) on suomalainen elektronisen musiikin artisti ja DJ. Klubien ja yökerhojen lisäksi hänen kappaleensa ovat menestyneet myös radioiden soittolistoilla. Hän on esiintynyt Suomen lisäksi myös muissa maissa.
 

<!-- 
NewPP limit report
Parsed by mw1363
Cached time: 20210521110742
Cache expiry: 86400
Reduced expiry: true
Complications: []
CPU time usage: 0.191 seconds
Real time usage: 0.271 seconds
Preprocessor visited node count: 1878/1000000
Post?expand include size: 19158/2097152 bytes
Template argument size: 8036/2097152 bytes
Highest expansion depth: 17/40
Expensive parser function count: 0/500
Unstrip recursion depth: 0/20
Unstrip post?expand size: 83/5000000 bytes
Lua time usage: 0.061/10.000 seconds
Lua memory usage: 2540392/52428800 bytes
Number of Wikibase entities loaded: 1/400
-->
<!--
Transclusion expansion time report (%,ms,calls,template)
100.00%  260.807      1 -total
 78.49%  204.708      1 Malline:Muusikko
 73.98%  192.955      1 Malline:Henkilö/pohja
 72.12%  188.105      1 Malline:Tietolaatikko
 25.14%   65.567     18 Malline:Wikidata-fr
 18.96%   49.461      1 Malline:Tietolaatikko/kuva
 15.87%   41.384      1 Malline:Verkkoviite
 12.00%   31.298      3 Malline:Tietolaatikko/uusitietorivi
  8.69%   22.656      1 Malline:IETF-kielisymboli
  6.43%   16.762      1 Malline:Tietolaatikko/tyhjä
-->
```
for Alex Kunnari (MusicBrainz 806bfb43-bcd9-4315-8fa8-d14a1b6eb229)

**Comment by techie2000** [comment]
Having just tried Robert Miles (MusicBrainz e83144dd-bb95-49fe-b1dd-00bab25cca9e), I see that Died has similar issue, returning `<a href="/deathdate/2017-05-09">May 9, 2017</a> in <a href="/deathplace/ibiza-spain-mz0000040256">Ibiza, Spain</a>`

**Comment by bugwelle** [comment]
Reproduced and fixed locally. I've added tests to ensure that this won't happen again. Sorry for the (very long) delay.
I'll check all UniversalMusicScraper-scrapers (not just AllMusic) to ensure that they work as well.
