### ISSUE TITLE
quazip-1.1 compatibility

### ISSUE THREAD

**Issue by bell07** [Komet/MediaElch#1339]
Currently MediaElch can be compiled only with quazip version 0.9. In some Linux distros (like Gentoo) the version 0.9 is already removed from packages tree and only the newest version 1.1 is available.

Please add support for the new quazip-1.1 version

If I try to compile with new version, I get the error message

```
FAILED: src/export/CMakeFiles/mediaelch_export.dir/ExportTemplateLoader.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DEXTERN_QUAZIP -DMEDIAELCH_UPDATER -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_WIDGETS_LIB -Isrc/export/mediaelch_export_autogen/include -I. -I/var/tmp/portage/media-video/mediaelch-9999/work/mediaelch-9999 -I/var/tmp/portage/media-video/mediaelch-9999/work/mediaelch-9999/src -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql  -O2 -march=native -pipe -fdiagnostics-color=always -Wall -Wextra -pedantic -pedantic-errors -Wunknown-pragmas -Wundef -Wold-style-cast -Wno-useless-cast -Wdisabled-optimization -Wstrict-overflow=4 -Winit-self -Wpointer-arith -Wduplicated-cond -Wdouble-promotion -Wshadow -Wduplicated-branches -Wrestrict -Wnull-dereference -Wlogical-op -Wunsafe-loop-optimizations -Wno-error=unsafe-loop-optimizations -Wformat=2 -Wmissing-field-initializers -Wconversion -Wsign-conversion -Wno-gnu-zero-variadic-macro-arguments -fPIC -MD -MT src/export/CMakeFiles/mediaelch_export.dir/ExportTemplateLoader.cpp.o -MF src/export/CMakeFiles/mediaelch_export.dir/ExportTemplateLoader.cpp.o.d -o src/export/CMakeFiles/mediaelch_export.dir/ExportTemplateLoader.cpp.o -c /var/tmp/portage/media-video/mediaelch-9999/work/mediaelch-9999/src/export/ExportTemplateLoader.cpp
/var/tmp/portage/media-video/mediaelch-9999/work/mediaelch-9999/src/export/ExportTemplateLoader.cpp:13:14: fatal error: quazip5/quazip.h: No such file or directory
   13 | #    include "quazip5/quazip.h"
      |              ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
**MediaElch Version:**
 - [X] 2.8.13-dev (3c254f416deb834ca92fc23bde2a3f6ad9732cbb)

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [X] Linux (distribution: Gentoo)

**Comment by bugwelle** [comment]
Oh man... Why is it removed? :-/

I'll see how hard it will be to switch. I won't update our in-source QuaZip copy, yet. I will need to support both 0.9 and 1.1 of QuaZip as there are older distributions that don't have 1.1.

**Comment by bell07** [comment]
Seems removed without any reason :-( https://github.com/gentoo/gentoo/commit/379fe08fc51ec93dfaa8042c152953183fdcd736
Is there a smart way to patch the source? In Gentoo it is possible to apply additional patches before compiling.

**Comment by bugwelle** [comment]
hmmm... According to the QuaZip repo, we may only need to change the included headers. The source _should_ be compatible... Let's see. :)

**Comment by bugwelle** [comment]
Seems Arch is already patching MediaElch: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/mediaelch

**Comment by bugwelle** [comment]
@bell07 With #1340 it should be possible to build MediaElch with QuaZip 1.1 :-)

**Comment by bugwelle** [comment]
@anthraxx  I hope it's ok to ping you directly. I've seen that you're the MediaElch Arch package maintainer and that you have also updated MediaElch to v2.8.12 here:

 - https://github.com/anthraxx/arch-pkgbuilds/blob/79068f3cc51faa07d52b1c85a1ed0ec7b0ac5f3f/mediaelch/PKGBUILD

Just wanted to inform you that the workaround _should_ no longer be necessary in the next release. :-)
Furthermore, MediaElch does not depend on `qt5-script`, i.e. you can remove the dependency. 

Also, if there is anything I can do to make your life as a packager easier, please let me know.

**Comment by bell07** [comment]
Confirm the git master version works on gentoo now with quazip-1.1 and no additional patches

**Comment by bugwelle** [comment]
@bell07 Thank you very much for confirming that my patch has fixed this issue. :-)

**Comment by scottfurry** [comment]
This seems messy.
There are multiple references to `quazip5` in the files. Untangling will take some time.
On a gentoo system, quazip sources are installed as `/usr/include/QuaZip-Qt5-1.1`. I am concerned about mistakenly adding distribution specifics. Will look into this.

**Comment by bugwelle** [comment]
@scottfurry If you use CMake to build MediaElch, `/usr/include/QuaZip-Qt5-1.1` will be used and will work as the subdirectory structure is what we need (`/usr/include/QuaZip-Qt5-1.1/quazip/quazip.h` exists).

Whether MediaElch tries to load QuaZip 0.9 or 1.x will be printed in the output of the `cmake` configuration step.

I tested a few systems and on all the include path `quazip/` instead of `quazip5/` worked. If there are systems where this is not the case, please let me know.
