### ISSUE TITLE
Can't build: Incorrect include path for QuaZip with QMake

### ISSUE THREAD

**Issue by warchild13** [Komet/MediaElch#1341]
Did a git pull and followed steps: git status is "up to date"

../src/export/ExportTemplateLoader.cpp:9:10: fatal error: quazip/quazip.h: No such file or directory
 #include "quazip/quazip.h"
compilation terminated.
make: *** [Makefile:10513: ExportTemplateLoader.o] Error 1

So build fails and make is terminated

**Comment by bugwelle** [comment]
Hi,

I need a few more details:

 - What Operating System do you use? Windows/macOS/Linux (which distribution?)
 - Do you use CMake oder QMake to build it?
 - Do you use `USE_EXTERN_CMAKE`?
 - Have you initialized the git submodules? (`git submodule update --init`)

**Comment by warchild13** [comment]
Ach, sorry!

I'm on Debian (linux). I use qmake to build and make -j4. I don't usually but I tried initializing the submodules, which went fine but made no changes to the make; it still failed. Oh, and I didn't use external cmake.

Thanks.

**Comment by bugwelle** [comment]
Thanks. Reproducible. I'll fix this ASAP :)

**Comment by bugwelle** [comment]
Fixed by https://github.com/Komet/MediaElch/commit/3b81667a19be2767d21ac0d50c79c678b8e923e9
