### ISSUE TITLE
option to disable "Add Multipe Studios"

### ISSUE THREAD

**Issue by Nanomani** [Komet/MediaElch#1342]
**Is your feature request related to a problem? Please describe.**
I use a skin in kodi with a feature to display all movie from the same Studio.
But this don't work fine when there are more one Studio for the same movie

**Describe the solution you'd like**
I would like to have an option for limit the number of Studio to 1 and not all as in Kodi

**Describe alternatives you've considered**
Use the scrapper from Kodi :-)

![1](https://user-images.githubusercontent.com/3939543/121329701-bbf7af80-c915-11eb-8a94-d5a4395878b8.jpg)

**Comment by ticao2** [comment]
If u use the **advancedsettings.xml** file it should solve.
He has the option:
```
<!-- If useFirstStudioOnly is set to true then only the first studio will be written to the nfo file. -->
<!-- This is the same what XBMC does. -->

<studios>
<useFirstStudioOnly>false</useFirstStudioOnly>
```

**Comment by Nanomani** [comment]
this works very well and make what I need
thank you very much for this information :)

**Comment by Nanomani** [comment]
Feel free to close the PR if you think it is no more needed

**Comment by bugwelle** [comment]
Thanks @ticao2 for answering this question. :)

@Nanomani  thanks for confirming that it works. :)
