### ISSUE TITLE
[Status] Current state of MediaElch

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#1344]
Hi,

this is only a "FYI" issue.

MediaElch is still being _actively_ developed.
 However, as I'm currently writing my Master's thesis, I will likely take a lot longer to answer issues.

Just in case anyone wonders if there's still development here. :)

Regards,
Andre

**Comment by ticao2** [comment]
But after all, is the thesis ready?
All that's left is to defend to the bench?
Or are you just giving your head a break? **:-)**

**Comment by bugwelle** [comment]
Hi,

I've already started working on MediaElch again. I've finished my thesis and am starting with some smaller issues on MediaElch. :)

But yeah, I need(ed) a break. :smile:
