### ISSUE TITLE
Settings menu can't be opened!

### ISSUE THREAD

**Issue by Mike8822** [Komet/MediaElch#1348]
**Describe the bug**
See Header

**To Reproduce**
1. Click on 'Settings Icon'
4. See error / Crash -> Menu wont open

**Expected behavior**
Lef click on settings icon should open the settings/preferences/folders menu.

**MediaElch Version:**
 - [ ] 2.8.13-dev (nightly)
 - [X ] 2.8.12 stable

**Operating System:**
 - [X ] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Comment by bugwelle** [comment]
Hi,

does MediaElch really crash or just not open the window? Do you have multiple monitors? :)

**Comment by Mike8822** [comment]
Everything else works as intended. MediaElch does not crash. It just does not open the settings menu. Yes i have multiple monitors. How do i solve this problem if it is a "me" problem :D

**Comment by bugwelle** [comment]
Hi,

this is (sadly) a known problem. It may be an issue of Qt (the GUI framework we use) but I'm not 100% sure.
Others solved this issue by moving the window from off-screen to one of the monitors. There are a few links that may help:

 - https://www.howtogeek.com/howto/windows/bring-misplaced-off-screen-windows-back-to-your-desktop-keyboard-trick/
 - https://www.technipages.com/bring-off-screen-window-back-onto-screen

I googled "windows app off screen". :)

Please let me know if anything from there works.

Regards,
Andre

**Comment by Mike8822** [comment]
i'm sorry. i tried all those solutions, but neither of them work. It seems to me there is not additional window popping up in the first place that i have to catch elswhere from outside the screens. the window of the preferences just doesnt even open up. in the taskbar there is no second instance of mediaelch, which would indicate a second window open.

thanks 
mike

**Comment by bugwelle** [comment]
Another option is to look into MediaElch's settings in the Windows Registry, see https://mediaelch.github.io/mediaelch-doc/faq.html#where-are-mediaelchs-settings-stored , and delete all keys with `POS`, `POSITIOIN` and `SIZE` in it.

I don't have a Windows computer to test it at the moment and can't find the old issues. :-/

**Comment by Mike8822** [comment]
Problem solved:

"Another option is to look into MediaElch's settings in the Windows Registry, see https://mediaelch.github.io/mediaelch-doc/faq.html#where-are-mediaelchs-settings-stored , and delete all keys with POS, POSITIOIN and SIZE in it.

I don't have a Windows computer to test it at the moment and can't find the old issues. :-/!

Thank you so much :D

**Comment by bugwelle** [comment]
Glad that it worked. It's in the back of my head that this is an issue with multi-monitor setups. Maybe I'll have some time to debug this.

Thanks for confirming that it solved your issue. :)
