### ISSUE TITLE
Scrapers can't be reached.

### ISSUE THREAD

**Issue by Mike8822** [Komet/MediaElch#1349]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [ ] TmdbConcert
 - [X ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
Add a list of information that is not loaded correctly.

**MediaElch Version:**
 - [ ] 2.8.13-dev (nightly)
 - [ X] 2.8.12 stable

**Operating System:**
 - [X ] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**
![problem](https://user-images.githubusercontent.com/86961313/124600214-c5b5f980-de66-11eb-9931-57f6b3f63548.PNG)

**Comment by bugwelle** [comment]
TheTvDb is not reliable at all. Please try again in a few hours. :)


Btw, I can't update to their APIv4, yet, because of some issues on their side.  
TheTvDb will  stop working in ~October as they will shut down their API v3.

**Comment by Mike8822** [comment]
Sad to hear TvDB closes the API. Consider this closed. :D

**Comment by bugwelle** [comment]
Yeah, TheTvDb will switch to a subscription model :/

See this thread: https://github.com/Komet/MediaElch/issues/1120
