### ISSUE TITLE
Information from IMDB not being fetched

### ISSUE THREAD

**Issue by monisriz** [Komet/MediaElch#1350]
**Describe the bug**
IMDB scrapper not fetching information

**To Reproduce**

When using custom scraper to choose some things to be fetched from IMDB (e.g. plot, ratings, votes, etc.) the information is not being populated.

**Expected behavior**
When using custom scraper to choose some things to be fetched from IMDB (e.g. plot, ratings, votes, etc.) the information should be populated.

**Screenshots**

**MediaElch Version:**
 - [ ] 2.8.13-dev (nightly)
 - [x] 2.8.12 stable

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**

**Comment by bugwelle** [comment]
Thanks. Also happens with IMDB-only for some movies. Related: #1092

**Comment by bugwelle** [comment]
I'm working on it, see  #1092

**Comment by bugwelle** [comment]
Fixed by #1092

New nightly will be available in a few hours.
