### ISSUE TITLE
AEBN scrapper not working gives network error 

### ISSUE THREAD

**Issue by myxtrastufff** [Komet/MediaElch#1354]
**Describe the bug**
AEBN scrapper not working gives network error 

**To Reproduce**
Scrape any movie from AEBN scraper

**Expected behavior**
When scraping with AEBN it works. Sorry, I'm not trying to sound like an ass.

**Screenshots**

**MediaElch Version:**

 - [ X] 2.8.12 stable

**Operating System:**
 - [ X] Windows 10

**Additional context**
Works on version  2.8.6

**Comment by bugwelle** [comment]
Thank you for opening this issue.

> Sorry, I'm not trying to sound like an ass.

You don't. That's exactly what you're supposed to write :smile: 
Thank you for following the template.

I will check this later today. If it's an easy fix, I'll fix it in the next few days. However, if it's a larger issue, I don't have time at the moment because I'm currently writing my a thesis at university and it's taking a lot of my time. :)

Btw, what network error is shown? :)

**Comment by myxtrastufff** [comment]
Network Error: Content not found

**Comment by bugwelle** [comment]
Ok, does that happen for all movies? On my setup, I can load movies just fine. :)

If you could give me an example, that would be great. The error indicates that the website/resource we try to scrape does not exist. It could be that we load the wrong URL.

**Comment by geek-baba** [comment]
Yes it happens with all the movie and It was working before I updated to 2.8.12, maybe a coincidence but it happened exactly after I updated. I believe I was on 2.7 version before, but not sure...

**Comment by RodrigoTMorais** [comment]
I have same insue.

MediaElch 2.8.12 - Coridian
Windows 10

error with AEBN scraper:  Network Error: Content not found

**Comment by geek-baba** [comment]
I see the same issue, I thought it was intermittent...

**Comment by bugwelle** [comment]
Thank you for reporting this issue. I'm looking into it but couldn't reproduce the issue, yet. I'll have to check on a virtual machine whether it may be an issue with the AppImage on Manjaro or similar linux distributions.

I should have time for that next week.

Regards,
Andre

**Comment by sergi256** [comment]
Hi, the last time I checked it's working fine. It fixed itself some weeks
later I wrote the error report.
Manjaro has update itself multiple times since then.
If you need any more information please let me know.

Best,
Sergi

**Comment by bugwelle** [comment]
Thank you for letting me know, and sorry about the late answer. If this error comes up again, please let me know. :-)
