### ISSUE TITLE
IMDb not working 

### ISSUE THREAD

**Issue by Mahmoud4422** [Komet/MediaElch#1355]
**Scrapers that don't work:**

 - [* ] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [ ] TmdbConcert
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
its not scrape anything no rating or anything for all movies for me.

**MediaElch Version:**
 - [ ] 2.8.13-dev (nightly)
 - [*] 2.8.12 stable

**Operating System:**
 - [ *] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**
how to fix it

**Comment by bugwelle** [comment]
Thanks for reporting this issue. :)

See #1350 for more details. :)

**Comment by bugwelle** [comment]
Fixed by  #1092

New nightly will be available in a few hours.
