### ISSUE TITLE
MediaElch.exe keeps crashing on launch on Windows 10 (21H1). Faulting module name: ig4icd64.dll

### ISSUE THREAD

**Issue by goodboydheeraj** [Komet/MediaElch#1363]
Hey its the first time I'm running MediaElch on my PC. Every time I open MediaElch.exe it just keeps exiting. Even in Administrator mode. The .exe file sows up in the Task manager processes for a while but just crashes/closes immediately.

Below is the error log from windows event viewer

> Faulting application name: MediaElch.exe, version: 0.0.0.0, time stamp: 0x5fd639ad
> Faulting module name: ig4icd64.dll, version: 8.15.10.2869, time stamp: 0x506dfa58
> Exception code: 0xc0000005
> Fault offset: 0x00000000006d5912
> Faulting process id: 0x1958
> Faulting application start time: 0x01d7c925b2bcbb7f
> Faulting application path: C:\Users\DHEERAJ\Desktop\MediaElch\MediaElch.exe
> Faulting module path: C:\Windows\SYSTEM32\ig4icd64.dll
> Report Id: 83226b9d-dfd7-4a2d-966a-c69724f681d8
> Faulting package full name: 
> Faulting package-relative application ID: 

This is on my Dell Inspiron 1545 with potato graphics: Mobile Intel(R) 4 Series Express Chipset Family (Microsoft Corporation - WDDM 1.1)
Driver Version: 8.15.10.2702
Windows 10 21H1 (19043.1237)

**Comment by bugwelle** [comment]
Tested on Windows 10 Education 10.0.19044, clean installation: MediaElch starts up just fine.

I'm currently installing the latest updates and will test again.

It could indeed be a driver issue in which case I can't help. My advice is to update all drivers and Windows itself.

**Comment by bugwelle** [comment]
Tested with latest updates as well and works just fine.

Please update all drivers and/or Windows as well. If the issue still persists, please reply to this issue and I will reopen it. :-)

Regards,
Andre
