### ISSUE TITLE
Issue with build/update

### ISSUE THREAD

**Issue by warchild13** [Komet/MediaElch#1371]
*Hi,
A bit of a problem building on debian 11.

WARNING: Failure to find: /home/david/MediaElch/third_party/quazip/quazip/quachecksum32.cpp
WARNING: Failure to find: /home/david/MediaElch/third_party/quazip/quazip/quazip_qt_compat.h

make: *** No rule to make target '/home/david/MediaElch/third_party/quazip/quazip/quachecksum32.cpp', needed by 'quachecksum32.o'.  Stop

**Comment by bugwelle** [comment]
Hi,

it may be because I've updated git-submodule QuaZip to 1.1.
Have you updated MediaElch's git submodules? If not, this should do the trick:

```
git submodule update --init
```

Do you use CMake or QMake to build MediaElch? :)

Regards,
Andre

**Comment by warchild13** [comment]
git submodule update --init
Ah, that did the trick. I use qmake. 
Running well, first impression is that it
s a bit snappier.

**Comment by bugwelle** [comment]
Glad I could help :-)

The reason I updated QuaZip was that MediaElch will fully support Qt6 soon. And QuaZip 0.9 does not support Qt6.

Unless there are any further questions, I'll close this issue. :)
