### ISSUE TITLE
MediaElch adds Î to end of media files

### ISSUE THREAD

**Issue by jeffabailey** [Komet/MediaElch#1376]
**Describe the bug**

**To Reproduce**
1. Go to 'Rename selected files'
2. Click on 'Rename'

**Expected behavior**

No Î added to the end of media files 

**MediaElch Version:**
 - [ ] 2.8.12 (Coridian)

**Operating System:**
 - [ ] Windows
 - [X ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**

I use homebrew to install MediaElch.

```
$ ▶ brew info MediaElch
mediaelch: 2.8.12,2021-05-10_06-33,08ebf8c0
https://www.kvibes.de/en/mediaelch/
/usr/local/Caskroom/mediaelch/2.8.12,2021-05-10_06-33,08ebf8c0 (123B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/mediaelch.rb
==> Name
MediaElch
==> Description
Media Manager for Kodi
==> Artifacts
MediaElch.app (App)
==> Analytics
install: 15 (30 days), 38 (90 days), 148 (365 days)
```

**Comment by bugwelle** [comment]
Hi there,

I couldn't reproduce the issue. I need a bit more details here: :smile:

1. What language do you use?
2. In the renamer dialog, what did you enter in the text fields? That is, what placeholders, etc. do you use?

See also: https://mediaelch.github.io/mediaelch-doc/renaming.html

Regards,
Andre

**Comment by bugwelle** [comment]
Closed due to inactivity of about a month.

Please reply and I will reopen this issue.

**Comment by jeffabailey** [comment]
It turns out that the File Naming field had this as the value.

```
<title>.<extension>Î
```

I don't recall ever adjusting that value. I don't have a clue how to even type that character, but thanks for the response!

**Comment by bugwelle** [comment]
Ah, thank you very much for your response! :-)
Hmmm.. I had that happen to me as well. A text field was auto-selected and I accidentally typed something.
