### ISSUE TITLE
Allow season names to be used when renaming season folders

### ISSUE THREAD

**Issue by ReK42** [Komet/MediaElch#1378]
Some shows have named seasons. MediaElch supports these names and will save them in the NFO file, but it cannot be used when automatically renaming the season folders. A useful feature would be to implement the <seasonName> variable in the renamer. For example, the settings in the first screenshot below should result in the folder structure shown in the second screenshot.

![image](https://user-images.githubusercontent.com/4775937/147843431-01c52e70-7904-4349-8445-cfd8c4ffa40f.png)

![image](https://user-images.githubusercontent.com/4775937/147843452-b94de623-8883-4c3f-9afa-49b01742fe9d.png)

**Comment by bugwelle** [comment]
This was implemented by @oellan in  #1381. :-)

You can now use `<seasonName>` and `{seasonName}` in the renamer. The former is the placeholder, the latter is the condition.

Regards,
Andre

**Comment by bugwelle** [comment]
A new nightly for Linux is now available. One for Windows will be uploaded in the next 10min.
