### ISSUE TITLE
Recognise OGV videos

### ISSUE THREAD

**Issue by Rygle** [Komet/MediaElch#1382]
MediaElch 2.8.12 does not presently recognize .ogv format videos. These play in a variety of media players - see https://extension.nirsoft.net/ogv - also seems to be supported by Kodi - see https://forum.kodi.tv/showthread.php?tid=34491

Should hopefully be a very easy fix/enhancement as it just requires adding that extension to a list of recognised formats.

**Comment by Rygle** [comment]
Added a pull request that might fix this issue.

https://github.com/Komet/MediaElch/pull/1383

**Comment by bugwelle** [comment]
Thank you very much for opening the pull request. I've also added them to our default list in this commit:
https://github.com/Komet/MediaElch/commit/66831baf1dd99451c85570c8038516b8d489f0cd

I very much appreciate your contribution :-)

Regards,
Andre
