### ISSUE TITLE
Better movie match while scraping

### ISSUE THREAD

**Issue by superpupervlad** [Komet/MediaElch#1400]
**Is your feature request related to a problem? Please describe.**
I have a lot of movies with weird filenames which MediaElch poorly recognize. So I started thinking how it can be improved.

**Describe the solution you'd like**
The easiest solution is **consider runtime of the movie** file: if length of movie is 123 minutes and list of IMDB's result contains only one movie with this runtime MediaElch will choose this movie. There are lot of options for user to tweak:
- Set difference in how much runtime can differ +- 2 minutes or +-5%
- Filter or not results with different runtime
Some movies has different cuts with different runtime but IMDB has [info about it](https://www.imdb.com/title/tt0167261/technical).

**Describe alternatives you've considered**
Some other methods that can help improve recognition of films:
- **Online search filename of movie**. This may sound stupid and inefficient but I was really surprise how well it works, we just need to choose a good search engine. While `movie_filename_without_.extenstion site:imdb.com` or `site:themoviedb.org` query in  Google gives 0 results, Bing and Yahoo finds random movies, first link in **DuckDuckGo** and **Yandex** is **exactly the one I wanted**.
- **Use movie title from metadata**. When file has this value it often contains "searchable" name of movie. And better use this one instead of filename.

**Comment by bugwelle** [comment]
Hi, thank you for this feature request. It took a year, but I finally got the time to go through old issues.

I have some minor improvements planned in https://github.com/Komet/MediaElch/issues/1627

> The easiest solution is consider runtime of the movie file: if length of movie is 123 minutes and list of IMDB's result contains only one movie with this runtime MediaElch will choose this movie. 

The runtime of a movie when searching is not known until a movie is scraped. Neither TMDB, IMDB, nor other websites I know provide this detail in their search. As matching "expected runtime<->search result runtime" could be implemented for single-movie-searches, the multi-movie-search would become extremely slow, as we would need to scrape e.g. the top 5 results for each movie. That's not feasible.

For single movie searches, there is now a preview, see https://mediaelch.github.io/mediaelch-blog/posts/mediaelch-v2.10.4/

> Online search filename of movie. 

That would mean to parse search results of DuckDuckGo, Google or other search engines.
That is actually not a bad idea, at least with the site-filter. :smile:
However, I think that (at least Google) explicitly prohibit using their search that way... 

While I think the underlying idea could work, I think the development overhead does not warrant this to be implemented.

> Use movie title from metadata.

That should now be the case. If there is a NFO file with a corresponding name tag, it will be used by default.

----

Improving the default file name will be tracked in  https://github.com/Komet/MediaElch/issues/1627

The other feature requests will not make it, though. Sorry about that.

Regards,
Andre
