### ISSUE TITLE
Renamer doesn't respect custom pattern

### ISSUE THREAD

**Issue by spacecowboy** [Komet/MediaElch#1401]
**Describe the bug**
I am modifying the File name pattern in Renamer. But Dry-Run doesn't respect what I input. I always renames according to default pattern.

**To Reproduce**
1. Open a season worth of episodes in Renamer (22 episodes in my case)
2. Modify the File Naming pattern to start with `<title> - ` (default is to start with `S<season>`)
3. Press Dry Run

**Expected behavior**
Dry run should indicate that episodes are going to be renamed according to the pattern I inputted

**Screenshots**
![Screenshot from 2022-01-22 12-04-54](https://user-images.githubusercontent.com/223655/150635942-b8a5a9b8-07b9-4cb6-b685-502e2ca8c636.png)
![Screenshot from 2022-01-22 12-04-37](https://user-images.githubusercontent.com/223655/150635945-c63c5d3b-aaae-4279-8b46-868bf519854d.png)

**MediaElch Version:**
 - [x] `MediaElch_linux_2.8.12_2021-05-10_06-46_git-master-08ebf8c.AppImage`

**Operating System:**
 - [x] Linux (distribution: Debian Buster)

**Additional context**
No

**Comment by bugwelle** [comment]
Hi,

as far as I can see in your screenshot, the dry run shows exactly what I would expect (episode name starts with `<title>`).
Could you give me an explicit example of what you would expect and what is shown?

Regards,
Andre

**Comment by spacecowboy** [comment]
I just realized my mistake. `title` is plainly visible first in the renames.

I didn't notice it because I should have used `showTitle`.

**Comment by bugwelle** [comment]
Ah, ok! Thanks for clarifying. :-)
