### ISSUE TITLE
IMDB works, but missing Overview and Ratings

### ISSUE THREAD

**Issue by jillian1701** [Komet/MediaElch#1405]
**Scrapers that don't work:**

 - [x] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [ ] TmdbConcert
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
Overview not loading
Ratings not loading

**MediaElch Version:**
 - [x] 2.8.13-dev (nightly)
 - [ ] 2.8.12 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: Pop OS 21.10)

**Additional context:**
I tried the Nightly (AppImage) b/c IMDB wasn't working at all in Stable. Success! It works. Alas, it won't download the Overview text or the rating. I did try each of the nightly AppImage's that are currently available. All have the same issue.

**Comment by jillian1701** [comment]
Hello again. I don't see anything that immediately jumps out at me from the log file. Here is the complete log when searching for and scraping 1 episode:

`MediaElch 2022-02-03 10:04:29.806 DEBUG : [TvShowFilesWidget] Selected item at row 0 and column 0
MediaElch 2022-02-03 10:04:29.806 DEBUG : Entered, show= "Star Trek Voyager" season= "1"
MediaElch 2022-02-03 10:04:32.120 DEBUG : [TvShowFilesWidget] Selected item at row 0 and column 0
MediaElch 2022-02-03 10:04:32.120 DEBUG : Entered, episode= "Star Trek Voyager Season 1 Episode 01 - Caretaker"
MediaElch 2022-02-03 10:04:32.121 DEBUG : Entered, episode= "Star Trek Voyager Season 1 Episode 01 - Caretaker"
MediaElch 2022-02-03 10:04:34.361 DEBUG : [TvShowFilesWidget] Multi Scrape: Selected 0 shows and 1 episodes
MediaElch 2022-02-03 10:04:34.368 DEBUG : Entered, currentIndex= 1
MediaElch 2022-02-03 10:04:34.377 CRIT  : [TvShowSearch] Couldn't find season order element in combo box
MediaElch 2022-02-03 10:04:34.379 INFO  : [TvShowSearch] Start search for: "Star Trek Voyager"
MediaElch 2022-02-03 10:04:34.379 INFO  : [ImdbTv] Search for: "Star Trek Voyager"
MediaElch 2022-02-03 10:04:36.108 DEBUG : [TvShowSearch] Result count: 3
MediaElch 2022-02-03 10:04:41.625 DEBUG : Entered, message= "Scraping episode..." id= 10003
MediaElch 2022-02-03 10:04:41.627 INFO  : [TvShow] Load episode with show id ShowIdentifier("tt0112178") using scraper "IMDb TV"
MediaElch 2022-02-03 10:04:41.627 DEBUG : [ImdbTv] Load single episode of TV show with id: EpisodeIdentifier(Show("tt0112178"), SeasonNumber("01"), EpisodeNumber("01"))
MediaElch 2022-02-03 10:04:41.627 DEBUG : [ImdbTvEpisodeScrapeJob] Have to load season first.
MediaElch 2022-02-03 10:04:41.714 DEBUG : [TvShowFilesWidget] Selected item at row 10 and column 5
MediaElch 2022-02-03 10:04:41.714 DEBUG : Entered, show= "Star Trek"
MediaElch 2022-02-03 10:04:41.716 DEBUG : Entered, show= "Star Trek"
MediaElch 2022-02-03 10:04:44.031 INFO  : [ImdbTvEpisodeScrapeJob] Loading episode with IMDb ID "tt0114530"
MediaElch 2022-02-03 10:04:46.126 DEBUG : [NotificationBox] Hide Progress bar with id 10003
MediaElch 2022-02-03 10:04:46.126 DEBUG : [NotificationBox] Removing message with ID: 10003
MediaElch 2022-02-03 10:04:46.127 DEBUG : [DownloadManager] Enqueue download at pos  0 | QUrl("https://m.media-amazon.com/images/M/MV5BN2ExMzM5OGQtM2M1Yy00OWM1LWE1YWMtYTQzNjQ5YmE1NjU3XkEyXkFqcGdeQXVyMzQ2MDUxMTg@._V1_UX400_CR0,0,400,225_AL_.jpg")
MediaElch 2022-02-03 10:04:46.127 DEBUG : [DownloadManager] Start next download | Files left: 0
MediaElch 2022-02-03 10:04:46.903 INFO  : [DownloadManager] All downloads finished
MediaElch 2022-02-03 10:04:46.903 DEBUG : Got a backdrop
MediaElch 2022-02-03 10:04:46.910 DEBUG : [ImageCache] Using cache dir: DirectoryPath("/home/jillian/.local/share/kvibes/MediaElch/images")
MediaElch 2022-02-03 10:04:48.821 DEBUG : [TvShowFilesWidget] Selected item at row 0 and column 0
MediaElch 2022-02-03 10:04:48.821 DEBUG : Entered, episode= "Caretaker"
MediaElch 2022-02-03 10:04:48.823 DEBUG : Entered, episode= "Caretaker"`

**Comment by jillian1701** [comment]
Seems like MediaElch Coridian fixed this issue, at least for re-scraping existing shows. Nicely done! :)

**Comment by bugwelle** [comment]
Thanks for your reply! :-)

In that case I'll close this issue.
