### ISSUE TITLE
Ignore Articles when sorting ignored forign word articles.

### ISSUE THREAD

**Issue by snostormjp** [Komet/MediaElch#1406]
**Describe the bug**
Incorrectly ignoring articles from a foreign language, when system set to a different language.  The example I found was Die Hard which gets sorted as Hard, Die  on English System.

**To Reproduce**
Steps to reproduce the behaviour:
1. On system with LANG set to en_US.UTF-8
2. Load Movie Die Hard 
2. enable ignore articles 
3. Sort and Movie is in H for Hard, Die 

**Expected behavior**
Should be sorted as Die Hard on English system.  Expect that in setting Title are set a Language, and only Articles from that Language are ignored.  

**MediaElch Version:**
 - [ ] 2.8.12 stable

**Operating System:**
 - [ ] Linux (distribution: Arch Linux)

**Comment by bugwelle** [comment]
Hi,

MediaElch ignores the language of the movie. However, you can change the words MediaElch removes in the `advancedsettings.xml` file. See

- https://mediaelch.github.io/mediaelch-doc/settings.html#advanced-settings
- https://github.com/Komet/MediaElch/blob/0431858d9e3628d34b3dbff3a0bbba4a92b6c939/docs/advancedsettings.xml#L68-L84

Regards,
Andre

**Comment by snostormjp** [comment]
This worked thanks,  my opinion would be this should not be an advanced
option or set based on a language setting but thanks for the help, close or
shift report to enhacement.

**Comment by bugwelle** [comment]
> This worked thanks,  my opinion would be this should not be an advanced
option or set based on a language setting but thanks for the help, close or
shift report to enhacement.

Totally agree! It's a matter of spare-time. I didn't get to implement it in the UI, yet. :)
