### ISSUE TITLE
Rescrape of scraped movie -> actors listed multiple times

### ISSUE THREAD

**Issue by Roemer** [Komet/MediaElch#1410]
**Describe the bug**
It seems that #877 is back. When I rescrape a movie and save it, each time the actors are all added again.

**To Reproduce**

1. Open an already scraped movie.
2. Open actors tab.
3. Click scrape or Ctrl-F.
4. Watch the list multiply.

**Expected behavior**
The list should be emptied and populated according to the scraper source or at least not having the actors already on the list added once again.

**MediaElch Version:**
 - [ ] 2.8.15-dev (nightly)
 - [x] 2.8.14 stable

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Comment by bugwelle** [comment]
Thanks for opening this issue. No idea how and why this happened. I will look into it.

**Comment by bugwelle** [comment]
Can't reproduce anymore. Tested with IMDb, TMDb, VideoBuster and custom movie scraper. Also via "multi-movie search".

Sorry for the long delay. I haven't looked into this issue for a while.
