### ISSUE TITLE
tvdb doesn't appear as scraper

### ISSUE THREAD

**Issue by martynjlewis** [Komet/MediaElch#1413]
Hi, as the title says, tvdb doesn't appear as a scraper for TV despite showing up despite being set as the TV scraper in options and showing as Initialized. Please see the attached Screenshot.
![Screenshot_20220213_221736](https://user-images.githubusercontent.com/24782505/153777810-8c07dcc3-1fe7-42b7-b9c4-7a41e66493c3.png)

**Comment by martynjlewis** [comment]
![Screenshot_20220213_221736](https://user-images.githubusercontent.com/24782505/153777763-667d72c4-f683-4a56-b1db-241165d4b777.png)

**Comment by ticao2** [comment]
See here: https://github.com/Komet/MediaElch/issues/1120

**Comment by martynjlewis** [comment]
> See here: #1120

Aw, damn. I didn't know that. Thanks for the info, I will move to TMDb in that case.

**Comment by bugwelle** [comment]
> > See here: #1120
> 
> Aw, damn. I didn't know that. Thanks for the info, I will move to TMDb in that case.

Yeah, sorry about that. Due to their changes and my limited time, TheTvDb is no longer supported. But because it's so deeply rooted into MediaElch, I did not yet get to remove it everywhere.

Regards,
Andre
