### ISSUE TITLE
Loading StreamDetails does not work

### ISSUE THREAD

**Issue by JalilArfaoui** [Komet/MediaElch#1414]
**Describe the bug**

On newly detected movies, stream details comes empty : 

![image](https://user-images.githubusercontent.com/3037833/153780254-f35fec43-1497-4c7c-9e04-3d9d8b9b01a5.png)

If open an existing movie with existing information (from Ember Media Manager), I can see the existing info : 

![image](https://user-images.githubusercontent.com/3037833/153780074-e796a919-8f67-418a-8155-97f8a0808773.png)

But as soon as I click on «load from file» it gets all lost : 

![image](https://user-images.githubusercontent.com/3037833/153780254-f35fec43-1497-4c7c-9e04-3d9d8b9b01a5.png)

**To Reproduce**

1. Go to any movie
2. Click on Stream Details
3. Click on load from files
4. See all fields empty

**Expected behavior**

Audio and video informations from file should load.

**MediaElch Version:**
 - [ ] 2.8.15-dev (nightly)
 - [x] 2.8.12 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: Nixos 21.11)

**Additional context**
Gnome, Wayland, French

**Comment by JalilArfaoui** [comment]
I forgot to paste developer info : 

```
MediaElch 2.8.12 - Coridian

Compiled with Qt version 5.15.3 (64 Release, GCC 10.3.0)
Using Qt version 5.15.3
System: NixOS 21.11 (Porcupine) (x86_64-little_endian-lp64)

Application dir: /nix/store/ambssjd6788n35c7yvg8kqmaqzvz71cl-mediaelch-2.8.12/bin
Settings file: /home/jalil/.config/kvibes/MediaElch.conf
Data dir: /home/jalil/.local/share/kvibes/MediaElch
Qt Translation Path: /nix/store/41zwi3a4c80vvgig5xglchkax37h04k5-qtbase-5.15.3/translations

MediaInfo Version: Unable to load libmediainfo.so.0

Default UI languages: fr-FR

Custom advancedsettings.xml: false
```

**Comment by JalilArfaoui** [comment]
Actually the developer info gave me a clue about the issue (Unable to load libmediainfo.so.0) so I opened another issue here : https://github.com/NixOS/nixpkgs/issues/159918 !

**Comment by Stunkymonkey** [comment]
In the build the `libmediainfo` is provided: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/mediaelch/default.nix#L31
Not sure if this is a configuration problem.

**Comment by JalilArfaoui** [comment]
> In the build the `libmediainfo` is provided: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/mediaelch/default.nix#L31

Yes I saw that …

Any clue of something I can try to understand why MediaElch cannot find it ?

**Comment by Stunkymonkey** [comment]
i got it working on my machine by using:
```
export LD_LIBRARY_PATH=/nix/store/pppvvyn48s0li7valx0ac2q402p4b51v-libmediainfo-21.09/lib:$LD_LIBRARY_PATH
```
and then run `MediaElch`.

**Comment by JalilArfaoui** [comment]
I confirm it works perfectly here with 

```
LD_LIBRARY_PATH=/nix/store/pb1b3gj5c2dmgjklag0kpxl6k0px8qan-libmediainfo-21.09/lib:$LD_LIBRARY_PATH MediaElch
```

**Comment by bugwelle** [comment]
Hi,

as @Stunkymonkey explained, libmediainfo could not be loaded. But MediaElch shouldn't silently fail.
In #1416 I will adapt MediaElch to at least no override existing values if MediaInfo fails to load.

Regards,
Andre

**Comment by bugwelle** [comment]
![Screenshot_20220219_162115](https://user-images.githubusercontent.com/1667306/154807101-c9134c76-69d3-473e-8c10-89abecbbeb75.png)

Nothing fancy, translations have to be created. But at least the use get's some sense that something is going wrong.
