### ISSUE TITLE
Some TV Series Episodes on one DVD are not recognized  (Multi Episodes)

### ISSUE THREAD

**Issue by habakuk007** [Komet/MediaElch#1429]
**Describe the bug**
I have this structure on my disc:

* Serie (2022)
  *  Season 1
     * S01E01E02E03E04
        * VIDEO_TS
     * S01E05
        * VIDEO_TS  
     * S01E6.disc
     * S01E07E08E09.disc

And try to scan and edit it with MediaElch. But it only recognizes this episodes: 01, 02, 05, 06, 07, 08

The episodes: 03, 04, 09 are not listed

**To Reproduce**
1. Use the folder structure from this zip file
[Serie (2022).zip](https://github.com/Komet/MediaElch/files/8366125/Serie.2022.zip)
2. Add it to MediaElch

**Expected behavior**
All episodes are listed

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2253878/160482454-4e4a4472-6ca6-4635-945a-0ab6265b5552.png)

**MediaElch Version:**
 - 2.8.12
 - 2.8.16

**Operating System:**
 - Windows 10

**Additional context**
Multi episodes from one file are described here: https://kodi.wiki/view/Naming_video_files/Episodes#Multi-Episode_Files

**Comment by bugwelle** [comment]
Hi,

thank you for bringing this up. Multi-Episode names are tricky. I've fixed some false-positives and false-negatives in the past, but apparently something is always missing. :smile: 

I will look into this issue soon. The filename `S01E01E02E03E04` is enough to reproduce this issue.

**Comment by bugwelle** [comment]
Your issue will be fixed by #1434. The next Nightly version will include this fix.
