### ISSUE TITLE
Files are renamed, but old filename stays in nfo

### ISSUE THREAD

**Issue by FredFoo** [Komet/MediaElch#1432]
**Describe the bug**
When using the file renamer to rename for instance srt files, the name for this file in the nfo stays the old one. But that file is gone. 

**To Reproduce**
1. Select a movie that has an srt file
2. Open file renamer
3. Change filename pattern to `<title>.<year>.<extension>`
4. Rename
5. Check the srt filename in the nfo file

**Expected behavior**
When renaming files, any file that is mentioned in the nfo file should also be renamed

**MediaElch Version:**
 - [ ] 2.8.17-dev (nightly)
 - [X] 2.8.16 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [X] Linux (distribution: Ubuntu.18.04)

**Comment by bugwelle** [comment]
Oh! That is a good point! Thank you for bringing this up. Reloading & Re-saving may help here.

**Comment by bugwelle** [comment]
With #1436 this will be fixed. Now, if the subtitle is renamed, the movie will be marked "changed". Clicking "Save All" will then save the renamed NFO file with the updated subtitle file name.

See the screenshots in #1436 for an example. :-)

Thank you very much for reporting this issue!
