### ISSUE TITLE
imdb not scraping

### ISSUE THREAD

**Issue by Mahmoud4422** [Komet/MediaElch#1441]
so any episode rating and info not scrape it rating become always 0 and info for episodes empty

**Comment by bugwelle** [comment]
I can confirm: Episodes don't work, TV shows do. I didn't have a test case for that, yet, which I will now add as well.

**Comment by bugwelle** [comment]
Fixed by commit 0efd5ee47aebb50a7cbe69d330cdd587df80400a

A new nightly version of MediaElch will become available shortly for Windows and Linux (AppImage).
