### ISSUE TITLE
icuin66.dll not found

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#1443]
Installed lated nightly.. 
trying to run it i get this error message
icuin66.dll not found

What sould i do?
thank you
Nicolas

**Comment by bugwelle** [comment]
Hi,

what version of Windows do you use? :-)

**Comment by nkatsidis** [comment]
Hello :)
Latest Windows 10 version (with latest update)

Nicolas

**Comment by bugwelle** [comment]
Reproduced. Seems that an update of MXE also updated Qt and I didn't notice. I will fix this ASAP. :-)

Thank you for reporting!

**Comment by bugwelle** [comment]
Should be fixed by https://github.com/Komet/MediaElch/commit/e1f27fdf50f4266ddaf2473964f73ab329795844

A new nightly is being build right now. It should be available in about 30min

**Comment by bugwelle** [comment]
Nightly now available. Tested and works. The ZIP file is about 10 MB larger than before. I will see if I can remove DLLs that are no longer needed.

https://mediaelch-downloads.ameyering.de/snapshots/Windows/
