### ISSUE TITLE
When Mediaelch start the  Scanning for Movies window takes for ever to complete

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#1445]
Latest 24/6 beta.
Windows 10.

I run Mediaelch then  Window Searching for movies pops up and it takes for ever to complete.

Closing it shows 0 movies.

Then i press scan for movies and again scanning for movies is reaaaaaaaallly slow... 

Something changed in movie scanning ??

**Comment by bugwelle** [comment]
:-/

Thanks for reporting! How many movies do you have?

**Comment by bugwelle** [comment]
Ok, thanks for letting me know. Do you happen to know which version was fast and which was slow? (do you use stable versions or Nightlies?)

Sorry for the late replies. :-)

**Comment by nkatsidis** [comment]
you may close this issue with latest nightlies (windows) its ok. Q)

**Comment by bugwelle** [comment]
Ok. That's strange. I don't think there were any changes in that regard. If it happens again, please let me know (even if I may not be able to help you quickly) :-)
