### ISSUE TITLE
Hide a specific episode. 

### ISSUE THREAD

**Issue by Estarna** [Komet/MediaElch#1447]
Hi there is there a way to tag an episode in MediaElch that tells Kodi to ignore this one?

Thanks!

-Eric

**Comment by Estarna** [comment]
Hi there,
Thanks for the follow-up!

Regards,

-Eric

**Comment by bugwelle** [comment]
Sorry for the late answer. I'm quite busy at the moment :-)

**Comment by Estarna** [comment]
No problem there Andre.

Talk to you soon!

De : Andre Meyering ***@***.***>
Envoyé : 19 juillet 2022 13:07
À : Komet/MediaElch ***@***.***>
Cc : Estarna ***@***.***>; State change ***@***.***>
Objet : Re: [Komet/MediaElch] Hide a specific episode. (Issue #1447)


Sorry for the late answer. I'm quite busy at the moment :-)
