### ISSUE TITLE
Scan and Art File Names

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#1448]
**Describe the bug**  

MediaElch **2.8.17 2022-06-24_00-12** - Win 11 - Portable Mode

**Scan**
I installed it, portable mode, and I scanned folders with movies that already have NFO with all the data.
All appear in the list as if they were new, without NFO, despite having the NFO.
I closed and reopened ME, and there were all movies with all data.
On the first scan it looks like it read the NFO but it didn't show that it did.
And it didn't show the data either.
When I reopened everything was OK.

**Art File Names**
Now both in Movies and in Series the fields have Dropdown.
In Series they appear normally.
But in movies the default names do not appear.
I put it with Copy and Paste.
I closed and reopened ME, and they were no longer there.
What I edited manually with copy and Past is gone.

The previous version I have installed and running is 
MediaElch_2.8.17_2022-03-21_00-12 .
It's just a bug.
When I manually add the Movie year, the year is not saved in the NFO.
The problem occurred with a family movie.
No scraper on TMDb or any other site.

**Comment by bugwelle** [comment]
That is strange. Thank you for reporting this issue!

Did version `MediaElch_2.8.17_2022-03-21_00-12` work for you?

I have the assumption 72c3d77a7f0b5423c978244afc22cd42ce484a97 is at fault. I will check.

**Comment by bugwelle** [comment]
Apparently it's b15d5d2752745ce60f36c3fd87b4b00503f3b6b0

**Comment by bugwelle** [comment]
Thank you SO MUCH, @ticao2 !

This was a major bug. I will need to do a release soon.

**Comment by bugwelle** [comment]
Thank god,... this is not part of 2.8.16, but only the latest nightlies...

**Comment by ticao2** [comment]
> That is strange. Thank you for reporting this issue!
> 
> Did version `MediaElch_2.8.17_2022-03-21_00-12` work for you?
> 
> I have the assumption [72c3d77](https://github.com/Komet/MediaElch/commit/72c3d77a7f0b5423c978244afc22cd42ce484a97) is at fault. I will check.

Yup. It's working without any problems.
Only the irrelevant Bug from when we manually added the date.
It only occurs in family videos, which will not be searched on TMDB.

**Comment by ticao2** [comment]
I installed the latest version of MediaElch.
MediaElch_win_2.8.17-dev_2022-07-20_00-07_git-master-9f97a511
Everything working perfectly. **:-)**

**Comment by bugwelle** [comment]
Thanks for confirming, @ticao2 !
