### ISSUE TITLE
Fanart.tv - bad gateway (resolved)

### ISSUE THREAD

**Issue by RaGo66** [Komet/MediaElch#1459]
**Describe the bug**
Trying to load additional art from fanart.tv, but receiving a bad gateway error message (both with 2.8.16 and 2.8.17-dev)

**To Reproduce**
1. Go to 'TV-Series', load basic data (I experienced with "Dexter New Blood")
2. Click on 'Logo' (or any other blank art field)
3. See error message in open 'select Art' dialog: Error transferring [file name] - server replied: Bad Gateway

**Expected behavior**

**Screenshots**

**MediaElch Version:**
 - [ X ] 2.8.17-dev (nightly)
 - [ X ] 2.8.16 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this issue. 

>  Bad Gateway

That seems like a problem of fanart.tv. Error 503 (Bad Gateway) normally means that the server tried to access another server which didn't respond --> an issue of fanart.tv, not MediaElch.

I just tested it locally and everything is working fine.

Could you test it again and see if it works?

Do you use any Proxy or VPN or similar?

Regards,
Andre

**Comment by RaGo66** [comment]
Thx for the response.
I just checked again, and the problem is no longer present. So likely it was a temporary glitch of fanart.tv

**Comment by RaGo66** [comment]
Hi, I'm out of town until Sunday.I'll test once I'm backI did try with and without VPN.I was suspecting that maybe fanart.tv did change a port or something, that would require changes to MediaElch. Even better if the issue resolved itselfRegards,Ralf--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 24.08.22, 19:01 schrieb Andre Meyering ***@***.***>:

   
  Hi, 
  thanks for reporting this issue. 
   
   Bad Gateway 
   
  That seems like a problem of fanart.tv. Error 503 (Bad Gateway) normally means that the server tried to access another server which didn't respond --> an issue of fanart.tv, not MediaElch. 
  I just tested it locally and everything is working fine. 
  Could you test it again and see if it works? 
  Do you use any Proxy or VPN or similar? 
  Regards, Andre
