### ISSUE TITLE
Crashes on poster select

### ISSUE THREAD

**Issue by warchild13** [Komet/MediaElch#1475]
When a film is selected double click on poster, alternate poster window opens. Select alt poster and ME Crashes instantly.
Holds true on last few builds.

Debian/GNU 11
QT 5.15.2
Kernel 5.10-18-amd64

**Comment by bugwelle** [comment]
Reproduced. Relevant crash log:

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   QtNetwork                     	       0x1090eb1a8 QNetworkReply::isFinished() const + 4 (qnetworkreply.cpp:590) [inlined]
1   QtNetwork                     	       0x1090eb1a8 QNetworkReply::isRunning() const + 8 (qnetworkreply.cpp:603)
2   MediaElch                     	       0x1079b0cc0 ImageDialog::cancelDownloads() + 96 (ImageDialog.cpp:498)
3   MediaElch                     	       0x1079b0c49 ImageDialog::accept() + 25 (ImageDialog.cpp:170)
```

Seems c25691b7321cd936d4e045e0fea133a87321ff1f was not enough.

Thanks for reporting!

**Comment by bugwelle** [comment]
Could you test #1476 ? :-)

For some reason, I couldn't reproduce this bug with address sanitizer enabled.

**Comment by warchild13** [comment]
That fixed it!
Thanks. For me MediaElch is used daily indispensable!

**Comment by bugwelle** [comment]
> That fixed it!

Great! Thanks for letting me know! Thank you very much for reporting this bug!

> Thanks. For me MediaElch is used daily indispensable!

That is great to hear! Please let me know if you find any other crash/bug. If I've got time, I will try to fix it ASAP. :-)
