### ISSUE TITLE
Feature: MPAA Rating / Certification Format Setting in Movie Scraper Settings

### ISSUE THREAD

**Issue by ksipple** [Komet/MediaElch#1482]
Some skins require the MPAA rating in a different format, please add a function to select what format to include in the .nfo file. Either prefixed with Rated or not. Every scraper returns it without rated in front.

I'm looking for "Rated" in front of these ratings:
Rated R
Rated PG-13
Rated PG
Rated G
Rated NC-17
Rated NR

I tried changing it in advancedsettings.xml, but this function was removed from Kodi a few versions ago:

```xml
  <certifications>
      <map from="R" to= "Rated R" />
      <map from="PG-13" to="Rated PG-13" />
      <map from="PG" to="Rated PG" />
      <map from="G" to="Rated G" />
      <map from="NC-17" to="Rated NC-17" />
      <map from="NR" to="Rated NR" />
  </certifications>
```

**Comment by bugwelle** [comment]
Hi,

MediaElch supports the same XML format for mapping certifications. Did you try it? :-)

See https://github.com/Komet/MediaElch/blob/master/docs/advancedsettings.xml#L124-L127

It could be that there are places missing this mapping, in which case it's a bug.

Regards,
Andre

**Comment by ksipple** [comment]
That worked, thank you.
