### ISSUE TITLE
Ubuntu: Enable builds for 22.04 and 22.10 in the launchpad repository

### ISSUE THREAD

**Issue by heldchen** [Komet/MediaElch#1483]
**Is your feature request related to a problem? Please describe.**

currently the lastest build in the launchpad repository (https://launchpad.net/~mediaelch/+archive/ubuntu/mediaelch-stable) is only availabe for Impish and older. 

**Describe the solution you'd like**

Please add support for jammy (22.04) and kinetic (22.10) in the repository. the .deb files are already fully compatible it seems.

**Describe alternatives you've considered**

the workaround currently is to reconfigure the apt ppa source to use impish when the host system is running 22.04 or 22.10

**Comment by heldchen** [comment]
thanks @bugwelle appreciated! 

unfortunately I have no experience with packaging at all. but I see some project using github actions to do the heavy lifting, f.e. something like https://github.com/yuezk/publish-ppa-package (https://github.com/marketplace/actions/publish-ppa-package) could be usable for Mediaelch?

**Comment by bugwelle** [comment]
A new version of MediaElch 2.8.18 is now being build on launchpad.net :-)

It should be available in about half an hour, assuming that the build succeeds.

**Comment by heldchen** [comment]
thanks alot, works perfectly in Ubuntu 22.10 now :)
