### ISSUE TITLE
Is it possibel to change the shown digits of the TMDB rating permanently?

### ISSUE THREAD

**Issue by TotoCon** [Komet/MediaElch#1484]
Just as the title says.
For example change from 7,345 to 7,3.
I know that you can edit that value within the selected movie, but i would love to have it just two digits permenently.

**Comment by bugwelle** [comment]
Hi,

that's not possible. We take the rating TMDb provides and don't modify it.

Kind regards,
Andre

**Comment by TotoCon** [comment]
Thanks you for that quick reply and this awesome tool.

**Comment by techie2000** [comment]
Shouldn't this issue be closed, along the lines of 'no action required', 'works as designed/intended', 'will not implement' ?

**Comment by bugwelle** [comment]
Yes. At the time of writing, I was still not sure if some sort of post-processing would be feasible. But as it is right now, I won't get to implement such a feature.

Closing as "won't fix" :)
