### ISSUE TITLE
Overview and Actor information (including photo) doesn't get scraped per Episode on IMdb

### ISSUE THREAD

**Issue by ManilaByNight** [Komet/MediaElch#1486]
**Describe the bug**
When scraping a TV show on MediaElch, the Overview and Actor information (including photo) doesn't get scraped per Episode when using IMdb. The top level folder gets the overview and actor details but per episode there is no overview and actor details using IMdb.

**To Reproduce**
1. Load a TV series folder containing episodes.
2. Adjust settings to Custom settings. Set all possible TV show details and Episode details to IMdb TV and save settings.
3. Select the top-level TV series folder and scrape using Custom TV scraper.
4. When scraping is finished you will note that the main title contains complete details but if you browse down to every episode there is no details in Overview and Actors (actor name and photo).

**Expected behavior**
I was expecting complete details for the TV series for every season and its episodes.

**Screenshots**

**MediaElch Version:**
 - [ ] 2.8.18 stable - Coridian

**Operating System:**
 - [ ] Windows 10 64bit
![Episodes1](https://user-images.githubusercontent.com/19881795/199377307-1670c155-605e-4d17-ad89-fc735c41de92.JPG)
![Episodes2](https://user-images.githubusercontent.com/19881795/199377312-b421247f-6d23-4803-be7e-c7d1a34ddec5.JPG)
![Main1](https://user-images.githubusercontent.com/19881795/199377318-973ace7e-c289-41eb-a480-ba1e9add1e87.JPG)
![Main2](https://user-images.githubusercontent.com/19881795/199377319-4dcf6434-9768-4a18-b3ac-c93fee187b75.JPG)

**Comment by bugwelle** [comment]
Hi, 

thanks for reporting this issue. 
I will look into it soon. Due to limited time on my side, it may take a week or two, before I get back to you. After that, feel free to ping me again.

Regards,
Andre

**Comment by eugeneblookd** [comment]
confirmed the issue still persists on 2.10.6 Benzar, Overview per episode does not load from IMDB

**Comment by beaverdude** [comment]
confirmed the issue still persists on 2.10.6 Benzar, Overview per episode does not load from IMDB

**Comment by bugwelle** [comment]
I can confirm that actor images aren't loaded when scraping for more than one episode. (for all scrapers)
