### ISSUE TITLE
Cannont Scrape TVShow 1923 in TMDB

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#1527]
TV Show 
1923

Cannot be scraped using TMDB

it scrapes ok using IMDB but it does not scrape actors .... 

So 2 bugs in one :)

**Comment by nkatsidis** [comment]
Using 31.12.2022 Windows build

**Comment by bugwelle** [comment]
Thanks for reporting! Our TMDb scraper tests seem to work (The Simpsons, etc). I will look into this in the next few days
. :)

**Comment by bugwelle** [comment]
Issue is:

https://github.com/Komet/MediaElch/blob/eb5329835da12449bae7e38ebf60edb39d204ace/src/scrapers/tmdb/TmdbApi.cpp#L155-L176

We assume that 1923 is a TMDb id...
