### ISSUE TITLE
PPA: Fails on Ubuntu 22.04 (libssl3)

### ISSUE THREAD

**Issue by larsskj** [Komet/MediaElch#1537]
I'm trying to make MediaElch run on a fresh install of Ubuntu 22.04.1 LTS.

This fails due to SSL errors: Ubuntu nowadays only supports libssl3 for security reasons, but apparently this makes MediaElch (and many others) applications fail as it only supports libssl 1.

Please add support for libssl3.

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this issue. We use Qt's functionality for network access. I don't think there is much I can do to change it. Building MediaElch with Qt 6 may work.

How did you install MediaElch (via PPA or AppImage)?

Regards,
Andre

**Comment by larsskj** [comment]
Hi Andre,

I installed it via PPA in attempt to avoid problems. :-)

**Comment by bugwelle** [comment]
Thanks. :)

Seems that Qt only supports OpenSSL 3 with version 6.2 or later:

> As some of you might know, Qt6 supports [OpenSSL 3](https://wiki.openssl.org/index.php/OpenSSL_3.0) since Qt 6.2.0.

- https://www.qt.io/blog/moving-to-openssl-3-in-binary-builds-starting-from-qt-6.5-beta-2

I'm preparing Qt6 builds of MediaElch for Windows and macOS already. I'll see if I can adapt packaging for our PPA. :)

**Comment by larsskj** [comment]
I've just tried the AppImage and that actually works.

It's probably baked with OpenSSL 1 I'd assume?

**Comment by bugwelle** [comment]
> It's probably baked with OpenSSL 1 I'd assume?

Yes. The AppImage uses an old version of Qt5 that still runs ob Ubuntu 16.04. It's all bundled in the AppImage. :)

**Comment by bugwelle** [comment]
Since Ubuntu 18.04 is still supported by our PPA, we need some way to use Qt6 for Ubuntu 22.04 or later. I'm not a PPA expert, so any help is welcome. I think I would create two `debian/` directories instead of the one. One for Qt5 and the other for Qt6.

**Comment by bugwelle** [comment]
Interestingly enough, on my Ubuntu 22.04 system, MediaElch works as expected:

![Screenshot_20230524_201334](https://github.com/Komet/MediaElch/assets/1667306/1ce3769a-dcff-4206-a4d6-4b0be42bf6bc)
![Screenshot_20230524_201359](https://github.com/Komet/MediaElch/assets/1667306/c26a4908-5b67-447d-9da2-3714aeea0b40)

**Comment by bugwelle** [comment]
I released v2.10.4 yesterday. On my Ubuntu 22.04 system, I can install it without any issues.

If the issue still persists, please let me know. I can't reproduce it, yet. :-/
