### ISSUE TITLE
User Interface Language

### ISSUE THREAD

**Issue by LordFader** [Komet/MediaElch#1538]
Hello and thank you so much for the great work.

I update for version 2.10 on WIN10 machine.

For some reason after update/installation the application read my Locale Settings and change the Language of the User Interface.
In Windows-10 I use EN_us for UI and PT_pt for Locale (date & time & Keyboard map). 
Media Elche after this update decide to use a non complete translation in PT_br (not nice since it's far different from PT_pt).

it will be nice if in Settings>Appearance... we could change the UI language.

![image](https://user-images.githubusercontent.com/4002168/217214248-efca4e9c-9334-42f3-b444-0b0493db9ad9.png)

Thank you.

**Comment by LordFader** [comment]
For a quick workaround... where I can found the settings file to change the UI language?

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this feature request. Moving settings from `advancedsettings.xml` to the UI is planned. The "appearance" tab will get a language dropdown. :-)

Out of curiosity: Could you paste the contents of MediaElch's "Developer Details"? See  https://mediaelch.github.io/mediaelch-doc/contributing/bug-reports.html#developer-information 

I'm interested in the default UI languages.

> Read the F** Manual...

Well, it's not intuitive. You're not to blame here :smile:

Regards,
Andre

**Comment by bugwelle** [comment]
Closing. Moving settings from `advancedsettings.xml` to the UI is on my radar. Will be implemented eventually.
