### ISSUE TITLE
Program ignores advancedsettings.xml entirely

### ISSUE THREAD

**Issue by LoserForever88** [Komet/MediaElch#1540]
**Describe the bug**
I downloaded the advancedsettings.xmls raw speciman from github here and placed it in the same folder of MediaElch.exe.  I made the following modifications:-

`<portableMode>true</portableMode>`
`<pattern applyTo="folders">^[.]ignore$</pattern>`

But nothing seems to work.  The cache folder is still generated in the user folder.  Folder name with .ignore is still not exluded from scanning upon reloading.  It seems to me that the program ignore the xml settings entirely as if doesn't exist.  I also tried deleting everything in the registry but the problem still persists.  

I really need to get the folder exclusion to work but as of now this doesn't seem possible without this xml settings.

Any help would be appreciated.  Thank you.

**MediaElch Version:**
 - 2.10.0 Benzar

**Operating System:**
 -  Windows 10

**Comment by ticao2** [comment]
Just to test if your **advancedsettings.xml** is working or not, try activating the creation of the **Log file**, and when you reopen MediaElch, see if the TEST file was created.

`	<log>
		<debug>true</debug>
		<file>./TEST.log</file>
	</log>`

**Comment by LoserForever88** [comment]
> Just to test if your **advancedsettings.xml** is working or not, try activating the creation of the **Log file**, and when you reopen MediaElch, see if the TEST file was created.
> 
> ` <log> <debug>true</debug> <file>./TEST.log</file> </log>`
> 
> ```
> <log>
> 	<debug>true</debug>
> 	<file>./TEST.log</file>
> </log>
> ```
> 
> I particularly prefer the file name to be the same as the MediaElch folder name. That's because I have several versions of MediaElch installed in Portable mode.
> 
> ```
> <log>
> 	<debug>true</debug>
> 	<file>./MediaElch_2.8.17_2022-07-20_00-07 NOTE.log</file>
> </log>
> ```

Thank you.  With your help it turns out that the advanced settings is working.  I guess it's normal to have a cache folder in the user path whether it's portable or not.  Regarding the exclusion pattern I will open up a new issue for clarity purpose.  I will mark this issue as solved accordingly.
