### ISSUE TITLE
Allow tmdbId variable for renaming files

### ISSUE THREAD

**Issue by Rygle** [Komet/MediaElch#1542]
**Is your feature request related to a problem? Please describe.**
Allow us of the tmdbId variable (or whatever version of capitalization you like, as long as it's documented) for renaming files like the imdbId variable currently works. This would seem to be in line with goals to move from proprietary or paywalled data sources.

**Describe the solution you'd like**
Can currently rename a file using `<title> (<year>) imdbId-<imdbId>` and it will come out for example, "101 Dalmatians (1996) imdbId-tt0115433"
Would like to have
`<title> (<year>) tmdbId-<tmdbId>` come out for example, "101 Dalmatians (1996) tmdbId-11674" or similar

**Describe alternatives you've considered**
nfo files work. Just thought as some people use this functionality already, e.g. https://www.youtube.com/watch?v=4VkY1vTpCJY (14:43), why not expand it slightly? I know that video is jellyfin specific, but JF is following Kodi nfo and file naming specs afaik, and I know JF can use this naming - https://jellyfin.org/docs/general/server/media/movies/

Thanks for considering this!

**Comment by bugwelle** [comment]
Thanks for this feature request! I've implemented it in #1543. A new Nightly version should be available in about 30min.

**Comment by Rygle** [comment]
Wow! Glad that was easy!

Thanks!

----------------------------------------

11 Feb 2023 9:04:59 pm Andre Meyering ***@***.***>:

**Comment by bugwelle** [comment]
In this case it was :smile:

The "renamer" actually needs some work, because some other replacements aren't that easy. But simple strings are. :)
