### ISSUE TITLE
In dark mode, items that have a label set are hard to see

### ISSUE THREAD

**Issue by ironhussar** [Komet/MediaElch#1545]
**Describe the bug**
When using the Dark mode, any items that have a label set are almost impossible to read because the text still renders as white. 

**To Reproduce**
1. Set Dark mode
2. Assign a label to a movie (eg green)
3. The label renders in bright green with white text. Happens to all colours

**Expected behavior**
In dark mode, text in labels should render dark (or adaptive, based on label colour).

**Screenshots**
![mediaelch](https://user-images.githubusercontent.com/12449972/218578524-56116cd4-7791-4297-818e-a292d5ab521f.jpg)

**MediaElch Version:**
 - [ ] 2.10.1-dev (nightly)
 - [x] 2.10.0 stable

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Comment by bugwelle** [comment]
Oh! Thank you very much for reporting. I totally forgot about the label contrast, thanks! Will be adapted.
