### ISSUE TITLE
Exclusion filter does not exclude subfolder

### ISSUE THREAD

**Issue by LoserForever88** [Komet/MediaElch#1547]
**Describe the bug**
Folder excluding filter in advancedsettings.xml doen't exclude subsfolders.

**To Reproduce**
1. Define a folder excluding pattern in advancedsettings.xml.
2. Eg. `<pattern applyTo="folders">[.]ignore$</pattern>`
3. Start MediaElch.
4. Perform rescan.

**Expected behavior**

Expectation: The whole Movie's path's directory, including its subfolders, is filtered and excluded.
Actual: Only direct parent (just files in upper level) directory is filtered.

For example, when the pattern is <pattern applyTo="folders">[.]ignore$</pattern>,

"/user/My Videos/.ignore/test.vob" is excluded, but,
"/user/My Videos/.ignore/test3/video1/test-003.vob" is not excluded.

**MediaElch Version:**
 -  2.10.0

**Operating System:**
Windows 10

**Additional context**

I found MediaElch filter exclusion is somewhat different from Emby.  In emby, if there is a folder renamed to exact match of ".ignore" ,  the entire folder and its subfolders will be excluded from scanning.   Emby even allows file name detection, which means that if you rename any file (note: not folder) to ".ignore" in say "Folder A", anything inside "Folder A" (including things in subfolders) will be excluded from scanning. Is this achievable in MediaElch?  Even if it's not exactly like that, I suppose one would expect that subfolders exclusion should work properly?

**Comment by bugwelle** [comment]
If I remember correctly, we either run the filter on each full directory path (which only matches the first due to the `$`) or don't correctly respect child-directories. Either way, it's a bug. Thanks. :)

**Comment by Neinei0k** [comment]
I tracked this problem to [MovieDiskLoader::loadMovieContents()](https://github.com/Komet/MediaElch/blob/f12f823075685d9e247ae9ae16a17a86783efa60/src/file_search/movie/MovieDirectorySearcher.cpp#L132). It uses `QDirIterator` to generate a list of files and directories, each of them is checked against exclusion filters and a bunch of other hardcoded filters. But all of them only check the file `fileName` or its direct parent `dirName`. Parents of parent directory are not checked.

**Comment by bugwelle** [comment]
@Neinei0k Correct. What I wanted to do is following:

- replace the QDirIterator with custom traversal
- don't visit subdirectories if a folder is excluded (that is not possible with QDirIterator if I got it right)

The second point is the reason why it doesn't work now: I don't want to check all parent directories for each file we visit. That would waste resources.

I currently don't find the time to do so. Pull requests are welcome, though and I'm happy to test code and provide guidance if necessary.

Regards,
Andre

**Comment by bugwelle** [comment]
Fixed in  #1653 by @Neinei0k . Thank you very much!
