### ISSUE TITLE
Selected item on TV Show non-visible

### ISSUE THREAD

**Issue by regorxxx** [Komet/MediaElch#1569]
**Describe the bug**
When an item is selected,  colors are not set properly, thus becoming non-visible (either the item or the selection).

**To Reproduce**
1. Go to TV Shows
2. Click on any item (Show, season or episode).

**Expected behavior**
Follow the same behavior than other items at other tabs.

**Screenshots**
Light UI, item becomes invisible
![image](https://user-images.githubusercontent.com/83307074/235737546-ce6124d4-cf82-429e-b986-52bd37032e01.png)

Dark UI, no selection is shown
![image](https://user-images.githubusercontent.com/83307074/235737757-bdf4cee4-36c8-4725-af0c-3f8fb30d563a.png)

**MediaElch Version:**
 - [x] 2.10.0 stable

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**
Windows 7

**Comment by bugwelle** [comment]
Thanks. Noticed this locally as well, but forgot about it. This happens because we use the system's color there, even if the background color does not match.

**Comment by bugwelle** [comment]
Oh, that's not it. The background effect is missing! I'll look into it.

**Comment by regorxxx** [comment]
Yep, it's both. 

And depending on the UI mode it makes either impossible to know where is the current selection or the text of the selected item. Glad you also reproduced it. Thanks ;)

**Comment by bugwelle** [comment]
![Screenshot 2023-05-04 at 17 33 51](https://user-images.githubusercontent.com/1667306/236256923-89bf7940-6348-47ed-8b9e-1feeb5ac4572.png)

This is how it looks like for macOS and is what I expected. For some reason, it doesn't work (anymore?) on Linux and Windows.

**Comment by bugwelle** [comment]
Thanks for reporting. I figured out how to fix it. #1570 fixes your issue. A new snapshot version will be available in the next ~1h.

**Comment by regorxxx** [comment]
Selection works fine now in both modes. Thanks :)
