### ISSUE TITLE
All images vanish on saving

### ISSUE THREAD

**Issue by warchild13** [Komet/MediaElch#1572]
MediaElch 2.10.1-dev - Benzar

Compiled with Qt version 5.15.2 (64 Release, GCC 10.2.1 20210110)
Using Qt version 5.15.2
System: Debian GNU/Linux 11 (bullseye) (x86_64-little_endian-lp64)

Application dir: /usr/bin
Settings file: /home/david/.config/kvibes/MediaElch.conf
Data dir: /home/david/.local/share/kvibes/MediaElch
Qt Translation Path: /usr/share/qt5/translations

MediaInfo Version: MediaInfoLib - v20.09

Default UI languages: en-US

Custom advancedsettings.xml: false

The image files are not removed and are still in the movie direcfory but are not visible or editable in MediaElch. Last time in worked properly was in 4-30-2023 build.

**Comment by Rygle** [comment]
Can confirm using Windows build Qt6_2.10.1-dev_2023-5-12_git-master-53a9bb6f. Artwork disappears from any item scanned then saved. Shows red icons for artwork, poster, fanart, etc. If I then run 2.8.12 it all shows up with green icons. If I then run 2.10.1 Dev it is all there with green icons, but a rescan turns everything red again.

**Comment by bugwelle** [comment]
Thanks for reporting this issue. I've been busy the last week so only now get to look into it.

I assume it could be due to ecdee9229dae60bbd5db5c1c7a48ccbf7ff056b4 (the time line matches).

I can confirm that images disappear as soon as I click "save". They are on disk, though. They also remain not visible when reloading all movies.

**Comment by bugwelle** [comment]
Thank you very much for reporting this bug! It went unnoticed because the first page of movies I had locally were un-scraped. This should not have happened and I will add this to the list of tests I finally need to write.

Expect new snapshot versions for Windows/Linux in the next 1h.

**Comment by warchild13** [comment]
Running qmake I get : WARNING: Failure to find: src/scrapers/movie/imdb/ImdbMovieScraper.h
after make it does not build with an error msg: g++: error: /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so: No such file or directory
make: *** [Makefile:2159: MediaElch] Error 1

Leaving nothing to install.

Appreciate your efforts and still using the app!

**Comment by bugwelle** [comment]
Argh... I forgot my CI no longer uses QMake (only CMake now). Thanks. I will add it to my CI system. It's been fixed on `master`. Though I wonder why it didn't fail for me. On my system, everything compiles (with clang). No idea why, though...

**Comment by warchild13** [comment]
It failed again with my old installation, so I recloned the master and still got a failed build. Odd error:

g++: error: /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so: No such file or directory
make: *** [Makefile:2158: MediaElch] Error 1

I've little idea what this means, so no help from me! I'm willing to keep trying. Love the app.

**Comment by bugwelle** [comment]
Hi,

thanks. That looks as if the Open GL plugin for Qt isn't installed. Which linux distribution do you use? Then I'll look which packages are required. :)

For Ubuntu 22.04, following packages are required:

```sh
apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
        g++ gcc \
        build-essential \
        git \
        cmake \
        wget \
        libmediainfo-dev \
        ffmpeg \
        qtbase5-dev \
        qtbase5-dev-tools \
        qt5-qmake \
        qttools5-dev \
        qttools5-dev-tools \
        qtmultimedia5-dev \
        qtdeclarative5-dev \
        libqt5opengl5 \
        libqt5opengl5-dev \
        libqt5svg5 \
        libqt5svg5-dev

```

**Comment by warchild13** [comment]
Hi,
I'm on Debian 11 Bullseye.
Installed your reqs and it built easily and runs perfectly once again. 
Thanks!

**Comment by bugwelle** [comment]
Great to hear that! :)
