### ISSUE TITLE
Add directory hangs 

### ISSUE THREAD

**Issue by bisento** [Komet/MediaElch#1577]
**Describe the bug**

When trying to add a new directory to the global media locations, MediaElch does not add this directory and the settings button is inactive afterwards - clicking does not open settings anymore.

**To Reproduce**
1. open MediaElch
2. Click Settings Button in GUI
3. First Tab "Global": click "Add" Button to add media directory
4. pick media directory from computer, finish with "open"
5. Setting Window disappears, Settigns button is unresponsive, 
6. quitting MediaElch and restarting reveals no added directory

**Expected behavior**
after Step 4. I expect a return to the settings window with the newly selected media directory added to the list and the possibility of changing the media type from "movie" to tv show" or smth like that

**Screenshots**

**MediaElch Version:**

 - [ ] 2.10.0 stable

**Operating System:**
 - [X] macOS
 
**Additional context**

**Comment by bugwelle** [comment]
Are there by any chance additional windows that are accidentally moved to another screen or behind another window?
Which macOS version do you use? :)

**Comment by titanic-jb** [comment]
Same here.

Here are the requested infos concerning OS version and ...

> MediaElch 2.10.0 - Benzar
> 
> Compiled with Qt version 5.15.2 (64 Release, Clang 14.0 (Apple))
> Using Qt version 5.15.2
> System: macOS 13.3 (x86_64-little_endian-lp64)
> 
> Application dir: /Applications/MediaElch.app/Contents/MacOS
> Settings file: /Users/tmjb/Library/Preferences/com.kvibes.MediaElch.plist
> Data dir: /Users/tmjb/Library/Application Support/kvibes/MediaElch
> Qt Translation Path: /Applications/MediaElch.app/Contents/translations
> 
> MediaInfo Version: MediaInfoLib - v22.09
> 
> Default UI languages: de-DE
> 
> Custom advancedsettings.xml: false

Bye

  Jan

**Comment by titanic-jb** [comment]
> Are there by any chance additional windows that are accidentally moved to another screen or behind another window?
> Which macOS version do you use? :)

Nope.

**Comment by titanic-jb** [comment]
And even with the latest dev version, same effect:

> MediaElch 2.10.1-dev - Benzar
> 
> Compiled with Qt version 6.5.0 (64 Release, Clang 14.0 (Apple))
> Using Qt version 6.5.0
> System: macOS Ventura (13.3) (x86_64-little_endian-lp64)
> 
> Application dir: /Applications/MediaElch.app/Contents/MacOS
> Settings file: /Users/tmjb/Library/Preferences/com.kvibes.MediaElch.plist
> Data dir: /Users/tmjb/Library/Application Support/kvibes/MediaElch
> Qt Translation Path: /Applications/MediaElch.app/Contents/translations
> 
> MediaInfo Version: MediaInfoLib - v22.12
> 
> Default UI languages: de-DE, de-Latn-DE, de
> 
> Custom advancedsettings.xml: false

**Comment by bugwelle** [comment]
That's,... strange. I used MediaElch myself on the latest macOS version with pretty much the same settings. I'll try to tomorrow again.

**Comment by titanic-jb** [comment]
Hi,

> Am 13.06.2023 um 19:50 schrieb Andre Meyering ***@***.***>:
> 
> 
> That's,... strange. I used MediaElch myself on the latest macOS version with pretty much the same settings. I'll try to tomorrow again.

Maybe, it’s because, I’ve got a brand new installation.  No prior config files on my hard drive?

Bye

  Jan

**Comment by titanic-jb** [comment]
Good morning,

> When the window disappears, could you try to show all Windows of MediaElch?

I am awfully sorry.

I tried the menu from the menu bar, where it was disabled:




But your screenshot was made, using the context menu on the icon in the dock.  Never had used that menu.

Good news: the windows popped up and everything is fine now.

So my kind of fault.  Again, sorry, to bother you.

Thank you for helping me!

Bye

   Jan

**Comment by bugwelle** [comment]
It's not your fault. The Window shouldn't disappear. I don't know what changed: Whether it was a Qt version update or a macOS version update...

I will try to force the settings window to be on-top.

**Comment by titanic-jb** [comment]
Good morning Andre,


> I will try to force the settings window to be on-top.

Thank you very much.

Bye

	Jan

**Comment by bugwelle** [comment]
I've adapted MediaElch to raise the settings Window on-top after adding a directory. Even though ugly (it falshes shortly), it works now.
