### ISSUE TITLE
Images Aren't Showing in MediaElch After Scraping and Saving a Group of Movies, But Are Saved to Disk

### ISSUE THREAD

**Issue by tfjield** [Komet/MediaElch#1591]
**Describe the bug**
After scraping and saving a bunch of movies that originally didn't have posters or fanart, the images are saved to disk but the movie list in MediaElch doesn't show the icons to indicate the posters or fanart are present.  Further, when looking at a particular movie, the images aren't present in MediaElch, even though it did save them to disk.

**To Reproduce**
1.  Turn on the posters and fanart indicators in the list.
2.  Select several movies in the list that don't have posters or fanart (but there is artwork available to the scraper).
3.  Scrape and save the movies.
4.  The icons don't update.  Go into the movie and see that they are still not there.
5.  Scrape the individual movie again using the same scraper, and now the images are present.  (But note, they were already saved to disk before re-scraping.)

**Expected behavior**
After scraping and saving a group of movies, the artwork in MediaElch should be updated.

**MediaElch Version:**
MediaElch_win_10_or_later_Qt6_2.10.0_2023-02-05_git-960303af

**Operating System:**
Windows 10

**Comment by bugwelle** [comment]
Thanks for reporting. Reproduced the issue. Images appear for a split second and disappear then again. Saving it again or reloading it works.

**Comment by tfjield** [comment]
Thank you for confirming!
