### ISSUE TITLE
AdultDVDEmpire Scraper missing title and artists

### ISSUE THREAD

**Issue by waywit** [Komet/MediaElch#1592]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] TMDb
 - [ ] TmdbConcert
 - [ ] TvTunes
 - [ ] AEBN
 - [X] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
Title is not added/corrected (and also deleted) to the Movie automatically, Title is always empty. But Titles are shown in the list to select from. Manually adding the title result in stored title in nfo.
No artists are loaded at all and not stored in .nfo.

**MediaElch Version:**
 - [ ] 2.10.1-dev (nightly)
 - [X] 2.10.0 stable
 - [X] compiled version from source code

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [X] Linux (distribution: Ubuntu 22.04)

**Additional context:**
Using the stable release, the filename/directoryname is left as titel (before it was set to the title delivered by scraper), in case of the source compiled version it will be blanked out and is empty.

**Comment by bugwelle** [comment]
Thanks for reporting! Will be fixed by #1593
