### ISSUE TITLE
MediaElch don't scrapping

### ISSUE THREAD

**Issue by Santicoma** [Komet/MediaElch#1597]
**Scrapers that don't work:**

-[]Universal Music Scraper

**Details which are wrong / not loaded:**
Add a list of information that is not loaded correctly.
in the window of the scrapping do not appear anyone artist 

**MediaElch Version:**

 - [ ] 2.10.2 stable

**Operating System:**
 - [ ] Windows

**Additional context:**
I already was having problems with the details of discography (don Loaded), and today knew about latest version. I installed with chocolatey an instance of MediaElch with console (admin) without uninstalling the previous one, but it only upgrade MediaElch to 2.10.0 version. Then I deleted the previous one manually and uninstalling the chocolatey version by console, all to upgrade with the newest version of Github. I Copy the folder in programfiles folder, and it
![Bartok-don't-appears](https://github.com/Komet/MediaElch/assets/28769953/b707c33d-0a81-4968-a142-5b665957d942)
 appears with the problem.

**Comment by Santicoma** [comment]
I send you gays screenshots
![Bartok-don't-appears](https://github.com/Komet/MediaElch/assets/28769953/88a6bb05-ce1d-46d4-bc97-faa2175100d0)
![imageformats](https://github.com/Komet/MediaElch/assets/28769953/72d4315e-5ca5-4adb-adf7-ce23bf19746e)
![mediaelch1](https://github.com/Komet/MediaElch/assets/28769953/0745b574-289b-4cbd-807b-11135d9f0559)
![mediaelch2](https://github.com/Komet/MediaElch/assets/28769953/15b6dd98-a7f6-4af3-a72b-a9e2d3bc8836)
![plattforms](https://github.com/Komet/MediaElch/assets/28769953/2b9ee81c-18bd-48e7-b45b-cf96badcbc22)
![primera](https://github.com/Komet/MediaElch/assets/28769953/a7608c0b-6c1c-448b-9e72-f8b0429df5e7)
![sqldrivers](https://github.com/Komet/MediaElch/assets/28769953/7c2a308b-fbd8-4675-93ef-a53b370f13fb)
![styles](https://github.com/Komet/MediaElch/assets/28769953/b788c593-2a04-43c5-b737-d413971543a8)
![tls](https://github.com/Komet/MediaElch/assets/28769953/8025ad70-4e22-47de-bc23-4ede363abb82)
![vendor](https://github.com/Komet/MediaElch/assets/28769953/2246a5b4-1d83-4c2f-b35d-7d47fb598236)
 in case you need i6

**Comment by bugwelle** [comment]
Thanks for reporting! I'll have a look at it on the weekend. :)

**Comment by Santicoma** [comment]
Thanks for your interest.
In the previous version I had problems with discography section two or three days before I updated to latest version. I have an archive with developer section in About information.
[info.about.developer.txt](https://github.com/Komet/MediaElch/files/11971357/info.about.developer.txt)
I hope it will help you to help me.

**Comment by bugwelle** [comment]
I can reproduce the issue. I'm working on a fix.

**Comment by bugwelle** [comment]
Fixed by #1603. It appears MusicBrainz changed something and they could no longer handle a HTTP header that we were sending for simple GET requests.
