### ISSUE TITLE
custom movie scraper / fanart.tv: Logo,… won't load automatically

### ISSUE THREAD

**Issue by Diskutant** [Komet/MediaElch#1598]
**Scrapers that don't work:**

 - [x] Fanart.tv

**Details which are wrong / not loaded:**
Logo
Clear Art
CD Art

**MediaElch Version:**
 - [x] 2.10.2 stable

**Operating System:**
 - [x] macOS

**Additional context:**
When scraping a new movie, the Logo, Clear Art and CD Art don't load.
I can manually click on each of those placeholders and I get the correct list to choose one. 

My settings:

<img width="888" alt="Bildschirmfoto 2023-07-08 um 12 00 57" src="https://github.com/Komet/MediaElch/assets/898220/8b8fd24d-2377-405b-ba90-1566d42026ff">
<img width="899" alt="Bildschirmfoto 2023-07-08 um 12 01 40" src="https://github.com/Komet/MediaElch/assets/898220/20824e5d-35e4-461d-a9c6-b35930fa3cd3">

**Comment by bugwelle** [comment]
Good point. Thanks for reporting. I will look into this.

**Comment by bugwelle** [comment]
Will be fixed by #1604. A new snapshot version for macOS will be available in the next ~ 1h.
