### ISSUE TITLE
Use Plot if short description isn't available doesn't work

### ISSUE THREAD

**Issue by Diskutant** [Komet/MediaElch#1599]
**Describe the bug**
The option "Use Plot, if short description isn't available" is activated, yet the short description is empty while Plot get's filled.

**To Reproduce**
1. Go to Settings
2. Click on Movies
3. Activate "Use Plot, if short description isn't available" 
4. Scrape a movie 
5. short description stays empty but Plot is filled

**Expected behavior**
short description should contain the same text as Plot, or a different text if available, but should not stay empty.

**Screenshots**

![SCR-20230708-gw3](https://github.com/Komet/MediaElch/assets/898220/5d7cb690-73a3-4df6-a625-6a9f716b75bd)
<img width="934" alt="Bildschirmfoto 2023-07-08 um 12 12 45" src="https://github.com/Komet/MediaElch/assets/898220/6dc7affa-59c2-4020-8d20-f2e9baa18cd2">

<img width="1305" alt="Bildschirmfoto 2023-07-08 um 12 10 52" src="https://github.com/Komet/MediaElch/assets/898220/405add79-faf2-4ae1-92f8-c0519dc36bf5">

**MediaElch Version:**
 - [x] 2.10.2 stable

**Operating System:**
 - [x] macOS

**Additional context**
This worked as expected in 2.10.0

**Comment by bugwelle** [comment]
Thanks for reporting. Fixed by https://github.com/Komet/MediaElch/pull/1602
