### ISSUE TITLE
Original Title doesn't load

### ISSUE THREAD

**Issue by Diskutant** [Komet/MediaElch#1601]
**Scrapers that don't work:**
 - [x] IMDb
 - [x] TMDb

**Details which are wrong / not loaded:**
Original Title

**MediaElch Version:**
 - [x] 2.10.2 stable

**Operating System:**
 - [x] macOS

**Additional context:**
When Scraping a Movie, the original Title won't load even though it is needed to find the result. 
It doesn't matter if Title is set to IMDb or TMDB, the result is the same.

Also the option "Don't save orginal movie name, if it's the same as the main name" has no effect on this.

<img width="893" alt="Bildschirmfoto 2023-07-08 um 12 55 09" src="https://github.com/Komet/MediaElch/assets/898220/b069246a-1276-451a-aefb-c829cbd4ce92">

<img width="887" alt="Bildschirmfoto 2023-07-08 um 12 55 35" src="https://github.com/Komet/MediaElch/assets/898220/daf27b41-cb15-4e18-97b5-1cd2a4d891b0">

Second search (see bug #1600):
<img width="886" alt="Bildschirmfoto 2023-07-08 um 12 56 03" src="https://github.com/Komet/MediaElch/assets/898220/17e5a6e9-4371-4065-a276-40ceba1f2889">

<img width="1303" alt="Bildschirmfoto 2023-07-08 um 12 56 47" src="https://github.com/Komet/MediaElch/assets/898220/8ebf8da7-4828-4570-85a8-34597268c501">

**Comment by HansUrst** [comment]
same here.

MediaElch Version: 2.10.2 Benzar

Operating System: LinuxMint 20.3 MATE 64bit

**Comment by bugwelle** [comment]
Thanks for reporting. I found the issue and will come back to you when it's fixed.
Our tests check the scrapers directly, where the original title was scraped. But the integration of the movie scraper into MediaElch was broken.

**Comment by bugwelle** [comment]
Thanks again. Fixed by #1602. I added tests to ensure that such a regression won't appear again (hopefully).

**Comment by HansUrst** [comment]
thanks a lot.

**Comment by bugwelle** [comment]
A new snapshot version will be available in the next ~1h.

**Comment by bugwelle** [comment]
I will wait a few days. If there aren't any more bugs, I will release a new version soon. Or maybe tomorrow if I find the time. Then it will be available in our PPA and elsewhere as well.
