### ISSUE TITLE
Renamer: <director> placeholder does not work when in Directory Naming

### ISSUE THREAD

**Issue by berg-stein** [Komet/MediaElch#1611]
**Describe the bug**
The \<director\> placeholder is being replaced by just *director* when placed in the *Directory Naming* field.

**To Reproduce**
1. Go to 'Renamer'
2. Click on 'Directory Naming' field
3. Type '\<director\>'
4. Click on 'Dry Run'
5. See the Result in the **move** row

**Expected behavior**
The \<director\> placholder should be replace by the director of the movie, like it happens when it is being placed in the File Naming field.

**Screenshots**
![Screenshot 2023-07-23 094026](https://github.com/Komet/MediaElch/assets/61465053/796569f7-383e-4f9e-9ac6-55322ec41304)
ribution: _._)
![Screenshot 2023-07-23 094135](https://github.com/Komet/MediaElch/assets/61465053/35f9c61e-f6bb-44d0-8db2-471f41b2a3ce)

**MediaElch Version:**
 - [x] 2.10.3-dev (nightly)
 - [x] 2.10.2 stable

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Comment by bugwelle** [comment]
Thanks for reporting. This was forgotten when `<director>` was added in 8de9fde1ce69e464d701ecabb6a16f7fabcfec33 / #1021

**Comment by bugwelle** [comment]
Thanks for reporting! The next version will have this fixed. :)

**Comment by berg-stein** [comment]
Thanks for your great work. 🙏
