### ISSUE TITLE
TV Shows: Undo changes button doesn't work 

### ISSUE THREAD

**Issue by Diskutant** [Komet/MediaElch#1615]
**Describe the bug**
For TV Shows the Undo button doesn't seem to do anything.

**To Reproduce**
1. Go to TV Shows
2. Scrape a show 
3. Click the Undo button
4. Nothing happens

**Expected behavior**
Everything (for the selected show) should get reverted or reloaded from disc.

**Screenshots**
![SCR-20230723-k3f](https://github.com/Komet/MediaElch/assets/898220/18200005-702d-4cd7-98a5-a80e2e4facc0)

**MediaElch Version:**
 - [x] 2.10.3-dev (nightly)

**Operating System:**
 - [x] macOS

**Comment by bugwelle** [comment]
Thanks. I'll try to have a look at this next week.

Workaround: Close MediaElch and re-open or reload all TV shows.

**Comment by bugwelle** [comment]
Thanks for reporting. Fixed via #1624
