### ISSUE TITLE
Fanart.tv ignores language setting

### ISSUE THREAD

**Issue by Diskutant** [Komet/MediaElch#1619]
**Describe the bug**
Fanart.tv ignores the language setting and shows all available logos

**To Reproduce**
1. Go to a tv show or movie
2. Click on the logo
3. See logos in all languages

**Expected behavior**
It should only show logos for the currently set language, and maybe english as a fallback 

**Screenshots**
<img width="1182" alt="Bildschirmfoto 2023-07-27 um 17 37 56" src="https://github.com/Komet/MediaElch/assets/898220/1b96bd80-0ac0-4f16-92dd-5f6c40a8b865">

**MediaElch Version:**
 - [x] 2.10.3-dev (nightly)

**Operating System:**
 - [x] macOS

**Additional context**
This also happens when using the scraper to load all information for a show.

**Comment by bugwelle** [comment]
Thanks. I can't remember if this is a bug or feature. :smile:
In some cases (as in this), there aren't any images for the selected German.

I'll check if the images are sorted with the preferred language first.

Regards,
Andre

**Comment by Diskutant** [comment]
This indeed looks like intended, if there is an artwork in the selected language it will always put those in front. 
But if there isn't, the fallback isn't really predictable. 
I think either english or orignal language should be 1st level and 2nd level fallback.

**Comment by bugwelle** [comment]
The images are now sorted by language before being downloaded. That is, only if a language matches the preferred/selected one, is it prepended. I decided against sorting by English, though. Looking at the results, there are many with invalid language codes (e.g. `00`), which I don't want to move after the preferred language _and_ English.

See #1632 for screenshots.
