### ISSUE TITLE
In the graphics chooser, the graphics are shown below each other

### ISSUE THREAD

**Issue by Diskutant** [Komet/MediaElch#1620]
**Describe the bug**
In the graphics chooser the graphics are shown below each other even though there is enough space to show 2 or 3 in a row. They will be rearranged when resizing the panel.
Seems only Poster and Fanart are affected by this.
Also the chooser doesn't remember it's size.

**To Reproduce**
1. Go to a movie
2. Click on Poster
3. See graphics in only one column

**Expected behavior**
The graphics should be arranged like they do when resizing the panel.

**Screenshots**
<img width="1194" alt="Bildschirmfoto 2023-07-29 um 19 40 31" src="https://github.com/Komet/MediaElch/assets/898220/d8230b88-c83b-4ae2-9a5e-e9bd2ccb29a0">

**MediaElch Version:**
 - [x] 2.10.3-dev (nightly)

**Operating System:**
 - [x] macOS

**Comment by bugwelle** [comment]
Thanks for reporting. Seems it only happens on the first time opening the window. If I click "zoom out" and then "zoom in" again, it's correctly aligned.

**Comment by Diskutant** [comment]
For me it happens each time. But yes, doing something like change zoom level, or only resizing the height of the window it will be correctly aligned. So it might just need a realign when opening the window.

**Comment by bugwelle** [comment]
Yes, I meant that any resize-action fixes the issue.

https://github.com/Komet/MediaElch/pull/1623 will fix this issue. Thank you very much for reporting it.
The linked pull request also has a before and after image. :)
