### ISSUE TITLE
Movie Search: Auto-remove non-title parts such as H.264

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#1627]
**Is your feature request related to a problem? Please describe.**
Because MediaElch uses the movie's filename by default, searching for e.g. "The.Black.Demon.2023.1080p.WEB-DL.DDP5.1.H.264" does not work.

**Describe the solution you'd like**
Auto-remove some parts such as 1080p, H.264, etc.

**Describe alternatives you've considered**
User-define list of values to remove from the title.

**Additional context**
Requested on the Kodi forum.

**Comment by Diskutant** [comment]
just a fyi

There already is a list of values which are meant to be excluded.

![SCR-20230731-ust](https://github.com/Komet/MediaElch/assets/898220/ea9dcd09-5325-43ea-8d37-898181166882)

Also it seems Media Elch doesn't use the file name but the folder name, at least if separate folders is activated.
This might be why I never ran into this problem?

**Comment by bugwelle** [comment]
😂😅 Seems I don't know the software I'm developing anymore. Indeed. I will have to add a few default values, though.

**Comment by bugwelle** [comment]
Fixed via 58a75780c085289e08a6d02774466eee28290e71
