### ISSUE TITLE
Search panel popup is white on white when in darkmode

### ISSUE THREAD

**Issue by Diskutant** [Komet/MediaElch#1629]
**Describe the bug**
When using dark mode, the search panel shows white text on white background.

**To Reproduce**
1. Go to search field
2. Enter some text
3. See white panel
4. Press down arrow to actually see something and realize there is a neat feature behind that panel. :D

**Expected behavior**
Should be white text on dark background

**Screenshots**
<img width="481" alt="Bildschirmfoto 2023-07-31 um 21 39 14" src="https://github.com/Komet/MediaElch/assets/898220/6a02099d-159c-4822-b435-16b155b4aa0a">

<img width="381" alt="Bildschirmfoto 2023-07-31 um 21 41 35" src="https://github.com/Komet/MediaElch/assets/898220/320ffba7-14ad-4d10-a784-3ab9d6229979">

**MediaElch Version:**
 - [x] 2.10.4 stable

**Operating System:**
 - [x] macOS

**Comment by bugwelle** [comment]
Thanks. Wasn't noticed because my underlying system isn't in dark mode. This is how it looks for me:

![Screenshot_20230731_214611](https://github.com/Komet/MediaElch/assets/1667306/624b023f-60a2-4143-8568-2ae6ad490924)


Btw, I __very much appreciate_ that you open all these bug reports! :smile:

**Comment by bugwelle** [comment]
Note to self: We still have explicit colors in some C++ files:

```cpp
topItem->setBackground(QColor(255, 255, 255, 200));
```

=> remove them!

**Comment by Diskutant** [comment]
> Btw, I _very much appreciate that you open all these bug reports! 😄

Thanks, and I very much appreciate that you fix all these bugs so fast. :)

**Comment by bugwelle** [comment]
It should look like this (using KDE):

![Screenshot_20230731_215224](https://github.com/Komet/MediaElch/assets/1667306/cea8ce5c-2040-4b72-abd0-8554efccba80)


TODO:

- [ ] Add a proper name to `FilterWidget:m_list`
- [ ] style the item in the dark and light theme
     It needs to be styled explicitly, because otherwise the underlying system's theme is used, which may contradict the main window's theme (it's a long story why both are different...)

**Comment by bugwelle** [comment]
Fixed via https://github.com/Komet/MediaElch/pull/1630

See the PR for before/after images. Also fixed the music tree view.
