### ISSUE TITLE
IMDB only loads 5 tags

### ISSUE THREAD

**Issue by lion3162001** [Komet/MediaElch#1634]
MediaElch 2.10.4 will only load the 5 tags on the imdb page for movies with the load all tags box checked in settings.

**Comment by bugwelle** [comment]
Thanks for reporting. I'm aware of it currently failing, but didn't get to fix it, yet. (our tests fail)

**Comment by bugwelle** [comment]
Finally fixed via https://github.com/Komet/MediaElch/pull/1677
