### ISSUE TITLE
TMDB ID for episodes isn't shown in the UI

### ISSUE THREAD

**Issue by Metal-Snake** [Komet/MediaElch#1644]
**Describe the bug**
In the Episode view, the TMDB ID isn't shown. It is written into the nfo file by MediaElch. So this is only a UI bug (or missing feature?).

**To Reproduce**
1. Go to Series
2. Click on an episode
3. search for the TMDB ID

**Expected behavior**
Show the TMDB ID

**Screenshots**
<img width="1264" alt="grafik" src="https://github.com/Komet/MediaElch/assets/898220/774684f9-8135-4bf9-a2c9-6aab232fb431">

for comparison, in the TV series it is shown:
<img width="1285" alt="grafik" src="https://github.com/Komet/MediaElch/assets/898220/0154cc7d-a133-4f0d-9e80-18f1ba1493fa">

**MediaElch Version:**
 - [x] 2.10.5-dev (nightly)
 - [x] 2.10.4 stable

**Operating System:**
 - [x] macOS

**Additional context**
I checked 2.10.4 and 2.10.5 (2023-Sep-07)

**Comment by ticao2** [comment]
I believe the TMDb only assigns an ID to the Series.
Does not attribute to Season or Episode.
API Requests fetch using Series ID, Season Number, and Episode Number.
For example:
`https://api.themoviedb.org/3/tv/4614/season/19/episode/7?api_key=THE_KEY&language=en-US`

To be more precise, Episode has an ID but only for internal use of the Database system.

**Comment by bugwelle** [comment]
TMDb does have episode IDs (IIRC), but we didn't show them.

Since the ID is already stored in the NFO, we should be able to show them. Will be fixed soon. :)
