### ISSUE TITLE
Add links next to IDs for Series and Episodes

### ISSUE THREAD

**Issue by Metal-Snake** [Komet/MediaElch#1645]
**Describe the solution you'd like**
For movies, next to the IDs (IMDB/TMDB) there are buttons which will open the IMDB/TMDB website, this is missing for series and episodes.

**Describe alternatives you've considered**
These buttons in the movies view
<img width="640" alt="grafik" src="https://github.com/Komet/MediaElch/assets/898220/af177e5a-a297-4087-a982-9111904603ee">

should be added here in the series and episodes view
<img width="625" alt="grafik" src="https://github.com/Komet/MediaElch/assets/898220/0fe66903-6f6e-47ac-908c-f24b2e1ef4aa">

**Comment by bugwelle** [comment]
:smile: 

Laziness won when I implemented that feature. :smile:

**Comment by bugwelle** [comment]
Btw: I'm not aware of a TMDb URL for episodes based on their ID. Do you know one?

**Comment by Metal-Snake** [comment]
Seems like that doesn't exist. I wasn't aware of that: https://www.themoviedb.org/talk/552e997ac3a36804cd0013ab

So I guess it makes sense to save the season and episode number instead of their ids? 
The user could change the season and episode number fields, so the tmdb season and episode numbers need to be saved as the uniqueid. 🤔

**Comment by bugwelle** [comment]
Fixed by #1651

Note that TheTvDb does not have proper URLs with their IDs. At least I couldn't find any. For episodes, only IMDb and TVMaze have proper URLs with episode-IDs.

Kind regards,
Andre
