### ISSUE TITLE
Scraper "adultdvdempire" broken (no poster and no description)

### ISSUE THREAD

**Issue by waywit** [Komet/MediaElch#1650]
**Describe the bug**
Build with the latest source code on my ubuntu 22.04 system and tried to scrape movies with adultdvdempire, but the description and poster is missing. For example you can check "Wasteland Ultra" DVD or VOD Version has Poster and Description, but this does not get pulled. I think the website has changed with overlay poster and description.

**To Reproduce**
1. Go to scrape movie with adultdvdempire
2. Use movie with all supported info and artwork
3. See if everything is downloaded correctly

**Expected behavior**
All information and artwork is downloaded

**MediaElch Version:**
 - [X] 2.10.5-dev (build from sourcecode)
 - [ ] 2.10.4 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [X] Linux (ubuntu: 22.04)

**Comment by bugwelle** [comment]
Can confirm. Tests are failing.

**Comment by bugwelle** [comment]
Fixed via https://github.com/Komet/MediaElch/commit/4572a7b11cbb26c9ec8b8f202310740614e7028e

Thanks for reporting! :smile:
