### ISSUE TITLE
Adultdvdempire: Cover download does not work

### ISSUE THREAD

**Issue by SirCumAlot1988** [Komet/MediaElch#1661]
**Scrapers that don't work:**
AdultDvDEmpire

**Details which are wrong / not loaded:**
The download of movie covers does not work

Also, the Plot/Outline is not scraped.

**MediaElch Version:**
2.10.4 stable

**Operating System:**
Windows

**Comment by bugwelle** [comment]
Thanks!

May have been fixed by https://github.com/Komet/MediaElch/commit/4572a7b11cbb26c9ec8b8f202310740614e7028e

Could you try the latest nightly available on https://mediaelch-downloads.ameyering.de/snapshots/Windows_10_or_later/ ?

Regards,
Andre

**Comment by Klingen29** [comment]
Tested with 2.10.5 latest nightly, works like expected.

**Comment by bugwelle** [comment]
Thanks for confirming! @SirCumAlot1988 If you experience something different to what @Klingen29 said, please let me know.
