### ISSUE TITLE
when renaming a show the year is empty

### ISSUE THREAD

**Issue by Stunkymonkey** [Komet/MediaElch#1663]
**Describe the bug**
when renaming a show the year is empty.

**To Reproduce**
1. Go to 'Shows'
2. Click on 'Rename'
3. Wait for it to finish
4. See folder format `<name> ()`

**Expected behavior**
having `<name> (<year>)`

**MediaElch Version:**
 - [ ] 2.10.5-dev (nightly)
 - [x] 2.10.4 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: NixOS)

**Additional context**
Happened on multiple shows

**Comment by bugwelle** [comment]
It seems MediaElch didn't replace the folder's `year` with the TV show's year, but only did so for episodes. Thanks for reporting!

**Comment by bugwelle** [comment]
Couldn't reproduce this issue, yet. Do the TV shows, for which `MyTitle ()` is rendered, have a valid "firstAired" value?

Btw: Do you mean `<title>`? Because `<name>` does not exist for TV shows.

**Comment by Stunkymonkey** [comment]
sorry i did not use the variable-namings you see in the "Renamer"

I am having `<title> (<year>)` there. But the problem stays the same.

**Comment by Stunkymonkey** [comment]
And yes the "First Aired" looks good in the UI and is not empty/

**Comment by bugwelle** [comment]
Is the "First Aired" value the current date? I saw that we apparently show the current date if no "First Aired" value was set.

**Comment by Stunkymonkey** [comment]
oh yes you are right. It is the current date.

**Comment by bugwelle** [comment]
Argh... There is no way to store something like "empty" in a `QDateWidget`. It always has to be something, i.e. a date. I could show some old date instead. Something like 1970-01-01. The default appears to be 2000-01-01. Not great.

**Comment by bugwelle** [comment]
Because of Qt-internals, I also can't show the year `0000`...
I think the best is to show a "missing" marker.

**Comment by bugwelle** [comment]
Done via #1667

**Comment by Stunkymonkey** [comment]
thank you very much
