### ISSUE TITLE
TMDb: Scraping for a TV show and new/all Episodes doesn't scrape episode actors

### ISSUE THREAD

**Issue by mihawk90** [Komet/MediaElch#1676]
**Describe the bug**
When Scraping info for a TV show and using "Update TV Show and all Episodes" (also for "new"), the Scraper pulls in actors for the series, but not for the individual episodes. It does however pull writer and director.
To solve this one would have to scrape every episode individually, and that works fine (even though it takes forever).

**To Reproduce**
1. Get some files without NFOs
2. Scrape entire show, use "Update TV show and all Episodes"
3. Check Actors for individual episodes

**Expected behavior**
Actors for all episodes should be filled, i.e. the scraper should pull all information that is being selected.
Curently it fills actors for the show, and also writer and director for episodes, but episode actors are missing.

**Screenshots**
As an example:
https://www.themoviedb.org/tv/100088-the-last-of-us/season/1/episode/3/cast

After scraping show:
![image](https://github.com/Komet/MediaElch/assets/556162/793ef48f-8b1d-43cb-b85f-7a5704960836)

After scraping individual episode:
![image](https://github.com/Komet/MediaElch/assets/556162/cc7f3c20-53fa-4840-b7a7-d427f5d11c56)

**MediaElch Version:**
 - [ ] 2.10.5-dev (nightly)
 - [x] 2.10.4 (stable)

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: Fedora 38)

**Comment by bugwelle** [comment]
Can confirm. This could be a limitation of TMDb, I faintly remember something in that regard.

**Comment by bugwelle** [comment]
Ok, so turns out: When requesting a season (and all its episodes), we get a cast for the whole season + guest stars per episodes. On a quick glance, when I scrape a single episode, I get the same details. I'll add the season's actors to each episode as well.

**Comment by bugwelle** [comment]
Fixed via https://github.com/Komet/MediaElch/pull/1678

**Comment by mihawk90** [comment]
> On a quick glance, when I scrape a single episode, I get the same details. I'll add the season's actors to each episode as well.

if that's the case then the Guest Stars weren't written either though. In the example above only Pedro Pascal and Bella Ramsay are Season regulars, the rest are all Guest Stars :thinking:

**Comment by bugwelle** [comment]
> Thanks for looking into it
> 
> > On a quick glance, when I scrape a single episode, I get the same details. I'll add the season's actors to each episode as well.
> 
> if that's the case then the Guest Stars weren't written either though. In the example above only Pedro Pascal and Bella Ramsay are Season regulars, the rest are all Guest Stars 🤔

Yes, guest stars were also missing :)

**Comment by ticao2** [comment]
Just a guess.
I don't know if it will help.
In the TV API Request, two filters can be used.
**&credits** - Returns the credits from the last season.
**&aggregate_credits** - Returns credits for the entire series.
