### ISSUE TITLE
TV Shows: Support for multiple <studio> tags

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#1705]
### Discussed in https://github.com/Komet/MediaElch/discussions/1703

<div type='discussions-op-text'>

<sup>Originally posted by **rainerhillebrand** January 18, 2024</sup>
Under the assumption that my understanding of the definitions on the page https://kodi.wiki/view/NFO_files/TV_shows is correct I would assume that multiple <studio> tags are supported in nfo files for TV Shows.

MediaElch seems to support only a single <studio> tag so that multiple studios can only be given in a single string.

When filtering TV Shows on studios in Kodi (at least in Nexus 20.2) then you cannot select one of these multiple studios that are given in a string of multiple studios.
Example content of a <studio> tag: "ZDF, ORF, SRF1"
I want to filter all TV Shows from the studio "SRF1". However, if there is no other TV Show with the <studio> tag content "SRF1" then I cannot select the filter for "SRF1".

Wouldn't it make sense that MediaElch supports multiple <studio> tags for TV Shows nfo files as well?</div>

**Comment by rainerhillebrand** [comment]
Dear bugwelle,

Many thanks!

Best regards,

Rainer

**Comment by bugwelle** [comment]
I've implemented it in #1712. Note that there is no auto-completion like for other fields. For that, I don't have time (see #1710).

The next nightly will have this feature.

Also note:

> There is no automatic update: Existing `<studio>` tags with comma separate lists will remain that way. Only once you edit it in the UI (e.g. click in the studio field, add a character), will we store multiple `<studio>` tags. I want to avoid too many changes in user NFOs.
