### ISSUE TITLE
IMDB missing episode overview when scraped

### ISSUE THREAD

**Issue by kolbdog3333** [Komet/MediaElch#1724]
**Describe the bug**
Whenever you scrape a show using imdbtv the overview is missing. 

**To Reproduce**
1. Go to 'the show'
2. Click on 'scrape.'
3. Scroll down to 'Overview.'
4. The Overview is missing it is blank

**Expected behavior**
The full summary of the show should have shown up.

**Screenshots**

**MediaElch Version:**
 - [ ] 2.10.6 (stable)

**Operating System:**
 - [ ] Windows

**Comment by bugwelle** [comment]
Hi,

thanks for reporting. Could you please ensure that you've selected "Overview" in the scrape dialog? If it is selected, please give an example for which show it doesn't work. I'm not able to reproduce it locally (e.g. for "Family Guy"), yet.

Regards,
Andre

**Comment by kolbdog323** [comment]
It is for many shows i have tried Helluva Boss, Angry Bird Blues, Piggy Tales  excetra it seems it doesnt work if you just select imdbtv scraper by itself since it works if you use the Universal Scraper but not imdbtv scraper by itself. Since reason i use imdtv scraper by itself is some shows aren't on tmdb scraper or i have some shows as one episode.

Also this is the same user who made the report i had to create a new account. 

> Hi,
> 
> thanks for reporting. Could you please ensure that you've selected "Overview" in the scrape dialog? If it is selected, please give an example for which show it doesn't work. I'm not able to reproduce it locally (e.g. for "Family Guy"), yet.
> 
> Regards, Andre

**Comment by kolbdog323** [comment]
Also it only does it for episodes the tv show part works fine.

**Comment by kolbdog323** [comment]
Sorry i should have put episode not show when i posted the issue

**Comment by bugwelle** [comment]
> Sorry i should have put episode not show when i posted the issue

I should have looked at episodes. I can confirm the issue. :)

**Comment by kolbdog323** [comment]
Any luck on this progress to fix it?

**Comment by bugwelle** [comment]
Should be fixed by #1732.

Sorry for the delay. Please see https://github.com/Komet/MediaElch/issues/1710 for reasons. tl;dr: I don't have much time for MediaElch anymore. Feel free to ping me, if you have issues that are important. :)

**Comment by bugwelle** [comment]
Also, please let me know what else is missing. I didn't look into it too much. Only checked the IMDb overview tests.
