### ISSUE TITLE
IMDBTV Episdoe thumbnail wont scrape on Custom TV Scraper if no image

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1725]
**Scrapers that don't work:**

 - [ ] Custom TV Scraper/IMDBTV Episode Thumbnail

**Details which are wrong / not loaded:**
When you scrape a episode using the Custom Tv Scraper and have iIMDBtv selected for epiosde thumbnail the image wont scrape if there is no image to replace if there is one on TMDB as a subsitute. But if there is an image it will work. The imdbtv scraper will grabe the episode thumbnail but on custom if no image on tmdb it wont grab it.

**MediaElch Version:**
 - [ ] 2.10.6 (stable)

**Operating System:**
 - [ ] Windows

**Additional context:**

**Comment by kolbdog323** [comment]
An example is if episode 6 doesnt have a thumbnail for the episdoe on tmdb the custom scraper wont scrape an image from imdb for the same episdoe you have to use the imdbtv scraper first then custom scraper to keep the image. Its very annoying.

**Comment by bugwelle** [comment]
Thanks for reporting! I will have a look soon.

**Comment by kolbdog323** [comment]
Any luck on this as well. Also I will try the nightly build tomorrow to try out the missing overview and see if it's fixed.

**Comment by bugwelle** [comment]
Thank you very much for reporting this issue. I've found few other bugs (one crash) that I've now also fixed.

Your bug was a copy&paste error. I looked at the _TV show_ settings when loading episodes. The fix is trivial:

```diff
--- a/src/scrapers/tv_show/custom/CustomEpisodeScrapeJob.cpp
+++ b/src/scrapers/tv_show/custom/CustomEpisodeScrapeJob.cpp
@@ -46,7 +46,7 @@ void CustomEpisodeScrapeJob::onTmdbLoaded(EpisodeScrapeJob* job)
     copyDetailsToEpisode(episode(), job->episode(), job->config().details);
     job->deleteLater();
 
-    const QStringList scrapersToUse = m_customConfig.scraperForShowDetails.values();
+    const QStringList scrapersToUse = m_customConfig.scraperForEpisodeDetails.values();
     const bool loadImdb = episode().imdbId().isValid() && scrapersToUse.contains(ImdbTv::ID);
 
     m_loadCounter = 1;
```

It will be fixed shortly. Note that there are currently issues with our Nightly-build pipeline for Windows. It may take another day for a Nightly to appear.
