### ISSUE TITLE
Play button missing

### ISSUE THREAD

**Issue by schoenid** [Komet/MediaElch#1727]
**Is your feature request related to a problem? Please describe.**
I miss a play button, directly in the main window of any movie.
Like now, I have to search for the movie in the left hand movie list, select it with the right mouse button and select "Film abspielen" to play it. It's not straight away from the data or properties window.

**Describe the solution you'd like**
It would be much more comfortable, if a big (like the size of the title) would be in a place directly before or after the title.  

**Describe alternatives you've considered**
I've used TinyMediaManager until now, but I'm looking for a replacement.
There are play buttons on the main window and also in edit dialogs, so it's easy to suddenly start any movie, without to search for a location, where the movie can be started from.

**Additional context**

**Comment by bugwelle** [comment]
Indeed. Thanks for opening this feature request. :)

**Comment by bugwelle** [comment]
I've added a play button to the top right corner of the movie widget in  #1762 :)
