### ISSUE TITLE
TVDB Episode thumbnails not showing up.

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1740]
**Describe the bug**
When you click on an episode thumbnail it doesn't show any results from the TVDB website since that is the scraper it uses when you click on an episode thumbnail. But there are episode thumbnails on the website. I think the the episode thumbnails for TVDB is broken.

**Comment by bugwelle** [comment]
Thanks for reporting this bug.

Did you by any chance scrape the TV series or episode already?

**Comment by kolbdog323** [comment]
> Thanks for reporting this bug.
> 
> Did you by any chance scrape the TV series or episode already?

yes I did and it always says none are available no matter what episode thumbnail you click

**Comment by kolbdog323** [comment]
Also a slight addition it is now showing thumbnail results for tvdb but they are for the wrong shows for example i tried to change a picture for addams family episode cousin itt visits the addams family but it didn't show a picture from that show when i clicked tvdb it showed a picture from a completely differnt show.

Here is a screenshot to show you the error.
![for online](https://github.com/Komet/MediaElch/assets/161794176/fe461b2d-fb65-4963-9bb3-f7b871ed2afe)

**Comment by kolbdog323** [comment]
> As far as I know, it is no longer possible to obtain data and images from TheTVDB using MediaElch. See here: #1120 Did it work again?

Did you not just the the screenshot? 
Also it does get images from tvdb it is able to get season posters from tvdb same with banners. Just the thumbnails is broken.

**Comment by bugwelle** [comment]
I never removed TheTvDb completely. Some APIs are still up and running, including for images. But as soon as they are shut down, I'll remove it for good. 

----

If an episode was scraped, the thumbnail dialog shows the images whose URLs were scraped, and may not show _other_ thumbnails. The only other episode thumbnail provider we currently have is TheTvDb, and that may or may not work anymore.

This is partly a feature: A new thumbnail provider, e.g. via fanart.tv

**Comment by bugwelle** [comment]
Regarding your screenshot: Did you by any chance scrape that episode or TV show _wrong_ before? e.g. did you scrape another TV show before or did the NFO file contain URLs to to images of another show?

**Comment by kolbdog323** [comment]
NO i didnt it was the fist time scraping it.

> Regarding your screenshot: Did you by any chance scrape that episode or TV show _wrong_ before? e.g. did you scrape another TV show before or did the NFO file contain URLs to to images of another show?

No i didnt it was the first time scraping it there was no nfo or anything liek that.

**Comment by bugwelle** [comment]
> NO i didnt it was the fist time scraping it.

Ok, in your first response you stated `yes I did and […]`. :)

> No i didnt it was the first time scraping it there was no nfo or anything liek that.

Ok, thanks.

If I remember correctly (and I could be mistaken here, it's been a long time), the thumbnail dialog only shows images once you've scraped it.  The "default" image provider just looks at what the episode/TV show scraper loaded: image URLs. If they aren't there, nothing is loaded.  The TheTvDb image provider no longer works (as their API and business model changed), hence there is currently no proper image provider for it.

That needs to change and the current behavior is rather confusing (which I consider a bug). :)

**Comment by kolbdog323** [comment]
> > NO i didnt it was the fist time scraping it.
> 
> Ok, in your first response you stated `yes I did and […]`. :)
> 
> > No i didnt it was the first time scraping it there was no nfo or anything liek that.
> 
> Ok, thanks.
> 
> If I remember correctly (and I could be mistaken here, it's been a long time), the thumbnail dialog only shows images once you've scraped it. The "default" image provider just looks at what the episode/TV show scraper loaded: image URLs. If they aren't there, nothing is loaded. The TheTvDb image provider no longer works (as their API and business model changed), hence there is currently no proper image provider for it.
> 
> That needs to change and the current behavior is rather confusing (which I consider a bug). :)

That makes no sense if its able to find tvdb banners and season posters.

**Comment by bugwelle** [comment]
Ok, then let me say it like that: There won't be TheTvDb support. If it works for you: Great! But it's luck whether it works or not. For me, it hasn't been working for all shows I've tested:

![Screenshot_20240423_203623](https://github.com/Komet/MediaElch/assets/1667306/9e70eafc-e4c4-4983-9f50-9cb6fbde46c9)

There won't be a fix in the near future. I consider a new image provider to be a feature. The UI part, i.e. the inconsistent behavior, is a bug that needs fixing eventually.

**Comment by kolbdog323** [comment]
I'll close this then since it's not going to be fixed
