### ISSUE TITLE
ADVDE / AEBN / HM : scrap both front and back cover?

### ISSUE THREAD

**Issue by gutn8** [Komet/MediaElch#1743]
Currently using 2.10.7 nightly since it fixed an AdultDVDEmpire issue.

Hi, new user user here. Love this tool. I searched in the issues and docs but I didn't see a way to do this. If there is a way I apologize for the unnecessary request and would appreciate being pointed to instructions on how to do this.

When I scrape from AdultDVDEmpire / AEBN / HotMovie, the item for Poster will pull the cover for the front cover of the movie. However, seems like on all the sites above (although I only use AdultDVDEmpire), both front and back covers are available.

AdultDVDEmpire has the covers in the <front>h.jog and <back>bh.jpg format. Looks like HotMovies is the same (maybe they get the covers from AdultDVDEmpire? AEBN also has <name>_xlf.jpg and <back>_xlb.jpg

Would it be possible to add a field called something like "Poster (back)" (or whatever) that allows these adult site scrapers to scrap both the front and back covers? 

Alternatively, re-using an existing field like Logo or Banner to put the back cover world work too.

Would love to have this ability for AdultDVDEmpire since that's what I use, but would be great to have it for AEBN and HotMovie as well.

Thank you.

**Comment by bugwelle** [comment]
Good point. I'll have to check where your idea fits within Kodi's image files.

Note: I'm on vacation for the next 2 weeks and won't be active here. Also, please see https://github.com/Komet/MediaElch/issues/1710 :)

**Comment by gutn8** [comment]
- I use MediaElch purely as a scraper, independent of Kodi, so I hadn't considered Kodi integration.
- Re #1710: Makes sense with your shifting priorities that you only have resources for small bug fixes and new features are long ways away. Understandable.

Enjoy your vacation and thanks for the reply/update.

**Comment by bugwelle** [comment]
The item `MovieBackdrop` would probably fit here. It's displayed as "fanart" on the right side. You can also click on the poster and then select the back cover.  I've implemented it for HM and ADVDE.
