### ISSUE TITLE
Add Premiered Date Field.

### ISSUE THREAD

**Issue by VRArt1** [Komet/MediaElch#1749]
This is not related to a bug, MediaElch has been lovely for my media hoarding and organizing habits but there is one field that MediaElch doesn't cover that I'd love to see in a future update. Specifically a field for the premiered date tag that I think would go nicely next to the Released year field. It's the only tag I have to go in manually into the nfo field to set.

As a side note within the Contributing.md file there is a dead link to the FAQ. It currently leads to a 404 page not found.

**Comment by bugwelle** [comment]
Hi, 

thanks for the feature request! I've updated the FAQ in https://github.com/Komet/MediaElch/commit/41a9646a9c4fd3d42a83d912571fe5fb5c979921 , thanks for reporting!

Internally, we already use the `<premiered>` field. It may already be scraped correctly. But the UI doesn't represent that! Oh! That will be fixed. I consider this a bug. :)

Regards,
Andre

**Comment by bugwelle** [comment]
FYI: Kodi 17 and later don't support the `year` tag anymore. It's now only the `premiered` field.

**Comment by bugwelle** [comment]
The next Nightly version will have this fixed. Thanks for reporting!
