### ISSUE TITLE
TV Link Field Request

### ISSUE THREAD

**Issue by VRArt1** [Komet/MediaElch#1753]
**Is your feature request related to a problem? Please describe.**
I discovered a field that is not currently represented in Media Elch that kodi is able to utilize. The TV Show link tag. This tag allows you to when scraping nfo files to link a movie to the relevant show it's attached to.

I propose adding this field to the Extended section for movies in a similar form as how Genres/Tags/Countries/Studios are listed with the ability to type in one and then it's added below in a clickable toggle fashion like the others as you can add multiple tv shows the movie is linked to by adding more tags.

Below is the format of the tag how it shows in nfo, movies can be linked to multiple shows by adding in extra showlinks. As well here is a link to the kodi page describing the feature, at the bottom is the section about nfo https://kodi.wiki/view/Linking_movies_to_TV_shows
```
<movie>
   <showlink></showlink> 
</movie>
```
**Describe the solution you'd like**
I'd like to see this implemented as a feature for ease of nfo creation entirely within MediaElch.

**Describe alternatives you've considered**
Alternatively they can be just added in separately after creating the initial MediaElch. However as MediaElch doesn't support the field if you later attempt to update the nfo file with MediaElch again it'll delete the showlink tags.

**Comment by bugwelle** [comment]
Thanks for this feature request. Do you happen to know what value the `<showlink>…</showlink>` tag has?

Please be aware of https://github.com/Komet/MediaElch/issues/1710 :)

**Comment by VRArt1** [comment]
The <showlink>...</showlink> tag allows movies to be linked to relevant shows. For example if on the movie nfo file for the Drawn Together movie I were to add <showlink>Drawn Together</showlink> then when clicking on the show it'll show up at the top next to the episodes. It's a pretty useful featuring for remembering which shows have related movies. Kodi supports adding multiple shows to a movie which is useful for say crossover movies that feature two different shows.

Unfortunately I'm not a coder or I'd love to assist. My "coding" knowledge maxes out at manually editing nfo files.

**Comment by bugwelle** [comment]
That's already enough, thank you! :)

I thought it had to be a file-path or something. But if all you need is the TV show's title, then it should be "rather easy" (well, let's see) :smile: 

First step: Allow it in NFO files. Then you can at least edit the files without MediaElch overriding them. :)

**Comment by bugwelle** [comment]
I've added a "showlink" tag to movies. You can set it via the UI as well as NFO files. In the NFO, it works via the `<showlink>` tag, and in the UI via the movie->extended->TV show link text field. There is no drop-down menu or sanity check, yet. :)

Next nightly versions will be available within the next hour.

**Comment by VRArt1** [comment]
Just checked and it seems to be working but doesn't seem to account for multiple showlinks. It should work like the director/writer field where if you use a comma to separate multiple entries since you can have more than one showlink to a movie. I'm not sure if this is included in the 'sanity check' you mentioned or not so I thought it prudent to mention.

**Comment by bugwelle** [comment]
Oh, well, seems I was a bit too fast with my change and didn't properly read Kodi's Wiki.
Thanks!

**Comment by VRArt1** [comment]
Yeah this is why I recommended making it into a tag system like the tags in case for like shows that might have a comma in the name.

**Comment by bugwelle** [comment]
Oh, sorry about that 😄 
Seems I didn't read your issue properly (yesterday evening).

**Comment by bugwelle** [comment]
The next Nightly version will contain your feature with multiple `showlink` entries. In the UI, you will need a comma-separated list.

**Comment by VRArt1** [comment]
Wouldn't this cause issues then for tv shows that contain commas in their name like ```Murder, She Wrote```?

**Comment by bugwelle** [comment]
Yes, it would. This isn't a proper solution. Only the MediaElch UI part does the comma-separation stuff. Once we have a proper UI widget for lists, this field, as well as other fields need to be adapted/fixed.

I'm open for contributions here. :)

**Comment by VRArt1** [comment]
What I recommend is doing it similar to the tags where you can type out the name and then click enter and it pops down below as an entry that you can click on and off. It'd at least be good standby until the new list widget is created.

**Comment by bugwelle** [comment]
You're right. :smile: 
I was lazy here. Will be fixed by https://github.com/Komet/MediaElch/pull/1761
