### ISSUE TITLE
Weird title once scraped if use IMDB special characters are in it.

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1754]
For some reason when you screape a title with imdb scraper only and it has one of these in it " , & !" The Title of the show become's strange for example I scraped Mater's Tall Tales using imdb and tvmaze. The tvmaze version work's fine and looks proper here is a screenshot using imdb scraper.

![Untitled](https://github.com/Komet/MediaElch/assets/161794176/bdd8fa58-c300-424e-9a27-82e7d36158da)

**Comment by bugwelle** [comment]
Argh... Thanks for reporting! 

Link: https://www.imdb.com/title/tt1384816/?ref_=fn_al_tt_1

Replace `&apos;` with `'` for now.

----

Notes: I thought the JSON wasn't HTML-encoded, but is is: `,"name":"Mater&apos;s Tall Tales"`.

**Comment by bugwelle** [comment]
Thanks again for reporting this!
I've fixed your issue in #1759.  The next nightly version will fix your issue.
