### ISSUE TITLE
GUI not showing, Qt wayland plugin not found

### ISSUE THREAD

**Issue by galettof** [Komet/MediaElch#1763]
**Describe the bug**
Running the app from the icon does not bring up GUI. Running from the terminal returns:
`qt.qta.plugn: Could not find the Qt platform plugin "wayland" in ""`
System monitor shows a process for the app.

The app was previously working fine on Fedora 40. The qt5-qtwayland and qt6-qtwayland packages are installed. System is updated regularly and the issue started after a recent update.

**To Reproduce**
Start the app.

**Expected behavior**
Expect app GUI to open.

**MediaElch Version:**
 - [X] 2.10.7-dev (nightly)
 - [X] 2.10.6 (stable)

**Operating System:**
 - [X] Linux (distribution: Fedora 40)

Thanks!

**Comment by bugwelle** [comment]
Hi!

Thanks for reporting this issue. How did you install MediaElch? Did you install it via the AppImage or via a package repository (and if so, which one?). :)

Regards,
Andre

**Comment by galettof** [comment]
Sorry, I forgot to say. I installed via the AppImage.

Thank you!

**Comment by bugwelle** [comment]
Ah, ok. Makes sense. It could be that my Dockerimage uses Wayland (accidentally)? Maybe something is missing.

**Comment by bugwelle** [comment]
Strange. I can't reproduce it on a fresh "Fedora 40 Workstation Edition" installation with Wayland (`$XDG_SESSION_TYPE` is `wayland`).

![Screenshot_20240630_150157](https://github.com/Komet/MediaElch/assets/1667306/cb37c2b9-6173-4a11-98df-d53b0e0f0b41)

@galettof I'm sorry, but I don't know how to help here. If it has been working before, I wonder whether something was (un-)installed that the AppImage needed. Though I'm curious what it could have been.

You shouldn't even need any Qt packages. :-/
I think the only solution for you is to follow the build instructions.

**Comment by galettof** [comment]
No problem, thanks for looking into it!
