### ISSUE TITLE
Add the play widget to the shows for episodes 

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1764]
I am just wondering since you added the play widget for movies can you also add it for episodes as well since be nice so you can play episodes using the widget instead of right-clicking and then play for those videos. Thanks.

**Comment by bugwelle** [comment]
Sure. :)

I wanted to add it there as well sooner or later. Also for concerts.

**Comment by bugwelle** [comment]
Fixed via #1769
