### ISSUE TITLE
Content disappear if save and load another scraper

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1765]
For some reason if you save the show using one of the scrapers example TVmaze then rescrape using another scraper example TMDB all the content from all the episodes disappear. Be nice if the contents would stay saved so when you rescrape using another scraper you have all missing info. 

Reason i do this instead of custom scraper is because some episodes are only on tvmaze and not tmdb same with shows so be nice if could save the missing data. Or is that only if you scarpe entire show and not a single episode using 2 scrapers? Sorry not exactly sure how that works.

**Comment by bugwelle** [comment]
Indeed. Merging of scraper details is currently not implemented.

**Comment by kolbdog323** [comment]
I figured it out you can merge scrapers just need to scrape tvmaze first then tmdb then can have missing actors but hae to do tvdb or tvmaze episode or imdb show only or episode not all episodes and shows. Then you can merge differnt scrapers to get all results.

**Comment by kolbdog323** [comment]
Ill close this issue. since not supported.
