### ISSUE TITLE
[feature request] anime organizer based on anidb relations

### ISSUE THREAD

**Issue by tamodolo** [Komet/MediaElch#1766]
This is somewhat a sequence to the anidb as scraper request from 2018 (!!!). (yeat maybe not as necessary to implement this)

Anidb has a relation flow for anime series that work amazingly to guide you through complicated anime name schemes. I'll try to describe what I do manually so this idea makes some sense:

I'll use KONOSUBA as example:

![image](https://github.com/Komet/MediaElch/assets/9446795/5c756f65-4ab9-4045-b2e5-d53652239192)

As you can see there are TV Show, OVAs and Movies as main story sequels. I put all of them manually as episodes where they should be to respect watch order but sinse we have this scraper that already organizes that it could be nice to use this part to make apropriate changes to local data.

Sinse KODI does not parse movies as series properly then we could force this behavior by using an organizer that convert the movie metadata to season metadata and list as an episode inside a season or reorder series to fit movies and OVAs between seasons as a season between them (the second solution is better).

I think this could be done without making anidb as a proper scraper as just the relation data is needed.

Extra: I think even if anidb isn't used to automaticaly do this, an organizer should be made anyway.

**Comment by bugwelle** [comment]
Hi,

thanks for this feature request! I'm currently limiting myself to bug fixes only, as I don't find the time for feature requests anymore. Please see https://github.com/Komet/MediaElch/issues/1710 for details.

Your feature request is valid. You're not the only one, it has been requested long ago, see https://github.com/Komet/MediaElch/issues/433 , on which you also commented.

I'm closing this issue as a duplicate, but will link to it in the other issue. Thanks for the example!

Regards,
Andre
