### ISSUE TITLE
TVMaze year missing when scraping show

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1767]
For some reason when you scrape using the tvmaze scraper for series the year is missing and it shows the current date in the first aired since i tried it on multipel shows tvmaze only like Three Stooges, Little Raccals the tvmaze first air date is missing and that is needed for the file renamer to work properly.

**Comment by kolbdog323** [comment]
The year shows up when you search for the show but not in the actual scraping part where it shows first air date.

**Comment by bugwelle** [comment]
I can reproduce your issue and found the bug.
