### ISSUE TITLE
The string "(UHD)" in a movie's directory name causes all scrapers to fail ("(BLURAY)" and "(DVD)" work fine)

### ISSUE THREAD

**Issue by zacharyfreeman70** [Komet/MediaElch#1773]
**Scrapers that don't work:**

 - [x] IMDb
 - [x] TMDb
 - [ ] TmdbConcert
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
When I right-click on a new movie I'm trying to add to my collection and select "Load Information", if the directory looks something like `D:/movies/THE_MATRIX_(1999)_(BLURAY)/`, MediaElch will scrape the information for that movie without any issue. This is as expected.

But if I try to do the same for a directory like `D:/movies/THE_MATRIX_(1999)_(UHD)/` (note the "(UHD) at the end), MediaElch will fail. This is because the search string that gets populated into the "Scraper Result" window that pops up after selecting "Load Information" from the right-click menu is "THE MATRIX (1999) (UHD)".

The "(UHD)" part of the string seems to confuse scrapers. If MediaElch strips this part out just like it does for "(BLURAY)" and "(DVD)", this will fix this issue.

**MediaElch Version:**
 - [ ] 2.10.7-dev (nightly)
 - [x] 2.10.6 (stable)

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [x] Linux (distribution: ___)

**Additional context:**
This feels like it might be a pretty straightforward fix: find the part of the code that strips "(BLURAY)" and "(DVD)" from directory names and add "(UHD)" to the list of strings that get stripped out.

I spent an hour or two looking at the code on GitHub to see if I could help and do this myself. I believe there are some QRegularExpressions that might be of interest. Maybe one of these could be expanded such that strings like "UHD" are treated similarly to strings like "DVD" and "BLURAY" in folder names?

In the spirit of trying to reduce the burden of implementing a fix, here's a potential starting point that might be relevant:

https://github.com/Komet/MediaElch/blob/6745a44bbbbcafb68c980758e0a8baba005f8744/src/ui/import/ImportDialog.cpp#L476

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this issue! :)

MediaElch does some name-preprocessing to get a "default movie title". The list of "excluded words" is defined in:

https://github.com/Komet/MediaElch/blob/6745a44bbbbcafb68c980758e0a8baba005f8744/src/settings/Settings.cpp#L215-L223

I've added "uhd" and have also added a test ([link](https://github.com/Komet/MediaElch/pull/1775)). Please note that we don't have an update process for those settings, yet. You will need to manually add an "exclude-word" to your settings.

Go to MediaElch -> settings -> scroll down -> add `,uhd` to the list:

![Screenshot_20240720_150157](https://github.com/user-attachments/assets/5101ebdd-c2b5-4a1a-96a8-e12fd4459645)

Regards,
Andre

**Comment by zacharyfreeman70** [comment]
This is great, thank you @bugwelle! I'll add that phrase to my exclude-word list.

I'm sure you've heard this sentiment before, but MediaElch is easily the best media manager out there. Beyond the clean UI with useful features, it's hard to beat the high quality developer support.

Thank you for the suggested fix.
