### ISSUE TITLE
Wont scrape actor images if scrape using TMDBTV just for episode.

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1784]
I noticed when you scrape just an episode using TMDBTV it wont scrape any actor images just the names of the actors and the roles but no images are scraped please fix this the actors images will scrape if you do the TMDBTV for show just not for episode only.

**Comment by bugwelle** [comment]
Seems we don't do any image scraping for episodes! Oh. Same for IMDb, see #1486
