### ISSUE TITLE
Enable Ubuntu 24.04 (Noble) builds on the PPA

### ISSUE THREAD

**Issue by heldchen** [Komet/MediaElch#1789]
**Is your feature request related to a problem? Please describe.**
Currently, the MediaElch PPA (http://ppa.launchpad.net/mediaelch/mediaelch-stable/ubuntu/dists/) is missing packages for the latest Ubuntu LTS release 24.04 (Noble)

**Describe the solution you'd like**
Please enable `noble` / `24.04` as packaging target, similar to what you did 2 years ago for 22.04 in https://github.com/Komet/MediaElch/pull/1485

**Describe alternatives you've considered**
As a temporary workaround I am using the `jammy` packages on `noble`

**Comment by bugwelle** [comment]
There hasn't been a release this year, which I plan to change next month. It will then be published for 24.04 as well.

Note: I'm on vacation for the next two weeks and may likely not respond in time. :)

**Comment by heldchen** [comment]
that's great, thanks @bugwelle and enjoy your holidays!

**Comment by omnicortex** [comment]
Looking forward to this :smiley:

**Comment by bugwelle** [comment]
2.12.0.0-1~noble  was released in October. :)
