### ISSUE TITLE
Bug: Overview pasting formatting issue.

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1790]
When you paste text into overview it should be plain text not the format you are pasting from example if you paste text and it has italics it willl paste the italiacs along with the plain text same if you paste something taht is bold font orgially it should be plain text wehn you paste it.
 Can you please fix it so it will be plain text when you paste text into orview and not carry over the formatting from the original source?

**Comment by bugwelle** [comment]
Valid point. Never did that. Note, however, that formatted text is never stored. If you save the movie/TV show/etc., only the plain text will be stored.

Test via (copy&paste)
__bold__ _italic_ normal __bold again__
