### ISSUE TITLE
Bug: TvMaze won't scrape actual actor images only character images

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1800]
When you scrape a show from tvmaze only the charactrer images will download/scrape the actual actor images wont scrape . Example if the tv show hsa a character image it will downlad that fine but not if the character has an actual actor image of the real actor. Example if the show only has actual actor images that someoen didnt add character imagees for those wont scrape but if it has an image of the chjaracter it will scrape. 

A show i just tried to scrape from on tvmaze was Olaf Presents and taht only had one character olaf and it had a real actor image not an image of the character from the show and it wouldtn scrape/download it. Same with the show Berenstein Bears it would scrape 2 chracter images but not 2 of the characters who had real actor images not the chararacter specirfc image.

Sorry not sure if makes sense or not.

**Comment by bugwelle** [comment]
Hi,

indeed. This was more or less on purpose. But you're right, we should scrape the actor image first, and only the character image if the other one is not available.

Note to self: switch these statements:

https://github.com/Komet/MediaElch/blob/07b9d107ccddde2054131646290ed2bdc1c20b24/src/scrapers/tv_show/tvmaze/TvMazeShowParser.cpp#L158-L162

Regards,
Andre

**Comment by bugwelle** [comment]
Fixed via #1804
