### ISSUE TITLE
PPA Build for Jammy failed

### ISSUE THREAD

**Issue by chaosfreak93** [Komet/MediaElch#1807]
**Describe the bug**
[Launchpad/PPA Build](https://launchpad.net/~mediaelch/+archive/ubuntu/mediaelch-stable/+packages) for Ubuntu Jammy failed.
Linuxserver.io Docker Images depends on this build.

**Expected behavior**
Succesfull Ubuntu Jammy Build on Launchpad.

**MediaElch Version:**
 - [ ] 2.12.1-dev (nightly)
 - [x] 2.12.0 (stable)

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: _._)

**Additional context**
[Linuxserver.io Response](https://github.com/linuxserver/docker-mediaelch/issues/3#issuecomment-2414302079)
[Launchpad](https://launchpad.net/~mediaelch/+archive/ubuntu/mediaelch-stable/+packages)

**Comment by bugwelle** [comment]
Thanks. Indeed, but I didn't get to fix those builds, yet. :)
Not Just jammy, but two other versions as well.

**Comment by bugwelle** [comment]
MediaElch 2.12.0.1-1~jammy  and 2.12.0.1-1~focal  have been published.

Sorry for the delay!

```
# apt info mediaelch
Package: mediaelch
Version: 2.12.0.1-1~jammy
Priority: extra
Section: misc
Maintainer: Andre Meyering <info@andremeyering.de>
Installed-Size: 7157 kB
Depends: libc6 (>= 2.34), libgcc-s1 (>= 3.3.1), libqt5concurrent5 (>= 5.6.0~rc), libqt5core5a (>= 5.15.1), libqt5gui5 (>= 5.14.1) | libqt5gui5-gles (>= 5.14.1), libqt5multimedia5 (>= 5.6.0~beta), libqt5multimediawidgets5 (>= 5.6.0~beta), libqt5network5 (>= 5.14.1), libqt5sql5 (>= 5.0.2), libqt5widgets5 (>= 5.15.1), libqt5xml5 (>= 5.0.2), libstdc++6 (>= 5.2), zlib1g (>= 1:1.1.4), libqt5sql5-sqlite, libqt5gui5, libqt5svg5, libqt5opengl5, libmediainfo0 | libmediainfo0v5, libzen0 | libzen0v5, libcurl3 | libcurl4, libpulse0
Download-Size: 2757 kB
APT-Sources: https://ppa.launchpadcontent.net/mediaelch/mediaelch-stable/ubuntu jammy/main amd64 Packages
Description: Kodi Media Manager
```

**Comment by chaosfreak93** [comment]
Thank you so much! All good everyone has a life.
