### ISSUE TITLE
Missing HDR entry in nfo

### ISSUE THREAD

**Issue by AngeluS7510** [Komet/MediaElch#1810]
Hello
When the *.nfo is written (for 4k, UHD), there is no entry for HDR, it is then marked as SDR in Kodi. If I scrape the film via Kodi (TMDB), then the entry is created in the *.nfo. I like MediaElch and it would be nice if this could be fixed.

**Comment by AngeluS7510** [comment]
Yes, that meant <hdrtype>. There is no entry and so it is marked as "sdr" in Kodi.

Windows 11
Kodi 21.1
Skin: Aeon Nox: SiLVO
MediaElch 2.12.0

I understand that this is your time that you are investing in this software and I read #1710 before I published #1810. I must admit that I now use a different software in which I invested €10 for an annual license. Out of fairness, I have just donated €20 via PayPal to support your project and in the hope that you will soon find new contributors (#1810 is not urgent either). :)

Best regards
Andreas

**Comment by bugwelle** [comment]
Thanks for being so open and for your reply! :)

It seems `<hdrinfo>` was added a year ago, see https://kodi.wiki/index.php?title=NFO_files%2FMovies&type=revision&diff=249053&oldid=244234

HDR Type in NFO files will be added in https://github.com/Komet/MediaElch/pull/1817
