### ISSUE TITLE
make <tmdbId> available for renaming TV Shows.

### ISSUE THREAD

**Issue by tocotronaut** [Komet/MediaElch#1814]
I can rename Movies with the TMDB-ID.

The Variable `<tmdbId>` works there.

But i cant rename TV Shows with this `<tmdbId>` variable.

-> Please make this <tmdbId> Variable available when Renaming TV Shows.

**Comment by bugwelle** [comment]
Hi,

thanks for opening this feature request. Will be fixed. :)



Regards,
Andre
