### ISSUE TITLE
Mediaelch not saving movie media info

### ISSUE THREAD

**Issue by MrBabafemi** [Komet/MediaElch#1818]
hello all.
mediaelch user for quite a while. LOVE this app. has kept my media neat and proper  for a long time now.  recently i had an issue that seemed to wipe out my config files for a few of my arrs*.  i believe it was associated with some spacing issues that i have since corrected (I HOPE). well after rerconfiguring my arrs i happened to notice that when i opened medialelch it was as if all the files were brand new. unsaved info, no images. as if it hadnt been scraped.  it only seemed to affect the movies, not the shows.  i rescraped everything (almost 2800 movies) over the next couple of days.  a day or so later i go back in do a full scan and its back to the unscraped movies again.  over the next few days i scrape a few,  give it a day, rescan and its unscraped again.  so then thats when i found that there was a docker version and figured ok maybe its my installed ubuntu version.  i install the docker version, start it up, see unscraped, scrape a few wait a day or so rescan and the issue is still there.  here is all the info i have been asked to include.  thank you in advance for any assistance.

https://hastebin.com/share/ubexujurow.yaml

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this issue. Sorry to ask, what is `arrs`? :smile: 

Besides that, MediaElch stores NFO files as well as images right next to the movie files. Did those files also disappear?
If so, what files remained?

Regards,
Andre

**Comment by MrBabafemi** [comment]
Arrs... Sonarr/Radarr/Lidarr... selfhosting apps.
That's the strange part, all movie.nfo and images are still in folders.
Everything is in the folders, but it's as if the program has gone blind and
doesn't see anything.
Ok that made me notice that the nfo files are saved as movie.nfo instead of
the movie name.nfo.   there are maybe 10 movies with proper nfo files but
all the rest are not.

**Comment by MrBabafemi** [comment]
Well after replying to your msg and realizing the nfo difference.  I was
able to find that a setting in Radarr had the default setting to save
Metadata as "movie.nfo" (not sure how it got activated in the new install)
and it was overwriting the star wars (1977).nfo files every morning as it
did a scan.  Once that was disabled and radarr rescanned my files it gave
them the proper nfo files and when I scanned with mediaelch it was able to
see the proper files and all is right in the world again.

Thank you again for your assistance. And thank you again for such a great
app.

LAG
