### ISSUE TITLE
prevent the .nfo file from being generated

### ISSUE THREAD

**Issue by freeztyler** [Komet/MediaElch#1820]
I only need the poster JPEG when saving, but unfortunately, a .nfo file is always created as well. Is there a way to prevent the .nfo file from being generated?

**Comment by bugwelle** [comment]
Hi,

no, there isn't. MediaElch supports Kodi only, and it will therefore always create an NFO file, as that file is used to store all scraped details.

As MediaElch is tightly coupled to Kodi (XBMC), we will always rely on NFO files. :)

Regards,

Andre
