### ISSUE TITLE
AdultDvDEmpire Scraper does not work

### ISSUE THREAD

**Issue by SirCumAlot1988** [Komet/MediaElch#1828]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] TMDb
 - [ ] TmdbConcert
 - [ ] TvTunes
 - [ ] AEBN
 - [x] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
I get a network error. Other scrapers do work though.

**MediaElch Version:**
 - [ ] 2.12.1-dev (nightly)
 - [x] 2.12.0 (stable)

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**

**Comment by bugwelle** [comment]
Hi,

could you please try the latest nightly version? I fixed ADE and HM in https://github.com/Komet/MediaElch/pull/1816 :)

See https://mediaelch.github.io/mediaelch-doc/download/windows.html (use "latest - unstable").

Regards,
Andre

**Comment by SirCumAlot1988** [comment]
Works very well :-) Thanks!

**Comment by bugwelle** [comment]
Great! :)
Thanks for reporting issues!
