### ISSUE TITLE
Bug: IMDBTV Writer and Director not scraping for episodes

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1832]
When you try to scrape from imdbtv for tv shows the writer and director for episodes will show up as blank exxample i tried scraping S01E31 - Dig those DIglet and the show Pokemon from imdb to get the missing writer and director that was missing from TMDB but when i scraped from imdb the writer and director were blank even though on the imdb site it shows the director as Masamitsu Hidaka for that episode and the writers Jun'ichi Masuda,Takeshi Shudô, Ken Sugimori and Satoshi Tajiri.
Please fix this thanks.

**Comment by bugwelle** [comment]
Thanks for reporting. Could you point me to the exact Pokemon show you're referring to? :)
That is, link to the IMDB page? There are too many Pokemon shows and I can't find the episode you're referring to there.

Regards,
Andre

**Comment by bugwelle** [comment]
Reproduced it with another show/episode.

**Comment by bugwelle** [comment]
Fixed via  #1835

The next nightly version will contain this fix.
