### ISSUE TITLE
Episode file name matching

### ISSUE THREAD

**Issue by Komet** [Komet/MediaElch#291]
Add regex for identifying season and episode number. At least the following should be matched:

S01E02
S1E2
S01.E02
S01_E02
1x02
102

**Comment by MetaStazz** [comment]
Would be nice to do that it's from 2013 we are 2021 and naming is still a freaking pain !!!

**Comment by ticao2** [comment]
Just to make the conversation easier:
https://kodi.wiki/view/Naming_video_files/Episodes
