### ISSUE TITLE
Scraper settings per directory

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#420]
*This was originally requested on the old MediaElch forum*

It would be nice to have the possibility to set scraper settings like language on a directory basis.

**Comment by ludi113** [comment]
It might even make sense to go on step further: what about adding next to the fixed languages option (i.e.: en, de, fr,...) also a dynamic language option based on the audio language of the file. In other words, if for example the audio language of the file is german, then scrape the german info for the movie/tvshow. 

There will probably have to be a priority and fallback mechanisme for files with multiple audio languages and for files whose information is not available in a particular language; it might be nevertheless interesting to try to find a way to choose the language of the information to scrape based on the audio language.

**Comment by bugwelle** [comment]
We now have a language selection in all search windows to easily change the language. I think that is sufficient.

I think, implementing this would be confusing in some ways: I don't want to have too many places to change a language: We currently have the global settings and the search window. Changing the language in the search window also changes it in the global settings. A per-directory settings would increase the complexity of MediaElch's settings. I want it to stay simple where possible. Maybe TinyMediaManager is better suited for such cases.
