### ISSUE TITLE
Windows 4k support | HDPI Support

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#429]
*This was originally requested on the old MediaElch forum*

It seems that icons aren't scaled correctly.

![mediaelchbutton](https://user-images.githubusercontent.com/1667306/40315631-363a732c-5d1c-11e8-8ca3-1974f6a49843.png)

**Comment by dersch81** [comment]
I have the same issue. The 4k scaling is not good with the icons. Until the maintainer is fixing it i could help myself with a manifest file.

**Comment by bugwelle** [comment]
![ZIFWZjZ](https://user-images.githubusercontent.com/1667306/103566238-f4f0ab80-4ec1-11eb-941e-ea2b82306d3c.jpg)


Reported on the kodi forum as well.

dersch81's manifest file as a txt:

[MediaElch.exe.manifest.txt](https://github.com/Komet/MediaElch/files/5766194/MediaElch.exe.manifest.txt)

(Usage: Save next to MediaElch.exe and remove the `.txt` postfix)

**Comment by bugwelle** [comment]
Ok, reproducing this is rather simple. I have a PC with Windows 10 Education in German.

You have to adapt your Scaling to e.g. 200% and then you get this output:

![Screenshot 2021-02-04 182808](https://user-images.githubusercontent.com/1667306/106931606-0cb48d00-6717-11eb-947a-24d6557c8211.png)

Multiple Issues:

 - Sorting isn't properly scaled (New/Name/...)
 - Icons are not scaled
 - About Dialog: Heading is too large?

**Comment by bugwelle** [comment]
A workaround is to use `/MediaElch.exe -platform windows:dpiawareness=0`. MediaElch will look pixalated but at least it doesn't look strange as above.

**Comment by Thunderbolt32** [comment]
The text in the settings is also not scaled and theirfor unreadable small. That's a major issue... Pretty much unusable on a 14" notebook with a 4k display. 

Something goes completely wrong with the scaling, as the icons get even smaller with each zoom level and at 300% they disappear completely. Compare 250% Scaling (frist image) with 100% Scaling (second image)

![2021-08-29_12h53_06](https://user-images.githubusercontent.com/10698184/131247843-5678cf61-a148-4c93-a341-5c9b2e448411.png)

![2021-08-29_12h59_10](https://user-images.githubusercontent.com/10698184/131248049-6ffbaaca-cd31-422b-b647-331edddcd007.png)


The only solution is to let the operating system do the scaling. Instead of starting MediaElch via PowerShell, it is much more convenient to simply configure the compatibility settings.
<img src="https://user-images.githubusercontent.com/10698184/131247377-4917e9f5-61cb-4971-b3d8-50c67cfbe6ff.png" width="500" >

The result is (Note: My Screenshot application does edge smoothing.):
![2021-08-29_13h07_42](https://user-images.githubusercontent.com/10698184/131248271-e6dcb6d8-9653-4714-984d-c41dadee2d16.png)

**Comment by bugwelle** [comment]
Thanks! :)

**Comment by habakuk007** [comment]
Not usable on current windows laptops or high dpi displays (with windows 10):

![grafik](https://user-images.githubusercontent.com/2253878/148695361-88c8cf35-eaf7-40bd-936c-95b735ac879f.png)

After changing compatibility settings (should not be needed for current applications), items have the right size, but are very blurry:

![grafik](https://user-images.githubusercontent.com/2253878/148695491-8240d025-e6f6-446e-9803-651745835e4e.png)

![grafik](https://user-images.githubusercontent.com/2253878/148695501-f9544635-9609-418e-8bde-08de66147738.png)

**Comment by bugwelle** [comment]
Hi,

some good news. With Qt6, we will most likely finally get HiDPI scaling. Here are two screenshots from my test system. The first on Qt 5.15 and the latter with Qt6. My Windows installation has a scaling factor of 175%.


![Unbenannt](https://user-images.githubusercontent.com/1667306/149673646-f0d2812f-a459-40c4-9662-78290374affc.PNG)


![Unbenannt2](https://user-images.githubusercontent.com/1667306/149673655-06796034-26c1-4042-ba66-82eacc21a217.PNG)

Not perfect, but a lot better. Display resolution: 3840x2024

**Comment by dersch81** [comment]
Looks pretty good!

**Comment by danilovesky** [comment]
@bugwelle What prevents you from releasing Qt6-based version of MediaElch? Are there some compatibility issues?

**Comment by bugwelle** [comment]
> @bugwelle What prevents you from releasing Qt6-based version of MediaElch? Are there some compatibility issues?

Mainly that it's not properly tested, yet. But also that I want to support older systems such as Windows 7 and macOS 10.13, which Qt6 does not support. 

So I will have to distribute two versions for macOS and Windows: One with Qt5 and one with Qt6. I already planned to do so, and as a first step, MediaElch's download page was split up into Windows/macOS/Linux subpages: https://mediaelch.github.io/mediaelch-doc/download/windows.html

Furthermore, we only recently began to test Qt6 in our CI, see https://github.com/Komet/MediaElch/commit/d23b7e391a433ec3252e8f8d343e68a6e99a787f , but now MediaElch fully supports Qt6. :smile:

I tried to package MediaElch for macOS with Qt6, but the resulting `MediaElch.app` (from the `*.dmg`) was about 100MB larger than the Qt5 version because of QtQuick.Controls2... I'll have to look into that as well.

__tl;dr__: After finally porting [the last bit](https://github.com/Komet/MediaElch/commit/377620991bc371c396c95f86e3cb1af5a616acd2) to Qt6, the only thing stopping me is time. I'll get to it. :)

**Comment by danilovesky** [comment]
@bugwelle Great! Looking forward to this release and happy to be a beta-tester if needed.

**Comment by bugwelle** [comment]
@danilovesky I assume you are using Windows as well? :-)

Current state: MediaElch + Qt6 release script works for macOS. For Windows, I'm half-finished. The build script works locally. Now I need to make it run on Jenkins (for automatic Nightly releases) + update my packaging script (for creating the ZIP file with dependencies).

**Comment by danilovesky** [comment]
> @danilovesky I assume you are using Windows as well? :-)

Yes, mostly a Windows 10 user since recently.

**Comment by bugwelle** [comment]
Current state: Build & Packaging script works locally. Screenshot (my system is German, but you can clearly see the differences)

![Screenshot_20221113_151954](https://user-images.githubusercontent.com/1667306/201526691-5dab6ebe-2085-49be-98af-c36f9dad49e1.png)

I'll let you know when this is published.

**Comment by danilovesky** [comment]
This is a significant improvement, looking forward to the release!

**Comment by bugwelle** [comment]
MediaElch is now packaged with Qt6. Snapshots are available at https://mediaelch-downloads.ameyering.de/snapshots/Windows_10_or_later/

Only Windows 10 or later is supported (untested on Windows 11; I only have Windows 10).

I tested it with 175% scaling on a 4k display. Works as shown in the display.
Please let me know of any issues you find (please open a new GitHub issue then).

Fixed by https://github.com/Komet/MediaElch/pull/1492

**Comment by danilovesky** [comment]
Works very well with 200% scaling on a 4k display too - all elements are good size (compared to tiny buttons in Qt5 with no upscaling), the text and icons are crisp clean (compared to blurry system-level upscaling).
