### ISSUE TITLE
Exclude a folder from scan

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#430]
*This was originally requested on the old MediaElch forum*

It would be nice to have a function to exclude a folder from a scan.

Example:

Harddrive: TV Series
Folders:
 - !unsorted
 - Scrubs
 - Breaking Bad

Something like: 

![unbenanntesbildvgukl](https://user-images.githubusercontent.com/1667306/40380148-79538ad6-5df8-11e8-91c1-8e607b403022.png)

**Comment by Megapit** [comment]
+1 for that

my reason: My files are on a Synology network share. It seems that Synology is creating a special folder "@eaDir" which MediaElch always want to scan.

For my needs, excluding with the advancedsettings.xml would be enought.

By the way: I work with an Docker Image direct on the Syno. When my Image is finished i will pulish it.
![Bildschirmfoto 2019-05-18 um 18 20 09](https://user-images.githubusercontent.com/50706199/57972385-c135da80-7999-11e9-9071-b079aead4ae9.png)

**Comment by bugwelle** [comment]
Hi, thanks for your feedback. :)
That would be a bit different than I had in mind, i.e. have a list of excluded directories to filter against instead of just ignoring excluded entries. :+1: 

PS: I didn't know that you could use GUI applications with docker. Cool!

**Comment by snakyjake1** [comment]
I would like to exclude folders.
Examples:
.unwanted
samples
featurettes
extras

**Comment by bugwelle** [comment]
This is supported in MediaElch's advancedsettings.xml, see https://github.com/Komet/MediaElch/issues/840

There are known bugs, see https://github.com/Komet/MediaElch/issues/1111
