### ISSUE TITLE
The TVDB changing APIs

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#432]
https://api.thetvdb.com/swagger
https://www.thetvdb.com/wiki/index.php?title=Programmers_API (seems to have been taken down)

> A new version of the API has been written which uses JSON instead of XML files. Documentation for this version can be found at https://api.thetvdb.com/swagger. It is highly recommended that any new development be done using the new API. This version of the API will continue to function until October 1st, 2017 at which time it will be discontinued.

The old API still works, but who knows how long it will stay that way?

-----------------

- [x] TvShow Scraping works
- [x] Single Episode Scraping works
- [x] "Show all episodes" works
- [x] Update (New/All) Episodes works
- [ ] TVShowUpdate uses new API and works

**Comment by bugwelle** [comment]
I'm mostly done and need to test it now :smiley:

**Comment by Xairoo** [comment]
Is there an ETA for this? =) Kodi v18 uses the v2 API URLs.

**Comment by bugwelle** [comment]
Oh, not yet. I'll try to work on it this weekend. No promises, though. I've had problems with Qt's signals&slots which slowed me down quite a bit.
Corresponding PR: #487

**Comment by bugwelle** [comment]
I can't believe that it took me 1.5 years...
The PR is finally merged!

Please open new issues in case that are problems with the new API. :smiley:
