### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by alexls74** [Komet/MediaElch#455]
Add full Russian translation, please.
https://www.transifex.com/komet/mediaelch/language/ru/

**Comment by bugwelle** [comment]
Thanks for creating this issue 😄 
Could you have a look at the strings and tell us if they are correct?
https://www.transifex.com/komet/mediaelch/viewstrings/#ru/main/18455598

At first I thought, that we already have Russian language support. But apparently we have to update our language files.
https://github.com/Komet/MediaElch/blob/master/i18n/MediaElch_ru.ts#L5454

**Comment by alexls74** [comment]
> Thanks for creating this issue 😄
Could you have a look at the strings and tell us if they are correct?
https://www.transifex.com/komet/mediaelch/viewstrings/#ru/main/18455598

I've done this translation. So... I think it's correct ;)

**Comment by bugwelle** [comment]
Will be fixed by #463
I need Komet to review my pull request. So it could still take a some days until it is merged.

Thanks for taking time to translate MediaElch. :)

**Comment by bugwelle** [comment]
Latest version now has Russian language support :smile:
