### ISSUE TITLE
IMDB Movie scraper bug

### ISSUE THREAD

**Issue by spooki3** [Komet/MediaElch#456]
Plot and Outline are not being pulled from IMDB using the movie scraper on the latest MacOS build "MediaElch_macOS_2.4.3-dev_2018-05-26_19-18_git-master-af8b965.dmg"

**Comment by bugwelle** [comment]
Thanks for reporting this. I can confirm this and will look into this.

**Comment by bugwelle** [comment]
This will be fixed by #457
