### ISSUE TITLE
Music scraper not working

### ISSUE THREAD

**Issue by alexbaroni** [Komet/MediaElch#464]
From yesterday only info scraped are artist but album isn't working

**Comment by alexbaroni** [comment]
I'm sorry it works.
The problem was the path it contains a comma.
Removed the comma and all works

2018-06-02 16:23 GMT+02:00 Andre Meyering <notifications@github.com>:

**Comment by bugwelle** [comment]
Glad to hear that it works. :smiley:

**Comment by ldgbc** [comment]
@bugwelle Hi, did MediaEilch remove MusicBrainz? I see Audio DB, Discog and AllMusic scraping but not MusicBrainz.

**Comment by bugwelle** [comment]
As far as I can tell, MusicBrainz was never selectable in a dropdown like AudioDb or Discog are.
I checked commits back from last year and even back there, only Audio DB, Discog and AllMusic were selectable. :-)

**Comment by danieldoof** [comment]
Hi MediaElch Support Team,

I seem to face a similar problem with the music scraper.
No information on any Artist or Album is found with the `Universal Music Scraper` with `The Audio DB` in `English` or in `German`. 

I just scraped my video library without any problem. I just had to alter the movie title a bit in the scraper window `The Movie DB` (erase extra stuff) and the correct movie title was found and could be added.
`IMDB` as scraper did not find anything though, which was weird. IMDB is reachable in my browser (`Firefox`), as is `The Audio DB`.

Now with the music scraper nothing is found. Not even when I only enter an artist like Frank Zappa who is defininately on the _theaudiodb_ website (I checked ;) ). The same goes for `AllMusic` and `Discogs`, it finds nothing.

My os is `archlinux` on a Lenovo Thinkpad T61.
Any help would be greatly appreciated.

Regards,
Daniel

**Comment by alexbaroni** [comment]
Hi check out if you have character like comma in the path, remove it and it
should work

Il giorno dom 4 nov 2018, 19:54 danieldoof <notifications@github.com> ha
scritto:

**Comment by danieldoof** [comment]
Okay I have removed all the characters that are not alphabet letters like `a-z` or whitespace between words in a test-folder.
Still not working.

Is opening a `request` the same as opening an `issue`?

Greetings,
Daniel

**Comment by alexbaroni** [comment]
Yes sorry issue not request... I'm bit tired...

Il giorno dom 4 nov 2018, 21:18 danieldoof <notifications@github.com> ha
scritto:
