### ISSUE TITLE
[Scraper] Incorrect IMDb ID

### ISSUE THREAD

**Issue by levander051** [Komet/MediaElch#471]
Hi, I've found out that many movies has incorrect imdb id written in nfo. For example instead ttxxxxxxx there is just random xxxx number. I don't know how it happened (I only use MediaElch, TMM and Emby) and I'm not going into it. What matters is that somehow that happened and I can't find a way to easily fix this, I can only tap one by one movie and then manually rescrape. MediaElch shows green icon when imdb id is filled so that doesn't help - in all these cases where incorrect id exists there is "tt" missing. If that could be recognised by MediaElch as id NOT imported would be of great help in this case and it would be more precise at same time.

**Comment by bugwelle** [comment]
I agree that this is indeed not the intended way to check for IMDb IDs.
I will look into this as soon as possible but it could take one or two weeks 😃

**Comment by bugwelle** [comment]
#522 will fix this. MediaElch now only shows the green ID icon if the format of the IMDb id matches `tt\d{7}`.
