### ISSUE TITLE
TV show list - Long titles get cut off

### ISSUE THREAD

**Issue by hirnsushi** [Komet/MediaElch#475]
MediaElch_linux_2.4.3-dev_2018-06-18_08-58_git-master-2501f19

Only happens for very long titles in combination with the default window size, maximized window not affected.
![grafik](https://user-images.githubusercontent.com/5706729/41546045-e56b4770-731c-11e8-8250-7e795c95f382.png)
vs. maximized
![grafik](https://user-images.githubusercontent.com/5706729/41546082-0045d574-731d-11e8-97ca-8a261b17b527.png)

**Comment by bugwelle** [comment]
I fixed this for episodes in #406 but forgot it for TV shows. Thanks for reporting. :smiley:

**Comment by bugwelle** [comment]
Could you please tell me what linux distro you use?
Because the icons should not be stretched that much. Seems there are issues that still need to be fixed in the AppImage version.

**Comment by hirnsushi** [comment]
I'm using Arch with Plasma 5.12.5. The icons look the same in my installed (old) version of Media Elch, so I didn't notice.
