### ISSUE TITLE
[Windows] Can't stream trailers | Unresolved error code

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#480]
When searching trailers, I can neither download nor watch trailers on windows. Works on linux.

**Comment by sharkbit** [comment]
I run on Windows 10, and have no issue with this.  What is the title of the movie?  if it is an older movie it might not be found on [HD-Trailers.net](http://www.hd-trailers.net).

Playing them woks as well as long as they are named exactly like the `movie-trailer.mkv` 
- I have a feature request to get any file in the Dir named `-trailer.ext` to show as a local trailer #479

**Comment by bugwelle** [comment]
Thanks for your reply. I tested it a week ago on Windows 7. Haven't looked into it since.
(I wasn't able to download trailers nor stream them. I haven't tested local trailers.)

**Steps to reproduce:**  
1. Select movie 
1. scrape it
1. Click "Download Trailer" button
1. Search for your trailer
1. Select e.g. "480p, Trailer"
1. Click play button.

This works on linux but didn't work on windows when I tested it.

**How it should look like:**

![screenshot_20180626_161338](https://user-images.githubusercontent.com/1667306/41918094-ea241f4a-795b-11e8-86ee-79d2c3d8a417.png)

**Comment by bugwelle** [comment]
I have to correct myself. Download works, but streaming does not:

`WARNING:  DirectShowPlayerService::doRender: Unresolved error code 0x80040218`

**Comment by bugwelle** [comment]
I've created a PR that shows better error messages. I'll try if streaming trailers works after installing e.g. VLC. If so, I'll add a note to our `README.md`.

**Comment by alexls74** [comment]
Streaming and downloading trailers are working on macOS.
But videos don't fit the frame:
![02](https://user-images.githubusercontent.com/12618414/41964602-c3c402e2-7a3d-11e8-9bed-7c25c126e499.png)
And some buttons glitch after downloading:
![01](https://user-images.githubusercontent.com/12618414/41964764-3ae18070-7a3e-11e8-80a9-c51c545b3999.png)

**Comment by bugwelle** [comment]
Thanks. I'll look into this soon :)
