### ISSUE TITLE
Filter: Wrong tooltip

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#506]
The filter seems to be buggy. See screenshot below:

![screenshot_20180708_123917](https://user-images.githubusercontent.com/1667306/42418975-f730e778-82ab-11e8-8fe3-5f69d0e11a6c.png)

Related to #504

**Comment by alexls74** [comment]
I can’t reproduce this. Everything looks good.
![2018-07-08 23 13 39](https://user-images.githubusercontent.com/12618414/42420174-f7bc65a6-8304-11e8-9341-0f94dcdb38bf.png)
![2018-07-08 23 14 01](https://user-images.githubusercontent.com/12618414/42420177-fda86686-8304-11e8-96b7-bc15ece66ec1.png)
macos 10.11.6 and 10.12.6

**Comment by bugwelle** [comment]
After the first keywords is highlighted (after it becomes a tag), the tooltip for the second one has the value of the previous one. I can reproduce this on every try. Tested for TV Shows and movies:

![screenshot_20180708_152913](https://user-images.githubusercontent.com/1667306/42420288-b2a66af2-82c3-11e8-8015-2bcaf544fbcd.png)

**Comment by bugwelle** [comment]
The issue was that each Filter (Title/Filename/IMDB ID) can only be applied once. There was a check missing whether the filter was already set. Furthermore it defaulted to adding a new title filter when pressing enter. This resulted in having the same pointer in the list of filters twice. When deleting a filter, the pointer was deleted and when one tried to access the first one, a segfault happened. I'll check if I can revert d1088c1a71742857368893b5f554570d38fc9960 without errors.
