### ISSUE TITLE
[FilterWidget] Broken filters

### ISSUE THREAD

**Issue by alexls74** [Komet/MediaElch#512]
Directors
![01](https://user-images.githubusercontent.com/12618414/42432737-789e83c2-838f-11e8-9443-c9a419bc9154.png)

Video codecs
![02](https://user-images.githubusercontent.com/12618414/42432743-7e8d8b84-838f-11e8-8676-bb8f9c4b77e5.png)

**Comment by bugwelle** [comment]
My bad, sorry. I refactored a lot of code and forgot to pass a second argument. Should be fixed by the latest commit.
