### ISSUE TITLE
[ui] TV Shows

### ISSUE THREAD

**Issue by alexls74** [Komet/MediaElch#514]
If the TV show has different sources, it looks like this:
![2018-07-11 8 01 36](https://user-images.githubusercontent.com/12618414/42551388-51d21312-851a-11e8-9ff0-5cf22702df3a.png)

Joining by ID?

**Comment by bugwelle** [comment]
You mean file sources? :)
I agree, we should join them.

**Comment by alexls74** [comment]
> You mean file sources? :)

yes of course

**Comment by alexls74** [comment]
There are too many problems to fix that (extra fan-arts merge etc.) :(

**Comment by bugwelle** [comment]
Indeed. I wonder how we should handle those issues. Both tvshow folders may already contain fanart, posters, etc.; Which do we use? Where to we save new posters? 
:/

**Comment by alexls74** [comment]
I think we should close this issue

**Comment by bugwelle** [comment]
mmhhh... I kinda don't want to close this but don't see any *good* solution to this either. We can reopen this issue if we find a good solution.
