### ISSUE TITLE
Some shows not found on The TVDB

### ISSUE THREAD

**Issue by weakfl** [Komet/MediaElch#528]
If you search for "Taboo" for example, the show with Tom Hardy (2017) is not found. Searching by the tvdb id instead of the title works (using dev build from 2018-07-11).

Might be related to #432

Btw: great to see so much progress, keep it up guys!

**Comment by bugwelle** [comment]
Can confirm this.

Website: https://www.thetvdb.com/series/taboo-2017 :heavy_check_mark:   
New API: https://api.thetvdb.com/search/series?name=Taboo :heavy_check_mark:  

```json
...
		{
			"aliases": [],
			"banner": "graphical/292157-g3.jpg",
			"firstAired": "2017-01-07",
			"id": 292157,
			"network": "BBC One",
			"overview": "James Keziah Delaney has...",
			"seriesName": "Taboo (2017)",
			"status": "Continuing"
		},
...
```

There is one major feature which the new API is missing (get all episode details in one API call). The beta API already has it. I'll need to implement some changes in PR #487 it we're ready to use the latest API when it's up :-)  
https://gitlab.thetvdb.com/site/thetvdb_api/issues/28

> Btw: great to see so much progress, keep it up guys!

Great to hear that :smiley:

**Comment by bugwelle** [comment]
I can't believe that it took me nearly 1.5 years...
The PR #487  is finally merged!

Please open new issues in case that are problems with the new API. :smiley:
