### ISSUE TITLE
[Mac] Preferences file, name changed

### ISSUE THREAD

**Issue by noyannus** [Komet/MediaElch#538]
The mac preferences file of the version from `MediaElch_macOS_2.4.3-dev_2018-07-24_18-16_git-master-7409f31.dmg` now sets the the name of the preferences file to `de.http:  mediaelch.MediaElch.plist`, so previous settings (in `com.kvibes.MediaElch.plist`) are not found.

**Comment by bugwelle** [comment]
Thank you very much for reporting this! This is a bug and needs to be changed.

@alexls74 I haven't looked into this and I won't have time for it in the next 2 weeks (as I'm on vacation). Could you have a look at this? :)

**Comment by alexls74** [comment]
> Could you have a look at this? :)

We’ve lost **OrganizationDomain** :)

**Comment by bugwelle** [comment]
Oh, so commit cba0b3252b49ffe2661a44862b7c729c757eb736 was at fault. Seems I've misunderstood what "OrganizationDomain" means. Thanks!
We can remove ` QCoreApplication::setOrganizationDomain(MediaElch::Constants::OrganizationDomain);`. It wasn't really necessary to begin with. 😃

**Comment by alexls74** [comment]
Ok. Updated.

**Comment by noyannus** [comment]
You guys are really fast. Chapeau!
