### ISSUE TITLE
Capitalize on movie titles when scraping

### ISSUE THREAD

**Issue by Serjudo** [Komet/MediaElch#542]
Unfortunately, each title is registered in a different way, sometimes in lower case, sometimes in upper case..... I think it would be very useful if, when scraping the film or series, the titles were capitalized.

**Comment by bugwelle** [comment]
You mean when loading movies and tv shows from your hard drive?
MediaElch uses the file's name. I'm not sure if it's better to capitalize each word than to use the filename. I'll mark this as a feature request.  :-)

**Comment by Serjudo** [comment]
I mean that Mediaelch puts the title as it is in IMDB, and this title does not always follow the same format. I think it would be very useful to be able to capitalize on the titles through a preference option.

**Comment by bugwelle** [comment]
Hi,

I'm currently going through some older feature requests.
AFAIK, most if not all scrapers have case-insensitive searches. Capitalizing them does not have any effect as far as I can see.

Do you have any example where this is not the case? If you have one, then I'm willing to capitalize movie and TV show names when scraping media items. :)

**Comment by ticao2** [comment]
In the case of Scraper on the TMDb, it may not be necessary.
This is because Capitalization follows the rules of each language.
If the original title is French, follow the French rules.
If the local title, in your language, is in Portuguese or English, follow the rules of your language.
In addition, the rules for each language are slightly different.
The most complex case is France. Capitalization rules are the most confusing and complex I have ever seen.
They even generate heated discussions among French users.
So, if this feature were to be implemented, I suggest that it be optional, perhaps enabled in advancedsettings.

**Comment by bugwelle** [comment]
Thanks, @ticao2 !

I agree with you and IMHO, MediaElch should not try too hard to make the filenames look more like titles.

@Serjudo If you can give me an example of a movie or TV show that is not properly scraped due to case-sensitivity, I may add such a feature. :)

**Comment by Serjudo** [comment]
Sorry for the delay in replying.

The request was for the titles to be saved capitalised in the .nfo file after scraping. Personally I have not detected any problem due to case-sensitivity when scraping.

**Comment by bugwelle** [comment]
> The request was for the titles to be saved capitalised in the .nfo file after scraping.

_After_ scraping? :)
Then the title should be scraped as well. We store the title returned by the scraper. There are movies that don't have a capitalized title where such a change would be wrong.

Or are there movies where scrapers return the wrong, i.e. non-capitalized, title?

**Comment by Serjudo** [comment]
Hello again,

The request is for the film title to be processed after scraping, and the film title to be capitalised and saved as such in the .nfo file.

**Comment by bugwelle** [comment]
Yes, I understood that part. :)

I'm just curios as to _why_ the movie title isn't capitalized. The scraper should already return the title in the correct way (which often means it is capitalized). And MediaElch stores the movie's title in the NFO. 😃 

Are there movies or scrapers where this is _not_ the case? If you could tell me a movie as an example, I may be able to investigate why it isn't capitalized in the NFO.
