### ISSUE TITLE
Chocolatey package now broken due to changes in downloadable product

### ISSUE THREAD

**Issue by sumo300** [Komet/MediaElch#544]
I have been maintaining a [Chocolatey](https://chocolatey.org) package for MediaElch for a little while.  However, the recent changes in the builds and removal of the 2.4.2 download from the main site have broken the package.  I have been unable to find an already compiled version to link to for the package.  I would love to transfer ownership of the Chocolatey package to you as well.  I was just maintaining it as it made installing it on a new system much easier.  Below is the link to the package.  Let me know if there is a way to fix this (need a link to an already compiled, downloadable copy that I can calculate a SHA256 hash on and I'll update the package.  If you are interested in taking over the project, just let me know and I'll add you as the owner and point you to the GitHub project that contains the files/code for it.

https://chocolatey.org/packages/MediaElch/2.4.2

**Comment by bugwelle** [comment]
Hello @sumo300 😃 
Thank you very much for opening this issue. I don't use Windows, so I've never heard of Chocolatey. But it looks interesting and may be worth supporting officially!
Version 2.4.2 has been removed from the official website for a few month now. The reason behind it is that MediaElch became unusable as too many scrapers were broken. The latest MediaElch version for windows can be downloaded from bintray.com: https://bintray.com/komet/MediaElch/MediaElch-win/2.4.3-dev_2018-08-08_11-56_git-master-1e9e0ed
Note that this is still a developer/nightly version so it may still contain bugs. But it works better than 2.4.2.

I'll come back to this issue when we'll release the next stable version. (I don't think an unstable version should be included in Chocolatey but I'm open to dicussion).

Regards,
Andre

PS: I'm sorry it took so long. I've been on vacation for the last two weeks :)

**Comment by bugwelle** [comment]
Hi,

thank you for updating the Chocolatey package. :-)
Just found https://github.com/sumo300/chocolatey-mediaelch

If you're willing to continue maintaining that package, I'll gladly notify you whenever a new MediaElch version is released. Also the package should not break in the future as we know host the ZIP files on GitHub :)
I'll update https://github.com/Komet/MediaElch/blob/master/docs/admin/release.md to contain instructions on how to do that.

Btw., would a `.msi` be useful to you? I'm thinking about creating a Windows installer using [Wix](https://wixtoolset.org/) (though I'm not familiar with Windows development at all).

**Comment by sumo300** [comment]
That'd be great.  As for msi, because of the way Chocolatey works, it's
really not necessary because it creates a command shim to the exe to easily
run it.  Only benefit I could see is that you can add a shortcut to the
start menu and desktop.  Your app runs as a portable app, so thats the only
benefit I can see.

**Comment by bugwelle** [comment]
Done in #748 :)

> Only benefit I could see is that you can add a shortcut to the start menu and desktop.

Do you have a bit more information about that? Sorry that I have to ask but I'm really a Windows noob and only develop on Linux and macOS :)

**Comment by bugwelle** [comment]
@sumo300 Oh and btw.: are your interested in moving your repository to https://github.com/mediaelch/ and being listed as the official maintainer of that package in MediaElch's documentation? :)

notify @Komet

**Comment by sumo300** [comment]
@bugwelle Sure.  What do we need to do to move it there?

**Comment by bugwelle** [comment]
In the repository's settings scroll down to "Danger Zone" and click "Transfer ownership". There you should be able to move the repository to `mediaelch`. @Komet then needs to re-add you as the repository's maintainer (if I remember correctly, you lose all privileges if a repo is moved to an organization). I can't do that as I don't have admin rights for that :)

**Comment by sumo300** [comment]
Got an error that stated I don't have permissions to create repositories on
mediaelch.

**Comment by bugwelle** [comment]
Interesting :/
@Komet Any ideas?

**Comment by sumo300** [comment]
Is there an organization created called mediaelch or do I just need to
transfer it to @Komet?

**Comment by bugwelle** [comment]
Oh, sorry, yes: @mediaelch :-)
It already contains a few repositories. It's a GitHub team. Currently only I and @Komet are members.

**Comment by Komet** [comment]
@sumo300 I've invited you to the @mediaelch organization.

**Comment by sumo300** [comment]
Repo moved!

**Comment by bugwelle** [comment]
https://github.com/mediaelch/chocolatey-mediaelch

Great! :)
Do you have write permissions? If not, @Komet may need to make you the repo's maintainer again.

**Comment by bugwelle** [comment]
Download instructions have been updated: https://mediaelch.github.io/mediaelch-doc/download.html

@sumo300 https://chocolatey.org/packages/MediaElch => "Package Source" URL needs to be updated. It's not broken because you moved the repository but I don't know if GitHub's redirects are persistent or temporary. :smiley:

**Comment by sumo300** [comment]
Awesome!  I updated the package source URL and it'll get updated in the
actual package for the next release you do.

**Comment by bugwelle** [comment]
Great! :)
I'll probably release a new version in September. Has been long enough since the last one :)
