### ISSUE TITLE
showTitle not supported in season folder template

### ISSUE THREAD

**Issue by Loki3000** [Komet/MediaElch#553]
When I try to rename series, I use following template:
![default](https://user-images.githubusercontent.com/12333165/44360845-c3c7da00-a4c4-11e8-85e8-b599a007ec2d.png)
Expected result:
folder structure Some series/Some series 01/Some series s01e01.avi
Actual result:
Some series/showTitle 01/Some series s01e01.avi
![default](https://user-images.githubusercontent.com/12333165/44361005-40f34f00-a4c5-11e8-9167-cb501d3de752.png)

\<showTitle\> tag not recognized in season folder template.

MediaElch 2.4.3-dev - Talax

Compiled with Qt version 5.10.1 (64 Release, GCC 7.3.0)
Using Qt version 5.10.1
System: Linux Mint 19 (x86_64-little_endian-lp64)

**Comment by bugwelle** [comment]
Can confirm. This is not the intended behavior. Will look at this tomorrow or at the weekend :-)
