### ISSUE TITLE
Not pulling information from IMDB

### ISSUE THREAD

**Issue by thunder3dan** [Komet/MediaElch#556]
Plot and Certification are not be pulling from IMDB.

**Comment by bugwelle** [comment]
Can confirm. Will fix this as soon as possible.

**Comment by bugwelle** [comment]
So, tested IMDb:

- [x] IMDb ID
- [ ] Title
- [ ] Tagline
- [ ] Rating
- [ ] Released
- [ ] Runtime
- [ ] Director
- [ ] Writer
- [ ] Certification
- [ ] Overview
- [ ] Poster
- [ ] Actors
- [ ] Genres
- [ ] Studios
- [ ] Countries
- [ ] Tags

That's all that is supported by IMDb.

Will upload a fix soon. :-)

**Comment by alexls74** [comment]
Hi,
Rating and Top 250 don’t work again :(
