### ISSUE TITLE
Adult DVD Empire does not return any search results

### ISSUE THREAD

**Issue by EdwinDijkshoorn** [Komet/MediaElch#565]
Adult DVD Empire does not return any search results.

**Comment by bugwelle** [comment]
Thanks for reporting. Will look into it as soon as possible :)

**Comment by bugwelle** [comment]
Fixed it. They slightly changed their website. :-)

**Comment by bugwelle** [comment]
Oh well,... I committed a wrong patch. Forgot a space. Will fix it soon :)
