### ISSUE TITLE
[Bintray] Error message: "Download Forbidden!"

### ISSUE THREAD

**Issue by 720720** [Komet/MediaElch#573]
https://dl.bintray.com/komet/MediaElch/MediaElch_win_2.4.3-dev_2018-08-30_16-18_git-master-30148a7.zip returns `Forbidden!`

**Comment by bugwelle** [comment]
Thanks for reporting this. I guess that @Komet cleared old downloads (because storage space is limited on bintray). I'll trigger a new build in a few minutes and will let you know if a new version is ready for downloading it. :-)

**Comment by bugwelle** [comment]
Yeah, just checked some logs:

```
Bintray response: 403 Forbidden. Account resource usage limits were met for 'komet'
```

**Comment by bugwelle** [comment]
It's working again :-)
