### ISSUE TITLE
wrong id for The Movie DB

### ISSUE THREAD

**Issue by XtradrY** [Komet/MediaElch#578]
with the latest update the id for TMDB is set to '**id**xxxxx' up till now the leading '**id**' was not part of the tag <tmdbid>**id**xxxxx</tmdbid>. The effect is that if I want to scrape with TMDB again, the id can not be found since it is then showing up as '**idid**xxxxx'
To be backwards compatible the '**id**' should be removed again from the tag.

**Comment by bugwelle** [comment]
Oooh. Sorry. Will be fixed asap.

**Comment by bugwelle** [comment]
e7e8f8f4b1adc71a940f2af11bd1beb4dc9a7652 is the commit responsible for it. #580 reverts the changes regarding `id`.
