### ISSUE TITLE
[Export] Add CSV export option

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#585]

**Comment by GarfieldS** [comment]
What is this? A request unrequited by a person who could fulfill it.

**Comment by bugwelle** [comment]
This is a feature request that someone (or maybe I myself) likely requested in the Kodi forum or via eMail. I opened this issue to keep track of it.

It's open for anyone to take and implement. I don't have time for this feature request and it doesn't have a high priority in my backlog. :-/

**Comment by GarfieldS** [comment]
Understood. Thanks for clarifying.

**Comment by bugwelle** [comment]
@GarfieldS With #1147 I've added a (for now hidden) CSV export dialog. It currently only supports movies, though.
Please let me know if that's something you would like to have for shows as well. :-)

**Comment by GarfieldS** [comment]
Thank you and yes I would like this for TV Shows as well. These are the main categories I use. I can't promise that someone else who uses "music" heavily won't come along and eventually request that as well :-). Thanks again.

**Comment by bugwelle** [comment]
Ok. :-)
Would you rather have me create one huge CSV with all episodes for all shows or one CSV for each show per default?

**Comment by GarfieldS** [comment]
One huge one is fine. I know enough about Excel to break it up if I need to. It's easier to start with one big one and make them separate than to take separate files and make them one. Thanks.

**Comment by bugwelle** [comment]
Current state:

All fields of all media types should be exportable. Missing:

- [ ] checkbox states are saved throughout restarts
- [ ] order is saved throughout restarts
