### ISSUE TITLE
[IMDb] Only loads character name if it has a link

### ISSUE THREAD

**Issue by tusharbhutt** [Komet/MediaElch#587]
Hello,

thanks for making this product, it's nice to have something that seems to be actively developed as I try to find a replacement for another program.  

I noticed the IMDB scraper pulls down the actors correctly, but only one actor has the character filled in; however this behaviour is inconsistent.  For example, in the movie "Wonder Woman", the major actors are located and Gal Gadot is listed as "Wonder Woman"

In the movie "Welcome Back" (imdbid: tt3159708), only one actor's role is filled in (Nana Petakar's character is listed correctly as "Uday Shankar Shetty").  I think that if the IMDB character name is a URL, only that character is scraped, if that helps any.

In both cases, the scraper does not grab the entire list of actors.  

Other scrapers such as TMDB do pull in the correct character names for the movie example I gave.

This is for the Windows file MediaElch_win_2.4.3-dev_2018-09-11_18-45_git-master-35ac397

Thank you for any advice you may have.

**Comment by bugwelle** [comment]
Thank you very much for this detailed bug report. It is indeed correct that the current version of the IMDb scraper requires the actor to have an IMDb page. I'll fix this ASAP.

I'll also add tests for "Welcome Back" :)

**Comment by bugwelle** [comment]
Will be fixed by #589
