### ISSUE TITLE
[Duplicate Movies] "Open folder" context menu

### ISSUE THREAD

**Issue by jordi-j** [Komet/MediaElch#591]
In my opinion, adding a context menu option to the results in the "Find duplicate movies" section will make it more usable. Opening the movie folder straight from the result will be really convenient, as it will allow users to quickly check the folder to verify if the movie is really a duplicate (and delete it if that's the case). At the moment you need to take note of the potential duplicate movie folder path, manually open an explorer window and navigate to the movie folder to take a decision.

**Comment by bugwelle** [comment]
![screenshot_20180919_191800](https://user-images.githubusercontent.com/1667306/45769727-bf681b80-bc40-11e8-8b88-30c2efd376a6.png)

Like this? :)
