### ISSUE TITLE
Rename files all in lowercase/upper case

### ISSUE THREAD

**Issue by tanrak** [Komet/MediaElch#592]
Only a little feature request. It would be nice if we can rename files all in lower- or uper case. For logical reasons with a new placeholder in the rename window.

**Comment by bugwelle** [comment]
Hi,

great idea!

I'll merge this issue with #436 because it's an general improvement.

Just adding new tags would make the renamer way to complicated (too many tags, etc). We have to invent something new... a better renamer. So, I'll merge this with #436 :smiley: 

Regards,
Andre
