### ISSUE TITLE
TVSeries Season Poster not shown even if there are posters for the show

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#600]
When scraping a poster for a tv show, 
if in tvdb there is no poster for Season 1 but there are available posters for the Series, when selecting Season 1 no poster is shown.

This does not occur for Fanart , (fanart has the proper behaviour)
if in tvdb there is no fanart for Season 1 but there are available fanarts for the Series, when selecting Season 1 all fanart of the show are displayed.

Try Dragon Prince Season 1 and you will understand what i am saying (try scraping from tvdb poster and fanart)

**Comment by bugwelle** [comment]
Thank you very much for reporting this! :smiley: 

I'll try to reproduce this in the next few days. It's inconsistent behavior which we should try to avoid.

**Comment by bugwelle** [comment]
Ok, so my setup is:

```
Dragon Prince
├── banner.jpg
├── extrafanart
│   ├── fanart1.jpg
│   ├── fanart2.jpg
│   └── fanart3.jpg
├── fanart.jpg
├── poster.jpg
├── Season 01
│   └── S01E01.mov
├── Season 02
│   └── S02E01.mov
└── tvshow.nfo
```

I loaded information about the series and even some extra fanart. Poster, Fanart and Banner were loaded. I then click on "Season 01" but no images are shown (neither fanart nor poster).

So no images are shown as no season images are available. I'd say this is expected behavior.
Could you please elaborate on your issue? :-)

**Comment by nkatsidis** [comment]
Agreed no poster images are shown because no season images are available..
BUT,,, there are TVshow poster images that are availabe and i think that they should be shown also :)
in fanart, altough there are no season 1 fanart available the tvshow fanart is shown.

**Comment by bugwelle** [comment]
Hi,

I'm currently going through some old issues (that aren't feature requests). First of all: sorry that I didn't answer earlier, I forgot about this issue.

I think I misunderstood your issue. I thought that no posters were loaded and that this was a bug. However, it's more a feature request.

#953 fixes this issue. MediaElch will now also load TV show posters when searching for a season one.

**Comment by nkatsidis** [comment]
PROOOOOO :)

Στις Σάβ, 11 Απρ 2020 στις 2:13 μ.μ., ο/η Andre Meyering <
notifications@github.com> έγραψε:
