### ISSUE TITLE
I can't start the program

### ISSUE THREAD

**Issue by riccardoprandini01** [Komet/MediaElch#601]
```sh
sudo ./MediaElch_linux_2.4.3-dev_2018-09-24_19-37_git-master-63e7d75.AppImage
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[MediaElch] DEBUG:    Loading advanced settings...
[MediaElch] DEBUG:    No advanced settings found!
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered, enabled= false
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    MediaElch version "2.4.3-dev" starting up
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered

(gst-plugin-scanner:19351): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstpng.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstpng.so: undefined symbol: gst_element_class_add_static_pad_template

[...] more gestreamer warnings

(MediaElch:19320): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

[...] more gestreamer warnings

(MediaElch:19320): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Now processing files
[MediaElch] WARNING:  Unrecognized OpenGL version
[MediaElch] WARNING:  Unrecognized OpenGL version
```

**Comment by babbomaria** [comment]
So I 
`sudo apt-get install gstreamer-1.0`

**Comment by babbomaria** [comment]
Now error are:
`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[MediaElch] DEBUG:    Loading advanced settings...
[MediaElch] DEBUG:    No advanced settings found!
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered, enabled= false
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    MediaElch version "2.4.3-dev" starting up
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered

(MediaElch:19981): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_object_ref: assertion 'object != NULL' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_bin_add_many: assertion 'GST_IS_ELEMENT (element_1)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_bin_remove: assertion 'GST_IS_ELEMENT (element)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed
[MediaElch] WARNING:  Linking video output element failed

(MediaElch:19981): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_object_ref: assertion 'object != NULL' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_bin_add_many: assertion 'GST_IS_ELEMENT (element_1)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(MediaElch:19981): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Entered
[MediaElch] DEBUG:    Now processing files
[MediaElch] WARNING:  Unrecognized OpenGL version
[MediaElch] WARNING:  Unrecognized OpenGL version
`

**Comment by bugwelle** [comment]
Hello @babbomaria 

what linux distribution are you running? 
The gestreamer warnings are known but can mostly be ignored. What is interesting is `libGL error: unable to load driver: r600_dri.so`as well as `[MediaElch] WARNING:  Unrecognized OpenGL version`. I need your distribution name and version to run some tests (e.g. "Ubuntu 16.04, all updates installed").


Regards,
Andre

**Comment by babbomaria** [comment]
Hi thanks for fast reply.

Distro is Crunch Bang Plus Plus  https://www.crunchbangplusplus.org
It's a Debian distro. 



```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
```




I have also backports


`Linux Host001 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.16-2~bpo9+1 (2018-06-26) x86_64 GNU/Linux
`

**Comment by bugwelle** [comment]
Hi, 

thanks for the detailed information. I've never heard of the distribution. I'll try to install it and will test MediaElch :)
I'll come back to you when I've got results.

Regards,
Andre

**Comment by bugwelle** [comment]
Hi,

the latest AppImage has updated quite a lot. I've tried it on some distributions where it previously didn't work. Could you give it a try? :-)
