### ISSUE TITLE
(Un)check all button does not uncheck in scraper dialog

### ISSUE THREAD

**Issue by tusharbhutt** [Komet/MediaElch#603]
As per subject lines... used to work, now it doesn't as of the Sep 21 update for the windows version.  The toggle works to add all the infos to load, but not the other way.  Restarting did not help.

**Comment by bugwelle** [comment]
This was fixed yesterday in #598
See commit ebe2c415ad8b89eb04a6c57a6125640f17338254

Version 2.4.3-dev_2018-09-29_17-45_git-master-b419422 fixes this issue. :-)
