### ISSUE TITLE
Runtime Flag is not saving

### ISSUE THREAD

**Issue by Rychem28** [Komet/MediaElch#604]
NFO file is not saving the runtime tag when manually adding or scraping run time for movies and then saving. Always says 0 min and tag is not listed in the nfo file.

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this. I can't reproduce this behavior, yet.
I need more information, could you please tell us:

 - What operating system are you on? (Windows, macOS, Ubuntu,...)
 - What MediaElch version are you using? (When did you download it?)
 - What movies are affected?

Regards,
Andre

**Comment by Rychem28** [comment]
I am using Windows 7, and used the dev build that was available one day ago (MediaElch_win_2.4.3-dev_2018-09-29_17-43_git-master-b419422) . All movies were effected.

I am using Kodi v18 and had exported the nfo files from there. Reading these nfo files in the above build yielded a runtime of 0 minutes in MediaElch. After manually editing the runtime and saving the entire runtime tag is removed from the nfo file. 

I am going to try to do a fresh install of MediaElch as I had installed the dev build over another earlier build.

Cheers,

**Comment by bugwelle** [comment]
Can reproduce. When I use "Save" (single movie) it is saved. If I use "Save all", runtime is gone..

**Comment by bugwelle** [comment]
Oh, nevermind. This is what happens: First time changing the runtime and saving it works, second time it fails.

**Comment by bugwelle** [comment]
This happens if "Automatically load and save stream details from file" is enabled. But if MediaElch cannot detect the duration then it should not change it.
