### ISSUE TITLE
[Installation] Not working on Linux Mint Debian (lmde3)

### ISSUE THREAD

**Issue by Degeurige** [Komet/MediaElch#616]
After downloading your AppImage and making it executable, running it just opens a with a scaled version of my desktop-background and nothing in it, am i missing something?

Edit by @bugwelle: Typos

**Comment by bugwelle** [comment]
Hi, 

thanks for reporting this. On some distributions, the AppImage does not work. I'll try to reproduce this and will come back to again 😃

**Comment by Degeurige** [comment]
thanks for the info, today i am going to reinstall linux mint 19 again in ln ldme3 also problems with administrator rights. will let you now if in 19 Tara all is ok. Tara is ubuntu based instead of debian.

**Comment by Degeurige** [comment]
reinstall done . Now working correctly in Linux Mint 19 Tara. LDME3 was the problem (still to buggy) sorry to bother you guys for this.
Thanks for the Hint

**Comment by bugwelle** [comment]
Seems that there's a OpenGL version mismatch.
