### ISSUE TITLE
MediaElch not responding

### ISSUE THREAD

**Issue by BlueBunnyNation** [Komet/MediaElch#619]
MediaElch  2.4.3-dev-Talax
Mac OS Mojave 10.14

In  mediaElch tab, when I right click in the left column, and select load information or Open Movie Folder, nothing happens. after looking at the FAQ, it would seem that something should happen.
![image](https://user-images.githubusercontent.com/24627161/48632205-537b0880-e98e-11e8-8dcf-fa62f3a7171d.png)

**Comment by BlueBunnyNation** [comment]
your update fixed it, thanks!

**Comment by bugwelle** [comment]
That popup shouldn't even appear :o
I'm surprised that the latest version fixed this as I've not done anything related to that issue in the last two weeks. I'll look into it :)

Thanks for reporting. :+1:
