### ISSUE TITLE
Build error using Qt 5.12.0: Missing QtQuickWidgets/QQuickWidget

### ISSUE THREAD

**Issue by alexls74** [Komet/MediaElch#628]
I've tried to build with Qt 5.12.0
Got this error:
`No rule to make target QtQuickWidgets/QQuickWidget, needed by ui_ImageWidget.h`

Any idea what that might be?

**Comment by bugwelle** [comment]
How did you install Qt 5.12? (Qt Installer or Homebrew?)

Qt 5.12 marks QtQuickControls 1 as deprecated. You may need to install them separately (i.e. select it in the Qt Maintenance tool). See https://wiki.qt.io/New_Features_in_Qt_5.12
Haven't tested in on Mac, yet. So I'm not sure :-)

**Comment by bugwelle** [comment]
Can reproduce this issue. Will look into it. :)

**Comment by bugwelle** [comment]
CI build is no failing as well. :/

**Comment by bugwelle** [comment]
Works again :-)
