### ISSUE TITLE
Filter by Media Status

### ISSUE THREAD

**Issue by smilerz** [Komet/MediaElch#634]
Filtering TVs and Movies by missing metadata elements & artwork types would be useful.
Also, automatically scraping for extra artwork would be useful.

**Comment by ticao2** [comment]
**Filter**.  
My interface is in pt-BR. But it should work with en-EN.  
Enter in the Filter field the word **No** and a **Space**.  
There should be a Dropdow list with all the possibilities.  
As I recall, there were more than 20.

**Comment by bugwelle** [comment]
Great! I'll close this issue then. If you have any further questions or feature requests, feel free to open this issue again or create a new one :-)
