### ISSUE TITLE
Movie set fanart

### ISSUE THREAD

**Issue by IvanGavrilenko** [Komet/MediaElch#638]
Movie set fanart is not downloaded not from fanart.tv not from themoviedb.org - on the "Set view" I see i.e. "Harry Potter collection" set, but when I press a poster or fanart button to download image a search table with "not fond media" arrises. While if I directly search "Harry Potter collection" on the themoviedb.org I receive page [https://themoviedb.org/search?query=Harry%20potter%20collection](https://themoviedb.org/search?query=Harry%20potter%20collection) which shows that it found 1 item in "Colletions" [https://themoviedb.org/collection/1241](https://themoviedb.org/collection/1241).

And can you add some sort of tick that the file is written to every movie in the collection? As according to [kodi wiki](https://kodi.wiki/view/Movie_artwork#Movieset_Fanart) if the single dirrectory contains more than one file the file naming should be <originalFileName>-movieset-fanart.jpg or if files are organized singlefolder-singlemovie it might be nice to have complete set of artwork for movie in the folder.

**Comment by mason-xx** [comment]
+1

**Comment by bugwelle** [comment]
Hi there :-)
I'm currently on Christmas vacation and can't check and fix this. I'll have time for this next week 😃 
If MediaElch can't find any fanart, then this is a high priority bug. Thanks for reporting!

Regards,
Andre
