### ISSUE TITLE
SOLVED - File Dialog to choose any Art not Opening

### ISSUE THREAD

**Issue by dzogas** [Komet/MediaElch#643]
I am on Windows 10 x64 - 1809
When I choose to add any kind of Art the File Dialog is not Opening.
If I press Esc the program works again. It looks like the File Dialog is opened but it just does not show.

**Comment by dzogas** [comment]
Actually I have a dual monitor setup but the solution you proposed did not work unfortunately.

**Comment by dzogas** [comment]
When I leave the mouse pointer on the taskbar preview window it shows the first attached image.
I dont know if this is normal behaviour but this happens shen only the main window is open.



![mediaelch problem 1](https://user-images.githubusercontent.com/26818516/50927421-6971ea80-1460-11e9-83b8-6ea69fbdffdf.jpg)

**Comment by bugwelle** [comment]
Hi!
I still think that the window is just of screen. :/
Could you try and open MediaElch's configuration (see https://mediaelch.github.io/mediaelch-doc/faq.html#where-are-mediaelchs-settings-stored ; on windows it's in the registry, so you need to execute `regedit`). There's a category/key `[ImageDialog]` with a `Pos` sub-key. Could you reset that to e.g. `@Point(0 0)`?

![screenshot_20190112_124740](https://user-images.githubusercontent.com/1667306/51072853-487be600-1668-11e9-866a-a848aa0330f4.png)


As this has happened to other users as well, I think we should add some kind of "start with defaults" option. 

Regards,
Andre

**Comment by dzogas** [comment]
Wow!!! Pos was @Point(-3488 0) !!!!

This has solved it!!

Thank you very much bugwelle!!!

**Comment by bugwelle** [comment]
No problem :)
This has happened to other users as well. I'll at least add an entry to MediaElch's FAQ :-)
