### ISSUE TITLE
Multi threading support | Better performance

### ISSUE THREAD

**Issue by Seluj78** [Komet/MediaElch#644]
Would it be possible to have multithreading support to speed up the scraping process?

Love the software otherwise !

**Comment by Seluj78** [comment]
Amazing ! Thanks for the answer, love from France and keep up the good work ! 😍 🇫🇷

**Comment by bugwelle** [comment]
Hi,

the movie file searcher was improved a bit. On my test-directory I got down from 5.8s to 1.3s. :-)

See #1230
