### ISSUE TITLE
Number bubble not scaling

### ISSUE THREAD

**Issue by Seluj78** [Komet/MediaElch#645]
<img width="62" alt="screenshot 2019-01-08 at 09 53 56" src="https://user-images.githubusercontent.com/4641317/50819785-60333180-132b-11e9-9d3c-5e650077d0f0.png">

MacOS `10.14.2`

MediaElch `2.4.3-dev`

**Comment by Seluj78** [comment]
Glad I found something then 😛 I'm planning on using MediaElch for my movie and tv show library + maybe music if it works well along with itunes. I'll make sure i'll report all the bugs I can find !

**Comment by bugwelle** [comment]
Glad to hear that! Just "a warning": MediaElch does not encode any information into any music files (e.g. mp3; http://id3.org/ID3v1). We only add an `.nfo` file. :)

**Comment by Seluj78** [comment]
Yeah, And i dont think Itunes read `.nfo` files which kinda sucks :/ Any plan on adding some `id3` tag writing in the future ?

**Comment by bugwelle** [comment]
Not in the near future. There are too many tasks on my todo list that have higher priority (like better C++ code, multithreading, better Kodi integration, new scraper APIs and some of the many [feature requests](https://github.com/Komet/MediaElch/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22)) :-)

I'd recommend another tool for Id3 tags at the moment.
