### ISSUE TITLE
Translation - French

### ISSUE THREAD

**Issue by Seluj78** [Komet/MediaElch#646]
Would you like a French localisation of MediaElch to French ?

**Comment by bugwelle** [comment]
Hi,

yes! MediaElch is already available in French, though some strings have not been translated, yet.
We use Transifex to translate MediaElch. You can find it here: https://www.transifex.com/komet/mediaelch/viewstrings/#fr/main/157231155 :-)

See: https://mediaelch.github.io/mediaelch-doc/contributing/translations.html

Regards,
Andre

**Comment by Seluj78** [comment]
Thanks a lot! Will see what I can do 😁

**Comment by Seluj78** [comment]
I've translated all I could, but now they need to be reviewed :/
