### ISSUE TITLE
problems with quotes in title

### ISSUE THREAD

**Issue by Sir2B** [Komet/MediaElch#650]
I have a series with quotes in the episode title. 
When I get the information from thetvdb, all information behind the quotes is gone.

**Comment by bugwelle** [comment]
Hi,
thanks for reporting this issue. Could you provide us with an example? :)

**Comment by Sir2B** [comment]
I'm from Germany, so my example is a german tv show. So first you have to change the language of "The TV DB" in MediaElch to "Deutsch" (German).
Then create a folder with the series name "Die Rosenheim-Cops", create a file with the name "Die Rosenheim-Cops - S18E14".
The title of the show is 'Beim dritten "Om" bist du tot'. 
When MediaElch loads the information the title is only 'Beim dritten '.

Hopefully this example helps you.

**Comment by bugwelle** [comment]
Hi there,

is this still an issue? I'll close this issue due to inactivity and because I'm not able to reproduce this. 

Feel free to reopen this issue :-)
