### ISSUE TITLE
Issue with the & charchter

### ISSUE THREAD

**Issue by hewwra** [Komet/MediaElch#651]
If I scrape the movie Shrek the Third from themoviedb it returns the following for the plot:

The King of Far Far Away has died and Shrek and Fiona are to become King & amp; Queen. However, Shrek wants to return to his cozy swamp and live in peace and quiet, so when he finds out there is another heir to the throne, they set off to bring him back to rule the kingdom.

It should not say "King & amp; Queen".
It should say "King & Queen"

I've checked in Kodi and the & amp; is there as well so Kodi does not automatically fix this problem.
Note: I've added a space between & and amp;  so that the problem is properly displayed on this website.

**Comment by bugwelle** [comment]
Thanks for reporting. Seems to be an encoding issue. :)

**Comment by hewwra** [comment]
The & amp; appears everywhere, in titles, actors (roles), plots and even in the youtube trailer. 
However Kodi seems fine with it except when it appears in the plot.

**Comment by bugwelle** [comment]
Can confirm. `&amp;amp;` appears in the nfo file. Should be `&amp;`...
