### ISSUE TITLE
[Episode Guide URL] Request for modified line to contact the tvdb api

### ISSUE THREAD

**Issue by internetR** [Komet/MediaElch#652]
At the moment Kodi can't find new tv-show episodes based on the mediaelch nfo files.

The current episodeguide parameter is not working anymore:

` <episodeguide>`
`       <url>https://thetvdb.com/api/A0BB9A0F6762942B/series/108611/all/en.zip</url>`
`    </episodeguide>`
 
But if you replace the line by the one below, which includes te tvdb ID of the tv-show the problem is solved, in this example tvdbid **263365** is used
 

` <episodeguide>`
`  <url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:263365}|Content-Type=application/json</url> `
` </episodeguide>`

Kodi is also using this code.  Is this something to implemented in a newer mediaelch version?

Internetter

**Comment by bugwelle** [comment]
I had a quick look at it. MediaElch itself does not create an `<episodeguide>` tag on its own. It has to exist in the `tvshow.nfo` file to begin with and will be read.

The documentation for it is very sparse and I don't know whether I want to implement it. However, we shouldn't write old-style episodeguide URLs. I'll add a workaround where we simply don't write the episodeguide URL if it's an old style one. And I'll also add `post="yes"` and `cache="auth.json"` as attributes (only for Kodi v17 and above)

I may add that feature in the future. But I have to think about what API key we should store in the URL. Should we take the default one from the example?

```xml
<url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:80379}|Content-Type=application/json</url>
```

Relevant URLs:
 - https://kodi.wiki/view/NFO_files/TV_shows#episodeguide_URL
 - https://forum.kodi.tv/showthread.php?tid=323588

**Comment by bugwelle** [comment]
PR is merged, tests are updated. `<episodeguide>` should now be compatible with Kodi v17. Again, it will only be stored if it already exists.

**Comment by internetR** [comment]
> I had a quick look at it. MediaElch itself does not create an `<episodeguide>` tag on its own. It has to exist in the `tvshow.nfo` file to begin with and will be read.
> 
> The documentation for it is very sparse and I don't know whether I want to implement it. However, we shouldn't write old-style episodeguide URLs. I'll add a workaround where we simply don't write the episodeguide URL if it's an old style one. And I'll also add `post="yes"` and `cache="auth.json"` as attributes (only for Kodi v17 and above)
> 
> I may add that feature in the future. But I have to think about what API key we should store in the URL. Should we take the default one from the example?
> 
> ```
> <url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:80379}|Content-Type=application/json</url>
> ```
> 
> Relevant URLs:
> 
> * https://kodi.wiki/view/NFO_files/TV_shows#episodeguide_URL
> * https://forum.kodi.tv/showthread.php?tid=323588

I did some research, Tinymediamanager 3.05 also uses the default link as mentioned. I used an example below with Doctor Who (2005)
```
  <episodeguide>
    <url cache="auth.json" post="yes">https://api.thetvdb.com/login?{"apikey":"439DFEBA9D3059C6","id":78804}|Content-Type=application/json</url>
  </episodeguide>
  <id>78804</id>
```
So to quote a good tv-show "This is the Way"

**Comment by bugwelle** [comment]
Ok, thanks. In that case I'll add it to MediaElch as well :)

**Comment by bugwelle** [comment]
For reference: https://github.com/Komet/MediaElch/issues/888

https://github.com/Komet/MediaElch/pull/898 will fix this issue and MediaElch will then always write TheTvDb episode guide URLs.
