### ISSUE TITLE
pointer cursor always horizontal resize

### ISSUE THREAD

**Issue by atomGit** [Komet/MediaElch#659]
Manjaro 18.0.2 KDE/Plasma
MediaElch 2.6.0

after a first install of ME from the repo, i see the pointer/mouse cursor is stuck on the horizontal resize cursor for virtually the entire main interface - exceptions are the 'donate' label (hand), filter (I-beam), and the 'new', 'name', etc. buttons in the bottom left of the UI (hand)

this occurs with each cursor theme i tested, including the defaults packaged with Manjaro

**add info:**

i noticed this happens only after the cursor is moved over one of the resizable panels where it changes to the horiz. resize cursor - from then on the cursor never changes back

**Comment by atomGit** [comment]
all 3 panels on the main UI - if i move the cursor across either the right or left edge of the center panel (where media info is displayed), it becomes a h-resize cursor for ever more :)

in other words, the letf/right panels are re-sizable horizontally (drag the divider to resize) - if the cursor moves over the resize area, it changes to a h-resize cursor as expected, but then never change back

to reproduce, just move the cursor over one of the h-resize areas of either the left or right panel - you need not do anything special - just move the cursor around

i'm running Manjaro 18, KDE/Plasma with the Breeze dark theme and Adwaita dark GTK theme, however changing themes has no effect (and ME doesn't seem to use the OS themes anyway)

**Comment by bugwelle** [comment]
Was able to reproduce this. Don't know how, yet (happened "by accident")

**Comment by atomGit** [comment]
it's interesting that you have to work to reproduce it - in my case it happens every time i mouse over the left/right edges of the center panel

i suspect it may have something to do with a combination of whatever you're using to build the GUI and the resources available in the KDE version of Manjaro - for example, i set a dark theme for my workspace and GTK, but ME appears to use its own theme which had a white background

**Comment by bugwelle** [comment]
It only happens if I build MediaElch with the system's native Qt version. That happens rarely as I build MediaElch with  Qt 5.12 or later most of the time...
It's definitely reproducible. I only have do hover over the resize area in the Movie view and it's stuck.

My System: Kubuntu 18.04

**Comment by bugwelle** [comment]
> ME appears to use its own theme which had a white background
Yes. The UI is white. But "normal" widgets like the ones in MediaElch's settings use the system's ui. :)

**Comment by bugwelle** [comment]
Found  the culprit btw. It really seems to be our stylesheet that causes this. This means this issue exists since commit 15275ae014dd6214d7107aa8219c3f0ac08ae9aa (2018-04-20) and nobody has reported it, yet. Thank you very much! :-)

**Comment by atomGit** [comment]
glad you found the cause!
