### ISSUE TITLE
[Renamer] How to rename folders

### ISSUE THREAD

**Issue by atomGit** [Komet/MediaElch#662]
[Renaming files and directories](https://mediaelch.github.io/mediaelch-doc/renaming.html) doesn't seem to offer what i'm looking for

when i started organizing the library, i didn't have years in the file name and all video files were in one folder

i used a script to make folders for each file and move the file into the folders (be nice if ME could do this)

this left me with a folder name same as the file name, absent the year

after tagging the files i had the year, so i tried to rename the folders with 
`<title> (<year>)`
ME says 'Finished', but nothing happens

the drive is an NFS export on an Asus router - permissions, UIDs and GIDs are all set properly, i believe - not sure - i can access and write fine from my PC on the LAN

**Comment by bugwelle** [comment]
Hi there,

thanks for opening this issue. 
MediaElch should rename folders if "Sep. Folders" is enabled for each movie folder in MediaElch's settings. :-)


Regards,
Andre

**Comment by atomGit** [comment]
separate folders was enabled in the settings, but renaming didn't work

i suspect this had something to do with the NFS export and the way i was mounting it or something - i just tried renaming the folders again and it worked as expected

thanks

**Comment by bugwelle** [comment]
Oh, ok. Thanks for coming back to us :-)

**Comment by ticao2** [comment]
> i used a script to make folders for each file and move the file into the folders (be nice if ME could do this)

MediaElch has been doing this for a long time.
See this Komet explanation: https://github.com/Komet/MediaElch/issues/319
