### ISSUE TITLE
Missing tag for movie posters in NFOs generated by MediaElch

### ISSUE THREAD

**Issue by terzag** [Komet/MediaElch#665]
The thumb nodes in NFOs currently generated by MediaElch for movie posters have this syntax:

`<thumb preview="http://image.tmdb.org/t/p/w342/xxxx.jpg">http://image.tmdb.org/t/p/original/xxxx.jpg</thumb>`

According to [the Kodi wiki](https://kodi.wiki/view/NFO_files/Movies#Sample_Movie_nfo_File), the nodes for a movie poster should have an aspect tag alongside the preview one, like this:

`<thumb aspect="poster" preview="http://image.tmdb.org/t/p/w342/xxxx.jpg">http://image.tmdb.org/t/p/original/xxxx.jpg</thumb>`

This is only for posters, the fanart nodes don't seem to need that tag.

It seems that this triggers issues with Kodi 18, as it won't download the movie poster when that tag is missing in the NFO. For some reason, it worked fine with Kodi 17 even though the specs already required it.

**Comment by bugwelle** [comment]
Hi,

thanks for reporting. :-)
Related to #516


Regards,
Andre
