### ISSUE TITLE
MovieDb Scraper changing default language means no more results

### ISSUE THREAD

**Issue by moviefan65** [Komet/MediaElch#666]
Subject: Linux-Version of Media-Elch
Hello,
changing the default language for the Movie DB Scraper to e.g. german results in getting no more results. 
![grafik](https://user-images.githubusercontent.com/47474461/52519787-0c38a700-2c61-11e9-98aa-6bbc615029f6.png)
It also doesn't change the language within the search dialog - here it's always english.
![grafik](https://user-images.githubusercontent.com/47474461/52519798-2c686600-2c61-11e9-9127-015b01de1809.png)
But in this combination, you don't get any results anymore, no matter, if you switch the language in this dialog. You have to set the default language back to english, save and restart Media-Elch to get results again. And you have to change the language for each search if you need results other then english. Tested with the current Linux-Version 2.6.1-dev.

I tested this also with the older Windows-Version. Here it works like suggested.

**Comment by bugwelle** [comment]
Oh. Thank you very much for finding and reporting this issue! :smile:

**Comment by bugwelle** [comment]
Sorry, the dev version was broken. No settings were loaded. Should be fixed with the next nightly :)
