### ISSUE TITLE
[ui] Movies

### ISSUE THREAD

**Issue by alexls74** [Komet/MediaElch#668]
A small ui bug.

2.6.0
![2019-02-17 9 40 55](https://user-images.githubusercontent.com/12618414/52907135-b5f1e680-32a6-11e9-80ac-661933165275.png)
2.6.1
![2019-02-17 9 40 36](https://user-images.githubusercontent.com/12618414/52907138-bdb18b00-32a6-11e9-999a-7aa7053df71b.png)

**Comment by alexls74** [comment]
css QTreeView:: item {background-color: #ffffff;} overwrites the entire background to white (losing alternatingRowColors)

**Comment by bugwelle** [comment]
@alexls74 Yes. Oh boy... Didn't think about that one. `alternate-background-color` also doesn't exit on `QTreeView::item`.

**Comment by alexls74** [comment]
One more thing. Changing "%n movies" to "%n movie(s)" (and some other) caused this not to be translated. Could you update the language files?

**Comment by bugwelle** [comment]
Yes, I've updated them already on Transifex. Will push them to this repository soon :)
