### ISSUE TITLE
[Windows] Not retaining window size and placement/position

### ISSUE THREAD

**Issue by lynxstrike** [Komet/MediaElch#679]
Running portable version.
Just tried the new version for Windows 10 and for me, it's not keeping the size and placement.
It's a little annoying tho have to reconfigure this parameters each time I lunch the program.

It would be really great if you could look into it...

Thanks anyway for keeping this great program alive, free and feature rich...

**Comment by bugwelle** [comment]
Strange...
Thanks for reporting! :smiley: 

Btw. there's an issue for the "old" windows style: #678

**Comment by lynxstrike** [comment]
The new look is a welcome change. It's fresh and modern. For my part, I liked it.
The configuration windows work ok and with the new look.

The windows does not keep it's size and placement its the windows in which MediaElch works: the main program window.  

This is a screenshot of the window program which I choose to work in:
[https://imgur.com/pm7bUTm](url)

When I close the program, and then relaunch it, it reverts to it's original form and position:
[https://imgur.com/kFLPZRk](url)


Hope this helps...

**Comment by bugwelle** [comment]
Thanks :)

**Comment by ticao2** [comment]
In the **MediaElch.ini** file there are 2 parameters:  
**SettingsWindowSize=@Size(977 625)**  
**SettingsWindowPosition=@Point(470 176)**  
I remembered that in the past these parameters could be defined using 3 different parameters:  
**MainWindowSize=@Size(1296 729)**  
**MainWindowPosition=@Point(310 93)**  
**MainWindowMaximized=false**  
I used those old ones and it worked.  

I take the opportunity to ask if it is possible to define in the file **MediaElch.ini** these parameters for the **Image Preview** window.  
I would like to set a height that fits a **poster** of **500 x 750**, and a width that fits a **fanart** of **720 x 1280**.
It fits an image with **height 750** and **width 1280**.

**Comment by bugwelle** [comment]
Bug has been around since 93e2bdb7f19be7c419c76f88bc5e46ab172b3134 (2018-09-23). Will investigate :)

**Comment by bugwelle** [comment]
Will be fixed in #682 

@ticao2 Hi! The preview's size is set at https://github.com/Komet/MediaElch/blob/master/src/globals/ImagePreviewDialog.cpp#L71
Its height is set to its parent height minus 50px and its width is set to the parent window's width minus 100px (with a maximum of 1200px). I'll look what I can do or what would be best :)
