### ISSUE TITLE
Movie: Add "Go to IMDb/TMDb" buttons + TMDB filters

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#684]
Just a wish.
Assign to the TMDb ID the same features as the IMDB ID.
1 Be displayed on movie page
2 Can filter with **no TBDb ID**

And, perhaps, put a button next to each one that, when clicked, takes us to the Site.

**Comment by bugwelle** [comment]
At first I thought this was a bug and that one id was wrong :smiley: 

Thanks for this feature request :)
Great to here from you again, @ticao2 

I like your idea for the button :+1:

**Comment by bugwelle** [comment]
@ticao2 Will be implemented by #1022

**Comment by ticao2** [comment]
It seems that users are never satisfied, is it?
But in fact, ideas come to mind, and we only suggest implementation.
As my idea is related to this implementation, I will post here.
But if you prefer I can open a new topic.

**Proposal**
Along the same lines as the IMDB and TMDb buttons, add a button for **OpenSubtitles**.
Using the **IMDB ID** as **Query**.
https://www.opensubtitles.org/pb/search/sublanguageid-pob/imdbid-tt0062622
This Request is for the Portuguese interface and Portuguese subtitle language of Brazil.
It might be better to be without specifying language for anything.
https://www.opensubtitles.org/en/search/sublanguageid-all/imdbid-tt0062622

I have no idea if it is the most used subtitle font by everyone.
But if it is, it may be interesting to incorporate.
As the subject is fresh in your head, it may be easier. :-)

PS: I was getting worried about your absences.
I hope you did well on your college exams.

**Comment by bugwelle** [comment]
Interesting. I would prefer a context menu entry if we add more such quick-links. 😃 
Could you open another issue for this so that I can keep track of this?

**Comment by ticao2** [comment]
Sorry I'm late.
We are changing the elevator in my building.
And we only have one. So I moved house temporarily this week.
Of course, I open another one, certainly.
