### ISSUE TITLE
[StreamDetails] Does not load

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#688]
Strean Details - Does not load

**MediaElch 2.6.1 = NOT WORKING**
MediaElch_win_2.6.1-dev_2019-02-24_22-24_git-master-daccc3d.zip

MediaElch 2.6.0 = OK
MediaElch_win_2.6.0_win.zip

Does not charge automatically. And neither by clicking the button.
I tested in .mkv and .mp4 file
Windows 10 Pro

**Comment by tusharbhutt** [comment]
I have the same issue, the stream details do not load.

**Comment by alexls74** [comment]
On macOS, it gets all the information but behaves strangely.
It doesn't show any audio codecs and subtitle languages.
After manual refreshing the audio codecs appear but disappear all audio/subtitles languages.
The problem is only with displaying, writing to nfo-files is correct.

Linux version is the same.

**Comment by ticao2** [comment]
I compared the two .nfo files.  
2.6.0 wrote everything.  
2.6.1 did not write data from **<fileinfo> <streamdetails>**
MediaInfo.dll is apparently the same.
**4633** KB - File version **18.5.0.0**
Win 10 Pro

**Comment by alexls74** [comment]
> 4633 KB - File version 18.5.0.0

This is 32 bit DLL
But the build 2.6.1 is x64

Just replace with 
https://mediaarea.net/download/binary/libmediainfo0/18.05/MediaInfo_DLL_18.05_Windows_x64_WithoutInstaller.zip

**Comment by ticao2** [comment]
I changed the **MediaInfo.dll** file  
From: **4633 KB** - File Version 18.5.0.0
To: **5898 KB** - Same version.
Apparently it worked properly.
Win 10 Pro

Thank you.

**Comment by bugwelle** [comment]
> @bugwelle Mediainfo.dll is 32bit
Well...
I had to change a few things in the nightly build-setup (different dependency providers, etc). I changed `ffmpeg` to 64 bit as well. Seems I've forgotten MediaInfo.

Thanks for reporting!

**Comment by bugwelle** [comment]
I can confirm that v2.6.1 does not load any stream details. #693 fixes this (tested on Windows 8.1).
