### ISSUE TITLE
Advancedsettings - Mapping Countries does not work

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#689]
Advancedsettings - Mapping Countries does not work

In my advancedsettings.ini file I do mapping of certifications, genres and countries.
**Genres** is working **OK**.
But **Countries does not work**.
Does not work in MediaElch 2.6.0 or MediaElch 2.6.1

I have not tested Certifications.

**Comment by bugwelle** [comment]
Thanks for creating this issue! 😃 
I'll try to fix this issue ASAP. :-)

**Comment by bugwelle** [comment]
Found the issue. This should only happen with TMDb. :)
It was a Copy&Paste issue.
