### ISSUE TITLE
Cannot scrape multiple movies

### ISSUE THREAD

**Issue by tusharbhutt** [Komet/MediaElch#690]
The latest Windows version 2.6.1 does not allow for scraping of multiple movies, either with a set scraper (IMDB, etc) or custom.  Once in a while a random movie will scrape, but usually it comes back with a summary of "Scraping of 0 of x movies has finished".  A blank .nfo file is then created, with no info except the title.

**Comment by bugwelle** [comment]
Hi!
Thanks for reporting this issue. I will try to reproduce this and will come back to you again :-)
Does version 2.6.0 work on your machine?

Regards,
Andre

**Comment by tusharbhutt** [comment]
I downgraded to 2.4.3 and deleted the database and it still has the same problem.  Curious... because 2.4.3 worked before.

**Comment by tusharbhutt** [comment]
I tried it on another machine, it seems to be related to the checkbox for "Update only movies with IMDB/TheMovieDB ID".  If any movie is missing the ID, the program skips all of them.  When you look for movies individually, the program will not grab the movie by the title, but if the IMDB ID is used, then that single movie can be scraped.

So, two things:

1.  A movie without an ID will cause the entire set to fail scraping if any one is cannot be found
2. The movies that cannot be found by title (my filenames have movie title and year) are often found by the ID tag... which then gives the exact same movie title. It seems the search is weak.

The reason I never ran into this before is because the vast majority of my movies already had .nfo files and I was just using MediaElch to fill in other data.

**Comment by bugwelle** [comment]
Thanks for the detailed description!

I'm not yet able to reproduce this, i.e. an unrecognized movie does not make the whole scraping process fail.

> BONUS: If a title has a colon in it, IMDB often fails, but TMDB seems to figure it out.

Yeah, that's due to the IMDb/TMDb search... :/

*Update:*
Nevermind... While typing this message I tried and deleted all NFO files (instead of just removing the IMDb/TMDb id) and it just fails. Wow. Thanks for reporting! :-)

**Comment by bugwelle** [comment]
Oh. Well of course no movies are loaded if I remove all NFO files and select "only movies with IMDb/TMDb ID". For it to work all movies need to have a NFO file with an IMDb id set.

**Comment by tusharbhutt** [comment]
I have the checkbox removed, and sometimes it still finds the movies.  

Even for individual searches, the IMDB search is wonky.  I tried this...

1. Select Movie (in this case, Sicario)
2. Click the Cloud icon to start the metadata scraper 
3. In the dialog box, "Sicario (2015)" shows just below the scraper field.
4. No results are found
5. Enter the IMDB ID (tt3397884) in place of the title, and the movie is found

So, the question would be, why can't the program find the IMDB ID in the first place?  Perhaps if there were more than one movie with the same name, there could be some confusion, but not in this case.

Also, a suggestion: In cases where there are results with the same name and year (e.g. "Escape Room" ... there are several results from 2017 and 2019), maybe the program could display a one line description or list some of the actors so you can make a choice.  The reason for this is that as soon as you click the one you think is right, the program grabs the metadata and if you're wrong you have to redo it.

**Comment by bugwelle** [comment]
Hi there,

I haven't forgotten about this issue. :-)

> A movie that cannot be identified by title will cause the entire set to fail scraping if any single one cannot be found

I still wasn't able to reproduce this. In my case the unknown movie will simply be skipped but the download will not abort.

> So, the question would be, why can't the program find the IMDB ID in the first place? 

Don't know at this point. There have been changes on IMDB's side. I plan to release the next stable version this weekend. Could you test whether this issue still persists then? :smiley: 

I'm sorry that this didn't make v2.6.2.

**Comment by tusharbhutt** [comment]
Sounds good, I'll test it out

**Comment by bugwelle** [comment]
Hi,

could you try the latest stable version of MediaElch? :-)


Regards,
Andre
