### ISSUE TITLE
Movie Cast List - Pictures Changed

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#692]
Movie Cast List - Pictures Changed  
When I delete an actor from the list, an **actor who is without an image**, the next ones on the list have the image changed.  
Only after saving the movie does everything return to normal.

**Comment by puenktchen** [comment]
Confirmed. (Windows 10)

**Comment by bugwelle** [comment]
Thanks for reporting this issue. :+1: 
I'm sorry for not answering until now. I'll be busy for at least another month so I don't know when I'll have time to fix this. :-)

**Comment by ticao2** [comment]
Good to know.
I was worried about his absence.  :-)

**Comment by ticao2** [comment]
I suppose we can close this one.  
I believe the problem was fixed with https://github.com/Komet/MediaElch/pull/860
