### ISSUE TITLE
[ui] Stream Details

### ISSUE THREAD

**Issue by alexls74** [Komet/MediaElch#695]
Subtitle languages and audio codecs are not displayed.

Build from the 25th of January:
![2019-03-04 21 29 49](https://user-images.githubusercontent.com/12618414/53731167-a3da8f80-3ec5-11e9-8db5-fece3524c942.png)
All later:
![2019-03-04 21 31 32](https://user-images.githubusercontent.com/12618414/53731285-f87e0a80-3ec5-11e9-927f-b17faf50d30d.png)
After reloading:
![2019-03-04 21 31 57](https://user-images.githubusercontent.com/12618414/53731310-0a5fad80-3ec6-11e9-9620-4025434806aa.png)

**Comment by ticao2** [comment]
Maybe this will help.  
See here https://github.com/Komet/MediaElch/issues/688

**Comment by alexls74** [comment]
This is not related to mediainfo library.
I think it happened during the switching from QList to QVector. But I couldn't find where exactly.

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this issue.  
Haven't confirmed this issue, yet. @alexls74 You're using windows, right?

**Comment by alexls74** [comment]
@bugwelle Hi, I'm using macOS. But this is related to all version.

**Comment by bugwelle** [comment]
Thanks.

**Comment by bugwelle** [comment]
This should be fixed by #722 (hopefully and if I'm not missing something :-) )
