### ISSUE TITLE
Stream Details Not Fully Working

### ISSUE THREAD

**Issue by lynxstrike** [Komet/MediaElch#696]
Tested on TV Shows section
Portable version  2.6.1 2019-03-06
Windows 10 Pro x64
With and without deleting MediaElch.sqlite
With MediaInfo 18.5 and with MediaInfo 18.12 (vers x64)

Problem:

Works fine when scrapping totally new shows or new episodes. (pressing scrape new show or new episodes).

Not working when you have existing nfo files and press "update all" (a mix of old nfos and new episodes). Then, the old nfos are rewritten without stream details including the new ones.

To fix this, you have to erase all existing nfo files and scrape all the episodes...

Hope this help fixing the issue.

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this issue. Will need to confirm this first, though. It may or may not only happen on windows. In any case, this is indeed a bug. :-)

**Comment by lynxstrike** [comment]
Update:

As of ver. MediaElch_win_2.6.3-dev_2019-11-27_17-28_git-master-5f93809

MediaElch is fully loading stream codecs in all scrapping options available. Closing this issue.
Thanks for all your support guys. Great work !

**Comment by bugwelle** [comment]
Great to hear! Thank you for coming back to this issue. Out of curiosity: What MediaInfo version does your MediaElch version use (`About` -> `Developer`)?

**Comment by lynxstrike** [comment]
It's the one included with fusshub zip:

MediaInfo Version: MediaInfoLib - v19.04

If at some point you would like me to run some tests on some builds don't hesitate in ask... i would gladly do help.

**Comment by bugwelle** [comment]
Thanks! No, I just wanted to confirm that the latest MediaInfo lib (19.04) works. Thank you. :-)
