### ISSUE TITLE
[macOS] MediaElch uses discreet GPU

### ISSUE THREAD

**Issue by masi0** [Komet/MediaElch#702]
all versions since 2.4.x are enabling dGPU by default. Until versions 2.4.3 I was able to add the below string into info.plist to always use build in Intel GPU

<key>NSSupportsAutomaticGraphicsSwitching</key> <true/>

however this trick does not work in 2.6.1 - Is it possible to use internal GPU instead of discreet by default?

**Comment by bugwelle** [comment]
Hi,

short answer: I don't know

This is handled by the Qt framework (https://qt.io) and was likely changed in one of the latest versions.
I don't know what the difference is between internal and discreet GPU on macOS, though. Could you give us some links and/or article, please? I have to read into that topic first. :-)

Regards,
Andre

**Comment by masi0** [comment]
Some macs are equipped with two graphic cards. One, built into intel processor which is used as a daily driver for desktop tasks like word, excel, web browsing. It is usually default gpu while using laptop on battery. Discreet gpu is additional graphic card, in macs it’s usually amd which is powered when you need additional power, like playing games, using photoshop (or any high performince apps) etc. this also drains more than usual compared to intel gpu. Most of java based apps like java 😁 from oracle or that uses java are enabling discreet gpu due to bug in java. Normally it helped to add the string I posted. For some reason the very same string to force using internal gpu helped for some time with mediaelch.

Here are some links that may help (or not :) )

https://github.com/aluxian/Messenger-for-Desktop/issues/1172
https://stackoverflow.com/questions/8870304/dont-automatically-switch-to-the-higher-end-discrete-gpu
https://stackoverflow.com/questions/8870304/dont-automatically-switch-to-the-higher-end-discrete-gpu

**Comment by bugwelle** [comment]
Thanks :)

May be related: https://bugreports.qt.io/browse/QTBUG-62009

**Comment by bugwelle** [comment]
Hi,

#1157 should fix this issue. Tested on macoOS 11.1
