### ISSUE TITLE
TV Show title not scraped/replaced? [TVDB]

### ISSUE THREAD

**Issue by Extarys** [Komet/MediaElch#710]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [ ] TMDbConcerts
 - [x] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
Episode titles are not loaded

**MediaElch Version:**
 - [ ] 2.6.1-dev (nightly)
 - [x] 2.6.0 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux Mibt 19

**Additional context:**
I remember a couple of months ago I didn't have any problems.
It download the images but the title of each episode are not replaced. The episode number is correct though. (Notice it on the right)

![Screenshot from 2019-03-30 10-58-59](https://user-images.githubusercontent.com/11581433/55277865-2430bc80-52db-11e9-9db0-1a0c05591a61.png)

I'm not quite sure if this is the same issue here https://github.com/Komet/MediaElch/issues/630

**Comment by bugwelle** [comment]
Hi,

does this issue still occur in the latest nightly? We switched to the new TheTvDb API a month ago. That might have fixed your issue.

**Comment by bugwelle** [comment]
I am not able to reproduce this issue. Please let me know if it still occurs with the latest nightly.

There have been quite a few fixes regarding the TV scraper. :smiley:
