### ISSUE TITLE
Add TMDb as TV Show scraper

### ISSUE THREAD

**Issue by Donatzsky** [Komet/MediaElch#712]
It would be nice to have TMDb available for scraping TV shows.

**Comment by bugwelle** [comment]
Didn't know that TMDb works with TV shows as well. :-)
:+1:

**Comment by nkatsidis** [comment]
+1

**Comment by bugwelle** [comment]
I was told that Kodi already uses TMDb for TV shows. So we definitely should have a look at this now.

**Comment by txtsd** [comment]
Any ETA on this?

**Comment by bugwelle** [comment]
No. Not yet. It won't make it into v2.6.6 which will be a bugfix-release (probably this month).

**Comment by bugwelle** [comment]
The next nightly includes support for TMDb. :-)

See https://github.com/Komet/MediaElch/releases/tag/v2.7.0-beta.1
