### ISSUE TITLE
Certificate Expired

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#713]
Firefox informs you that the certificate has expired.  
https://www.kvibes.de/mediaelch

**Comment by bugwelle** [comment]
Hi!
I notified @Komet a week ago :-)
Try to reload the page. The current certificate is valid until July, 21st 2019, so I assume refreshing will get rid of that warning.

Regards,
Andre

**Comment by ticao2** [comment]
Firefox did not complain again. :-) 👍
