### ISSUE TITLE
Add labels in export

### ISSUE THREAD

**Issue by bastienpruvost** [Komet/MediaElch#715]
I use labels quite a bit to have custom lists of movies. 

These days I've been playing a bit with the export feature, and my biggest issue with it is that in any of the current themes, there is no way to access those shortlists.

I've started looking into building another theme myself, but looking at the code (`ExportDialog::replaceVars`) it seems that there is no variable to access a movie's labels.

I'm not completely proficient in C++ but i guess it would mean adding something like
`m.replace("{{ MOVIE.LABEL }}", movie->label().toHtmlEscaped());` in ExportDialog.cpp ?

Btw, could be cool to have the list of variables available (basically the content of `ExportDialog::replaceVars`) in the docs! (https://mediaelch.github.io/mediaelch-doc/export/create-theme.html)

**Comment by bugwelle** [comment]
Hi there,

thank you for opening this issue :)
I've added documentation about placeholder on: https://mediaelch.github.io/mediaelch-doc/export/create-theme.html#placeholders
The `{{ MOVIE.LABEL }}` placeholder will be added in #720

Regards,
Andre
