### ISSUE TITLE
Network Error during search on "The Movie DB"

### ISSUE THREAD

**Issue by IeP4nieF** [Komet/MediaElch#717]
**Describe the bug**
Strg-F while a film is highlighted, leads to a new window. There should be search results for the highlighted film. But there are no search results. On the console is printed:

[MediaElch] WARNING:  Network Error "SSL handshake failed"

**To Reproduce**
1. highlight one film
2. Hit Strg-F
3. Choose "The Movie DB"

**Expected behavior**
The results should be the same as on www.themoviedb.org.

**MediaElch Version:**
 - [x] 2.6.1-dev (nightly)
 - [ ] 2.6.0 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: debian)

**Comment by IeP4nieF** [comment]
Does anyone else does have this issue with themoviedb.org? Can't imagen, that I'm the only one.

**Comment by IeP4nieF** [comment]
Some further information:

Today I tested the MediaElch on two debian stretch machines. On one machine the error occures, on the other not! I don't have an idea why. Any hints for debugging?

**Comment by bugwelle** [comment]
> Today I tested the MediaElch on two debian stretch machines. On one machine the error occures, on the other not! I don't have an idea why. Any hints for debugging?

Oh... Are both systems up-to-date? I could only imagine that there were updates to some SSL libraries that are incompatible with Qt5's SSL handling. :/

**Comment by IeP4nieF** [comment]
Yes, both systems are up-to-date. And on both systems MediaElch is linked against the same library:

$ ldd /usr/bin/MediaElch | grep -i ssl
	libssl.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2

On both systems the version of libssl1.0.2 is 1.0.2r-1~deb9u1.

Let me know, if there ist something other to debug.

For me this issue isn't a problem at the moment, because I could use MediaElch on one machine.

**Comment by bugwelle** [comment]
Hi,

the latest versions improved error reporting quite a bit. This won't fix your SSL error but when the next stable is released (about a month I'd say) let me know whether this issue still occurs, please. 😃

**Comment by bugwelle** [comment]
The latest MediaElch AppImage is build on Ubuntu 16.04. Other users reported issues with v2.8.0 and SSL which were fixed in v2.8.2.

Please try the latest AppImage and let me know if this didn't fix your issue. :-)

**Comment by IeP4nieF** [comment]
The issue is fixed!

I tested the latest AppImage and also the Version from the Unbunt-repository.

Thanks!

**Comment by bugwelle** [comment]
Thank you for confirming it! 🎉
