### ISSUE TITLE
missing documentation for keyboard shortcuts

### ISSUE THREAD

**Issue by Stunkymonkey** [Komet/MediaElch#724]
**Is your feature request related to a problem? Please describe.**
there is no description for keyboard shortcuts, but it is mentioned in the release notes:
https://mediaelch.github.io/mediaelch-doc/release-notes.html#vulcan-2012-10-08

**Describe the solution you'd like**
update the docs

**Comment by bugwelle** [comment]
> Added keyboard shortcuts

You're right :)
We do have keyboard shortcuts like <kbd>F5</kbd> for reloading or <kbd>Ctrl+S</kbd> for saving but do not document them anywhere. 

Thanks for this issue! :)

**Comment by bugwelle** [comment]
Hi,

keyboard shortcuts have been added in https://github.com/mediaelch/mediaelch-doc/commit/a7d52c8b24bcf50772015f4fdf87088a30ca8e2a 

You can find them in each section, e.g. https://mediaelch.github.io/mediaelch-doc/movie/index.html#keyboard-shortcuts

Regards,
Andre
