### ISSUE TITLE
ADE Scraper does not load actors

### ISSUE THREAD

**Issue by waywit** [Komet/MediaElch#725]
With my latest build from Master the ADE scraper does not load and store the actors anymore.

Steps to reproduce:
- use ADE scraper on movie with stored actors
- save scraped movie
- check result in .nfo and empty <actor> tag

MediaElch 2.6.1-dev - Ferenginar
Compiled with Qt version 5.9.5 (64 Release, GCC 7.4.0)
Using Qt version 5.9.5
System: Ubuntu 18.04.2 LTS (x86_64-little_endian-lp64)

**Comment by bugwelle** [comment]
Hi,

thanks for letting us know. I should have found this bug sooner. We've got test for this and they failed..
So, thanks! :)
This will  be fixed in #726

A new nightly will be around ~30min after the PR has been merged.
