### ISSUE TITLE
Can't add Network Share on Linux

### ISSUE THREAD

**Issue by Slomo17** [Komet/MediaElch#727]
**Describe the bug**
I am unable to add a network location to mediaelch. When i click add i can't choose a networklocation like smb or sftp from file picker. I tried adding a local folder andt hen change the path manually to smb://... or sftp://... but it didn't scan the files.

**To Reproduce**
1. Open mediaelc
2. go to settings
3. click add to add source
4. no network locations available to add

**Expected behavior**
Network locations listed in file picker, or at least be able to add the path manually.

**Screenshots**
![image](https://user-images.githubusercontent.com/14056946/59372223-4b7a2000-8d47-11e9-85a1-b800bfefc027.png)

**MediaElch Version:**
 - 2.6.1-dev (nightly)
 - 2.6.0 stable
(tried with both)

**Operating System:**
 -  Linux (Fedora 30)

(works fine in Windows Version)

**Comment by alexls74** [comment]
You can add only mounted resources.

**Comment by bugwelle** [comment]
Hi,

as @alexls74 mentioned, only mounted resources can be added. That means a path without a scheme (i.e. `smb://`, `ftp://`). MediaElch is not a FTP client nor does it support other protocols like SMB. That's the operating system's task. :)

Regards,
Andre

**Comment by Slomo17** [comment]
Pity to hear that, as the main task for me is to manage movie collections on a network share

**Comment by alexls74** [comment]
> Pity to hear that, as the main task for me is to manage movie collections on a network share

[Just mount it](http://timlehr.com/auto-mount-samba-cifs-shares-via-fstab-on-linux/)

**Comment by bugwelle** [comment]
Hi,

I'll close this issue for now as this is nothing we will add to MediaElch. You can mount your network shares and then add them to MediaElch. :)

Regards,
Andre
