### ISSUE TITLE
Loading Streamdetails from file does not work properly

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#728]
Latest Nightly (8/6/2019)

Click a movie -> Streamdetails ->Reload from file

Audio does not show language and type (it shows only number of channerls)
subtitles do not show language

**Comment by nkatsidis** [comment]
also codec now from h264 goes to avc.. is it normal?

**Comment by nkatsidis** [comment]
problem still there in 16/6/2019 version

**Comment by ticao2** [comment]
I believe the answer is here:  
https://github.com/Komet/MediaElch/issues/695

**Comment by nkatsidis** [comment]
i replaced mediainfo.dll 64bit version but the problem is still there...

**Comment by nkatsidis** [comment]
using windows 10 64bit

**Comment by azriel84** [comment]
I have the same issue, windows 10 64bit, I just get 7.1 on sound streamdetails, no Atmos or DTS etc...

**Comment by nkatsidis** [comment]
problem still there in 20/6/2019 nightly

**Comment by alexls74** [comment]
Some fields have changed in mediainfo (>18.05).
We can back to version 18.05 or adapt to new versions.

**Comment by nkatsidis** [comment]
i can confirm that after using 18.03 version of Mediaelch.dll steamdetails seem to work - almost - properly..
BUT... in Codec it does not display h264 but avc..... ;)

**Comment by azriel84** [comment]
Plus latest nightly has issue with DTS:X 7.1 sound stream. Freshly released Hulk (2003) has that stream but mediaelch doesn't depict any sound details at all.

**Comment by bugwelle** [comment]
I'll consider switching back to an older version of MediaInfo until I've figured out what exactly changed.

@alexls74 Do you maybe know if v17 still worked as expected?

**Comment by bugwelle** [comment]
I'll close this issue. In case that streamdetails continue to not work, feel free to reopen it. :)

**Comment by nkatsidis** [comment]
Windows 10 64 bit. Latest Nightly

Loading Streamdetails still not working properly...
I have a Movie with atmos, in audio it does not displays what the audio is (dtshd, truehd, ac3 etc)

version 260 works fine ....

**Comment by monisriz** [comment]
AAC audio codec is not written to the nfo. It's not being shown in UI either.

**Comment by bugwelle** [comment]
For reference: #851 fixes some other audio issues :)
