### ISSUE TITLE
[Dev] MediaElch Development Roadmap 2019

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#743]
*This is a often-updated issue that exists for discussing decisions regarding MediaElch's development.**

## What is this issue?
This issue lists and describes planned features and other design decisions. It is intended for MediaElch's developers and may go into technical details. All of these issues are neither bug reports nor feature requests. They're not big enough to create new issues for them. But other developers may want to try and fix one of the issues below so I thought: Why not share my thoughts?

It's also easier to keep track of one issue with all development design decisions than to have multiple smaller issues.

### Table of Contents
(order: importance from highest to lowest)

 1. ~~Validate advancedsettings.xml~~
 1. ~~Test Kodi XML~~ (fixed in b671f29e43a0984a5cdbf0bff08319edba4f7730 )
 1. ~~Make EpisodeWriter testable~~
 1. ~~Coverage~~
 1. ~~cppcheck warnings~~
 1. ~~clang-tidy warnings~~
 1. ~~shellcheck warnings~~
 1. ~~Add Homebrew package~~
 1. ~~Use the distribution's QuaZip~~

### ~~Validate advancedsettings.xml~~
~~Currently I could pass e.g. -400 as the thumb size. This should be validated.~~
~~Furthermore if an element does not contain require sub-tags, the whole scanning process fails without notice.~~ See #776, #846

### ~~Test Kodi XML~~
~~We now have Kodi XML tests~~ :tada: 
~~But for some reason QDomDocument.toString() is not deterministic...~~
~~On each test run I get a different XML string. This is really annoying.~~
=> fixed in b671f29e43a0984a5cdbf0bff08319edba4f7730

### ~~Make EpisodeWriter testable~~
~~The EpisodeWriter is part of KodiXml which makes it difficult to test. Should be refactored just like MovieXmlWriter has been refactored.~~
Fixed in #775 

### ~~Coverage~~
~~We already have a `coverage` target, so it should be easy to deploy the coverage information to e.g. codecov. This issue also implies that we should add more unit tests. This on the other hand requires a better separation of concerns of our code (see "Separation of UI and Business Logic").~~
fixed in #767

### ~~cppcheck warnings~~
~~There are many annoying cppcheck warnings. That's why we haven't enabled the cppcheck step on TravisCI. For a list of warnings, see: https://travis-ci.org/Komet/MediaElch/jobs/558031311~~

### ~~clang-tidy warnings~~
~~Same as cppcheck warnings but with clang-tidy.~~
We now have a `.clang-tidy`

###  ~~shellcheck warnings~~
~~shellcheck warns about bad-practices in shell scripts. Very useful but also very noisy.~~
fixed in #770

### ~~Add Homebrew package~~
http://brew.sh
Already exists: https://formulae.brew.sh/cask/mediaelch

### ~~Use the distribution's QuaZip~~
~~#756 but for CMake~~
fixed in #758 and #765

**Comment by scottfurry** [comment]
I'll take a look at the CMake process to incorporate this change.

**Comment by bugwelle** [comment]
This issue will be continued in https://github.com/Komet/MediaElch/issues/847

Issues that didn't make it in 2019 have been transferred to that issue. :-)
