### ISSUE TITLE
[Renamer] Add placeholder for subtitles 

### ISSUE THREAD

**Issue by ludi113** [Komet/MediaElch#745]
Hi, 

Considering that MediaElch fetches the language of the subtitles in the stream details pane, it might be good to have a placeholder in the renamer to make use of that list of subtitle languages. 

Thanks

**Comment by bugwelle** [comment]
Hi, thanks for opening this issue.

I can add this feature but be aware of these details:
There are not only stream-details-subtitles (embedded subtitels) but also subtitles in form of `.sub` files, etc.
There can also be more than one for each. Should we always take the first one?
I could also add these:

 - `streamSubstitleLang`
 - `subtitleLang`

Or just the latter and use the first available language in the order of:
 1. embedded subtitles
 2. external subtitle files

Waht would you like? :)

Regards,
Andre

**Comment by ludi113** [comment]
First of all, thanks for the prompt reply. 

Picking simply the first subtitle language would not suit my use case, because I am interested in subtitles in specific languages (more than one language) and the first language picked by MediaElch might not be the languages I am interested in. 

Moreover, I suppose there is no point adding a placeholder to add the presence of external subtitles to the movie/episode filename, as the external subtitles are visible when looking at the files. Thus, the list of embedded subtitles would suit my use case for the renamer. 

Consequently, having the list of all the subtitle languages would already be helpful to me. 

On the other hand, a more elaborated approach would be, if I could tell MediaElch what languages I am interested in. In fact, in this case, it would be great to have a (second) placeholder, that would be restricted to the languages, I am interested in. 

By the way, I opened a similar feature request for the audio languages embedded in the file. #423

In any case, thank you very much for taking into account implementing it. 

Have a nice Sunday.
