### ISSUE TITLE
Latest MediaElch builds crash on start

### ISSUE THREAD

**Issue by waywit** [Komet/MediaElch#746]
Hi,

using the last two builds (linux) MediaElch crashes immidiately after start with my Ubuntu Ubuntu 18.04.2 LTS with XFCE 4.12:
```
...
[MediaElch] DEBUG:    TMDb base url: "http://image.tmdb.org/t/p/"
[MediaElch] DEBUG:    TMDb base url: "http://image.tmdb.org/t/p/"
[MediaElch] DEBUG:    TMDb base url: "http://image.tmdb.org/t/p/"
[MediaElch] DEBUG:    TMDb base url: "http://image.tmdb.org/t/p/"
[MediaElch] DEBUG:    Now processing files
Segmentation fault (core dumped)
```

In /var/log/apport.log the following is logged:
```
ERROR: apport (pid 7315) Sun Jul 14 00:07:47 2019: called for pid 7276, signal 11, core limit 0, dump mode 1
ERROR: apport (pid 7315) Sun Jul 14 00:07:47 2019: Unhandled exception:
Traceback (most recent call last):
  File "/usr/share/apport/apport", line 483, in <module>
    exe_mtime = os.stat('/proc/%s/exe' % pid).st_mtime
PermissionError: [Errno 13] Permission denied: '/proc/7276/exe'
ERROR: apport (pid 7315) Sun Jul 14 00:07:47 2019: pid: 7315, uid: 1000, gid: 1004, euid: 0, egid: 0
ERROR: apport (pid 7315) Sun Jul 14 00:07:47 2019: environment: environ({})
```

Also in /var/log/kern.log is something logged:
`Jul 14 00:07:47 homer kernel: [705221.391528] MediaElch[7276]: segfault at 7f59847cbaf8 ip 00000000005a6fc9 sp 00007fff9a9d6820 error 7 in MediaElch[400000+643000]`

I tried some older builds and the last one working is "MediaElch_linux_2.6.1-dev_2019-07-12_18-55_git-master-0ea07c3.AppImage"

If there is something I can do to help, do not hesitate to ask :-)

Thanks and best regards
Waywit ;-)

**Comment by bugwelle** [comment]
Thank for reporting this issue! :)
And thanks for the heads-up with the last working build.

**Comment by bugwelle** [comment]
Hi,

does the AppImage fail with this message?

```(MediaElch:1897): GStreamer-CRITICAL **: 14:06:33.295: gst_object_unref: assertion 'object != NULL' failed
MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
Aborted (core dumped)
```

**Comment by waywit** [comment]
Where may I find this error message? All log file entries which are produced during the crash are in my original post...

**Comment by bugwelle** [comment]
Ah, ok. Nevermind :)
Switched something up. In my case the AppImage won't even start because of some OpenGL errors. That's due to how we create the AppImage.
In your case there's an segmentation fault which is MediaElch's fault. :)

**Comment by waywit** [comment]
I can test your fix on my machine, it is setup to compile MediaElch and the issue is also reproducable in my own builds ;-) If you need help I can provide some time and computing time :-)

**Comment by alexls74** [comment]
It is not related to the appimage package.
The current build is crashing in any case.
[Crash log](https://www.dropbox.com/s/3vg360zotl03se8/_usr_bin_MediaElch.1000.crash?dl=1)

**Comment by bugwelle** [comment]
@alexls74 Thanks. I was talking about my case. I downloaded the latest AppImage and it immediately crashes whereas if I just compile it on the same machine and execute it, MediaElch works. Nevertheless, both cases shouldn't happen at all. I'm currently investigating that issue but couldn't figure out what's wrong, yet.

**Comment by alexls74** [comment]
The same on macOS
[CrashReport](https://www.dropbox.com/s/zztwwilvhdq292z/MediaElch_2019-07-17-230108_iMac.crash?dl=1)

**Comment by bugwelle** [comment]
@alexls74 Thank you. Errors seems to occur here: https://github.com/Komet/MediaElch/blob/master/src/media_centers/kodi/MovieXmlReader.cpp#L247

What the heck were I thinking? I can't assign to `m_movie.ratings().first()` if there are no ratings...
Will fix that ASAP. I shouldn't code when I'm tired. Sorry.

Those crash reports are awesome! Thanks you!

**Comment by TouchTone** [comment]
My fix, seems to work ok (at least for me):

diff --git a/src/media_centers/kodi/MovieXmlReader.cpp b/src/media_centers/kodi/MovieXmlReader.cpp
index 010afe8e..b0ac6c66 100644
--- a/src/media_centers/kodi/MovieXmlReader.cpp
+++ b/src/media_centers/kodi/MovieXmlReader.cpp
@@ -235,7 +235,14 @@ void MovieXmlReader::movieRatingV16(QDomElement element)
     if (!value.isEmpty()) {
         Rating rating = m_movie.ratings().empty() ? Rating{} : m_movie.ratings().first();
         rating.rating = value.replace(",", ".").toDouble();
-        m_movie.ratings().first() = rating;
+        if (m_movie.ratings().isEmpty())
+        {
+            m_movie.ratings().push_back(rating);
+        }
+        else
+        {
+            m_movie.ratings().first() = rating;
+        }  
         m_movie.setChanged(true);
     }
 }

**Comment by bugwelle** [comment]
Hi there,

does the latest nightly still crash? If not then I'll close this issue :)
I've fixed a few crashes yesterday.

**Comment by monisriz** [comment]
Can be closed. Open issues bug me.. :)

**Comment by bugwelle** [comment]
Yeah, I totally forgot about this (not user reaction here for nearly 2 months).

If MediaElch still crashes for anyone, please feel free to open another issue 😃
