### ISSUE TITLE
[All] Support multiple ratings

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#750]
**Is your feature request related to a problem? Please describe.**
Kodi supports multiple ratings and also `<userrating>0</userrating>`.

**Describe the solution you'd like**
Add a button to add multiple ratings and also an user rating.

**Describe alternatives you've considered**
none

**Additional context**
Internally `Movie` already supports multiple ratings. Just not the GUI. I will also add an user rating soon so make our XML tests pass.

**Comment by monisriz** [comment]
Something that needs to be kept in mind is that an nfo file is like a snapshot of the movie/tvshow/episode/album data that is scrapped at a given point in time. So, for example, the ratings (IMDb, TMDb) are written to the nfo and are only true at the point when they are scraped and will most likely be outdated after some time. 

While Kodi does have a third-party addon that update IMDb ratings, Kodi does not update the nfo files by itself. Only way to update the nfo files is to export the entire video library as separate files - either manually or through some automated process.

My point here is that, having outdated ratings in nfo files will have limited utility. IMDb ratings are fine as they can be updated through an addon and it's possible for a user to update nfo files periodically to reflect those updated ratings. But for other ratings, I don't think such an update addon is available currently.

**Comment by bugwelle** [comment]
@monisriz Thanks. I didn't even know such a plugin existed. In my opinion even an old snaphot of an IMDb rating is useful but that's up to the user, I would say :-)

**Comment by monisriz** [comment]
Yea having IMDb ratings is fine as it can be updated (via Light IMDb ratings addon). But I don't see any value in having other rating types (e.g. Metacritic, Rotten Tomatoes) included in the nfo as they are bound to get outdated and with no way to update them apart from manually changing them in the nfo. Since user would be using the nfo file as "Use local file" in Kodi content type option, refreshing the library won't scrape the new rating either...
My suggestion is to keep the ratings as they are right now (IMDb/TMDb for movies, IMDb/TVDb for tv shows, etc.). The effort saved adding more ratings related APIs could be spent fleshing out other features that need more attention :)

**Comment by bugwelle** [comment]
<img width="613" alt="Screen Shot 2020-02-11 at 10 54 23" src="https://user-images.githubusercontent.com/1667306/74226480-e6ebd800-4cbc-11ea-8f8b-35023033aabf.png">

I think I'll design multiple ratings like in the screenshot above. A bit nicer of course with proper "remove" buttons, better spacing and an "add" button. There must be at least one rating entry in my opinion, even if it is empty. Otherwise users could get confused.

I have to investigate whether Kodi accepts and kind of "source" string or has a list of predefined ones. A quick search found this (in a folder named `legacy`)

```
      ///  - Some example type (any string possible):
      ///  | Label         | Type                                              |
      ///  |:-------------:|:--------------------------------------------------|
      ///  | imdb          | string - rating type
      ///  | tvdb          | string - rating type
      ///  | tmdb          | string - rating type
      ///  | anidb         | string - rating type
```

I would like to comply with these names. However users could change those names to something more readable like `TheTvDb` and therefore I'm in favor of keeping a list of currently possible values. That of course may change in the future. We'll see how that works out.
