### ISSUE TITLE
Scraper the Tvdb not returning info due to tvdb changes?

### ISSUE THREAD

**Issue by internetR** [Komet/MediaElch#760]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [ ] TMDbConcerts
 - [X] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**MediaElch Version:**
 - [X] 2.6.1-dev (nightly)
 - [ ] 2.6.0 stable

**Operating System:**
 - [ ] Windows
 - [X] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**

No contact with the tvdb, but they made some modifications to the website on their side, the beta tvdb is now live. They have a New API protocol ?

**Comment by internetR** [comment]
API server is down at the moment
https://api.thetvdb.com/login|Content-Type=application/json

**Comment by internetR** [comment]
Kodi is contacting the tvdb again, but i am still unable to do so with mediaelch

**Comment by th12289** [comment]
I have the same issue. 

Scrapers that don't work:

- [ ]   IMDb
- [ ]   OFDb
- [ ]   TMDb
- [ ]   TMDbConcerts
- [x]  TheTvDb
- [ ]   TvTunes
- [ ]   AEBN
- [ ]   AdultDvDEmpire
- [ ]   HotMovies
- [ ]   VideoBuster

MediaElch Version:

- [ ]   2.6.1-dev (nightly)
- [x]   2.6.0 stable

Operating System:

- [x]   Windows, 1809
- [ ]   macOS
- [ ]   Linux (distribution: ___)

Additional context:
Can't work with series.

**Comment by psonnosp** [comment]
Does MediaElch completely rely on TheTVDB to work with TV-series?
Cause even if you change everything to IMDb under 'Settings-Scraper-TV Scraper' and try to scrape an episode you end up with zero results no matter if you search for the show ID or its proper name.
Or is the IMDb-scraper down too?

**Comment by internetR** [comment]
02-08 there is communication again with the tvdb

**Comment by th12289** [comment]
I can confirm @internetR @psonnosp

**Comment by bugwelle** [comment]
Thanks for openening this issue.

MediaElch needs to display better error messages...
These issues have been opened a few times because of that. I'll keep that in mind. :)

> Does MediaElch completely rely on TheTVDB to work with TV-series?

Yes, unfortunately.

**Comment by patrickmau** [comment]
Same here, as of April 5th I still get zero results for any IMDB/TVDB search.

Would appreciate if this could be fixed soon as I just moved 500+ tv shows to my ext HDD and really want to get it synced to Kodi T_T

**Comment by psonnosp** [comment]
Then you better contact TheTVDB since their API is down or up and acting extremely slow.

**Comment by bugwelle** [comment]
> Same here, as of April 5th I still get zero results for any IMDB/TVDB search.

IMDb takes forever to load, also in the browser. I'm sorry but that's an issue on IMDb's side. I already increased the timeout for downloads in the nightlies.

TheTvDb is sadly very unreliable. While there is indeed a bug with it, it is related to episodes and not the whole show. TheTvDb is under heavy load as well.
Seems everybody tries to update their home video libraries during the quarantine in many countries.
