### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#761]
[Windows] Dark Theme

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Windows 10, after version 1809 (October 10, 2018), has the ability to use a Dark Theme.  
In MediaElch, in the Linux or OSX version, I think there is this possibility.  
In Windows 10, Firefox has this capability. Apparently the MPC-HC too.  
Is there any chance MediaElch for Windows 10 has this ability?  

**Describe alternatives you've considered**
No alternative

**Additional context**
How to enable Dark Theme on Windows 10.  
https://pureinfotech.com/enable-file-explorer-dark-theme-windows-10/

**Comment by bugwelle** [comment]
Hi,

thank you for this feature request. MediaElch uses Qt for its graphical user interface and after a quick google search I found that Qt does not yet support the dark Windows theme.
See https://forum.qt.io/topic/101391/windows-10-dark-theme

We'd have to use a third-party color palette or define our own.
For example https://github.com/ColinDuquesnoy/QDarkStyleSheet

To be honest, I'm not sure whether I want to do that, though. And if we use a custom theme, we'd need to get Window's settings for the currently used theme (dark/light) and change or styles based on that information. I'll think about this and will evaluate the development costs / time it takes to implement this.

But please note that there are many other issues that need to be taken care of, first. :)

**Comment by ticao2** [comment]
My ignorance in programming has no limits.
I thought it would be simpler.
And, undoubtedly, there are more important questions than this.
But maybe when QT supports it, it's easier. :-)
Thank you one more time.

**Comment by ztarbugz** [comment]
So what about dark mode for macOS 10.14+ ? From what I have seem so far, QT is able to support the Dark Mode on macOS.

**Comment by bugwelle** [comment]
> So what about dark mode for macOS 10.14+ ? From what I have seem so far, QT is able to support the Dark Mode on macOS.

I'm not sure, maybe this works in Qt6. However, MediaElch's main window is customized, so it won't work with Qt's default UI colors.

**Comment by bugwelle** [comment]
I've done a lot of refactoring today and even played a few minutes with changing colors. The most relevant commit of today was https://github.com/Komet/MediaElch/commit/62c53047d3574f9c2a08e5775ab9fa0f88d6a36f which moved inline stylesheets to our `default.css`.  Replacing colors in that file now works better.

I'll be doing a bit more cleanup and refactoring and will try to write a stylesheet for a dark theme (of our main window at least).

Preview:

<img width="1792" alt="Screenshot 2022-12-27 at 21 20 25" src="https://user-images.githubusercontent.com/1667306/209718410-a9029771-443b-4580-ad3f-2598d925146e.png">

I only played with it for a few minutes. I know the colors don't look good, I just wanted to show that there are only a few places left that are bright white. Those need to be styled, but it's a lot better now compared to a few months ago.

There is also a lot to do:

- icon colors
- contrast
- consistent color scheme (we have 4 different "blue" colors for labels...)

**Comment by bugwelle** [comment]
With #1522, there will be an experimental dark mode. Not everything is perfect, yet, especially for TV shows, but it's a huge improvement over my 5min example from yesterday. :)

<img width="1792" alt="Screenshot 2022-12-28 at 18 31 00" src="https://user-images.githubusercontent.com/1667306/209850551-06a2d6fc-77bd-48fe-ac2c-323c736b4218.png">

**Comment by bugwelle** [comment]
More improvements with #1524.

**Comment by bugwelle** [comment]
TODO:

- [ ] revert https://github.com/Komet/MediaElch/pull/654
- [ ] add option to global settings
- [ ] follow https://successfulsoftware.net/2021/03/31/how-to-add-a-dark-theme-to-your-qt-application/

**Comment by bugwelle** [comment]
Besides some smaller issues, dark mode is now fully implemented (with UI settings).

**Comment by ticao2** [comment]
After 3 months of political turbulence in my country, which took all my attention to social networks, in an endless fight to combat Fake News, I believe that now I will be able to return to a more or less normal life and have fun with my movie collection.
I'll try to install it today and have some fun.
