### ISSUE TITLE
Can not select TV Episode to scrape 

### ISSUE THREAD

**Issue by sharkbit** [Komet/MediaElch#772]
**Describe the bug**
Cant use mouse to click on TV episodes,  works poorly on knows episodes,  not at all on new episodes.
- have to use the keypad to move to episode but even that works poorly
- Can select the Show then really tough to use arrows and select episodes

**Screenshots**
![image](https://user-images.githubusercontent.com/979670/62839126-c1214000-bc53-11e9-8198-e0bc24c95264.png)

**MediaElch Version:**
 - MediaElch_win_2.6.1-dev_2019-08-11_18-07 (nightly)

**Comment by bugwelle** [comment]
Hi,

try to click on the `S` in `S01E06 Civil Wars`. I noticed that yesterday as well. Apparently the clickable column width is reduced quite a lot, i.e. the space below the icons (green / red ones) is not clickable.

I can't say for sure whether this is a regression in MediaElch or in the Qt framework. Thanks for reporting this issue.

Regards,
Andre

**Comment by bugwelle** [comment]
I marked this high priority because it is a really annoying issue. Makes it unusable to new and old users.

I also fixed the multiple-line-issue quite a while ago. I don't understand why it's back...

**Comment by bugwelle** [comment]
Responsible commit: 02b0dc796b6d29afe71634fe9197017597e8fce9

```
commit 02b0dc796b6d29afe71634fe9197017597e8fce9 (HEAD, refs/bisect/bad)
Author: Andre Meyering <info@andremeyering.de>
Date:   Sun Jun 30 16:18:46 2019 +0200

    [FileSearcher] Remove messageId from signals
```
