### ISSUE TITLE
[Scraper] TMDb with problems

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#774]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [ X ] TMDb
 - [ ] TMDbConcerts
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
Add a list of information that is not loaded correctly.

**MediaElch Version:**
 - [ X ] 2.6.1-dev (nightly)
 - [ ] 2.6.0 stable

**Operating System:**
 - [ X ] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**
[Scraper] TMDb with problems

TMDb has problems. Mainly with search and discover endpoints.  
https://www.themoviedb.org/talk/5d545ed4b76cbb0013d828d8  
https://twitter.com/themoviedb/status/1161718247097454592  
There is a not too difficult solution.  
When doing research do not use the title of the movie.  
Use the IMDB ID.

**Comment by bugwelle** [comment]
TMDb search seems to be up again. Thanks for the heads up :)
I'll add that twitter account to my list of "must follow" users :smiley:
