### ISSUE TITLE
Change dimensions on screenshot

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#776]
Would be nice to be able to change the dimensions of the thumb generated by 'Capture random screenshot' future on the series episode page.
I know 400x225 is the standard but I've moved on to 1920x1080 since the standard looks like crap when using Yatse on my tablet to control Kodi.

Or perhaps it's already possible to change using advancesettings.xml or something?

**Comment by bugwelle** [comment]
Good idea. Always wondered where the resolution used by MediaElch came from. It's set here: https://github.com/Komet/MediaElch/blob/921599703abfecd670a440f365935d8cb5e8cd95/src/image/ImageCapture.cpp#L85

May be a good idea to add an optional tag to `advancedsettings.xml` before adding it to the GUI. :)
I don't know what resolution Kodi expects, though.

**Comment by psonnosp** [comment]
Yes I'm very happy with it being taken cared of in advancedsettings.xml, no problem at all.
Kodi don't have any problems with the thumbs being 1920x1080, they show up just as they do with the ones that are 400x225 so guess it just scale them to fit the current view.

**Comment by bugwelle** [comment]
#777 fixed this issue. The next nightly will have the option to change thumbnail sizes. It will keep the video file's aspect ratio, though. The sizes are more like the maximum image size.
This was a rather small change and was easy to implement. The `AdvancedSettings.cpp` was a file I wanted to get under test for a long time so this feature request came at the right time. :)

See https://github.com/Komet/MediaElch/blob/89168251a53613873ffce53daf040e70384239d5/docs/advancedsettings.xml#L51-L54

**Comment by psonnosp** [comment]
It's lovely when things just happen to fit in to each other like that.
Thanks for this!

**Comment by bugwelle** [comment]
Reminder to myself: I forgot about validation... Strangely nothing is validated inside AdvancedSettings.cpp
I could use negative sizes and so on. Not only for this feature but for other options as well.
