### ISSUE TITLE
Uniqueid is not properly scraped for episodes

### ISSUE THREAD

**Issue by hewwra** [Komet/MediaElch#788]
**Describe the bug**
If I scrape a tv show Mediaelch correctly writes the uniqueid to the tvshow.nfo file.
However if I scrape an episode it will only write the uniqueid for imdb and not for tvdb:

    <uniqueid type="tvdb" default="true"></uniqueid>
    <uniqueid type="imdb">tt9425134</uniqueid>

**To Reproduce**
1. Scrape episode  1 from  Conversations with a Killer: The Ted Bundy Tapes
2. Open the nfo file and observe the missing uniqueid for tvdb

**Expected behavior**
Properly write the tvdb uniqueid for episode 1 of Conversations with a Killer: The Ted Bundy Tapes

**Screenshots**

**MediaElch Version:**
 - [ ] 2.6.3-dev (nightly)
 - [ X] 2.6.2 stable

**Operating System:**
 - [X ] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context**

**Comment by bugwelle** [comment]
Thanks. I'll look into this issue after my vacation (next month). I must have missed this somehow...
Having a quick look at the code, it should print TheTVDb id: 

https://github.com/Komet/MediaElch/blob/720b7f1a13f6119e00865008085f001eae93cef8/src/media_centers/kodi/v17/EpisodeXmlWriterV17.cpp#L46-L50

**Comment by hewwra** [comment]
I took a look at some other episode nfo's and it seems like only imdbid has been written to them so you have maybe never retrieved the tvdb id in any version of MediaElch?

**Comment by bugwelle** [comment]
Ok, had a look at it. It's never written anywhere in TheTvDb scraper...
Will add this to #487

**Comment by bugwelle** [comment]
Found the issue. Will be fixed by #487

**Comment by bugwelle** [comment]
The PR is merged. It should work now. Sorry for the delay. :)
