### ISSUE TITLE
Search Results Hang

### ISSUE THREAD

**Issue by scuba-fan** [Komet/MediaElch#792]
**Describe the bug**
Scraper results screen hangs and displays "Custom Movie Scraper" and no results

**To Reproduce**
1. Select Title (Movie)
2. Right Click, Select Load Information
3. No search results, just a Search Result screen with action spinner running

**Expected behavior**
Present a result set for found titles

**Screenshots**
![image](https://user-images.githubusercontent.com/18339721/65105515-07bc3580-d98a-11e9-8b86-d9aa4a1dc0bb.png)

**MediaElch Version:**
 - [ ] 2.6.3-dev (nightly)
 - [XX ] 2.6.2 stable

**Operating System:**
 - [XX ] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context**

**Comment by ticao2** [comment]
Did MediaElch automatically choose "**Custom Movie Scraper**", or did you select it?  
In the "Custom Movie Scraper" setup, which service is selected for the title?   
And for the other items?  
In IMDB I did not find **Dirty Talk 5**. Only Dirty Talk. It looks like it's a TV series.   
Can you tell which IMDB ID (tt12345678) of this movie you are looking to make a Scraper?

**Comment by scuba-fan** [comment]
Automatically.  I had a working version 2.6.0 and updated to 2.6.2. didn’t change anything.

**Comment by ticao2** [comment]
Can't you change Scrapper? Select TMDb?
You need to answer my other questions.

In the "Custom Movie Scraper" **setup**, which service is selected for the **Title**?   
And for the other items?  
In IMDB I did not find **Dirty Talk 5**. Only Dirty Talk. It looks like it's a **TV Series**. Not a Movie.   
Can you tell which IMDB ID (tt12345678) of this movie you are looking to make a Scraper?  

**EDIT**  
I found **Dirty Talk 5** only on **TMDb**.  
https://www.themoviedb.org/movie/445501-dirty-talk-5  
So in this case, in the "Custom Movie Scraper" setting, TMDb should be selected for the Title.  
Or use the normal Scraper and select the **TMDb**.

**Comment by scuba-fan** [comment]
See screen captures.  They are identical between my 2.6.0 and 2.6.2 setup.  Still get the error

 

As for the other items…

 

1.	You can see in the capture that AdultDVDEmpire is selected for Title in both versions.
2.	You can see all item settings in the screen capture
3.	It’s an adult title so I don’t expect it to be in IMDB

 

Is this enough info to go on,  anything else I can provide?

 

Thanks

**Comment by ticao2** [comment]
I can not help.
I believe only the Administrator, bugwelle, can.
But I think he's on vacation. Then it won't be fast.
I searched here and found news that changes were made to the programming of ADE Scraper.
https://github.com/Komet/MediaElch/issues/703  
https://github.com/Komet/MediaElch/issues/639  
https://github.com/Komet/MediaElch/issues/565  
I don't know if this can help you.
PS: You mentioned images, screen captures, but I couldn't see it.

**Comment by ticao2** [comment]
Hi scuba-fan  
I found this today at Changelog.  
https://mediaelch.github.io/mediaelch-doc/release-notes.html  

2.6.2 - Ferenginar (2019-09-13)  
This release will affect your scraper settings. You’ll therefore have to reconfigure your scraper settings. You may also need to delete MediaElch.sqlite.
See: https://mediaelch.github.io/mediaelch-doc/faq.html#where-are-mediaelchs-settings-stored  

Maybe this statement will solve your problem.

**Comment by bugwelle** [comment]
Hi everyone,

I'll be on vacation for a week starting tomorrow but am currently moving to another city which is why I didn't have time to answer, yet.

As @ticao2 suggested, try to delete MediaElch.sqlite and reconfigure the "Custom Movie scraper" (i.e. select the scraper you want to use for each item again). If you want to know why you have to do this and why v2.6.2 breaks your seetings: I f**ked up by renaming the scrapers (internal names and the ones that are written to settings).
I can only apologise for this. 

If this doesn't help then I will have to look into this issue next week :-)

**Comment by bugwelle** [comment]
Found the issue btw. It was a deadlock and a bug on my side. Will be fixed in #798
