### ISSUE TITLE
Make episode scrape options permanent.

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#801]
**Describe the solution you'd like**
As the topic says, would it be possible to make the scrape options for a single episode and for multi scrape to be saved from session to session?
All other scrape options are saved but not these two for some reason and I don't really see why. Doubt I'm the only one that want the same things to be scraped most of the times I use the function.
Or am I the odd one (as usual)?

**Comment by bugwelle** [comment]
Neat idea 😄 

👍

**Comment by psonnosp** [comment]
Guess I'm not quite the odd ball I thought I was then ;)

Maybe I should create a new issue about this but it's kind of related.
When selecting pictures for actors it would be nice if the last used folder could be remembered, now it jumps to Windows %userprofile% every single time, it doesn't even remember it per session, as the scrape function does, and it gets kind of frustrating after a while.

**Comment by psonnosp** [comment]
Sad to see that this did a 360 and now no scraper settings whatsoever regarding details to load is saved.
Was this intentional or should it be considered a bug?

**Comment by bugwelle** [comment]
> Was this intentional or should it be considered a bug?

A bug. Noticed this yesterday... Only for the mutli-scrape-dialog as far as I can see.

**Comment by bugwelle** [comment]
Oh... For scraping episodes and TV shows as well. Will fix this ASAP.

**Comment by bugwelle** [comment]
#1126 will fix the bug. With that PR MediaElch will also store selected details, scraper, language, ... for the multi scrape dialog. :-)
