### ISSUE TITLE
[Scraper] TMDb does not download images

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#807]
**Describe the bug**
From 2019-10-09 20:00 approximately.
No posters or fanarts and no cast images.
Metadata only.
In 2019-10-10 09:30 I got posters of a movie.  
I already informed in the forum of TMDb.

**To Reproduce**
1. Just Scrape

**Expected behavior**
Download images

**Screenshots**
Not applicable,

**MediaElch Version:**
 - [ ] 2.6.3-dev (nightly)
 - [x] 2.6.2 stable

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context**
I have 2 MediaElch installed in Portable mode.
2.6.0 stable, the old, and 2.6.2 stable.
The two scraper the same folders.
Both are behaving the same way.

**Comment by ticao2** [comment]
I think the problem is solved, but I think it's temporary.  
I don't know how long it will work.  
Here's the explanation from Travis Bell, the boss at TMDb:  
https://www.themoviedb.org/talk/5d9e76cfbefd910034407d54?page=1#5d9f70dcf18ce7002b43c002

**Comment by bugwelle** [comment]
Hi,

@monisriz fixed this issue in #808. Thank you for reporting this issue. It seems that the TMDb scraper hasn't been updated in years...

Regards,
Andre
