### ISSUE TITLE
Runtime gets reset to "0" (zero) when using custom scraper

### ISSUE THREAD

**Issue by monisriz** [Komet/MediaElch#809]
**Describe the bug**
When using IMDb for scraping the runtime in custom scraper, the actual runtime gets reset to zero after the scraping is done. This doesn't affect all files but I have not been able to nail down why it happens for some and not for others. Scraping runtime using TMDb seems to be fine as far as I can tell (small sample size that I tested).

Runtime not being scraped:

https://www.imdb.com/title/tt0041094
https://www.imdb.com/title/tt0317219/

Runtime being scraped:
https://www.imdb.com/title/tt0103639/
https://www.imdb.com/title/tt0120623/

**MediaElch Version:**
 - [x] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [x] Windows
 - [x] macOS
 - [ ] Linux (distribution: ___)

IMDb scraper is essentially a HTML scraper that goes through the HTML code and based on various defined patterns "scrapes" the values. So from the IMDb scraper code, I can see that there are two different ways of scraping the "Runtime". @bugwelle might be able to provide more info about why is there a need to have two methods to capture one data-point? Maybe as a fail-safe in case one of these methods is not available for a given movie/tvshow.

**Comment by bugwelle** [comment]
From the top of my head: I think that it was because imdb provides two versions of a page based on your location, cookies,...
Or different movies have different layouts. 

There *was* a reason. I may remember the reason tomorrow :)

**Comment by monisriz** [comment]
from the HTML code, I can see that runtime info is specified in two places. One is in the script tag in json format and one as a regular html tag.
1. JSON: the format is slightly different for the above mentioned two cases. This change in matching pattern should take care of both cases.
2. HTML: the matching pattern had an attribute “item prop” which I could not find in the code for several movies I checked. Probably a deprecated attribute.

**Comment by bugwelle** [comment]
I don't remember now. I'll look at the code tomorrow. But I'm quite sure that it was due to imdb sometimes sending different html code. :)

**Comment by bugwelle** [comment]
Okay... I can't find an example where one runtime detection fails to work...
But I'm pretty sure that I got two different HTML versions of the same movie and I wasn't able to reproduce why that way the case. I thought maybe due to country or JavaScript detection...

You're PR looks good to me. I'll have to add a test for https://www.imdb.com/title/tt0317219/ so that we'll be able to detect this issue earlier the next time it happens.
