### ISSUE TITLE
Scrape results/images not displaying for non-Set movies (TMDb)

### ISSUE THREAD

**Issue by monisriz** [Komet/MediaElch#811]
**Describe the bug**
When scraping movies that are not part of the set (see below for reference), the scraped results do not populate in the UI. The images are not showing in their respective places either and only the default placeholders keep showing. The scraping progress bar (top right) is also missing. Basically there is no indication that the scraping has completed. The fields are inactive and some of the buttons in the top bar become inactive as well.

Only when the user clicks on another movie/title in the left pane and then clicks back on the scraped title, would they see the scraped information in the given fields. The images would still not show up instead of the placeholders. Clicking the placeholders obtains the images as usual however.

From my testing of different types of movies, the only common theme I could see was that the offending titles **did not** belong to a set/collection. The titles part of a set/collection scraped just fine. Since the collection info is scraped only by TMDb, I suspect recent changes for collections/sets in the TMDb scraper might be a good place to start...

**EDIT:** 
Just checked past few nightly versions. Only the two most recent nightlies seem to have this issue.
MediaElch_macOS_2.6.3-dev_2019-10-06_18-03_git-master-a03d9d0
MediaElch_macOS_2.6.3-dev_2019-10-11_05-59_git-master-f7b5a18

Reference:

Titles with this issue:
https://www.themoviedb.org/movie/497-the-green-mile
https://www.themoviedb.org/movie/10681-wall-e

Titles which scrape fine:
https://www.themoviedb.org/movie/694-the-shining
https://www.themoviedb.org/movie/812-aladdin

**MediaElch Version:**
 - [x] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [x] Windows
 - [x] macOS
 - [ ] Linux (distribution: ___)

**Comment by ticao2** [comment]
The same thing happens to me.
2.6.3 + Win 10

Titles with this issue:
https://www.themoviedb.org/movie/42595-strategia-del-ragno?language=pt-BR

Titles which scrape fine:
https://www.themoviedb.org/movie/9942-major-league?language=pt-BR

**Comment by ticao2** [comment]
Looking at Commit **[TMDb] Base url update**  we see that the new URL is this:
http://image.tmdb.org/t/p/  

But it seems to me it must be this:
https://image.tmdb.org/t/p/original/

**Comment by ticao2** [comment]
Original is the size of the image that has been blown into TMDb by users.
I don't know if here in ME, in some other file, another size is specified.

If it is, it may be a size that the new URL does not support.
The currently supported sizes are:

See here: https://developers.themoviedb.org/3/configuration/get-api-configuration
Some older ones may still work. But they can die at any time.
These are official sizes:

```
images
base_url "http://image.tmdb.org/t/p/"
secure_base_url "https://image.tmdb.org/t/p/"
backdrop_sizes
0 "w300"
1 "w780"
2 "w1280"
3 "original"
logo_sizes
0 "w45"
1 "w92"
2 "w154"
3 "w185"
4 "w300"
5 "w500"
6 "original"
poster_sizes
0 "w92"
1 "w154"
2 "w185"
3 "w342"
4 "w500"
5 "w780"
6 "original"
profile_sizes
0 "w45"
1 "w185"
2 "h632"
3 "original"
still_sizes
0 "w92"
1 "w185"
2 "w300"
3 "original"
```

**Comment by ticao2** [comment]
Forget everything I said.  
Sorry for my enthusiasm.  
I checked and in the **TMDb.cpp** file are the size specifications.
I ask for excuses.

**Comment by monisriz** [comment]
@ticao2 - You are right - base url doesn't affect this issue. Movies that are part of a set/collection scrape fine along with their poster and fanart in the main window. The issue only happens when a non-set related movie is being scraped. A recent set related change broke this and @bugwelle is aware of it.

**Comment by ticao2** [comment]
@monisriz  I know you did the Base url update.
Sorry for my enthusiasm.  :-)  

And yes, this change in SET made things weird.
My collections ran out of Poster or Fanart.
I already recaptured images from one of the collection.
I would like to know where these images are stored, in which folder.

**Comment by bugwelle** [comment]
Just had a look at it. The faulty commit is e1936dcd1848daed2172f35ee16eb4e4dba05d64 (using `git bisect`).

**Comment by bugwelle** [comment]
Fixed the issue btw.

Forgot a case. The `scraperLoadDone` event wasn't emitted if a movie didn't have a valid set id. I've fixed this locally. Will push the fix ASAP. :-)
