### ISSUE TITLE
[Scraper] Language Selection

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#813]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [x] TMDb
 - [ ] TMDbConcerts
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
Only in 2.6.3
I selected the pt-BR Language for TMDb and TMDb Concerts in Settings.
When I click on Scrape the language is in English, the search is done in English and the metadata comes in English.
Then in the Scraper interface I change the language to pt-BR.
Everything works correctly.
When I'm going to do another scrape of another movie, the selection has returned to the English language.

In 2.6.2 and 2.6.3
This problem already existed when it was clicked on poster to try to find another option.
The options searched are always in English and not in the language defined in settings.

**MediaElch Version:**
 - [x] 2.6.3-dev (nightly) MediaElch_2.6.3-2019-10-16_14-16
 - [x] 2.6.2 stable

**Operating System:**
 - [x] Windows 10
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**
I believe the language selected in settings should be selected in the Scraper UI.

**Comment by bugwelle** [comment]
Thank you for opening this issue. I was able to reproduce this. It will be fixed by #815 :smiley:
