### ISSUE TITLE
[Scraper] or [Bug] Concerts Adds Nothing

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#814]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [x] TMDbConcerts
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
Add a list of information that is not loaded correctly.

**MediaElch Version:**
 - [x] 2.6.3-dev (nightly)
 - [x] 2.6.2 stable

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**
Concerts Adds Nothing

It looks like it scans the folder but adds nothing.
Equal behavior in these 3 versions:
MediaElch_2.6.2_2019-09-13_19-28
MediaElch_2.6.3-2019-10-03_12-13
MediaElch_2.6.3-2019-10-16_14-16

It works almost correctly in this version:
MediaElch_2.6.1-2019-03-20_14-08
Does not read folder name. Uses the file name.
Name entered manually.
Scraper OK.

Remember that TMDb no longer has a Concert area.
I believe TMDb migrated the data to Movies in 2015.
But I think Kodi still has a concert area.

**Comment by bugwelle** [comment]
Oh. Thank you. Will look into this issue.

**Comment by bugwelle** [comment]
Hi, I wasn't able to reproduce this issue, yet. Do you have "Separate Folders" enabled in MediaElch's settings for your concert folder? Could you tell us your file structure?

This works for me:

```
.
├── Katy Perry: MTV Unplugged
│   └── concert.mov
├── RAMMSTEIN in Amerika
│   └── concert.mov
├── System Of A Down: Rock am Ring
│   └── concert.mov
└── System of a Down: Rock in Rio 2011
    └── Rammstein.mov # On purpose for testing
```

**Comment by ticao2** [comment]
Yes, "Separate Folders".

`VT_13_Concertos

	Diana Krall [2001] Let's Face The Music & Dance (2002) mkv@576p MMKV
		Diana.Krall.(2002).Let's.Face.The.Music.&.Dance.DVDRip.AC3x2.VOB9-MMKV.mkv
		Diana.Krall.(2002).Let's.Face.The.Music.&.Dance.DVDRip.AC3x2.VOB9-MMKV.nfo
		Diana.Krall.(2002).Let's.Face.The.Music.&.Dance.DVDRip.AC3x2.VOB9-MMKV-poster.jpg

	Diana Krall [2001] Live in Paris (2002) mkv@576p MMKV
		Diana.Krall.(2002).Live.in.Paris.DVDRip.DTSx6.AC3x6.VOB9-MMKV.mkv
		Diana.Krall.(2002).Live.in.Paris.DVDRip.DTSx6.AC3x6.VOB9-MMKV.nfo
		Diana.Krall.(2002).Live.in.Paris.DVDRip.DTSx6.AC3x6.VOB9-MMKV-poster.jpg

**Comment by ticao2** [comment]
I created a **Test Folder**.
I put in 3 videos: 2 from Diana Krall in **.mkv** and 1 from Mormon Tabernacle Choir in **.avi**
The 3 concerts have **Movie NFO**. But I have the previous **Concert NFO**.
So I created a copy of each of them with the **Concert NFO**.
And I created a **third copy** of each of them but this time **without NFO**.
So I got 9 concerts.
I will add this Test Folder to all versions of MediaElch I have.
And make an update. Let's see what happens.

**Comment by ticao2** [comment]
Result

MediaElch_2.6.0 **All OK**.
9 Concerts. 6 the NFOs were read. 3 without NFO, to make Scraper.

MediaElch_2.6.1-2019-03-20_14-08 **All OK**. Same as 2.6.0

MediaElch_2.6.2_2019-09-13_19-28 Problem. Nothing came up.

MediaElch_2.6.3-2019-10-03_12-13 Problem. Nothing came up.

MediaElch_2.6.3-2019-10-16_14-16 Problem. Nothing came up.

**Comment by bugwelle** [comment]
Thanks. I'll try to reproduce it.

**Comment by vidarak** [comment]
I have the same. I just upgraded from 2.4.2 to 2.6.2 and now the concerts aren't loaded. I have 3 folders with concerts in subfolders and 1 without subfolders. I can see it finds the folder names as it does the reload but the resulting lists contains 0 concerts.

**Comment by ljmarik** [comment]
How do I get version 2.6.0 or 2.6.1 as the Concerts doesn't work for me and this is why I downloaded the program.  Overall seems like a great program, but I want to use it solely for concerts.

**Comment by bugwelle** [comment]
Found one of possibly more issues:

https://github.com/Komet/MediaElch/blob/567ddb0fa0292fbb343411be4afe2c5ba2722aa9/src/scrapers/image/FanartTv.cpp#L310-L314

We want to load images from FanartTv and set the `url` accordingly but never assign the URL to the network request. Will fix it ASAP.

However, that seems to have never worked at all. If I have a look at the code from about 6 years ago, I can see that the bug existed back then as well. 

https://github.com/Komet/MediaElch/blame/ed005f45684375c515499be150051dd802b05a2e/imageProviders/FanartTv.cpp#L320-L327

**Comment by bugwelle** [comment]
Could you paste the contents of of one of your concert's `NFO` files here? :-)

**Comment by ticao2** [comment]
Hi

The same show. Diana Krall "Diana Krall [2001] Let's Face The Music & Dance", in 3 different folders.
Added in MediaElch as Concerts and 1 movie per folder ie separate folders.
Folder 1, without .NFO file.
Folder 2, with **old** .NFO file, generated in **Concerts**.
Folder 3, with **new** .NFO file, generated in **Movies**.

In MediaElch 2.6.0
Folder 1 = Recognized **.mkv** file and marked it as ready to make the Scraper.
Folder 2 = Acknowledged the old .NFO of concerts and everything is OK.
Folder 3 = Recognized .NFO movie,  but some data is missing.

In MediaElch 2.6.4
Nothing appears. Nor does it recognize the .mkv file

**Comment by ticao2** [comment]
Concert

**Comment by ticao2** [comment]
Movie

**Comment by bugwelle** [comment]
Hi,

thanks. I'm still not able to reproduce the error but I think I'm getting somewhere. Could you please enable the debug log in your `advancedsettings.xml` and paste the contents of it here after you tried to reload all concerts? I added some more checks between v2.6.0 and v2.6.2 that check whether the directory is readble, etc.

Furthermore, what are the contents of your `advancedsettings.xml`? I'm interested in the value of `fileFilters->concerts`, e.g. 

```xml
    <fileFilters>
        <movies>
            *.mkv,*.mk3d,*.avi,*.mpg,*.mpeg,*.mp4,*.m2ts,*.disc,
            *.m4v,*.strm,*.dat,*.flv,*.vob,*.ts,*.iso,*.ogg,*.ogm,
            *.rmvb,*.img,*.wmv,*.mov,*.divx,VIDEO_TS.IFO,
            index.bdmv,*.wtv"
        </movies>
        <tvShows>
            *.mkv,*.mk3d,*.avi,*.mpg,*.mpeg,*.mp4,*.m2ts,*.disc,
            *.m4v,*.strm,*.dat,*.flv,*.vob,*.ts,*.iso,*.ogg,*.ogm,
            *.rmvb,*.img,*.wmv,*.mov,*.divx,VIDEO_TS.IFO,
            index.bdmv,*.wtv"
        </tvShows>
        <concerts>
            *.mkv,*.mk3d,*.avi,*.mpg,*.mpeg,*.mp4,*.m2ts,*.disc,
            *.m4v,*.strm,*.dat,*.flv,*.vob,*.ts,*.iso,*.ogg,*.ogm,
            *.rmvb,*.img,*.wmv,*.mov,*.divx,VIDEO_TS.IFO,
            index.bdmv,*.wtv"
        </concerts>
        <subtitle>
            *.idx,*.sub,*.srr,*.srt,*.ass,*.ttml
        </subtitle>
    </fileFilters>
```

**Comment by vidarak** [comment]
Thanks for looking into it. I don't have any advancedsettings.xml.
According to https://mediaelch.github.io/mediaelch-doc/settings.html it is an optional file.

**Comment by bugwelle** [comment]
@vidarak Good to know! That means it happens with default settings as well. I would still like to see a debug log. Could you create a file `advancedsettings.xml` in the same folder as `MediaElch.exe`?

```xml
<?xml version="1.0" encoding="utf-8"?>
<advancedsettings>
    <!--
        If you want to enable the debug mode, change false to true and set a
        path to a log file. The path should either be absolute or relative
        to the MediaElch application directory.
    -->
    <log>
        <debug>true</debug>
        <file>./MediaElch.log</file>
    </log>
</advancedsettings>
```

Then start MediaElch, try to reload concerts, close MediaElch and paste the contents of `MediaElch.log` here. That file should be in the same folder as `MediaElch.exe` and the `advancedsettings.xml`. 😃 
You can go through the file and remove / replace filenames if they contain sensitive information. That would be very helpful!

**Comment by ticao2** [comment]
I always use the ME in portable mode. Therefore, with advancedsettings.xml.
My filters:

```
<!-- fileFilters = defines the extensions of files MediaElch will scan. -->
<!-- Multiple extensions can be added comma separated. -->
<!-- A special case is subtitle these files will also be renamed when renaming a movie. -->
	<fileFilters>
		<movies>*.avi,*.mkv,*.mp4,*.m4v,*.mov,*.flv,*.mpcpl,*.ifo,*.vob,*.iso,*.disc</movies>
		<concerts>*.avi,*.mkv,*.mp4,*.m4v,*.mov,*.flv</concerts>
		<tvShows>*.avi,*.mkv,*.mp4,*.m4v,*.flv</tvShows>
		<subtitle>*.srt,</subtitle>
	</fileFilters>

```

I never used the debugger. I'll try.

**Comment by bugwelle** [comment]
Thanks. I have to admit that I tried to reproduce your issue on my MacBook. Just tried it on my Windows machine and I'm seeing the exact same problem. I'll look into it ASAP.

**Comment by ticao2** [comment]
And ... I did it. Here is the debug file.
[MediaElch_02.txt](https://github.com/Komet/MediaElch/files/4334490/MediaElch_02.txt)

**Comment by bugwelle** [comment]
Thanks. I get the same log. No warnings or errors related to this issue, though. :-/

**Comment by ticao2** [comment]
I don't use Kodi anymore.
So I don't know if that makes a difference.
TMDb in the past, 2013/2015, had an area only for concerts.
Today there is no more. The concerts are with the films.
This may interfere with API Requests.
But of course, there remains the problem of ME not finding any files.

**Comment by bugwelle** [comment]
> But of course, there remains the problem of ME not finding any video files.

Which is strange because it only happens on Windows. I'm currently compiling MediaElch on Windows so that I can debug it. My Windows machine is very slow, though. It will take a while.

**Comment by bugwelle** [comment]
Oh my god... I found the issue:

```cpp
if (files.at(0).startsWith(m_directories[i].path.path())) {
```

Entries in `files` are just strings, e.g. `C:\Directory`. Qt's `QPath::path()` method returns a normalized path, e.g. `C:/Directory`. Comparing those two strings fails of course...

Offending commit: 78e169d196b7a55adb0fd7fbe15e79211ae29dbf

**Comment by bugwelle** [comment]
Fixed. Next nightly should work :)

**Comment by ticao2** [comment]
👍
