### ISSUE TITLE
[Bintray] Account resource usage limits were met for 'komet'

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#818]
Hi,

the resource limits were met. See:

 - https://travis-ci.org/Komet/MediaElch/jobs/600359501
 - https://travis-ci.org/Komet/MediaElch/jobs/600359504

@Komet Any updates on this? I don't find any Windows Nightlies anymore so I assume you already deleted old versions? 😃

**Comment by Komet** [comment]
I've deleted all builds except the last one yesterday (accidently all Windows builds). We have to wait for Bintray to remove the rate limit on the account.

**Comment by bugwelle** [comment]
Ah, ok. Thanks. :)

**Comment by monisriz** [comment]
Could Github be used as an alternative/backup for nightly releases?

**Comment by bugwelle** [comment]
Thought about it but didn't have the time to implement. I'm also unsure whether it requires a git tag (I'd like to avoid having to tag the latest commit all the time).

**Comment by Komet** [comment]
Rate limitation has been removed on bintray.

**Comment by bugwelle** [comment]
Great! I've restarted the Windows build.

**Comment by bugwelle** [comment]
Reopening. @Komet Could you clear the list again before the account resources are exceeded again? :-)

Btw. did you get my mail from last month?

**Comment by bugwelle** [comment]
Cleared. There is only one nightly available from 2020-04-04. Thanks, @Komet

**Comment by bugwelle** [comment]
@Komet The files are deleted (only one version is left over) but TravisCI says that resource limits were reached. Does the account still need to be re-activated? :smiley:

**Comment by Komet** [comment]
I've already contacted the support on 2020-04-05, still waiting for bintray removing the limitation.

**Comment by bugwelle** [comment]
OK, thanks. :)

**Comment by bugwelle** [comment]
Works again. :-)
