### ISSUE TITLE
[Scraper] AdultVODEmpire Scraper as variant of AdultDVDEmpire

### ISSUE THREAD

**Issue by waywit** [Komet/MediaElch#819]
**Is your feature request related to a problem? Please describe.**
Some movies are only listed at "adultdvdempire" as video on demand and not as DVD. Searchin with the UI brings a result, but with the scraper not.

**Describe the solution you'd like**
I think there are differen possible solutions:
1. Copy AdultDVDEmpire Scraper to AdultVODEmpire Scraper and change some names, IDs and the search string from:
`QUrl url(QStringLiteral("https://www.adultdvdempire.com/dvd/search?view=list&q=%1").arg(encodedSearch));`
to
`QUrl url(QStringLiteral("https://www.adultdvdempire.com/vod/search?view=list&q=%1").arg(encodedSearch));`

2. Change AdultDVDEmpire Scraper to search in "all" categories by changing the search string to:
`QUrl url(QStringLiteral("https://www.adultdvdempire.com/allsearch/search?view=list&q=%1").arg(encodedSearch));`

3. Change AdultDVDEmpire Scraper to search in DVD and VOD movies, but then I do not have any idea hw this may work.

**Describe alternatives you've considered**
I have found no alternatives.

**Additional context**

**Comment by bugwelle** [comment]
> Change AdultDVDEmpire Scraper to search in "all" categories by changing the search string to

Didn't know that there was `all` available. I can try and change that. :)

**Comment by waywit** [comment]
I have tried it locally with my own build and "allsearch" brings back more results, some are doubled... if "dvd" and "vod" are available, but as I see both sides are identically.

But during my tests I found out that the plot is not loaded with the latest source code anymore, perhaps this is because of a change on "adultdvdempire" site? But here I did not found out anymore, perhaps you can take a short look into it...? I may also open a Bug for this?

**Comment by bugwelle** [comment]
Thanks. We have scraper tests that I run occasionally. But I haven't run them in like two weeks and can't run them on my work computer due to the nature of ADA. I'l look into it on the weekend.

**Comment by waywit** [comment]
Thanks :-) If you need further information or support from my side do not hesitate to ask ;-)

**Comment by bugwelle** [comment]
@waywit I couldn't find any movie that uses `<p class="markdown-h1">` anywhere. Do you have an example (a more or less safe-for-work title would be appreciated).
Even though I couldn't find an example I changed the regex to be prepared for such changes. MediaElch now also uses "allsearch" instead of "dvd" for searches. To distinguish between duplicates, I added `[DVD]`, `[BlueRay]` and `[VOD]` as prefixes to the search results. 

Are you fine with these changes? If so, I'll merge the pull request after all tests succeed.

**Comment by waywit** [comment]
Hi @bugwelle 
great, great, great :-) Thanks a lot for your work! I can also do some testing as soon as your changes are available in git.

I have looked which movie I had found and put all information here: https://pastebin.com/CShwZ1jZ 
So you can decide when you want to take a look into it, should be safe to  ;-)

**Comment by bugwelle** [comment]
Ah, got it:

```html
<p class="markdown-h1">Scenes Include</p><p class="markdown-h2">Amicable Payment</p><p>Content...
```

The movie consists of multiple scenes which are each described here. This needs some more coding on my side. :)
