### ISSUE TITLE
Old UI does not display some specific years

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#821]
**Is your feature request related to a problem? Please describe.**
Old UI does not display some specific years

It was a BUG, but from versions **2.6.1 2019-03-20** and **2.6.0**
I always install MediaElch in Portable mode.
So I have several versions in use on the same computer.

I recently realized that in my version **2.6.0** the UI does not display some specific Release Year.
They are: 2019, 2013, 2008, 2002, 1991, 1985, 1980 and 1974.
My collection features movies from every year from 2019 to 1929.
So my check is valid until 1929.

If I use the filter by year, movies from these years appear in the UI, but the UI does not display the Release Year.
The data is in NFO, but for some reason is not displayed.
I have been checking if any other version has this problem.
Version **2.6.1_2019-03-20** is also with the same behavior.
The other versions installed are not having the problem. Are they:
2.6.2 2019-09-13
2.6.3 2019-10-03
2.6.3 2019-10-16
2.6.3 2019-10-20
2.6.3 2019-10-25

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by monisriz** [comment]
Can you please check if there is any difference in the NFO files for the working and non-working titles? Specifically check whether some years are listed in the nfo under <year></year> tags as opposed to <premiered></premiered> tags..

**Comment by bugwelle** [comment]
> My collection features movies from every year from 2019 to 1929.

First of all: Impressive 👍 

Then @monisriz asked the right questions. Could you check `premiered`  and `year` tags? :)

**Comment by ticao2** [comment]
MediaElch Premiere Date Test

Most are just tagged with the year.
`2019-07-16	<year>2019</year>	The.Wolf's.Call.2019.1080p.BluRay.x264-[YTS.LT].nfo
2019-10-03	<year>2019</year>	Dumbo.2019.1080p.BluRay.6CH.x264.DUAL-BLUDV.nfo
2019-08-06	<year>2019</year>	The.Professor.and.the.Madman.2019.1080p.WEB-DL.DD5.1.H264-CMRG[EtHD].nfo
2019-06-29	<year>1974</year>	Mame.1974.1080p.BluRay.x264-[YTS.AM].nfo
2019-06-28	<year>1974</year>	The.Enigma.Of.Kaspar.Hauser.1974.1080p.BluRay.x264-[YTS.LT].nfo
2019-07-21	<year>1974</year>	The.Taking.Of.Pelham.One.Two.Three.1974.1080p.BluRay.x264-[YTS.AM].nfo
2017-08-03	<year>1974</year>	Alice Doesn't Live Here Anymore
2017-11-12	<year>1974</year>	The.Great.Gatsby.1974.1080p.BluRay.x264.ENG.ITA-Shiv@.nfo`

Since I didn't find any NFOs that contained both tags,
I made the scraper of the year some to check then would appear in the UI.
`2019-10-28	<year>2019</year>	<premiered>2019-02-20</premiered>	The.Wolf's.Call.2019.1080p.BluRay.x264-[YTS.LT].nfo
2019-10-28	<year>2019</year>	<premiered>2019-03-27</premiered>	Dumbo.2019.1080p.BluRay.6CH.x264.DUAL-BLUDV.nfo
2019-10-28	<year>2019</year>	<premiered>2019-02-14</premiered>	The.Professor.2018.1080p.WEBRip.x264-[YTS.AM].nfo

2019-10-29	<year>1974</year>	<premiered>1974-03-07</premiered>	Mame.1974.1080p.BluRay.x264-[YTS.AM].nfo
2019-10-29	<year>1974</year>	<premiered>1974-11-01</premiered>	The.Enigma.Of.Kaspar.Hauser.1974.1080p.BluRay.x264-[YTS.LT].nfo
2019-10-29	<year>1974</year>	<premiered>1974-10-02</premiered>	The.Taking.Of.Pelham.One.Two.Three.1974.1080p.BluRay.x264-[YTS.AM].nfo`

Nothing changed. These years I listed do not appear in the UI.

**Comment by ticao2** [comment]
Films with date or year before 1929 I have only **9**.
I was checking if these years are having trouble appearing in the UI.
No problem. All these years appear in the **2.6.0** UI.

1927 Wings
1927 Sunrise: A Song of Two Humans
1927 Metropolis
1927 The Lodger: A Story of the London Fog
1925 Bronenosets Potemkin
1924 The Iron Horse
1918 The Cook
1903 The Great Train Robbery
1902 Le Voyage dans la Lune

**Comment by bugwelle** [comment]
Hi there,

sorry for the late answer. I wasn't able to reproduce your issue... :/
However I found an issue with empty or invalid `<premiered>` tags that overwrote the value of `<year>` tags. That will be fixed by #827 

If the next nightly version does not fix your issue, could you paste the developer information here? (available in the "About" dialog)

Regards,
Andre

**Comment by ticao2** [comment]
Hi @bugwelle  

As I said earlier, **this problem** that I reported **does not exist in current versions, 2.6.2 and 2.6.3**
This issue **only** affects **older versions** of MediaElch, versions **2.6.0 and 2.6.1**.
So nothing that is done now will affect the old versions, the problem versions.
I just reported to your knowledge of this **strange BUG**.
But for what I reported **nothing needs to be done**, since it does not happen in recent versions.
But at least it was worth it for you to find another problem. :-)

**Comment by bugwelle** [comment]
Don't know what could have caused it... :/
Would be interesting, though. I'll close this issue now. If you experience this issue anytime again, please let me know :-)

**Comment by ticao2** [comment]
Without a doubt it must be an interesting problem for you.  :-)
Very intriguing. I've never seen anything like it.
But, considering the immense amount of problems and necessary and desired implementations, it is better to leave this problem for later.
Also because it does not affect the new versions.
But it is certainly intriguing. And very "illogical".

tks
