### ISSUE TITLE
[Scraper] After fix actors were not loaded with AultDVDEmpire scraper anymore

### ISSUE THREAD

**Issue by waywit** [Komet/MediaElch#824]
**Describe the bug**
During my tests for #819 I found out, that new movies does not get actors even though they are listed on the corrosponding html site.

**To Reproduce**
1. Screpe new movie (with actors on adultdvdempire) and scrape it
2. Check actors tab and folder/movie.nfo

**Expected behavior**
all actors from html site are also in NFO and .actors directory

**Screenshots**

**MediaElch Version:**
 - latest git build

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [X] Linux (distribution: Ubuntu 18.04.3 LTS)

**Additional context**
I am not sure if the site was changed or the bugfix has something to do with it. I checked the "infos.contains(MovieScraperInfos::Actors)" but did not fully understand how this regex works :-(

**Comment by bugwelle** [comment]
Thank you for reporting this issue. Maybe something broke but we have scraper tests for actors here:

https://github.com/Komet/MediaElch/blob/465ee80e745bd9afc78f145930f0853bd87f6014/test/scrapers/testAdultDvdEmpire.cpp#L60-L68

I didn't run the tests since my last PR regarding ADE. Just like the last time this will take a few days since I can't run the tests on my work computer. :)

**Comment by waywit** [comment]
Hi, no problem... good things will take some time ;-)

I tried to run the automatic tests for myself but could not get them running... I tried to run them using this https://mediaelch.github.io/mediaelch-doc/contributing/testing.html instructions and also as described in the source code in "docs/contributing/testing.md" :-(

Thanks a lot for taking care :-)

**Comment by bugwelle** [comment]
Oh, the first link with qmake ist outdated... I'll remove that page. :)

**Comment by waywit** [comment]
Hi @bugwelle 

do you have any tip to get the test running...? Actually they fail with the following error:

```
MediaElch/test/build$ cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja
CMake Error at mocks/CMakeLists.txt:4 (mediaelch_post_target_defaults):
  Unknown CMake command "mediaelch_post_target_defaults".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "MediaElch/test/build/CMakeFiles/CMakeOutput.log".
```

The stated log file does not contain any errors... but I am not very familiar with running such tests in linux...

Thanks and best regards
Jens

**Comment by bugwelle** [comment]
Hi,

you nearly had it :)
You need to use the root `CMakeLists.txt`:

```
MediaElch/test/build$ cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja
```
You're using the `CMakeLists.txt` file from the `test` folder. It should be:

```
MediaElch/test/build$ cmake ../.. -DCMAKE_BUILD_TYPE=Debug -GNinja
```

**Comment by bugwelle** [comment]
Hi there,

I finally had time to debug this (on my private PC). Sorry for the delay. I scraped a random movie with ADE, clicked on "save" and checked the directory.

```
$ tree -a
.
├── .actors
│   ├── Bianca_Breeze.jpg
│   ├── Bibi_Noel.jpg
│   ├── Bolaji_Badejo.jpg
│   ├── Callie_Calypso.jpg
│   ├── Harry_Dean_Stanton.jpg
│   ├── Helen_Horton.jpg
│   ├── Ian_Holm.jpg
│   ├── Jessy_Jones.jpg
│   ├── John_Hurt.jpg
│   ├── Lea_Lexis.jpg
│   ├── Luna_C._Kitsuen.jpg
│   ├── Meiko_Askara.jpg
│   ├── Sarah_Shevon.jpg
│   ├── Sigourney_Weaver.jpg
│   ├── Tom_Skerritt.jpg
│   ├── Veronica_Cartwright.jpg
│   └── Yaphet_Kotto.jpg
├── movie-fanart.jpg
├── movie.mkv
├── movie.nfo
└── movie-poster.jpg

1 directory, 21 files
```

And it worked. I'll need a movie name where this happens :)

**Comment by waywit** [comment]
Hi, please try "Good Times" from 2017: https://www.adultdvdempire.com/1905366/good-times-porn-movies.html

There you can find many actors: "Starring:  Karlee Grey, Violet Starr, Ryan Madison, Logan Long, Jenna Reid, Alex Legend" but none of them showed up in MediaElch nor on my HD...
I have used the newest sources from git and build a clean binary for my actual test...

Thanks and best regards...

**Comment by bugwelle** [comment]
Thanks for letting me know. On my machine all actors with images were loaded (4 actors)...
However I found another issue: Old actor images are not deleted.. The ones in my previous post are actors of another movie (Argo 2012 I believe).

**Comment by waywit** [comment]
I think I have messed up something here... I deleted all configs, checked out into a new folder, build, installed and now it works... thanks for your effort and please excuse me for any inconvenience.
I close this issue...

**Comment by bugwelle** [comment]
Thanks for letting us know :-)
