### ISSUE TITLE
[Scraper] TMDb - Search with Wrong Date

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#825]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [x] TMDb
 - [ ] TMDbConcerts
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
[Scraper] TMDb - Search with Wrong Date.

Movie date does not match correct release date.
This problem only occurs with movies that will be added to the collection, which still **do not have an NFO**.
In addition, movies that also have latest release or re-release dates on TMDb from DVD or Bluray.

This is because in the initial TMDb API response is the field **"release_date"**, and comes with the last date registered for a given language.
What we need is the **"primary_release_date"** field, with the original release date, the first in the world.
TMDb has already been asked for a fix.
https://trello.com/c/ch1IcrmO/47-add-primaryreleasedate-field-to-media-cache-results
The question remains when and how this correction will be made.

As an example, the movie **Babette's Feast (1987)**  
https://www.themoviedb.org/movie/11832-babettes-g-stebud/edit?active_nav_item=release_information  
On this page we can see that in addition to the theatrical release dates of the late 1980s,  
we also have in some countries more recent DVD and Bluray release dates.
The languages​​/countries with these date variations in this movie are:
Portuguese (Brazil), Spanish (Spain), English (US), French (France), Dutch and Swedish.
If you search for the language of any of these countries, we can see that the release year varies greatly.

How to test:
Create a folder with the title **Babette's Feast (1987)**
Insert a small file, poster, or .txt file with the title of the movie.
**Babettes.Gaestebud.1987.720p.BluRay.AVC-mfcorrea.txt**
Make a copy and rename using the extension .avi
**Babettes.Gaestebud.1987.720p.BluRay.AVC-mfcorrea.avi**
So MediaElch will find the **fake movie**.
Do a search on **TMDb**.
To check just change the language selected in the language dropdown.
For each of the above languages ​​there will be a different release year.

As a byproduct of this test, I noticed that the Swedish date is different than it should be.
Maybe it's some problem with ISO code.

**MediaElch Version:**
 - [x] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**

**Comment by bugwelle** [comment]
Hi @ticao2 

thanks for opening this issue. I currently don't have enough time to work on this. 
I hope to be able to look into this in the next two weeks. Thank you.

Regards,
Andre

**Comment by ticao2** [comment]
I don't think you need to devote time to this problem right now.  
When TMDb implements the fix I notice here.  
The MediaElch file that will need to be modified, I think I already found it.  
And I believe the correction will be only to exchange one expression for another.

**Comment by ticao2** [comment]
Problem solved.
Nothing needs to be modified in MediaElch.
Look here: https://trello.com/c/8OU4ox4i/51-specifying-the-region-isnt-returning-the-right-date

**Comment by bugwelle** [comment]
Thanks! :)
