### ISSUE TITLE
Wrong file sizes displayed in import list

### ISSUE THREAD

**Issue by acolomb** [Komet/MediaElch#829]
**Describe the bug**
The file sizes reported in the "Importable items" list are totally mixed up. Most display very large negative numbers, some display too small but positive numbers.

**To Reproduce**
1. Go to 'Import' section
2. Check the 'Size' column for any file listed there

**Expected behavior**
Correct file size displayed for each file.

**Screenshots**
![Screenshot from 2019-11-10 18-16-32](https://user-images.githubusercontent.com/6996887/68547817-616b3a00-03e6-11ea-886c-04e314f3cb50.png)

**MediaElch Version:**
 - [x] 2.6.3-dev (nightly)
 - [x] 2.6.2 stable

Both versions are self-built and run from the build directory (without installation). Version 2.6.2 was also tried when installed from the stable PPA. Last working version which I used was 2.6.0, no problem there.

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: Ubuntu 18.04 LTS)

**Additional context**
The import directory is mounted from a CIFS share if that makes any difference. File sizes show correctly in other programs though.

**Comment by bugwelle** [comment]
Thank you. I'll have a look at it. The import feature is one thing I haven't used at all... :-/

**Comment by bugwelle** [comment]
Ok, are the files with negative numbers larger than 4GB? Then I know the reason this happens.
And the other files: How far off are the values? e.g. for a 10MB file it shows 9MB? The may be a wrong calculation factor. I don't know if we show MB (MegaByte) or MiB ([MebiByte](https://en.wikipedia.org/wiki/Mebibyte)). I'll look into it :-)

**Comment by acolomb** [comment]
Yesterday I checked again and found some that displayed 1.53 GB where the file was actually roughly 5 GB. There seems to be no obvious pattern for when it's a wrong positive number and when it's an insanely negative number (which always appears in bytes by the way).

**Comment by bugwelle** [comment]
I have an idea what may be causing that bug. I'll look into it this evening :-)

**Comment by bugwelle** [comment]
This issue will be fixed by #927.

The reason it showed strange numbers was because of a change I made over a year ago. Instead of using a `double` number I used an `int`. `int`s only have 32bit. We store the file size in Bytes and `2^32` Bits can only store numbers that represent up to 4GB (or 2GB because one bit is the sign bit). It's fixed now (tested locally).

On top of that MediaElch never showed file sizes in kB, MB and GB but in kiB, MiB and GiB (see https://en.wikipedia.org/wiki/Mebibyte ). That's fixed now as well.

Sorry for the inconvenience and thanks for reporting!

PS: We now display the the numbers in the user's locale (e.g. `,` for German, `.` for English as the decimal sign).

**Comment by acolomb** [comment]
Thanks for the fix, will test this weekend hopefully.

> On top of that MediaElch never showed file sizes in kB, MB and GB but in kiB, MiB and GiB (see https://en.wikipedia.org/wiki/Mebibyte ). That's fixed now as well.

In my opinion, this is a false "fix". Pretty much every computer program traditionally shows the binary-based (factor 1024) numbers, including file managers like Windows Explorer. The only place you usually see decimal kB, MB, GB is for the capacity printed on hard disks. That's why a 1 TB drive shows up as only about 931 GiB additional space you can use for files.

I'd vote for using factor 1024 again.

**Comment by bugwelle** [comment]
> Pretty much every computer program traditionally shows the binary-based (factor 1024) numbers

I first checked it with my MacBook. macOS' Finder shows file sizes in MB, GB, etc. (i.e. with factor 1000) and not MiB, GiB (i.e. with factor 1024) and that's why I switched it in MediaElch as well.

I won't change it back but I will instead show both sizes if that works for you. :-)

To cite [Wikipedia](https://en.wikipedia.org/wiki/Megabyte):

>  A common usage has been to designate one megabyte as 1048576bytes (220 B) [...] However, most standards bodies have **deprecated this usage in favor of a set of binary prefixes**

**Comment by acolomb** [comment]
Fair enough, it's not like displaying file sizes is the most important feature in MediaElch ;-) From a scientist's point of view, I agree that anything with a `k`, `M` or `G` prefix should actually factor in powers of ten.

Duplicating the display is not worth the screen space IMO.

**Comment by bugwelle** [comment]
> Duplicating the display is not worth the screen space IMO.

I agree. I also thought about having sizes with a factor of 1024 as a Tooltip. That may be better. :)  
Thanks!

**Comment by bugwelle** [comment]
For reference: #930

**Comment by acolomb** [comment]
I confirm that the sizes are now displayed correctly as of commit 9b98b68bc0cb1b48d224a2260542738c5dd82db3, though it does look strange with both sizes. So #930 sounds like a nice solution.

I stand corrected, in fact my file manager (Nautilus) does display 1000-based MB sizes. Didn't know the GNOME world was brave enough to move past that legacy :-)

**Comment by bugwelle** [comment]
> Didn't know the GNOME world was brave enough to move past that legacy :-)

Didn't know that either. So it's just Windows? 😃

**Comment by acolomb** [comment]
Did a quick comparison for one file in question:
GNOME Nautilus: 2.5 GB (correct unit)
Windows Explorer: 2,445,040 KB (JEDEC unit - metric would be kB). In the file properties window, it displays as 2.33 GB.
Synology Disk Station Manager: 2.33 GB.
MediaElch: 2.50 GB (2.33 GiB)

At least they all agree on the real file size, exactly 2,503,720,578 bytes.

**Comment by bugwelle** [comment]
Thanks! :-)
