### ISSUE TITLE
High CPU usage after several imports

### ISSUE THREAD

**Issue by acolomb** [Komet/MediaElch#830]
**Describe the bug**
After importing a movie, idle CPU usage of MediaElch rises significantly. Usually after two to three imports, it eats a whole CPU core and the UI becomes noticeably sluggish until restarting MediaElch.

**To Reproduce**
1. Go to 'Import' section.
2. Import several movie files, for each selecting a scraper match and hitting 'Import', then 'Close' on the import dialog.
3. Watch the CPU usage of the MediaElch process rise.

**Expected behavior**
CPU usage should return to normal level after import and be very low when not interacting with the GUI.

**MediaElch Version:**
 - [ ] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable
 - [x] 2.6.0 old stable

Unfortunately I cannot try to reproduce with an up-to-date version because of #828, which won't even let me import a single movie file. I grabbed the old 2.6.0 AppImage to have any working MediaElch at all.

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: Ubuntu 18.04 LTS)

**Additional context**
This problem has persisted for a couple of years already as far as I remember, but the workaround of restarting MediaElch after every couple of imports is getting very annoying by now. Sorry for not reporting earlier, I had a relevant stack trace once that led me to believe it's doing some image processing in the background, but cannot reproduce that now without an up-to-date development version. Any hints on how to investigate further are very welcome.

**Comment by bugwelle** [comment]
Thank you. I'll have a look at it. The import feature is one thing I haven't used at all... :-/

**Comment by bugwelle** [comment]
I'm not yet able to reproduce this issue in the latest versions. I've imported 4 items (each 100MB) and the CPU usage was and is still at 1%. :/

**Comment by bugwelle** [comment]
Do you use the AppImage? I'll try to fix #828 first.

**Comment by acolomb** [comment]
> Do you use the AppImage? I'll try to fix #828 first.

The 2.6.0 AppImage is just my workaround to have any working version at all.  This problem already appeared when the PPA version was still at 2.6.0.  However, I cannot find that old .deb file anywhere for comparison.

Solving #828 first sounds like a reasonable plan, because that one currently keeps me from testing development builds and doing any sensible debugging.

**Comment by bugwelle** [comment]
I can confirm that MediaElch not only has an unusual high amount of CPU usage but also a lot of memory usage.

**Comment by bugwelle** [comment]
MediaElch searches for files (download section) synchronously. I have only set one download folder with only few files and it takes over 1 second to search for everything. I'll refactor the code and will make it work asynchronously so that MediaElch does not freeze.

**Comment by bugwelle** [comment]
There are so many bugs in that feature that it will take longer than expected. I found some race conditions in MediaElch's DownloadManager due to fanart.tv being under heavy load.

**Comment by bugwelle** [comment]
#928 *may* fix your issue. There were multiple bugs that I had to fix. Here's an overview of my changes:

 - Fix crashes when importing items
 - Fix endless download loop that can occur when a scraper is used to download images
 - Make it *way* faster to reload the download section (in my case from 1.9 second down to 0.2 seconds for a small folder).  
   The reason for the high memory usage was that for *each* download item an import dialog was created (but not shown). That however was not necessary. MediaElch now creates the ImportDialog only when an item is actually downloaded
 - Make the file searcher asynchronous / non-blocking. MediaElch now uses another Thread to search for files so that MediaElch is more responsive.

**Comment by bugwelle** [comment]
Please note that there is yet another bug that I didn't fix, yet. After importing an item, the list of importable items "crashes". Well, it doesn't crash but all "Import" buttons may disappear. You *may* need to restart MediaElch then. I'll open another issue for that. :-)

**Comment by bugwelle** [comment]
See #929

**Comment by acolomb** [comment]
Thanks for your work on this.

The high CPU usage in fact did not occur anymore while testing 9b98b68bc0cb1b48d224a2260542738c5dd82db3. However, imports now take much longer after choosing the matching title - estimated about a minute stuck in "Loading movie information...". Would be great to have some indication about **what exactly** MediaElch is doing, in order to take measures if e.g. just some scraper is slow to respond. Judging by the console output, in fact it's fanart.tv timing out.

The step after that takes a bit long as well. When it shows "Movie information was loaded", I press the Import button, then it takes a few seconds during which the spinner is not moving. Can't imagine why *renaming* a couple of files and writing out some XML should take that long, even on a Wifi-attached SMB share.

Fortunately, I did not encounter the "crashing" problem you describe. Looking forward to your future refactoring, keep up the good work!

**Comment by bugwelle** [comment]
Yeah, MediaElch is not good when it comes to showing errors. It has improved a lot but is still not perfect.

The reason why it takes so long is that MediaElch tries to download images from fanart.tv but that page is under such heavy load that all requests run into a timeout. And MediaElch retries to load each image 3 times. 3 times 6 second times `N` images...  

> I press the Import button, then it takes a few seconds during which the spinner is not moving.

Thanks. I haven't looked into that, yet. There are a few places where a spinner or some other progress indicator is missing or is activated too late.

> Can't imagine why renaming a couple of files and writing out some XML should take that long

When I "import" a file it is copied and not moved. I never really used the Download section. Still new to me :-)  
I'll have a look at it.

> Fortunately, I did not encounter the "crashing" problem you describe. Looking forward to your future refactoring, keep up the good work!

Thanks for your feedback. Sorry, that it took so long.
