### ISSUE TITLE
TheTVDB malfunction.

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#833]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [ ] TMDbConcerts
 - [X] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
If the show already is scraped and have an TheTVDB ID assigned no info or images are found if you try to scrape a new episode since searching for an ID results in no hits. If you search for the show name you still wont get any images but the info is scraped. Not without errors though since Display Season is set to 0 and Display Episode is set to 4096 on every episode.
**MediaElch Version:**
 - [X] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**
I know they are having some issues but things should be up and running as far as I can understand.
Can this has something to do with it?
https://forums.thetvdb.com/viewtopic.php?p=163128#p163128

**Comment by claunia** [comment]
I don't think that is the issue as what I see in the console is:
 `https://artworks.thetvdb.com/banners//person/8034235/tv-250487.jpg`

Repeated for every artwork file.

**Comment by bugwelle** [comment]
Oh man. Thank you for reporting. I'll look into it. We're still using an outdated API version of TheTvDB..

**Comment by bugwelle** [comment]
Hi,

I've merged the new TheTvDb API code a month ago. I tried to reproduce your issue the following way:

 1. Scrape show and all episodes of "Family guy" that I have available
 2. Add a new season with two episodes
 3. Reload all shows
 4. Select first of the two new episodes
 5. Scrape ("id75978" is shown in the scrape window)
 6. Details + Thumb is loaded
 7. Save all
 8. Click on show and select "Update new episodes" in search dialog
 9. Check that second episode has all details + thumb

I plan to release a new stable version in the middle of January. Could you then test it again? :)
(Or a nightly version)

**Comment by psonnosp** [comment]
Sorry, forgot about this and should've updated it. Image and details issues probably had to do with something at thetvdb like claunia mentioned cause that began working  a while ago.
Only thing not working was the display episode/season info but updated to a new nightly a few days ago and now fill the fields with -1 as expected.

Thanks for your work!

**Comment by bugwelle** [comment]
> and now the fields are filled with -1 as expected.

Good to hear. Updated that a month ago and it should work now 😃 

Thank you for the fast answer and confirmation. 👍
