### ISSUE TITLE
Add TVmaze as scraper

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#834]
**Is your feature request related to a problem? Please describe.**
The program is vulnerable when it rely on TheTVDB as its main source since that site is so unreliable, they've been messing with their new site and API for several years now and they still haven't figured it out. 

**Describe the solution you'd like**
Add TVmaze as an option under TV Scraper along TheTVDB and IMDb.

**Describe alternatives you've considered**
Adding stuff manually but I got that crazy idea out of my head rather quickly ;)

**Additional context**
https://www.tvmaze.com/blogs/21/an-alternative-when-the-thetvdb-api-is-down

**Comment by bugwelle** [comment]
Hi,

thank you. TVmaze is definitely an option that I will consider. Thank you. :-)

**Comment by bugwelle** [comment]
After a year I've finally rewritten our TV scraper interface. Adding TV maze is now rather easy (they have a well structured API at https://www.tvmaze.com/api ).

**Comment by bugwelle** [comment]
#1096 is a first step for adding TVmaze as a provider. :-)

**Comment by bugwelle** [comment]
TVmaze will be added by #1098 😄
