### ISSUE TITLE
No debug logs created/generated when set in advancedsettings.xml

### ISSUE THREAD

**Issue by pgnd** [Komet/MediaElch#838]
I've build/installed ME from git,
```
  commit 5f938095325e1ec82a22dfdf8640643fcace07b6
```

on Linux.

It launches
```
MediaElch 2.6.3-dev - Ferenginar

Compiled with Qt version 5.13.1 (64 Release, GCC 9.2.1 20190903 [gcc-9-branch revision 275330])
Using Qt version 5.13.1
System: openSUSE Leap 15.1 (x86_64-little_endian-lp64)

Application dir: /usr/bin
Settings file: /home/pgnd/.config/kvibes/MediaElch.conf
Data dir: /home/pgnd/.local/share/kvibes/MediaElch
MediaInfo Version: MediaInfoLib - v19.09
```

and loads media from my server. I can scrape for individual media.

But I can't save/synch any changes at all.  No obvious error in UI.

To get to some debug logging, I created
```
ls -al /home/pgnd/.config/kvibes/advancedsettings.xml
	-rw-rw-r--+ 1 pgnd users 629 Dec  9 22:53 /home/pgnd/.config/kvibes/advancedsettings.xml

cat /home/pgnd/.config/kvibes/advancedsettings.xml
	<?xml version="1.0" encoding="utf-8"?>
	<advancedsettings>
	    <log>
	        <debug>true</debug>
	        <file>/home/pgnd/MediaElch.log</file>
	    </log>
	</advancedsettings>
```

But, on re-launch, no logfile's created,
```
	ls -al /home/pgnd/MediaElch.log
		ls: cannot access '/home/pgnd/MediaElch.log': No such file or directory
```

No errors in syslog or journal ...

What needs to be done to get logs?

**Comment by hewwra** [comment]
Did you really create the file in the right [place?](https://mediaelch.github.io/mediaelch-doc/settings.html)

[Here](https://github.com/Komet/MediaElch/blob/master/docs/advancedsettings.xml) is the default advancedsettings.xml, better to use this in order to ensure its 100% compatible with MediaElch.

**Comment by bugwelle** [comment]
Hi,

thank you for opening this issue and sorry for the delay, I was busy in the last days and didn't have time for MediaElch.

>  No obvious error in UI.

Indeed. The UI is very sparse about showing any warnings or errors.

About your issue: The file `advancedsettings` needs to be in the data directory not in the settings one. That is: put your file here: `Data dir: /home/pgnd/.local/share/kvibes/MediaElch`

That should work. Please let me know if that is not the case. 😃

**Comment by bugwelle** [comment]
I'll close this issue due to inactivity. If you still experience any issues, please let me know. 😃
