### ISSUE TITLE
Ignoring titles

### ISSUE THREAD

**Issue by jerauf** [Komet/MediaElch#840]
**Is your feature request related to a problem? Please describe.**
When I have multiple versions or extras in my library, MediaElch reads them as entirely new titles. I don't want to create NFO files for them.

**Describe the solution you'd like**
I want to be able to exclude files from being scanned.

**Comment by bugwelle** [comment]
Hi,

I thought about this as well but didn't find a solution that satisfies me...
Would you like to exclude certain folders, just files or would you like to ignore files using a pattern? :)

**Comment by jerauf** [comment]
I can see 3 options:

1. Excluding folder names (i.e. Extras)
2. Excluding files that contain a certain work (i.e. naming files Featurette - [filename].mkv)
3. Right click on the title in the list at left and choosing "Ignore" or have a checkbox when you open the title. Of course, you'd need a list of ignored titles (maybe in settings) to allow people to un-ignore if they change their mind.

Personally, I'd prefer the 3rd option

**Comment by bugwelle** [comment]
Third one is preferable in my opinion. 👍

**Comment by bugwelle** [comment]
Related: #430

**Comment by snakyjake1** [comment]
I need options 1 (exclude folder name patterns) and 2 (exclude filename patterns).  Sometimes the files are in a separate folder (e.g. .unwanted), sometimes the file is in the same folder.

Option 3 would require manual work for all titles, including new titles.  Options 1 and 2 would be a lot less work.

**Comment by bugwelle** [comment]
A possible implementation can be seen in PR #854 

Before adding it as a stable feature to MediaElch's settings, I want to test it using the `advancedsettings.xml` file. You can see the new tags here: https://github.com/bugwelle/MediaElch/blob/exclude-patterns/docs/advancedsettings.xml#L176-L187

The PR isn't finished, yet, but it works well for movies as far as I can see and have tested. You can use regular expressions to filter folders and filenames. :-)
