### ISSUE TITLE
[China/blocked] TheTVDb scraper does not work from China

### ISSUE THREAD

**Issue by fiumestella** [Komet/MediaElch#845]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [✅ ] TMDb
 - [ ] TMDbConcerts
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [ ] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
Add a list of information that is not loaded correctly.

**MediaElch Version:**
 - [✅] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [✅] Windows
 - [✅] macOS
 - [ ] Linux (distribution: ___)

**Additional context:**
TV scrapers for both Mac & Windows versions don't work

**Comment by bugwelle** [comment]
Hi there,

what exactly does not work with the TMDb scraper?
TMDb is a movie scraper and you can't select it for TV shows. But both TheTvDb for TV shows and TMDb for movies work for me on macOS.

I may be able to help you with more detailed information. 😃

**Comment by fiumestella** [comment]
> Hi there,
> 
> what exactly does not work with the TMDb scraper?
> TMDb is a movie scraper and you can't select it for TV shows. But both TheTvDb for TV shows and TMDb for movies work for me on macOS.
> 
> I may be able to help you with more detailed information. 😃

Thank you for answering and I've made a wrong option 😅，I mean scrapers for TV,  TvDb and  IMDB(in tv scraper selection). I can't get any information about TV shows, but the movie scraper did well. 

This is my first time to use GitHub, and I really want to show you some screenshots...😢

**Comment by bugwelle** [comment]
If you have screenshots available, you can drag&drop them onto the text field 😃 

The TV show scraper currently does not show any errors (unlike the movie one)... Could you please check:

 - can you reach https://thetvdb.com/ ?
 - do you have a proxy enabled in MediaElch's settings?
 
And just some more questions:

 - When did you download the nightly?
 - Do you have an `advancedsettings.xml` somewhere (if you don't know what it is, then you don't have one :-) )

**Comment by fiumestella** [comment]
> If you have screenshots available, you can drag&drop them onto the text field 😃
> 
> The TV show scraper currently does not show any errors (unlike the movie one)... Could you please check:
> 
> * can you reach https://thetvdb.com/ ?
> * do you have a proxy enabled in MediaElch's settings?
> 
> And just some more questions:
> 
> * When did you download the nightly?
> * Do you have an `advancedsettings.xml` somewhere (if you don't know what it is, then you don't have one :-) )


- I'm a new MediaElch user from China, I checked the website https://thetvdb.com/,  and it needs VPN 's 'Global Mode' to visit. if I use the 'Auto Pac Mode', or do not use the VPN, this website cannot be opened. the page will show ERR_CONNECTION_TIMED_OUT, 

- I don't have any proxy enabled setting.

- I downloaded MediaElch for mac the day before yesterday, after tv scraping failed, I tried to change the names of tv files, but it didn't work 😭  then I downloaded the newest version for windows & mac a few hours ago, both of them still cannot scrap from the Tvdb 💔

- I don't have  advancedsettings.xml , (and yeah I don't know what it is 😂)

so maybe it is a proxy problem? 😩 
![Snip20191230_2](https://user-images.githubusercontent.com/59361054/71589000-5b7c1480-2b5e-11ea-8d00-0d11ad3a0899.png)

**Comment by bugwelle** [comment]
> I'm a new MediaElch user from China, I checked the website https://thetvdb.com/, and it needs VPN 's 'Global Mode' to visit. if I use the 'Auto Pac Mode', or do not use the VPN, this website cannot be opened. the page will show ERR_CONNECTION_TIMED_OUT,

There's the issue. TheTvDb may be blocked in China so MediaElch can't reach their servers. I'm not familiar with "Global Mode" or "Auto Pac Mode" for VPNs. Do you have some more details about that?
If you can use a VPN that allows MediaElch to reach https://api.thetvdb.com then MediaElch should work (the page says "Not authorized" due to the API key missing; just in case you're wondering). 😃

**Comment by fiumestella** [comment]
> > I'm a new MediaElch user from China, I checked the website https://thetvdb.com/, and it needs VPN 's 'Global Mode' to visit. if I use the 'Auto Pac Mode', or do not use the VPN, this website cannot be opened. the page will show ERR_CONNECTION_TIMED_OUT,
> 
> There's the issue. TheTvDb may be blocked in China so MediaElch can't reach their servers. I'm not familiar with "Global Mode" or "Auto Pac Mode" for VPNs. Do you have some more details about that?
> If you can use a VPN that allows MediaElch to reach https://api.thetvdb.com then MediaElch should work (the page says "Not authorized" due to the API key missing; just in case you're wondering). 😃

the page says "Not authorized" indeed 😰   and  I saw IMDB option in tv scraper setting, buy it didn't work too, why? so can't I use this function? 😭
![Snip20191231_1](https://user-images.githubusercontent.com/59361054/71591591-e6154180-2b67-11ea-8a1e-78ab0e56f8ed.png)

**Comment by bugwelle** [comment]
> the page says "Not authorized" indeed 😰

That is good! It means MediaElch can reach their servers.
But thetvdb.com can't be reached? You don't get any search results when scraping a TV show?

> and I saw IMDB option in tv scraper setting, buy it didn't work too, why? so can't I use this function? 😭

MediaElch *first* loads the details from TheTvDb and *then* from IMDb if requested. If the first one doesn't work, neither will IMDb :/

**Comment by fiumestella** [comment]
these are the screenshots about website and MediaElch, I have no idea now 🤯
![Snip20191231_1](https://user-images.githubusercontent.com/59361054/71592784-8705fb80-2b6c-11ea-823f-ebde67e71afd.png)
![Snip20191231_2](https://user-images.githubusercontent.com/59361054/71592795-8c634600-2b6c-11ea-845b-3426c9eacf36.png)
nothing..

but I can open this page 👇
![Snip20191231_6](https://user-images.githubusercontent.com/59361054/71592852-c7fe1000-2b6c-11ea-9c75-45b2daccbc97.png)
and this one
![Snip20191231_5](https://user-images.githubusercontent.com/59361054/71592861-d2200e80-2b6c-11ea-8e69-c8196c6924c7.png)

thank you for your patiently answer!

**Comment by bugwelle** [comment]
Hi,

to be honest, I don't really know what may cause the issues except for proxy settings. Could you please enable the debug log by using the `advancedsettings.xml` file and paste the debug log here? 

 1. Add `advancedsettings.xml` with `<debug>true</debug>`
 1. Open MediaElch
 1. Scrape a show and ensure that it doesn't work
 1. Close MediaElch
 1. Open & Copy the log and paste it here

See: https://mediaelch.github.io/mediaelch-doc/settings.html#advanced-settings

**Comment by bugwelle** [comment]
I have to close this due to inactivity. I may be able to help you if you provide a debug log. :smiley:
