### ISSUE TITLE
Scrape Episodes in DVD order

### ISSUE THREAD

**Issue by Araldwenn** [Komet/MediaElch#848]
When trying to scrape a TV show, using DVD order doesn't work, it uses the official order (I tried with Space 1999, which have both official and DVD order, and they are different)

**To Reproduce**
Select TV show.
Clic scrape (or CTRL+F)
Check DVD ordezr checkbox
Clic TV show name to launch scrape

**Expected behavior**
MediaElch should use DVD order to name the files

**MediaElch Version:**
 - MediaElch_win_2.6.3-dev_2019-12-30_16-47_git-master-59da074

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Comment by bugwelle** [comment]
Thanks for reporting this issue! I'll add tests so that this issue won't happen again in the future.

I haven't tested this issue, yet. This may be an issue with the new TheTvDb v2 scraper. Maybe I've missed something.

**Comment by bugwelle** [comment]
So I had a look into it. If you are referring to the show https://thetvdb.com/series/space then the issue is with TheTvDb: They don't have a DVD order for that show. It's missing information...
Same goes for example for https://thetvdb.com/series/the-muppets/

The API of TheTvDb returns an season and episode number that is not valid. And MediaElch doesn't handle that too well... :-/

**Comment by Araldwenn** [comment]
The show which helped me find this issue is [https://thetvdb.com/series/space-1999] and it has both DVD and official order (I checked before sending a bug report), but MediaElch uses only official order, even if DVD order is ticked.

**Comment by bugwelle** [comment]
Got it. Thanks for providing a URL. I'll test it tomorrow and will come back to you :)

**Comment by bugwelle** [comment]
#866 will fix your issue. The issue was introduced when I switched to the new TheTvDb API. I'll have to add tests and will then merge the PR. 😃

**Comment by bugwelle** [comment]
TheTvDb seems to work again (was under heavy load 3 days ago). I've added a test case to fetch this issue in the future. I'll merge the PR after our CI pipeline has finished.
