### ISSUE TITLE
Problems with updating existing nfo

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#849]
**Describe the bug**
When updating an existing nfo written in the old format the new parameters is just added at the end and old stuff like URLs to fanart and actor images are left behind.

**To Reproduce**
1. Go to an already scraped TV-show.
2. Ctrl-F
3. Update show.
4. Open NFO to see result.

**Expected behavior**
A fresh new nfo in the new format with everything in the right place or at least one with the old stuff removed.

**MediaElch Version:**
 - [X] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context**
Same thing happen with nfo for TV-episodes and movies.

**Comment by bugwelle** [comment]
Hi there,

thank you for reporting this issue. I didn't think of this case when creating the v17 NFO writer. MediaElch keeps unknown tags and only updates the ones it knows. Because some tags are "unknown" in v17 but exist in v16, MediaElch keeps them.

Definitely an issue. Thank you for reporting!

**Comment by bugwelle** [comment]
Hi,

as a quick-fix, I'll keep a list of old v16 tags and will remove them in the v17/v18 NFO writers. However, I didn't find image tags that were kept. Could you give me the names of tags that are kept? :)

#856 will then fix this issue :-)

Please note that I would love the re-write the NFO writers in a way that this wouldn't happen but I currently don't have enough time for that.

**Comment by psonnosp** [comment]
They are still working so no worries, I get that there are more prominent stuff to fix and I appreciate and value every minute you spend on this without getting paid. Wish I knew how to do this stuff so I could actually do something about the bugs and not just point them out ;)

https://pastebin.com/iyj91UP1
There's an old nfo that's been rescraped, it's the <thumb> variations that need to go. Believe there are/were an issue posted about writing them or not some time ago.

If you have these in your nfo this is what shows up when you click an image, or image field, in ME instead of pulling them fresh from the scrapers.

**Comment by bugwelle** [comment]
Thank you for posting the NFO file.

I still don't get what exactly shouldn't be in the NFO (maybe I'm too tired at the moment). Could you that out to me? 
What variations are you referring to? Should the order of tags change oder what is expected? 😃

**Comment by psonnosp** [comment]
Sorry, kind of very sure I posted an answer to this already but something seems to have happened.
And also kind of sure I wrote fanart that would've made my post make a little more sense but guess it was auto corrected to variations. Think I'll stop posting here using my tablet. ;)

Anyhow.... It's the <thumb stuff that shouldn't be there.

And the reason I came back to this post was to add that if you have subtitles in a movie folder so they get scraped and later on remove the subtitles and re-scrape the subtitles tag aren't removed from the nfo.

**Comment by bugwelle** [comment]
> Anyhow.... It's the <thumb stuff that shouldn't be there.

Strange. After the PR that tag will be removed. It is already now removed but only if `<writeThumbUrlsToNfo>` is set to `true` in MediaElch's `advancedsettings.xml`

**Comment by bugwelle** [comment]
> And the reason I came back to this post was to add that if you have subtitles in a movie folder so they get scraped and later on remove the subtitles and re-scrape the subtitles tag aren't removed from the nfo.

In the `<fileinfo>` tag? That was only removed if there exist subtitles... which won't work if you don't have subtitles anymore. Will be fixed by that PR as well. :)

**Comment by bugwelle** [comment]
The next nightly  version should fix your issue. Please let me know if it does not. :)

**Comment by psonnosp** [comment]
> Strange. After the PR that tag will be removed. It is already now removed but only if `<writeThumbUrlsToNfo>` is set to `true` in MediaElch's `advancedsettings.xml`

I added that to advancedsettings.xml a long time ago but that has only worked when creating new nfos, not when updating an old one. But it works now and the nfo looks as it should.

> > And the reason I came back to this post was to add that if you have subtitles in a movie folder so they get scraped and later on remove the subtitles and re-scrape the subtitles tag aren't removed from the nfo.
> 
> In the `<fileinfo>` tag? That was only removed if there exist subtitles... which won't work if you don't have subtitles anymore. Will be fixed by that PR as well. :)

Don't really know what you are talking about here but yes it's was <subtitle> under <fileinfo> but as with the above it's all solved now so thanks.

**Comment by bugwelle** [comment]
Glad to hear that. Regarding the subtitles: The subtitle tag was only removed if there are (new) subtitles for a movie. Of course that's just stupid if you don't have subtitles anymore and the tags still exist. :-)
