### ISSUE TITLE
Adding episode to sync queue not working

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#850]
**Describe the bug**
When you right click on an episode to add it to the sync queue nothing happens.

**To Reproduce**
1. Right click on an episode.
2. Click on Add to Synchronization Queue.
3. Watch nothing happen.

**Expected behavior**
The episode should get added to the sync queue indicated with the two arrows in a circle in front of it so you can retrieve watched status under the Sync to Kodi dialogue.

**MediaElch Version:**
 - [X] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context**
Workaround is to mark one episode at the time and hit the save button but that's very time consuming.

**Comment by bugwelle** [comment]
Confirmed. Using `git bisect` I can see the offending commit:

```
54756bad8a33fafc049462f9aab96cb46de9eb1b is the first bad commit
commit 54756bad8a33fafc049462f9aab96cb46de9eb1b
Author: Andre Meyering <info@andremeyering.de>
Date:   Mon Feb 25 15:31:10 2019 +0100

    [TvShowModel] Refactor

:040000 040000 d80d76b5a5e1efeb2ab6e9038ae1d36bf2f68e78 7adf388fa03818546245c0c26618ffe89c832943 M	src
```
