### ISSUE TITLE
Not all fanart from fanart.tv shows

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#858]
**Describe the bug**
When you click to choose a background sometime not all of the available images on fanart.tv are shown for some reason.
Noticed it now when scraping 'Knives Out' and only two images show but fanart.tv have 13 ready for download.

**To Reproduce**
1. Scrape a movie
2. Click on background
3. Search for, in this case, Knives Out.
4. Count the images that shows.
5. Go to https://fanart.tv/movie/546554/knives-out/ and scroll down to Backgrounds and count the images.
6. Scratch head...

**Expected behavior**
All available images on fanart.tv's website should show in the Choose an Image-window.

**Screenshots**
![Image4](https://user-images.githubusercontent.com/28609335/71775744-4f40ee80-2f86-11ea-875a-ba3abd5379ac.jpg)
![Image5](https://user-images.githubusercontent.com/28609335/71775746-4fd98500-2f86-11ea-9954-d57fc446ee11.jpg)

**MediaElch Version:**
 - [X] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context**
Haven't thought of it before so maybe it's not a new thing but checked some other movies now and they all showed what was available on the site. Maybe the same thing happen on other types of images too, maybe even on TV shows? Kind of time consuming to check since fanart.tv is so slow but will do some looking around.

**Comment by bugwelle** [comment]
We filter Fanart.tv by language. Maybe some images are in a different language than the one you want? I'll have to check whether if fanart without any language is returned at all. Didn't think about that case.

You can set the language here (bottom of the image):

<img width="669" alt="Screen Shot 2020-01-05 at 11 38 42" src="https://user-images.githubusercontent.com/1667306/71778559-d9517d00-2faf-11ea-9781-5a4426f0cb9e.png">

**Comment by bugwelle** [comment]
Nevermind my previous comment. We only sort by preferred language...
This is the list of all Fanart we can receive from Fanart.tv for "Knives Out": https://webservice.fanart.tv/v3/movies/546554?api_key=842f7a5d1cc7396f142b8dd47c4ba42b

**Comment by bugwelle** [comment]
Ok, had a better look into it. It seems to be an issue with Fanart.tv itself. If you have a look at the URL above and look at the field `moviebackground` you see that only two images are listed:

 - https://assets.fanart.tv/fanart/movies/546554/moviebackground/knives-out-5d9e8863cab9d.jpg
 - https://assets.fanart.tv/fanart/movies/546554/moviebackground/knives-out-5d929873aad51.jpg

Those two are the ones from your screenshot. We don't get any more images from their API...
I'm sorry about it but there's nothing from my side that I can do :-/

**Comment by psonnosp** [comment]
Seems that it's only images that has got a vote that is listed in the API so even if there are images available but with out votes they can't be accessed through the API. That's beyond stupid if that's how it supposed to be.
Thanks for clearing it out.

**Comment by bugwelle** [comment]
Oh, that makes "sense". Probably to avoid unpopular images or spam images in Third-Party applications...

I'll add a entry to our [FAQ](https://mediaelch.github.io/mediaelch-doc/faq.html). It's indeed surprising that not all images appear...
Sadly, there isn't an option for their API to request *all* images.

**Comment by bugwelle** [comment]
https://github.com/mediaelch/mediaelch-doc/commit/70fa8b8f6b26286a15dfac5251eac76f7d8350fa

The FAQ will go live the next time I publish the documentation :-)

**Comment by psonnosp** [comment]
No not really since fanart.tv has very high standards for images to be approved. Logos for example get rejected if they are as much as a pixel off center so that can't be it. Feels more like a good thought and idea that went bad.
