### ISSUE TITLE
'missing episodes' seems not to work

### ISSUE THREAD

**Issue by LnarDo** [Komet/MediaElch#865]
If i check in context menu 'show missing episodes' it will not work. It shows me just the files in the tv show directory and the assigned episode. But the episodes which have no matching file are not listed. I know this works in a past version and since an update it wont work, but i cant tell you the version which changed the behaviour.

**Comment by LnarDo** [comment]
Problem found on MediaElch 2.6.3 on Windows

**Comment by bugwelle** [comment]
That feature is very buggy. Thank you for reporting this issue.

**Comment by bugwelle** [comment]
Hi, this issue will most likely be fixed by #883. I'll merge the pull request soon and a new nightly should be available in about an hour. 😃 
Please let me know if it there is still unexpected behavior..

**Comment by LnarDo** [comment]
it works well, thank you

**Comment by bugwelle** [comment]
Thanks for letting me know :-)
