### ISSUE TITLE
Issue scraping Star Trek : Short Treks

### ISSUE THREAD

**Issue by Araldwenn** [Komet/MediaElch#873]
**Describe the bug**
When scraping the tv show "[Star Trek : Short Trek](https://www.thetvdb.com/series/star-trek-short-treks)", it gives me almost nothing, whereas there's infos on The TvDB (plot, actors, episodes plots are not loading, but status, genres, director, writers are). 

**To Reproduce**
Scrape "Star Trek : Short Treks"

I tried adding other shows, some with ":" in the name, some without the langage asked for in settings (French in my case), couldn't reproduce the issue. Tried to swap the langage to english for scraping informations on the TVDB, as the show only has english informations, didn't change anything.

**Expected behavior**
MediaElch should download all informations

**MediaElch Version:**
 - [x] 2.6.3-dev (nightly) (latest january 19th)

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Comment by psonnosp** [comment]
When I scrape it in English I get all the info available.
Have you tried removing show nfo to make a new one? I've solved issues I've had with scraping gone bad by doing that.

**Comment by bugwelle** [comment]
Hi,

that is indeed strange. I tested it with the latest nightly and I'm able to load all information:
![Screenshot_20200411_184216](https://user-images.githubusercontent.com/1667306/79049487-46665580-7c24-11ea-9be9-2f2d0d7d42b1.png)

It is also possible that TheTvDb didn't send the data or that it was down. Please let me know if it still does not work.

Regards,
Andre
