### ISSUE TITLE
New Phrases - Typo

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#875]
New Phrases - Typo

I updated the translations for pt-BR on the **transifex**.
I found an original phrase, in English, that may be wrong.
`Cannot scrape a movie without an actice scraper!`
I believe that, instead of **actice**, it may be **active**.

**Comment by bugwelle** [comment]
Yeah, thanks! :)

**Comment by bugwelle** [comment]
Fixed. Will be uploaded to Transifex the next time I'm updating our translations :-)
