### ISSUE TITLE
Rescrape of scraped movie -> actors listed multiple times.

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#877]
**Describe the bug**
When scraping an already scraped movie the actors are added once again to the actors list even if they already exist.

**To Reproduce**
1. Open an already scraped movie.
2. Open actors tab.
3. Click scrape or Ctrl-F.
4. Watch the list multiply.

**Expected behavior**
The list should be emptied and populated according to the scraper source or at least not having the actors already on the list added once again.

**MediaElch Version:**
 - [X] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [X] Windows 10
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Comment by psonnosp** [comment]
Noticed now that it's even worse than listed above.
Every time you save a movie the entire list of actors are added again.
I've checked some NFOs created from before installing the latest nightly today and some are infested with thousands of actors so this was introduced in an earlier version. By the look of my NFOs the second newest one but can't be sure.

**Comment by ticao2** [comment]
It happens to me too.
MediaElch_2.6.3-dev_2020-01-28_18-48
In my previous versions it doesn't happen.
MediaElch_2.6.3-dev_2019-10-25_09-56
MediaElch_2.6.3-dev_2019-10-26_12-08
Windows 10 - 64

**Comment by bugwelle** [comment]
Confirmed. Know the cause. A fix is one the way :-)

**Comment by bugwelle** [comment]
#879 fixes the issue of scraping multiple actors and also adds tests for it to avoid having this problem again in the future. I haven't yet looked into the issue of saving movies and having actors multiple times, yet. I'll do that next week. #879 should fix the most critical issue. This issue does not exist in v2.6.2 but was introduced in the nightlies about a month ago.

**Comment by bugwelle** [comment]
Saving a movie does indeed duplicate all actors! Oh my god...

**Comment by bugwelle** [comment]
The next nightly fixes this issue.

Thanks to everyone who reported and confirmed this issue. 👍
