### ISSUE TITLE
Flickering and non-responsive windows | Image Cache issue?

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#878]
**Describe the bug**
I posted about this [here](https://github.com/Komet/MediaElch/issues/864#issuecomment-573524022) but since updating to 2.6.3-dev_2020-01-28_18 it's even worse and make ME unusable since pretty much any action I take make all child windows behave like in [this video](https://imgur.com/a/FF2aEgZ). CPU usage spike to ~30% when the window get unresponsive and jumps out of focus.
The same happens when clicking around in the main window, it doesn't jump out of focus though but it freezes for a short period of time and (Not responding) appears in the title bar.

Had an idea that it might have something to do with that two of my sources are network drives since I got a feeling it happened more often when working with them and ME seem to handle that extremely poorly speed wise. Are ME maybe using some outdated protocol or something that make file handling over network sluggish? Cause there are an ocean of difference between updating a local and network source. A difference that's not noticeable when using other programs.
But it made no difference removing them and only working with local sources.

This is probably not a wide spread issue since no one else is reporting it. And I don't know what to do about this since there are no log function that might tell you if this is something happening in ME or tell me if there's something wrong with my setup.

Any suggestion of what I can do to help resolving this?

**MediaElch Version:**
 - [X] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [X] Windows 10
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Comment by bugwelle** [comment]
Sadly, I wasn't able to reproduce that issue, yet. But I really want to help because that behavior is just not acceptable. Could you paste the developer information here? (See [docs](https://mediaelch.github.io/mediaelch-doc/contributing/bug-reports.html#developer-information))

**Comment by psonnosp** [comment]
MediaElch 2.6.3-dev - Ferenginar

Compiled with Qt version 5.12.3 (64 Release, GCC 5.5.0)
Using Qt version 5.12.3
System: Windows 10 (10.0) (x86_64-little_endian-llp64)

Application dir: E:/Program/MediaElch
Settings file: \HKEY_CURRENT_USER\Software\kvibes\MediaElch
Data dir: C:/Users/XxXxX/AppData/Local/kvibes/MediaElch
MediaInfo Version: MediaInfoLib - v19.04

**Comment by bugwelle** [comment]
Thanks. I'll have time for your issue in a few days. If I send you a custom build (e.g. with updated dependencies), could you test it? Of course that would only be necessary if I can't reproduce the issue :-)

**Comment by psonnosp** [comment]
Have you made any progress on this?

**Comment by bugwelle** [comment]
I'm sorry, I forgot about this after having some difficulties which are now resolved (I wanted to test it on my Windows machine first).

**Comment by bugwelle** [comment]
@psonnosp I finally got around to create a 32-bit version of MediaElch. You can download it at https://bintray.com/bugwelle/MediaElch/download_file?file_path=MediaElch_win_2.6.5-dev_2020-03-11_19-52_git-travis-archer96-961d76e.zip (the `travis-archer96`) is the name of my git branch; `archer96` was my previous GitHub username).

Tested on Windows 8.1:

![Unbenannt](https://user-images.githubusercontent.com/1667306/76458767-5697d480-63db-11ea-8120-d7e537c03f17.JPG)

It took a bit longer because I had to test what new dependencies were necessary. Some libraries had different names....
Please let me know whether everything works as expected. If it does then I may consider adding a "legacy" 32-bit Version for future versions as well. :-)

**Comment by psonnosp** [comment]
Thank you, will try it when I get home.

Maybe it's a dumb question but just out of curiosity, why would a 32-bit version be the solution to this when I have a x64 setup? Wouldn't that make the program even more sluggish?

**Comment by bugwelle** [comment]
Ooohhh... I'm sorry, seems i was too tired. I didn't even read through this issue. The 32bit version was part of #906 and I thought I replied to that...

I haven't yet looked into your issue. Sorry for the confusion.

**Comment by psonnosp** [comment]
LOL It can happen the best of us, no worries. Just wanted to check since it starting to drive me mad.

**Comment by psonnosp** [comment]
Without knowing much about the deeper things how programs like this live their life...
But does ME rely highly on the page file for its performance?
It was just a thought since I've noticed that this issue gets worse and worse the longer the uptime of Win10 is and the page file is the only thing I know of in Windows that get flushed on a reboot but maybe there's more.
Either way, something happens over time that gradually slows ME down and what's shown in the clip goes on for longer periods until it is unusable.
Every other program works OK the whole time though so it's an exclusive issue for ME.

And no pressure, I'm just writing down what I find so you have more to go on the day you find the time to look in to it whenever it may be.

**Comment by psonnosp** [comment]
Build 2.6.5-dev_2020-04-04_15-39_git-master-9a43b9f made ME unusable because of this.
I'm not even on 20h of uptime for my system and ME flickers for at least 30s for every move I do and often longer than that.

**Comment by bugwelle** [comment]
In response to https://github.com/Komet/MediaElch/issues/732#issuecomment-610444696

Still looking into this but couldn't reproduce this, yet. :-/
I assume it's still the same behavior as in the video you posted?

**Comment by bugwelle** [comment]
I updated our UI dependency (Qt). Could you check the latest stable (released today) v2.6.6?  
There is a small probability that it fixed this issue. 😃

**Comment by psonnosp** [comment]
Sorry but no noticeable change.

**Comment by bugwelle** [comment]
Thanks. That way I at least know that it is a bug in MediaElch and not in Qt.

**Comment by psonnosp** [comment]
I accidentally unplugged one of my screens and now it runs almost perfect so think this is where you should begin your hunt for a solution whenever you get the time.

**Comment by bugwelle** [comment]
Thanks. I don't have any time for MediaElch this month (due to exams at my University). I hope to debug this in August after the big TV scraper change. :-)

**Comment by psonnosp** [comment]
No worries, real life stuff is way more important than a flickering screen, good luck with the exams!

But I may have found something else.

Again... 😄

But at least I've tested it for a few days before posting this time so I know it's not just something temporary.

I just begun adding a bunch of new movies and shows and not just updating old stuff or adding episodes to already scraped shows as has been the case before.
And while doing that it works flicker free, but as soon as I hit save on stuff located on my NAS the nightmare begins. The stuff in my share that's stored on the same computer as ME still works more or less as flicker free as before hitting save.
This made me install Wireshark to see what was going on under the hood while ME was talking to my NAS via SMB and without knowing that much about it, it sure looks like it's talking a lot. Just selecting a show in ME generated close to 500 requests to my NAS, first the tvshow.nfo and then the different fanarts over and over again.
The NAS doesn't choke or overload so that shouldn't be the issue and maybe this is totally normal behavior so this post is as much worth as the one above 😆 
But ME has nevertheless since day one been extremely slow for me when it comes to accessing my NAS so maybe this is something that's been building up through out the versions and then one day resulted in this behavior. 

It's strange though since I can't be the only one with this setup and no one else is complaining about it...

**Comment by ticao2** [comment]
I've been following the development of this strange problem of yours since the beginning.
I'm just curious. I'm not a programmer.
And it occurred to me that it might be worth doing a simple test.
As you use Windows it is possible to do an "installation" in **Portable Mode**.
I believe it will not interfere with your current installation.
And add only local folders as a media source and not your NAS server.
If possible, first Movies and then Series.
And see if the defect still exists.
If the defect does not continue, then add a folder from the NAS server.
And gradually go until you test and add all the folders.
I'm just trying to find a method to isolate the problem.
Remember, I'm not a programmer. Just curious.
PS: This is looking like Dr. House trying to figure out why the patient is shaking in his legs. :-)

**Comment by psonnosp** [comment]
That's more or less what "But at least I've tested it" means in my previous post.

**Comment by psonnosp** [comment]
I'm going to walk out on some very thin ice and say that I've solved this issue that has had as many turns and twists as a walk home from the pub. But ME has been running smoothly for several weeks now so I finally feel confident enough do do it 😅 

I was cleaning my OS drive and found C:\Users\User\AppData\Local\kvibes\MediaElch\images that contained close to 90.000 images, some as old as when I probably installed ME for the first time like 8 years ago and images connected to stuff no longer in my source. So I wiped them and ME has been working perfectly ever since. (It will probably begin to flicker again as soon as I post this)

So I think you should add something that cleans that folder now and then or delete stuff that's not been accessed in a while cause Windows seem to have a hard time with folders containing such a large amount of files.
Why it behaved worse when working on a NAS-source is odd though but I don't know the inner workings of it all so maybe it's logical to you.

*holding both thumbs while clicking Close and comment*

**Comment by bugwelle** [comment]
Wow, thanks for coming back to us. 90.000 files is way to much for a single folder. Filesystem are meant as a hierarchy system. One level for so many files isn't enough. 

I am reopening this issue as MediaElch clearly does have an issue with temporary (?) images.

Thanks!

**Comment by bugwelle** [comment]
It appears that I forgot this issue for the last 3 years. I didn't have time to go through old issues.

This may have been fixed via https://github.com/Komet/MediaElch/pull/1643 which should load images asynchronously, which should make MediaElch responsive even if it takes a few seconds to load images from cache.
