### ISSUE TITLE
Version 2.6.4 "Ferenginar" - Name of Files

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#887]
**Is your feature request related to a problem? Please describe.**

Sorry for the bad news. :-)
I believe that all installation files (Linux, Mac and Windows) got the wrong name.
Instead of 2.6.4, everyone has 2.6.2.

**Describe the solution you'd like**

Correct file names.
Please don't blame the messenger. :-)

**Comment by bugwelle** [comment]
I would never blame the messenger.

I really don't know how the heck I messed up the file naming. At least it's version 2.6.4 if you download it. I'll fix that ASAP. Thank you very much for reporting. That's awkward. 😃

**Comment by bugwelle** [comment]
Just double checked. The files are all 2.6.4, just renamed them wrong. Fixed that. :-)
