### ISSUE TITLE
export movie-logo results in jpg

### ISSUE THREAD

**Issue by Stunkymonkey** [Komet/MediaElch#907]
**Describe the bug**
currently the save logo files are all `png`s which is perfectly fine. but when exporting everything to html file the file ending is `jpg`.

**To Reproduce**
1. Go to Export
2. Click on Export, but make sure the theme exports the logo as well.
3. Open folder and inspect files

**Expected behavior**
The file-content is still a valid png, so just the file-ending is wrong.

**MediaElch Version:**
 - [x] 2.6.2 stable

**Operating System:**
 - [x] Linux (distribution: arch)

**Comment by Stunkymonkey** [comment]
the commandline ist outputting errors:
```
...
libpng error: profile 'HD 709-A': 805D79A3h: length does not match profile
libpng error: profile 'HD 709-A': 805D79A3h: length does not match profile
[MediaElch] WARNING:  libpng warning: iCCP: known incorrect sRGB profile
libpng error: profile 'sRGB IEC61966-2.1': 40500441h: length does not match profile
[MediaElch] WARNING:  libpng warning: iCCP: known incorrect sRGB profile
libpng error: profile 'sRGB IEC61966-2.1': 909291A2h: length does not match profile
libpng error: profile 'HD 709-A': 306B70A3h: length does not match profile
libpng error: profile 'Generic RGB Profile': 90B568A3h: length does not match profile
[MediaElch] WARNING:  libpng warning: iCCP: known incorrect sRGB profile
libpng error: profile 'sRGB IEC61966-2.1': 909291A2h: length does not match profile
libpng error: profile 'Generic RGB Profile': 90B568A3h: length does not match profile
[MediaElch] WARNING:  libpng warning: iCCP: known incorrect sRGB profile
libpng error: profile 'sRGB IEC61966-2.1': 909291A2h: length does not match profile
[MediaElch] INFO:     [Export] Finished successfully
...
```
on the line [506 in SimpleEngine.cpp](
https://github.com/Komet/MediaElch/blob/ba983065976ebbaf3ba0968ad358286e75fb82df/src/export/SimpleEngine.cpp#L506) i can confirm, that the format is given in `png`

PS: some exported logos have size zero. I expect the ones with errors.

**Comment by Stunkymonkey** [comment]
found a fix, but the `libpng` errors persist.
PR is comming

**Comment by bugwelle** [comment]
Thanks for reporting! :-)

**Comment by Stunkymonkey** [comment]
about the errors:
`[MediaElch] WARNING:  libpng warning: iCCP: known incorrect sRGB profile`
I will create another issue.
