### ISSUE TITLE
Problem while scraping TV Shows

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#915]
Version 8/3/2020 - 18

Scraping TVShows 
While i scrape a season - lets say 10 episodes,
some of them appear blank,
i then have to manualy delete the wrong nfo file - then click on check for new episodes - rescrape each  problematic episode separately.

**Comment by Kurzhalspomputergiraffe** [comment]
I can confirm. Same issue here. Version 2.6.4 on ArchLinux x64. Log output attached. Episode is existing in thetvdb (https://www.thetvdb.com/series/tatort/episodes/7541695)

`[MediaElch] DEBUG:    Entered`
`[MediaElch] DEBUG:    m_scraperId= "83214"`
`[MediaElch] DEBUG:    Entered`
`[MediaElch] DEBUG:    Entered, m_scraperId "83214"`
`[MediaElch] DEBUG:    Entered, id= "83214" scraperInterface= "The TV DB"`
`[MediaElch] DEBUG:    [TheTvDb] Load single episode of TV show with ID: "83214"`
`[MediaElch] WARNING:  [TheTvDb][ApiRequest] Network Error: "Error transferring https://api.thetvdb.com/episodes/0 - server replied: Not Found" for URL QUrl("https://api.thetvdb.com/episodes/0")`
`[MediaElch] DEBUG:    [TheTvDb] Single episode scraper done`
`[MediaElch] DEBUG:    Entered`
`[MediaElch] DEBUG:    Entered`
`[MediaElch] DEBUG:    Entered`
`[MediaElch] DEBUG:    [DownloadManager] Enqueue download | QUrl("https://www.thetvdb.com/banners/")`
`[MediaElch] DEBUG:    [DownloadManager] Start next download`
`[MediaElch] WARNING:  [DownloadManager] Network Error: "Error transferring https://www.thetvdb.com/banners/ - server replied: Forbidden" | QUrl("https://www.thetvdb.com/banners/")`
`[MediaElch] DEBUG:    Got a backdrop`
`[MediaElch] DEBUG:    Entered, enabled= true`
`[MediaElch] DEBUG:    Entered, enabled= true`
`[MediaElch] DEBUG:    [DownloadManager] Start next download`
`[MediaElch] DEBUG:    [DownloadManager] All downloads finished`

**Comment by psonnosp** [comment]
> I can confirm. Same issue here. Version 2.6.4 on ArchLinux x64. Log output attached. Episode is existing in thetvdb (https://www.thetvdb.com/series/tatort/episodes/7541695)
> 
> `[MediaElch] WARNING: [TheTvDb][ApiRequest] Network Error: "Error transferring https://api.thetvdb.com/episodes/0 - server replied: Not Found" for URL QUrl("https://api.thetvdb.com/episodes/0")`

Think you posted the answer to this yourself.
TheTVDB isn't the most stable site and the web page performance is like a roller-coaster and the API is even more so. I don't say it can't be something wrong with ME but I guess it's most likely this is related to TheTVDB.

**Comment by bugwelle** [comment]
@Kurzhalspomputergiraffe Thank you for posting the log here. This line is suspicious: 
```
[MediaElch] WARNING: [TheTvDb][ApiRequest] Network Error: "Error transferring https://api.thetvdb.com/episodes/0 - server replied: Not Found" for URL 
```

Seems we try to load an episode with id "0". I'm unsure how that happens, though. But it's indeed not unlikely that TheTvDb has issues, as pointed out by @psonnosp

**Comment by nkatsidis** [comment]
its not TVDB issue.. :)

when i try to scrape whole season some of the episodes are not scrapped correctly.
Even i dont press save, the episodes that are not scrapped have saved nfo file (that is blank)

if i want for medialech to scrap those episodes correctly, i have to manually delete those blank nfo files, then press search for new episodes and then scrap them one by one.

**Comment by psonnosp** [comment]
How do you do this, step by step and what version are you using?

I'm on Win10 and 2.6.5 from March 8 and now that TheTVDB is up and running again I just finished scraping four different shows with several seasons. Tried all the approaches I could think of for doing the task and didn't see this behavior once.

**Comment by monyarm** [comment]
I'm having the same issue trying to scrape episodes of Kamen Rider.

```
MediaElch 2020-10-20 18:55:23.121 DEBUG : [TheTvDb] Load single episode of TV show with ID: "74096"
MediaElch 2020-10-20 18:55:23.315 WARN  : [TheTvDb][ApiRequest] Network Error: "Error transferring https://api.thetvdb.com/episodes/0 - server replied: Not Found" for URL QUrl("https://api.thetvdb.com/episodes/0")
MediaElch 2020-10-20 18:55:23.316 DEBUG : [TheTvDb] Single episode scraper done
```

S00E172, S00E173, S00E197

**Comment by bugwelle** [comment]
#972 was merged and has a rewritten TV scraper. Please reopen this issue if your problems persist in the next nightly (not yet available, though).
