### ISSUE TITLE
Concerts not recognized

### ISSUE THREAD

**Issue by vidarak** [Komet/MediaElch#918]
Since version 2.6.2, none of my concert folders are recognized. It's clearly scanning through them (show names briefly on the dialog box), but not adding any to MediaElech concerts list. Affects 2.6.4 and 2.6.5 nightly builds too. Reverted to 2.6.0 and things work fine again. Have tried wiping both preferences and temporary folders used by Mediaelch.

**Comment by bugwelle** [comment]
Duplicate of #814 

Thank you for reporting this issue. Many users have reported it. I'll look into it :-)
