### ISSUE TITLE
Possibility to sort by Sort-Title in the Movies-List

### ISSUE THREAD

**Issue by bta489** [Komet/MediaElch#919]
I have some movie collections, for which I have set the sort-title for the movie with sequential numbers to group them together (e.g. "james bond 01", "james bond 02" and so on). Unfortunately the movie list only sorts using the 'pretty' title (e.g. "James Bond 007 - Dr. No"). So in the movie list the first movie is "james bond 21" Casino Royale, and not "james bond 01" Dr. No. With other movies, where the titles vary more the movies are spread apart (like "Jurassic Park" sorted under 'J' and "The Lost World: Jurassic Park" sorted under 'L').

Ideally the sorting should work as it does today, but with the possibility to choose in the settings whether to use the 'pretty' title or the sort-title for sorting. After all, this is why there is a separate field for sort-titles.

Alternatively a new column could be added for this to the bottom of the list (where you can now choose between "New", "Title", "Added" and so on). 
I like to sort by "New", so I'd prefer the sort-title to be used there as well, but I could live with this solution as well.

**Comment by bugwelle** [comment]
I fully agree with you. I will change the default because it makes more sense in my opinion. :-)

**Comment by ticao2** [comment]
In this case, wouldn't it be interesting that when we add a new movie, the title is also copied to the sort-title?
Will films with the blank sort-title field be at the bottom of the list?

**Comment by bugwelle** [comment]
@ticao2 If the sort title is empty then the normal movie title/name is used. And if enabled in the settings, articles ("the", "der/die/das" in German, ...) are removed. :-)
