### ISSUE TITLE
Time calculation of TS stream (h264) broken

### ISSUE THREAD

**Issue by Belgose** [Komet/MediaElch#923]
**Describe the bug**
Having a movie as TS stream (Codec shows 27) clicking "Reload from File" results in 0 minutes length of the movie using version 2.6.4. Doing the same with 2.4.2 works fine.

**To Reproduce**
1. Select a movie of type .ts
2. Go to Streamdetails
3. Click on Reload from File
4. Codes changes to h264 and duration becomes 00:00:00

**Expected behavior**
Duration should be correct as in 2.4.2

**Screenshots**
2.6.4 before Reload:
![grafik](https://user-images.githubusercontent.com/62212755/76705460-7e8b7e80-66e0-11ea-90af-8dfc7bd57efa.png)
2.6.4 after Reload:
![grafik](https://user-images.githubusercontent.com/62212755/76705479-a11d9780-66e0-11ea-8bdf-b202ba933bbb.png)

2.4.2 before and after Reload:
![grafik](https://user-images.githubusercontent.com/62212755/76705532-feb1e400-66e0-11ea-9224-7e7431b4e4a5.png)

**MediaElch Version:**
 - [x ] 2.6.4 stable

**Operating System:**
 - [x ] Windows 10

**Comment by bugwelle** [comment]
Thank you for reporting this issue. Do you know by chance whether this issue happens in v2.6.2 as well? :-)

**Comment by Belgose** [comment]
I just tested 2.6.0, there it still working.

**Comment by Belgose** [comment]
2.6.3 is also working:
Before Reload:
![grafik](https://user-images.githubusercontent.com/62212755/76705876-bb0ca980-66e3-11ea-9742-fda1418eab14.png)
After Reload:
![grafik](https://user-images.githubusercontent.com/62212755/76705885-d081d380-66e3-11ea-83d8-d5911c28a905.png)

**Comment by bugwelle** [comment]
Thanks. That helps to pin the issue down. We updated one of our dependencies (MediaInfo) and they changed some properties. I'll look into it.

Codec "27" was wrong in v2.4.2, though. h264 is more likely to be correct. But I do wonder why the duration is wrong.

**Comment by bugwelle** [comment]
We use MediaInfo v19.04 but v19.09 is the latest version and according to its [changelog](https://mediaarea.net/MediaInfo/ChangeLog) at least one issue is related to yours. I'll update MediaInfo, though it may not fix your issue. We'll see. :-)

**Comment by bugwelle** [comment]
For testing I'm using a file from https://filesamples.com/formats/ts

I found the issue . Will be fixed shortlyl
