### ISSUE TITLE
Preview picture for movies as with the episodes

### ISSUE THREAD

**Issue by mattbutler2001** [Komet/MediaElch#934]
I love the feature available with the TV tab where you can simply click the camera button and it will skip through various points in the show to add that picture to the TV episode regarding thumbnails. 

I have a lot of home movies that I add to my NAS and it does not make sense to set these up as a TV series format like s01_e01 just to use this method. Therefore I have to create screenshots of every movie and import - very time consuming. 

Is it possible to just have the movie background (poster and fanart) also have the option to skim the movie and choose a pic from the movie? This would also be great when the scrapper grabs images that you are not crazy about or is limited.

**Comment by bugwelle** [comment]
For episodes, this feature selects a frame from the video file at random. I don't think this would make sense for poster. I'll have to look into the Kodi NFO specification for movies and images but maybe there's a background option. Fanart would make the most sense IMHO for that feature. 😃

**Comment by mattbutler2001** [comment]
For most things I would agree but for home movies it sure would be helpful to capture a random pic from my home movie than having to save screen captures to my hard drive then importing -20-50 movies at a time since home movies are usually less than a few minutes and we take so many.

**Comment by bugwelle** [comment]
Oh, sorry, I misunderstood what you meant by "home movie". Thought you meant a block buster movie or similar.

Yeah, I agree on that. 😃

**Comment by mattbutler2001** [comment]
👍😆

**Comment by mattbutler2001** [comment]
As long as it is the poster not the fanart...I am fine with however it crops. It's just so time consuming to do the screenshot thing but it turns out nice. Here is a pic of our Kodi after:

![IMG_20200328_092838959](https://user-images.githubusercontent.com/62713087/77824159-f68d7780-70d6-11ea-83ed-bd8d881512c4.jpg)

**Comment by bugwelle** [comment]
Ah, thanks! Btw. do you use Windows, Linux or a Mac for managing your media library? If you're on Linux or Mac, then I could write you a simple script to automate that (if you're familiar with a console) until MediaElch implements it. :-)

**Comment by mattbutler2001** [comment]
I don't have any real experience with coding or script but I do have a lot of general computer experience especially on Mac which is my platform. BTW I appreciate your help. I really love how mediaelch makes my library look in Kodi and believe it or not this day and age - my family doesn't have internet in our home so mediaelch help me set everything up nicely and I can scrape when I'm near internet access or I sometimes hotspot my phone to scrape so mediaelch is a life saver and having this feature will save a tone of time on home videos! Many thanks and blessings for your help!

**Comment by bugwelle** [comment]
Ok, I like the idea of being able to create a poster from a random screenshot for such home movies. It was also rather easy to enable so here we are: #937 will implement the random screenshot functionality for posters only.

Please have a look at it. I also inserted an example as to how MediaElch crops the screenshot. It you don't like the way we to it, please let me know. 😃 

-------------

> BTW I appreciate your help.

You're welcome. 😄 

> my family doesn't have internet in our home so mediaelch help me set everything up nicely and I can scrape when I'm near internet access or I sometimes hotspot my phone to scrape so mediaelch is a life saver and having this feature will save a tone of time on home videos! Many thanks and blessings for your help!

Thanks for sharing that info! I started using MediaElch because Kodi's builtin scrapers took too long for my library and managing it myself was easier. It's nice to know who uses MediaElch and how they do.

**Comment by bugwelle** [comment]
Oh and if there's anything else, just let me know. I can't say whether I will implement any new features but if I think that the feature is useful and rather quick to implement then I'll add it to MediaElch. I can't promise that though. There are about 100 open feature requests that I don't have time for at the moment.
