### ISSUE TITLE
[export] sometimes the fileinfo is not available

### ISSUE THREAD

**Issue by Stunkymonkey** [Komet/MediaElch#939]
**Describe the bug**
when exporting some movies have a duration of zero seconds.

**To Reproduce**
1. Go to Export
2. Click on "Export"
3. Visit HTML site
4. See duration of zero

**Expected behavior**
there should be the true value.

**MediaElch Version:**
 - [x] 2.6.5-dev (nightly)

**Operating System:**
 - [x] Linux (distribution: arch)

**Additional context**
reading out the correct value is hard yes. The cmd is not showing errors, but the GUI is showing the correct minutes.
Maybe we could use the duration from Imdb, because some value is still better then zero.

**Comment by Stunkymonkey** [comment]
not only the duration is zero the whole file info is missing

**Comment by Stunkymonkey** [comment]
this only happend to me on mp4 files, which all can be played by VLC.

**Comment by Stunkymonkey** [comment]
@bugwelle I think this issue is somehow fixed... I am unable to reproduce it...

**Comment by bugwelle** [comment]
Could be a new MediaInfo version. :-/
