### ISSUE TITLE
Scraping show without actors = loop

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#947]
**Describe the bug**
If you have an already scraped show, where actors are included, and scrape it again with the actors option not selected the scraping process never ends.

**To Reproduce**
1. Select an already scraped shows where actors are included.
2. Ctrl+F
3. Make sure Actors are not selected.
4. Click on show name to scrape.
5. Wait in infinity while watching the "Please wait while you TV show is scraped" status.

**Expected behavior**
The things you select to scrape should be scraped as usual and actors list with corresponding images should be left alone.

**MediaElch Version:**
 - [X] 2.6.5-dev (nightly)
 - [ ] 2.6.4 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Additional context**
Might be related to TheTVdb API being FUBAR but that's beyond my paygrade to figure out since I don't know the inner workings 😉

**Comment by bugwelle** [comment]
Do you by any chance load anything from IMDb using the TheTvDb Scraper? See Settings -> Scraper -> TV Scraper.

**Comment by psonnosp** [comment]
It appeared with both of those two checked but it probably was because of TheTVDB, or something else, cause I can't recreate it.

**Comment by bugwelle** [comment]
Ok. I'm working on a completely new TV show scraper interface so I hope that this issue will vanish in future releases. MediaElch should not end up in endless loops regardless of TheTvDb's state.

**Comment by bugwelle** [comment]
Should be fixed with the next nightly.
