### ISSUE TITLE
[Renamer] For Idiots

### ISSUE THREAD

**Issue by ticao2** [Komet/MediaElch#959]
**Is your feature request related to a problem? Please describe.**
Renamer For Idiots
I am a complete idiot.  :-)
I am creating the **.disc** files for my brother's collection.
And I was using **ME** to:
1 create the .nfo 
2 and then create the movie folder 
3 and then manually move the .disc and .nfo files into the folder.
So, in a rare moment of little idiocy, after creating some 60 folders and moving the files,
I decided to research if there was a less painful way to do this service.
And I discovered this indication of Komet: https://github.com/Komet/MediaElch/issues/319
That is, just create the **.disc** files in a folder and use the resource:
**settings -> global settings -> choose the directory -> Organize**.

**Describe the solution you'd like**
It would be interesting to do some things so that idiots like me don't suffer so much.
My sugestion:
1 Add the Renamer Label to this Komet explanation.
I don't know if I can do this myself. If I can, I will.
2 Add a phrase at the beginning of Renamer Help:
https://mediaelch.github.io/mediaelch-doc/renaming.html
Something like:
If the media files for the movies (mkv, avi, mp4 etc ...) are all in one folder,
you can use the **Organize Feature** to automatically create individual folders
and put the respective media files into the new folders.
Only the movie's media file is moved to the new folder.

**Describe alternatives you've considered**
I stop being lazy and research before working

**Additional context**

**Comment by bugwelle** [comment]
> 1 Add the Renamer Label to this Komet explanation.

Done. :)

> 2 Add a phrase at the beginning of Renamer Help:

Will do. Thank you for that proposal. :)

> I stop being lazy and research before working

😃 Well, our documentation isn't that great, yet. So this is an issue on our side. Don't be so harsh to yourself. :)

**Comment by bugwelle** [comment]
Fixed: https://mediaelch.github.io/mediaelch-doc/renaming.html

See https://github.com/mediaelch/mediaelch-doc/commit/9bd863764d08c6b79e6638b2a71955c35f476a20
