### ISSUE TITLE
[export] concert-file placeholder

### ISSUE THREAD

**Issue by Stunkymonkey** [Komet/MediaElch#962]
**Is your feature request related to a problem? Please describe.**
currently there is no option to get the folder/filname/...

**Describe the solution you'd like**
Maybe we can add the same placeholders like in `movies`:
```
{{ CONCERT.FILENAME }}
{{ CONCERT.DIR }}
```
not sure if these placeholders are also availbale:
```
{{ CONCERT.DATE_ADDED }}
{{ CONCERT.FILE_LAST_MODIFIED }}
```

**Comment by bugwelle** [comment]
```
{{ CONCERT.FILENAME }}
{{ CONCERT.DIR }}
``` 

Will be added by #963


```
{{ CONCERT.DATE_ADDED }}
{{ CONCERT.FILE_LAST_MODIFIED }}
```

Sorry, those aren't stored for concerts, yet. :smiley:
