### ISSUE TITLE
Application thinks directories are files

### ISSUE THREAD

**Issue by rassaei** [Komet/MediaElch#977]
**Describe the bug**
When scanning movie sources that contain directories like "directory.mkv", the application thinks it is a file.
This is from my Debug Log:
`MediaElch 2020-05-10 16:12:33.728 WARN  : First file of the movie is not readable FilePath("/home/user/videos/movies/testmovie/directory.mkv")`

This problem mainly occurs due to stupid behaviour of Synology devices. They index all files and create `@eaDir` directories everywhere which contain directories for each file. Those directories are named exactly like the files. Including the extension.

I have successfully used the new exclude directive in the advancedsettings.xml like this:
```
<pattern applyTo="folders">^.*@eaDir.*$<pattern>
<pattern applyTo="filename">^.*@eaDir.*$<pattern>
```
This works with tv shows but somehow not with the movies. That's how i noticed this bug.

**To Reproduce**
1. Set a new source for movies like "/home/user/videos/"
2. Check "Sep. folders"
3. Create a directory like you would for any new movie like "/home/user/videos/movie/"
4. Create a directory inside that one and name it "anything.mkv"
5. Scan your movie source

**Expected behavior**
The application knows directories are directories.

**MediaElch Version:**
 - [x] 2.6.6 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: Ubuntu 19.10)

**Comment by bugwelle** [comment]
`pattern`s are currently not used for movies. Will add it. :-)

However, it's really strange that a directory is seen as a file. Will look into it.

**Comment by bugwelle** [comment]
Ok, found one issue:

```
if (it.fileInfo().isDir() && Settings::instance()->advanced()->isFileExcluded(dirName)) {
```

It says `isFileExcluded` but should be `isFolderExcluded`. Doesn't affect you as you have the same regex for both but still...
